START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobCategory" ADD "BackgroundColor" character varying(20) NOT NULL DEFAULT '#FFFFFF';
    COMMENT ON COLUMN setup."FgsJobCategory"."BackgroundColor" IS 'Background color for displaying the Job Category, stored as a HEX color value such as #3B82F6.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobCategory" ADD "TextColor" character varying(20) NOT NULL DEFAULT '#000000';
    COMMENT ON COLUMN setup."FgsJobCategory"."TextColor" IS 'Text color for displaying the Job Category, stored as a HEX color value such as #FFFFFF.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobType" DROP COLUMN "BackgroundColor";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobType" DROP COLUMN "TextColor";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobTypeTask" DROP CONSTRAINT "FK_FgsJobTypeTask_FgsJobTypeCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    DELETE FROM setup."FgsJobTypeTask";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    DROP TABLE setup."FgsJobTypeCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE TABLE setup."FgsJobTypeCategory" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "JobTypeId" bigint NOT NULL,
        "JobTypeTaskId" bigint NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsJobTypeCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsJobTypeCategory_FgsJobType" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsJobTypeCategory_FgsJobTypeTask" FOREIGN KEY ("JobTypeTaskId") REFERENCES setup."FgsJobTypeTask" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsJobTypeCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsJobTypeCategory" IS 'Maps Job Type Tasks to Job Types. A Job Type can contain multiple Job Type Tasks, each with its own display order.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."Id" IS 'Unique identifier for the Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."TenantId" IS 'Identifier of the tenant that owns this Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobTypeId" IS 'Identifier of the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobTypeTaskId" IS 'Identifier of the Job Type Task assigned to the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."DisplayOrder" IS 'Controls the display sequence of Job Type Tasks within the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedOn" IS 'Date and time when the mapping was created.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedBy" IS 'User who created the mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedOn" IS 'Date and time when the mapping was last modified.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedBy" IS 'User who last modified the mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."IsActive" IS 'Indicates whether the Job Type Task assignment is active.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE INDEX "IX_FgsJobTypeCategory_JobTypeId" ON setup."FgsJobTypeCategory" ("JobTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE INDEX "IX_FgsJobTypeCategory_JobTypeTaskId" ON setup."FgsJobTypeCategory" ("JobTypeTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobType" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobType_DisplayOrder" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE UNIQUE INDEX "UX_FgsJobTypeCategory_Tenant_Company_JobType_Task" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "JobTypeTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobTypeTask" ADD CONSTRAINT "FK_FgsJobTypeTask_FgsJobTypeCategory" FOREIGN KEY ("JobTypeCategoryId") REFERENCES setup."FgsJobTypeCategory" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    INSERT INTO setup."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260927051512_RemapJobTypeCategoryAndMoveColors', '10.0.8');
    END IF;
END $EF$;
COMMIT;

