START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE c.conname = 'FK_FgsPriceBook_JobTypeId'
              AND n.nspname = 'setup'
              AND t.relname = 'FgsPriceBook') THEN
            ALTER TABLE setup."FgsPriceBook" DROP CONSTRAINT "FK_FgsPriceBook_JobTypeId";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        DELETE FROM setup."FgsPriceBookItem";
        DELETE FROM setup."FgsPriceBook";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        DROP TABLE IF EXISTS setup."FgsJobType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        DROP TABLE IF EXISTS setup."FgsJobTypeCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        DROP TABLE IF EXISTS setup."FgsJobTypeSubCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        DROP TABLE IF EXISTS glo."GloJobTypeSubCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        CREATE TABLE setup."FgsJobCategory" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "CategoryCode" character varying(50) NOT NULL,
            "Name" character varying(150) NOT NULL,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobCategory" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );
        COMMENT ON TABLE setup."FgsJobCategory" IS 'Stores the master list of Job Categories available for configuring Job Types. Categories organize related Job Tasks within a Job Type.';
        COMMENT ON COLUMN setup."FgsJobCategory"."Id" IS 'Unique identifier for the Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."TenantId" IS 'Identifier of the tenant that owns this Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."CategoryCode" IS 'Unique business code used to identify the Job Category within a tenant and company.';
        COMMENT ON COLUMN setup."FgsJobCategory"."Name" IS 'Display name of the Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."DisplayOrder" IS 'Controls the display sequence of Job Categories in lists and selection controls.';
        COMMENT ON COLUMN setup."FgsJobCategory"."CreatedOn" IS 'Date and time when the Job Category was created.';
        COMMENT ON COLUMN setup."FgsJobCategory"."CreatedBy" IS 'User who created the Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."UpdatedOn" IS 'Date and time when the Job Category was last modified.';
        COMMENT ON COLUMN setup."FgsJobCategory"."UpdatedBy" IS 'User who last modified the Job Category.';
        COMMENT ON COLUMN setup."FgsJobCategory"."IsActive" IS 'Indicates whether the Job Category is active and available for selection.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        CREATE TABLE setup."FgsJobType" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "JobTypeCode" character varying(50) NOT NULL,
            "Name" character varying(200) NOT NULL,
            "UsedFor" smallint NOT NULL,
            "BusinessUnit" character varying(100),
            "BackgroundColor" character varying(20),
            "TextColor" character varying(20),
            "ShowToFieldTech" boolean NOT NULL DEFAULT TRUE,
            "ShowOnCustomerPortal" boolean NOT NULL DEFAULT TRUE,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobType" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_FgsJobType_UsedFor" CHECK ("UsedFor" IN (1, 2, 3, 4)),
            CONSTRAINT "FK_FgsJobType_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );
        COMMENT ON TABLE setup."FgsJobType" IS 'Defines reusable Job Types that represent the type of work performed. A Job Type serves as the header for one or more Job Type Categories and their associated tasks.';
        COMMENT ON COLUMN setup."FgsJobType"."Id" IS 'Unique identifier for the Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."TenantId" IS 'Identifier of the tenant that owns this Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."JobTypeCode" IS 'Unique business code used to identify the Job Type within a tenant and company.';
        COMMENT ON COLUMN setup."FgsJobType"."Name" IS 'Display name of the Job Type shown throughout the application.';
        COMMENT ON COLUMN setup."FgsJobType"."UsedFor" IS 'Specifies the business process for the Job Type. Valid values: 1=Service, 2=Maintenance, 3=Warranty, 4=Installation. Corresponds to the JobTypeUsedFor enum in the application.';
        COMMENT ON COLUMN setup."FgsJobType"."BusinessUnit" IS 'Optional business unit or department responsible for this Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."BackgroundColor" IS 'Optional background color used when displaying the Job Type in the user interface.';
        COMMENT ON COLUMN setup."FgsJobType"."TextColor" IS 'Optional text color used when displaying the Job Type in the user interface.';
        COMMENT ON COLUMN setup."FgsJobType"."ShowToFieldTech" IS 'Indicates whether this Job Type is visible to field technicians in the mobile application.';
        COMMENT ON COLUMN setup."FgsJobType"."ShowOnCustomerPortal" IS 'Indicates whether this Job Type is available for customers through the customer portal.';
        COMMENT ON COLUMN setup."FgsJobType"."DisplayOrder" IS 'Controls the display sequence of Job Types in lists and selection controls.';
        COMMENT ON COLUMN setup."FgsJobType"."CreatedOn" IS 'Date and time when the Job Type was created.';
        COMMENT ON COLUMN setup."FgsJobType"."CreatedBy" IS 'User who created the Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."UpdatedOn" IS 'Date and time when the Job Type was last modified.';
        COMMENT ON COLUMN setup."FgsJobType"."UpdatedBy" IS 'User who last modified the Job Type.';
        COMMENT ON COLUMN setup."FgsJobType"."IsActive" IS 'Indicates whether the Job Type is active and available for new work orders.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        CREATE TABLE setup."FgsJobTypeCategory" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "JobTypeId" bigint NOT NULL,
            "JobCategoryId" bigint NOT NULL,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobTypeCategory" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobTypeCategory_FgsJobCategory" FOREIGN KEY ("JobCategoryId") REFERENCES setup."FgsJobCategory" ("Id") ON DELETE RESTRICT,
            CONSTRAINT "FK_FgsJobTypeCategory_FgsJobType" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_FgsJobTypeCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );
        COMMENT ON TABLE setup."FgsJobTypeCategory" IS 'Maps Job Categories to Job Types. A Job Type can contain one or more Job Categories, each with its own display order.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."Id" IS 'Unique identifier for the Job Type Category mapping.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."TenantId" IS 'Identifier of the tenant that owns this Job Type Category mapping.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Type Category mapping.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobTypeId" IS 'Identifier of the Job Type.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobCategoryId" IS 'Identifier of the Job Category assigned to the Job Type.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."DisplayOrder" IS 'Controls the display sequence of Job Categories within the Job Type.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedOn" IS 'Date and time when the mapping was created.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedBy" IS 'User who created the mapping.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedOn" IS 'Date and time when the mapping was last modified.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedBy" IS 'User who last modified the mapping.';
        COMMENT ON COLUMN setup."FgsJobTypeCategory"."IsActive" IS 'Indicates whether the Job Category assignment is active.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        CREATE TABLE setup."FgsJobTypeTask" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "JobTypeCategoryId" bigint NOT NULL,
            "TradeId" bigint NOT NULL,
            "TaskName" character varying(200) NOT NULL,
            "Priority" smallint NOT NULL DEFAULT 5,
            "EstimatedHours" numeric(5,2) NOT NULL DEFAULT 1.00,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobTypeTask" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobTypeTask_FgsJobTypeCategory" FOREIGN KEY ("JobTypeCategoryId") REFERENCES setup."FgsJobTypeCategory" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_FgsJobTypeTask_FgsSetupTechTrade" FOREIGN KEY ("TradeId") REFERENCES setup."FgsSetupTechTrade" ("Id") ON DELETE RESTRICT,
            CONSTRAINT "FK_FgsJobTypeTask_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );
        COMMENT ON TABLE setup."FgsJobTypeTask" IS 'Stores the tasks that belong to a Job Type Category. Each task defines the work to be performed, along with its associated Trade, Priority, and estimated labor hours.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."Id" IS 'Unique identifier for the Job Type Task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."TenantId" IS 'Identifier of the tenant that owns this Job Type Task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Type Task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."JobTypeCategoryId" IS 'Identifier of the Job Type Category that owns this task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."TradeId" IS 'Identifier of the Trade responsible for performing this task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."TaskName" IS 'Name of the task to be performed.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."Priority" IS 'Execution priority for the task. Lower values typically represent higher priority.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."EstimatedHours" IS 'Estimated labor hours required to complete the task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."DisplayOrder" IS 'Controls the display sequence of tasks within the Job Type Category.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."CreatedOn" IS 'Date and time when the Job Type Task was created.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."CreatedBy" IS 'User who created the Job Type Task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."UpdatedOn" IS 'Date and time when the Job Type Task was last modified.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."UpdatedBy" IS 'User who last modified the Job Type Task.';
        COMMENT ON COLUMN setup."FgsJobTypeTask"."IsActive" IS 'Indicates whether the Job Type Task is active and available for use.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        CREATE INDEX "IX_FgsJobCategory_Tenant_Company" ON setup."FgsJobCategory" ("TenantId", "CompanyId");
        CREATE UNIQUE INDEX "UX_FgsJobCategory_Tenant_Company_CategoryCode" ON setup."FgsJobCategory" ("TenantId", "CompanyId", "CategoryCode");

        CREATE INDEX "IX_FgsJobType_Tenant_Company" ON setup."FgsJobType" ("TenantId", "CompanyId");
        CREATE INDEX "IX_FgsJobType_Tenant_Company_BusinessUnit" ON setup."FgsJobType" ("TenantId", "CompanyId", "BusinessUnit");
        CREATE INDEX "IX_FgsJobType_Tenant_Company_UsedFor" ON setup."FgsJobType" ("TenantId", "CompanyId", "UsedFor");
        CREATE UNIQUE INDEX "UX_FgsJobType_Tenant_Company_JobTypeCode" ON setup."FgsJobType" ("TenantId", "CompanyId", "JobTypeCode");
        CREATE UNIQUE INDEX "UX_FgsJobType_Tenant_Company_Name" ON setup."FgsJobType" ("TenantId", "CompanyId", "Name");

        CREATE INDEX "IX_FgsJobTypeCategory_JobCategoryId" ON setup."FgsJobTypeCategory" ("JobCategoryId");
        CREATE INDEX "IX_FgsJobTypeCategory_JobTypeId" ON setup."FgsJobTypeCategory" ("JobTypeId");
        CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId");
        CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_DisplayOrder" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "DisplayOrder");
        CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobCategory" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobCategoryId");
        CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobType" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId");
        CREATE UNIQUE INDEX "UX_FgsJobTypeCategory_Tenant_Company_JobType_Category" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "JobCategoryId");

        CREATE INDEX "IX_FgsJobTypeTask_JobTypeCategoryId" ON setup."FgsJobTypeTask" ("JobTypeCategoryId");
        CREATE INDEX "IX_FgsJobTypeTask_Tenant_Company" ON setup."FgsJobTypeTask" ("TenantId", "CompanyId");
        CREATE INDEX "IX_FgsJobTypeTask_Tenant_Company_JobTypeCategory" ON setup."FgsJobTypeTask" ("TenantId", "CompanyId", "JobTypeCategoryId");
        CREATE INDEX "IX_FgsJobTypeTask_TradeId" ON setup."FgsJobTypeTask" ("TradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        ALTER TABLE setup."FgsPriceBook" ADD CONSTRAINT "FK_FgsPriceBook_JobTypeId" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        INSERT INTO setup."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260728183140_RedesignJobTypeHierarchy', '10.0.8');
    END IF;
END $EF$;

COMMIT;
