START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    DROP TABLE IF EXISTS setup."FgsLeadDisqualificationReason";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    DROP TABLE IF EXISTS setup."FgsLeadStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    DROP TABLE IF EXISTS glo."GloLeadDisqualificationReason";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    DROP TABLE IF EXISTS glo."GloLeadStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    ALTER TABLE glo."GloLeadSource" RENAME TO "GloSource";
    ALTER TABLE glo."GloSource" RENAME CONSTRAINT "PK_GloLeadSource" TO "PK_GloSource";
    ALTER INDEX glo."UX_GloLeadSource_SourceCode" RENAME TO "UX_GloSource_SourceCode";

    ALTER TABLE setup."FgsLeadSource" RENAME TO "FgsSource";
    ALTER TABLE setup."FgsSource" RENAME CONSTRAINT "PK_FgsLeadSource" TO "PK_FgsSource";
    ALTER TABLE setup."FgsSource" RENAME CONSTRAINT "FK_FgsLeadSource_FgsTenantCompanyCache_TenantId_CompanyId" TO "FK_FgsSource_FgsTenantCompanyCache_TenantId_CompanyId";
    ALTER INDEX setup."UX_FgsLeadSource_TenantId_CompanyId_SourceCode" RENAME TO "UX_FgsSource_TenantId_CompanyId_SourceCode";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    CREATE TABLE glo."GloTimeSlot" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "BeginTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "MarkTechArrivedLateAfter" interval,
        "MarkWorkOrderDelayedCompletionAfter" interval,
        "IsMobileVisible" boolean NOT NULL DEFAULT TRUE,
        "IsCustomerPortalVisible" boolean NOT NULL DEFAULT TRUE,
        "IncludeInCapacityPlanning" boolean NOT NULL DEFAULT FALSE,
        "ShowToExternalSystem" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloTimeSlot" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_GloTimeSlot_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "CK_GloTimeSlot_TimeRange" CHECK ("EndTime" > "BeginTime")
    );
    CREATE UNIQUE INDEX "UQ_GloTimeSlot_Code" ON glo."GloTimeSlot" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot') THEN
    INSERT INTO setup."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261007180052_RenameLeadSourceToSourceDropLeadStatusAndAddGloTimeSlot', '10.0.8');
    END IF;
END $EF$;

COMMIT;
