START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260811191700_AddFgsNonWorkingDate') THEN
    CREATE TABLE setup."FgsNonWorkingDate" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "NonWorkingDate" date NOT NULL,
        "Name" character varying(100) NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsNonWorkingDate" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsNonWorkingDate_TenantId_CompanyId_NonWorkingDate" UNIQUE ("TenantId", "CompanyId", "NonWorkingDate"),
        CONSTRAINT "FK_FgsNonWorkingDate_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsNonWorkingDate" IS 'Stores tenant/company specific calendar dates on which normal business operations are not scheduled.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."Id" IS 'Primary key identity of the non-working date record.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."TenantId" IS 'Tenant identifier owning this non-working date.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."CompanyId" IS 'Company identifier within the tenant owning this non-working date.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."NonWorkingDate" IS 'Calendar date on which the company does not operate under its normal working schedule.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."Name" IS 'Name identifying the non-working date, such as New Year''s Day, Thanksgiving, Company Holiday, or Emergency Closure.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."CreatedOn" IS 'Date and time the non-working date record was created.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."CreatedBy" IS 'User identifier that created the non-working date record.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."UpdatedOn" IS 'Date and time the non-working date record was last updated.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."UpdatedBy" IS 'User identifier that last updated the non-working date record.';
    COMMENT ON COLUMN setup."FgsNonWorkingDate"."IsActive" IS 'Indicates whether the non-working date is active and should be considered when determining business availability and scheduling.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260811191700_AddFgsNonWorkingDate') THEN
    CREATE INDEX "IX_FgsNonWorkingDate_TenantId_CompanyId_IsActive" ON setup."FgsNonWorkingDate" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260811191700_AddFgsNonWorkingDate') THEN
    INSERT INTO setup."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260811191700_AddFgsNonWorkingDate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

