START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE c.conname = 'UQ_FgsSetupPricingMatrixLabor'
              AND n.nspname = 'setup'
              AND t.relname = 'FgsSetupPricingMatrixLabor') THEN
            ALTER TABLE setup."FgsSetupPricingMatrixLabor" DROP CONSTRAINT "UQ_FgsSetupPricingMatrixLabor";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    COMMENT ON COLUMN setup."FgsSetupPricingMatrixOther"."CategoryCode" IS 'Billing category type code (FgsBillingCategory.BillingCategoryType) such as NI, OT, or SF.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    ALTER TABLE setup."FgsSetupPricingMatrixLabor" ALTER COLUMN "TechSkillLevelId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE TABLE setup."FgsPriceBook" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "PriceBookCode" character varying(50) NOT NULL,
        "PriceBookName" character varying(200) NOT NULL,
        "Description" text,
        "JobTypeId" bigint NOT NULL,
        "PricingModel" character varying(20) NOT NULL,
        "EstimatedDurationMinutes" integer NOT NULL DEFAULT 60,
        "BasePrice" numeric(18,2),
        "IsTaxable" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsPriceBook" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsPriceBook_PricingModel" CHECK ("PricingModel" IN ('Flat Rate', 'Dynamic')),
        CONSTRAINT "FK_FgsPriceBook_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsPriceBook_JobTypeId" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsPriceBook" IS 'Defines the master catalog of services offered by a company. Each price book header represents a reusable service template used by estimates, work orders, invoices, scheduling, and pricing.';
    COMMENT ON COLUMN setup."FgsPriceBook"."Id" IS 'Unique identifier of the price book record.';
    COMMENT ON COLUMN setup."FgsPriceBook"."TenantId" IS 'Identifier of the tenant that owns the record.';
    COMMENT ON COLUMN setup."FgsPriceBook"."CompanyId" IS 'Identifier of the company that owns the record.';
    COMMENT ON COLUMN setup."FgsPriceBook"."PriceBookCode" IS 'Unique business code of the price book item.';
    COMMENT ON COLUMN setup."FgsPriceBook"."PriceBookName" IS 'Display name of the service offered in the price book.';
    COMMENT ON COLUMN setup."FgsPriceBook"."Description" IS 'Detailed description of the service.';
    COMMENT ON COLUMN setup."FgsPriceBook"."JobTypeId" IS 'Default work order type associated with this service.';
    COMMENT ON COLUMN setup."FgsPriceBook"."PricingModel" IS 'Determines whether pricing is Flat Rate or Dynamic.';
    COMMENT ON COLUMN setup."FgsPriceBook"."EstimatedDurationMinutes" IS 'Estimated time in minutes required to complete the service.';
    COMMENT ON COLUMN setup."FgsPriceBook"."BasePrice" IS 'Base selling price when the pricing model is Flat Rate. Null for Dynamic pricing.';
    COMMENT ON COLUMN setup."FgsPriceBook"."IsTaxable" IS 'Indicates whether the service is taxable by default.';
    COMMENT ON COLUMN setup."FgsPriceBook"."CreatedOn" IS 'Date and time when the record was created.';
    COMMENT ON COLUMN setup."FgsPriceBook"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN setup."FgsPriceBook"."UpdatedOn" IS 'Date and time when the record was last updated.';
    COMMENT ON COLUMN setup."FgsPriceBook"."UpdatedBy" IS 'User who last updated the record.';
    COMMENT ON COLUMN setup."FgsPriceBook"."IsActive" IS 'Indicates whether the price book item is active and available for use.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE TABLE setup."FgsPriceBookItem" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "PriceBookId" bigint NOT NULL,
        "InventoryItemId" bigint,
        "ItemCode" character varying(50),
        "ItemDescription" character varying(500) NOT NULL,
        "Quantity" numeric(18,4) NOT NULL DEFAULT 1.0,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsPriceBookItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsPriceBookItem_FgsPriceBook" FOREIGN KEY ("PriceBookId") REFERENCES setup."FgsPriceBook" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsPriceBookItem_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsPriceBookItem" IS 'Defines the inventory, non-inventory, and free-form items that make up a price book service.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."Id" IS 'Primary key identifier of the price book item.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."TenantId" IS 'Tenant identifier owning the record.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."CompanyId" IS 'Company identifier owning the record.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."PriceBookId" IS 'Reference to the parent price book.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."InventoryItemId" IS 'Identifier of the inventory or non-inventory item. No database foreign key is enforced because the inventory module resides in a separate schema.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."ItemCode" IS 'Business code of the selected item. Stored as a snapshot for reporting and historical consistency.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."ItemDescription" IS 'Description of the item as it should appear within the price book.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."Quantity" IS 'Default quantity required to perform the service.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."DisplayOrder" IS 'Controls the display order of items within the price book.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."Notes" IS 'Optional notes or installation instructions.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN setup."FgsPriceBookItem"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "UQ_FgsSetupPricingMatrixLabor" ON setup."FgsSetupPricingMatrixLabor" ("TenantId", "CompanyId", "PricingMatrixId", "LaborRateTypeId", "TechSkillLevelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBook_JobTypeId" ON setup."FgsPriceBook" ("JobTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBook_Tenant_Company" ON setup."FgsPriceBook" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBook_Tenant_Company_IsActive" ON setup."FgsPriceBook" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE UNIQUE INDEX "UX_FgsPriceBook_Tenant_Company_PriceBookCode" ON setup."FgsPriceBook" ("TenantId", "CompanyId", "PriceBookCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBookItem_PriceBookId" ON setup."FgsPriceBookItem" ("PriceBookId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBookItem_TenantId_CompanyId" ON setup."FgsPriceBookItem" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    CREATE INDEX "IX_FgsPriceBookItem_TenantId_CompanyId_PriceBookId" ON setup."FgsPriceBookItem" ("TenantId", "CompanyId", "PriceBookId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184920_AddFgsPriceBook') THEN
    INSERT INTO setup."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260720184920_AddFgsPriceBook', '10.0.8');
    END IF;
END $EF$;
COMMIT;

