using Fgs.Contracts.Api;
using Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Dtos;
using MediatR;

namespace Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Commands.CreateFgsSetupPricingMatrixMaterialTier;

public sealed record CreateFgsSetupPricingMatrixMaterialTierCommand(FgsSetupPricingMatrixMaterialTierCreateDto Dto) : IRequest<ApiResponse<FgsSetupPricingMatrixMaterialTierDetailDto>>;
