START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193653_AddAssetUnitNumberAttributeValueAndRenameIsOurInstallation') THEN

    ALTER TABLE asset."FgsAsset"
    ADD COLUMN IF NOT EXISTS "UnitNumber" character varying(50);

    COMMENT ON COLUMN asset."FgsAsset"."UnitNumber"
    IS 'Apartment, suite, unit, condo, office, bay, or other sub-location identifier within the service location where the asset is installed. Examples: Apt 1205, Suite 400, Unit 8B, Bay 12.';

    ALTER TABLE asset."FgsAsset"
    ADD COLUMN IF NOT EXISTS "IsOurInstallation" boolean NOT NULL DEFAULT false;

    COMMENT ON COLUMN asset."FgsAsset"."IsOurInstallation"
    IS 'Indicates whether the asset was originally installed by the company. TRUE if installed by this company; FALSE if installed by another contractor or the customer.';

    ALTER TABLE asset."FgsAsset"
    ALTER COLUMN "ServiceLocationId" DROP NOT NULL;

    COMMENT ON COLUMN asset."FgsAsset"."ServiceLocationId"
    IS 'Optional service location where the asset is installed.';

    ALTER TABLE asset."FgsAssetAttribute"
    DROP COLUMN IF EXISTS "AssetId";

    CREATE TABLE IF NOT EXISTS asset."FgsAssetAttributeValue" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AssetId" bigint NOT NULL,
        "AssetAttributeId" bigint NOT NULL,
        "OptionId" bigint,
        "ValueText" character varying(500),
        "ValueInteger" integer,
        "ValueDecimal" numeric(18,4),
        "ValueDate" date,
        "ValueBoolean" boolean,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAssetAttributeValue" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsAssetAttributeValue_Asset" FOREIGN KEY ("AssetId") REFERENCES asset."FgsAsset" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsAssetAttributeValue_Attribute" FOREIGN KEY ("AssetAttributeId") REFERENCES asset."FgsAssetAttribute" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsAssetAttributeValue_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );

    COMMENT ON TABLE asset."FgsAssetAttributeValue"
    IS 'Stores the values of custom attributes for individual assets. Each record contains the value of one attribute assigned to one asset.';

    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."Id" IS 'Unique asset attribute value identifier.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."AssetId" IS 'Asset that owns the attribute value.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."AssetAttributeId" IS 'Reference to the asset attribute definition.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."OptionId" IS 'Selected option identifier when the attribute input type is DROPDOWN.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."ValueText" IS 'Text value for TEXT or TEXTAREA attributes.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."ValueInteger" IS 'Integer value for INTEGER attributes.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."ValueDecimal" IS 'Decimal value for DECIMAL attributes.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."ValueDate" IS 'Date value for DATE attributes.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."ValueBoolean" IS 'Boolean value for BOOLEAN attributes.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAssetAttributeValue"."UpdatedBy" IS 'User who last updated the record.';

    CREATE INDEX IF NOT EXISTS "IX_FgsAssetAttributeValue_AssetAttributeId"
    ON asset."FgsAssetAttributeValue" ("AssetAttributeId");

    CREATE INDEX IF NOT EXISTS "IX_FgsAssetAttributeValue_AssetId"
    ON asset."FgsAssetAttributeValue" ("AssetId");

    CREATE INDEX IF NOT EXISTS "IX_FgsAssetAttributeValue_TenantCompany"
    ON asset."FgsAssetAttributeValue" ("TenantId", "CompanyId");

    CREATE UNIQUE INDEX IF NOT EXISTS "UQ_FgsAssetAttributeValue_AssetAttribute"
    ON asset."FgsAssetAttributeValue" ("TenantId", "CompanyId", "AssetId", "AssetAttributeId");

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193653_AddAssetUnitNumberAttributeValueAndRenameIsOurInstallation') THEN
    INSERT INTO asset."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803193653_AddAssetUnitNumberAttributeValueAndRenameIsOurInstallation', '10.0.8');
    END IF;
END $EF$;
COMMIT;
