DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'asset') THEN
        CREATE SCHEMA asset;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS asset."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152522_InitialSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'asset') THEN
            CREATE SCHEMA asset;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152522_InitialSchema') THEN
    COMMENT ON SCHEMA asset IS 'Asset Management Domain

    Stores customer-owned equipment and installed assets.

    Examples:
    - Air Conditioners
    - Furnaces
    - Water Heaters
    - Boilers
    - Generators

    Assets are shared business entities referenced by:
    - Service Agreements
    - Estimates
    - Jobs
    - Invoices
    - Inspections

    Asset definitions such as Asset Type, Manufacturer and Model are stored in the setup schema.'
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152522_InitialSchema') THEN
    INSERT INTO asset."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611152522_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'asset') THEN
            CREATE SCHEMA asset;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE asset."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the asset schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN asset."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsAssetManufacturer" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(75) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAssetManufacturer" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsAssetManufacturer_Code_Upper" CHECK ("Code" = upper("Code")),
        CONSTRAINT "FK_FgsAssetManufacturer_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsAssetManufacturer" IS 'Stores equipment manufacturers available for asset management.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."Id" IS 'Unique asset manufacturer identifier.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."Code" IS 'Unique manufacturer code within the tenant company. Stored in uppercase.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."Name" IS 'Manufacturer name displayed to users.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."Description" IS 'Optional description of the manufacturer.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."IsActive" IS 'Indicates whether the manufacturer is active and available for selection.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAssetManufacturer"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsAssetStatus" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(75) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAssetStatus" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsAssetStatus_Code_Upper" CHECK ("Code" = upper("Code")),
        CONSTRAINT "FK_FgsAssetStatus_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsAssetStatus" IS 'Stores lifecycle status values used to classify service assets.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."Id" IS 'Unique asset status identifier.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."Code" IS 'Unique status code within the tenant company. Stored in uppercase.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."Name" IS 'Display name of the asset status.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."Description" IS 'Optional description of the asset status.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."IsActive" IS 'Indicates whether the status is active and available for selection.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAssetStatus"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsAssetType" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(75) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAssetType" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsAssetType_Code_Upper" CHECK ("Code" = upper("Code")),
        CONSTRAINT "FK_FgsAssetType_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsAssetType" IS 'Defines equipment classifications used by service assets.';
    COMMENT ON COLUMN asset."FgsAssetType"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAssetType"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAssetType"."Id" IS 'Unique asset type identifier.';
    COMMENT ON COLUMN asset."FgsAssetType"."Code" IS 'Unique asset type code within the tenant company. Stored in uppercase.';
    COMMENT ON COLUMN asset."FgsAssetType"."Name" IS 'Display name of the asset type.';
    COMMENT ON COLUMN asset."FgsAssetType"."Description" IS 'Optional description of the asset type.';
    COMMENT ON COLUMN asset."FgsAssetType"."IsActive" IS 'Indicates whether the asset type is active and available for selection.';
    COMMENT ON COLUMN asset."FgsAssetType"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAssetType"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAssetType"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAssetType"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsServiceLocationCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "ServiceLocationId" bigint NOT NULL,
        "CustomerId" bigint NOT NULL,
        "LocationSequence" integer NOT NULL,
        "LocationNumber" character varying(50) NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsServiceLocationCache" PRIMARY KEY ("TenantId", "CompanyId", "ServiceLocationId"),
        CONSTRAINT "FK_FgsServiceLocationCache_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsServiceLocationCache" IS 'Local cache of CRM service location information used by the asset schema to eliminate cross-schema dependencies on crm.CrmServiceLocation.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."ServiceLocationId" IS 'Service location identifier mapped from crm.CrmServiceLocation.Id.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."CustomerId" IS 'Customer identifier that owns the service location.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."LocationSequence" IS 'Sequential location number within the customer.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."LocationNumber" IS 'User-visible service location number.';
    COMMENT ON COLUMN asset."FgsServiceLocationCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from crm.CrmServiceLocation.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsAssetModel" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AssetTypeId" bigint NOT NULL,
        "AssetManufacturerId" bigint NOT NULL,
        "ModelNumber" character varying(100) NOT NULL,
        "ModelDescription" character varying(500) NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAssetModel" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsAssetModel_AssetManufacturer" FOREIGN KEY ("AssetManufacturerId") REFERENCES asset."FgsAssetManufacturer" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAssetModel_AssetType" FOREIGN KEY ("AssetTypeId") REFERENCES asset."FgsAssetType" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAssetModel_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsAssetModel" IS 'Catalog of equipment models that may be associated with service assets.';
    COMMENT ON COLUMN asset."FgsAssetModel"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAssetModel"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAssetModel"."Id" IS 'Unique asset model identifier.';
    COMMENT ON COLUMN asset."FgsAssetModel"."AssetTypeId" IS 'Asset type associated with this model.';
    COMMENT ON COLUMN asset."FgsAssetModel"."AssetManufacturerId" IS 'Manufacturer associated with this model.';
    COMMENT ON COLUMN asset."FgsAssetModel"."ModelNumber" IS 'Manufacturer model number.';
    COMMENT ON COLUMN asset."FgsAssetModel"."ModelDescription" IS 'Description of the model.';
    COMMENT ON COLUMN asset."FgsAssetModel"."IsActive" IS 'Indicates whether the model is active and available for selection.';
    COMMENT ON COLUMN asset."FgsAssetModel"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAssetModel"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAssetModel"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAssetModel"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE TABLE asset."FgsAsset" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AssetGuid" uuid NOT NULL,
        "AssetNumber" character varying(100) NOT NULL,
        "ServiceLocationId" bigint NOT NULL,
        "AssetTypeId" bigint,
        "AssetManufacturerId" bigint,
        "AssetModelId" bigint,
        "AssetDescription" text,
        "CustomerAssetNumber" character varying(100),
        "CustomerAssetName" character varying(200),
        "ManufacturerName" character varying(200),
        "ModelNumber" character varying(100),
        "SerialNumber" character varying(200),
        "ManufactureDate" date,
        "InstallDate" date,
        "InstalledWorkOrderId" bigint,
        "IsInstalledByCompany" boolean NOT NULL DEFAULT FALSE,
        "AssetStatusId" bigint NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(200),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(200),
        CONSTRAINT "PK_FgsAsset" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsAsset_AssetManufacturer" FOREIGN KEY ("AssetManufacturerId") REFERENCES asset."FgsAssetManufacturer" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAsset_AssetModel" FOREIGN KEY ("AssetModelId") REFERENCES asset."FgsAssetModel" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAsset_AssetStatus" FOREIGN KEY ("AssetStatusId") REFERENCES asset."FgsAssetStatus" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAsset_AssetType" FOREIGN KEY ("AssetTypeId") REFERENCES asset."FgsAssetType" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAsset_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES asset."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsAsset_ServiceLocationCache" FOREIGN KEY ("TenantId", "CompanyId", "ServiceLocationId") REFERENCES asset."FgsServiceLocationCache" ("TenantId", "CompanyId", "ServiceLocationId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE asset."FgsAsset" IS 'Stores customer-owned equipment and installed assets at service locations.';
    COMMENT ON COLUMN asset."FgsAsset"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN asset."FgsAsset"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN asset."FgsAsset"."Id" IS 'Unique asset identifier.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetGuid" IS 'Globally unique asset identifier used by integrations and external systems.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetNumber" IS 'User-visible asset number within the tenant company.';
    COMMENT ON COLUMN asset."FgsAsset"."ServiceLocationId" IS 'Service location where the asset is installed.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetTypeId" IS 'Optional catalog asset type reference.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetManufacturerId" IS 'Optional catalog manufacturer reference.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetModelId" IS 'Optional catalog model reference.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetDescription" IS 'Internal asset description.';
    COMMENT ON COLUMN asset."FgsAsset"."CustomerAssetNumber" IS 'Customer-provided asset number or tag.';
    COMMENT ON COLUMN asset."FgsAsset"."CustomerAssetName" IS 'Customer-provided asset name.';
    COMMENT ON COLUMN asset."FgsAsset"."ManufacturerName" IS 'Free-text manufacturer name when not linked to catalog.';
    COMMENT ON COLUMN asset."FgsAsset"."ModelNumber" IS 'Free-text model number when not linked to catalog.';
    COMMENT ON COLUMN asset."FgsAsset"."SerialNumber" IS 'Equipment serial number.';
    COMMENT ON COLUMN asset."FgsAsset"."ManufactureDate" IS 'Date the equipment was manufactured.';
    COMMENT ON COLUMN asset."FgsAsset"."InstallDate" IS 'Date the asset was installed at the service location.';
    COMMENT ON COLUMN asset."FgsAsset"."InstalledWorkOrderId" IS 'Work order that installed the asset. References job service; no FK by design.';
    COMMENT ON COLUMN asset."FgsAsset"."IsInstalledByCompany" IS 'Indicates whether the asset was installed by the service company.';
    COMMENT ON COLUMN asset."FgsAsset"."AssetStatusId" IS 'Current lifecycle status of the asset.';
    COMMENT ON COLUMN asset."FgsAsset"."IsActive" IS 'Indicates whether the asset record is active.';
    COMMENT ON COLUMN asset."FgsAsset"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN asset."FgsAsset"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN asset."FgsAsset"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN asset."FgsAsset"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_AssetManufacturerId" ON asset."FgsAsset" ("AssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_AssetModelId" ON asset."FgsAsset" ("AssetModelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_AssetStatusId" ON asset."FgsAsset" ("AssetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_AssetTypeId" ON asset."FgsAsset" ("AssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId" ON asset."FgsAsset" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_AssetManufacturerId" ON asset."FgsAsset" ("TenantId", "CompanyId", "AssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_AssetModelId" ON asset."FgsAsset" ("TenantId", "CompanyId", "AssetModelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_AssetStatusId" ON asset."FgsAsset" ("TenantId", "CompanyId", "AssetStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_AssetTypeId" ON asset."FgsAsset" ("TenantId", "CompanyId", "AssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_InstalledWorkOrderId" ON asset."FgsAsset" ("TenantId", "CompanyId", "InstalledWorkOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_IsActive" ON asset."FgsAsset" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_IsInstalledByCompany" ON asset."FgsAsset" ("TenantId", "CompanyId", "IsInstalledByCompany");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_SerialNumber" ON asset."FgsAsset" ("TenantId", "CompanyId", "SerialNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAsset_TenantId_CompanyId_ServiceLocationId" ON asset."FgsAsset" ("TenantId", "CompanyId", "ServiceLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAsset_AssetGuid" ON asset."FgsAsset" ("AssetGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAsset_TenantId_CompanyId_AssetNumber" ON asset."FgsAsset" ("TenantId", "CompanyId", "AssetNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetManufacturer_TenantId_CompanyId" ON asset."FgsAssetManufacturer" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetManufacturer_TenantId_CompanyId_IsActive" ON asset."FgsAssetManufacturer" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetManufacturer_TenantId_CompanyId_Name" ON asset."FgsAssetManufacturer" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAssetManufacturer_TenantId_CompanyId_Code" ON asset."FgsAssetManufacturer" ("TenantId", "CompanyId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_AssetManufacturerId" ON asset."FgsAssetModel" ("AssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_AssetTypeId" ON asset."FgsAssetModel" ("AssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_TenantId_CompanyId" ON asset."FgsAssetModel" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_TenantId_CompanyId_AssetManufacturerId" ON asset."FgsAssetModel" ("TenantId", "CompanyId", "AssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_TenantId_CompanyId_AssetTypeId" ON asset."FgsAssetModel" ("TenantId", "CompanyId", "AssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_TenantId_CompanyId_AssetTypeId_AssetManufacturerId" ON asset."FgsAssetModel" ("TenantId", "CompanyId", "AssetTypeId", "AssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetModel_TenantId_CompanyId_IsActive" ON asset."FgsAssetModel" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAssetModel_TenantCompanyManufacturerModelNumber" ON asset."FgsAssetModel" ("TenantId", "CompanyId", "AssetManufacturerId", "ModelNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetStatus_TenantId_CompanyId" ON asset."FgsAssetStatus" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetStatus_TenantId_CompanyId_IsActive" ON asset."FgsAssetStatus" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetStatus_TenantId_CompanyId_Name" ON asset."FgsAssetStatus" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAssetStatus_TenantId_CompanyId_Code" ON asset."FgsAssetStatus" ("TenantId", "CompanyId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetType_TenantId_CompanyId" ON asset."FgsAssetType" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetType_TenantId_CompanyId_IsActive" ON asset."FgsAssetType" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsAssetType_TenantId_CompanyId_Name" ON asset."FgsAssetType" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsAssetType_TenantId_CompanyId_Code" ON asset."FgsAssetType" ("TenantId", "CompanyId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsServiceLocationCache_TenantId_CompanyId_CustomerId" ON asset."FgsServiceLocationCache" ("TenantId", "CompanyId", "CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsServiceLocationCache_TenantId_CompanyId_LocationNumber" ON asset."FgsServiceLocationCache" ("TenantId", "CompanyId", "LocationNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON asset."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON asset."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON asset."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM asset."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152817_AddAssetSchema') THEN
    INSERT INTO asset."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611152817_AddAssetSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

