namespace Fgs.Bff.Application.Features.Lookups;

/// <summary>
/// Stable keys for BFF batch lookup orchestration. Maps 1:1 to owning-service GET lookup routes.
/// </summary>
public enum LookupKey
{
    // Glo (Setup, non-tenant)
    GloCountry,
    GloStateProvince,
    GloTimeZone,
    GloLanguage,
    GloLocationType,
    GloBusinessType,
    GloSetupDescriptionType,
    GloMasterEntityType,
    GloUnitOfMeasure,
    GloInventoryTransactionSource,
    GloInventoryTransactionType,
    GloAccountingIntegrationType,
    GloAppointmentAssignmentEventType,
    GloVehicleMaintenanceType,
    GloSetupTenantStatus,

    // Setup tenant catalog
    TechTrade,
    JobCategory,
    JobType,
    JobTypeCategory,
    JobTypeTask,
    BillingCategory,
    PriceBook,
    PriceBookItem,
    PricingMatrix,
    PricingMatrixLabor,
    PricingMatrixLaborTier,
    PricingMatrixMaterialTier,
    PricingMatrixOther,
    UniversalPricingService,
    UniversalMatrixItem,
    UniversalMatrixTier,
    UniversalMatrixAddOn,
    UniversalMatrixOneTimeFee,
    UniversalMatrixSizeTier,
    UniversalMatrixFrequencyDiscount,
    PaymentMethod,
    PaymentTerm,
    Tax,
    TaxAuthority,
    LaborRateType,
    TechSkillLevel,
    ResolutionCode,
    Timeslot,
    NonWorkingDate,
    Zone,
    Tag,
    TitleOfCourtesy,
    SetupDescription,
    BusinessType,
    TermsCondition,
    EntityDefaultTermsCondition,
    CommunicationTemplate,
    Employee,
    Vehicle,
    VehicleMaintenance,
    PostalCode,
    PostalCodeCity,
    LeadSource,
    LeadStatus,
    LeadDisqualificationReason,
    SalesActivityType,
    SalesActivityOutcome,
    SalesPipelineStatus,
    SalesDispositionReason,
    GlBreak,

    // User
    Role,
    Permission,
    DataAccess,
    RolePermission,
    RoleDataAccess,
    RoleMenu,
    UserRole,
    TenantMenu,
    ApiClient,
    ApiWebhook,
    ApiEvent,
    PublicEndpoint,

    // Asset
    Asset,
    AssetType,
    AssetStatus,
    AssetManufacturer,
    AssetModel,
    AssetAttribute,
    AssetAttributeOption,
    AssetAttributeValue,
    AssetWarranty,

    // Inventory
    InventoryItem,
    InventoryItemType,
    InventoryCategory,
    InventorySubCategory,
    InventoryLocation,
    InventorySerial,
    Vendor,
    VendorInventoryItem,
    TruckStockTemplate,

    // Billing / CRM
    Invoice,
    Customer
}
