namespace Fgs.Inventory.Application.Features.Vendors.Dtos;

public sealed record FgsVendorSummaryDto(
    long Id,
    string VendorCode,
    string Name,
    string? LegalName,
    string VendorType,
    string VendorStatus,
    string? VendorAccountNumber,
    long? PaymentTermId,
    string? ContactName,
    string? ContactTitle,
    string? Email,
    string? PurchaseOrderEmail,
    string? PhoneNumber,
    string? MobileNumber,
    string? FaxNumber,
    string? Website,
    string? Address1,
    string? Address2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? Country,
    string? TaxIdNumber,
    string? LicenseNumber,
    string? InsurancePolicyNumber,
    string? Notes,
    bool Is1099Eligible,
    bool IsActive);

public sealed record FgsVendorDetailDto(
    long Id,
    string VendorCode,
    string Name,
    string? LegalName,
    string VendorType,
    string VendorStatus,
    string? VendorAccountNumber,
    long? PaymentTermId,
    string? ContactName,
    string? ContactTitle,
    string? Email,
    string? PurchaseOrderEmail,
    string? PhoneNumber,
    string? MobileNumber,
    string? FaxNumber,
    string? Website,
    string? Address1,
    string? Address2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? Country,
    string? TaxIdNumber,
    string? LicenseNumber,
    string? InsurancePolicyNumber,
    string? Notes,
    bool Is1099Eligible,
    bool IsActive);

public sealed record FgsVendorLookupDto(
    long Id,
    string VendorCode,
    string Name);

public sealed record FgsVendorCreateDto(
    string VendorCode,
    string Name,
    string? LegalName,
    string VendorType,
    string? VendorStatus,
    string? VendorAccountNumber,
    long? PaymentTermId,
    string? ContactName,
    string? ContactTitle,
    string? Email,
    string? PurchaseOrderEmail,
    string? PhoneNumber,
    string? MobileNumber,
    string? FaxNumber,
    string? Website,
    string? Address1,
    string? Address2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? Country,
    string? TaxIdNumber,
    string? LicenseNumber,
    string? InsurancePolicyNumber,
    string? Notes,
    bool Is1099Eligible);

public sealed record FgsVendorUpdateDto(
    string VendorCode,
    string Name,
    string? LegalName,
    string VendorType,
    string VendorStatus,
    string? VendorAccountNumber,
    long? PaymentTermId,
    string? ContactName,
    string? ContactTitle,
    string? Email,
    string? PurchaseOrderEmail,
    string? PhoneNumber,
    string? MobileNumber,
    string? FaxNumber,
    string? Website,
    string? Address1,
    string? Address2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? Country,
    string? TaxIdNumber,
    string? LicenseNumber,
    string? InsurancePolicyNumber,
    string? Notes,
    bool Is1099Eligible);

public sealed record FgsVendorPatchDto(
    string? VendorCode,
    string? Name,
    string? LegalName,
    string? VendorType,
    string? VendorStatus,
    string? VendorAccountNumber,
    long? PaymentTermId,
    string? ContactName,
    string? ContactTitle,
    string? Email,
    string? PurchaseOrderEmail,
    string? PhoneNumber,
    string? MobileNumber,
    string? FaxNumber,
    string? Website,
    string? Address1,
    string? Address2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? Country,
    string? TaxIdNumber,
    string? LicenseNumber,
    string? InsurancePolicyNumber,
    string? Notes,
    bool? Is1099Eligible,
    bool? IsActive);

public sealed record FgsVendorListFilters(
    string? VendorCode = null,
    string? Name = null);
