DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'crm') THEN
        CREATE SCHEMA crm;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS crm."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260603212808_InitialSchema') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603212808_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'crm') THEN
            CREATE SCHEMA crm;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE TABLE crm."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE crm."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the CRM schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON crm."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON crm."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON crm."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604132121_AddFgsTenantCompanyCache', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE TABLE crm."CrmOutboxMessage" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint,
        "CompanyId" bigint,
        "EventType" character varying(150) NOT NULL,
        "AggregateType" character varying(100),
        "AggregateId" character varying(100),
        "CorrelationId" uuid NOT NULL,
        "CausationId" uuid,
        "ExchangeName" character varying(200),
        "RoutingKey" character varying(200),
        "Payload" jsonb NOT NULL,
        "Headers" jsonb,
        "Status" character varying(50) NOT NULL DEFAULT 'Pending',
        "RetryCount" integer NOT NULL DEFAULT 0,
        "MaxRetryCount" integer NOT NULL DEFAULT 10,
        "NextRetryOn" timestamptz,
        "ProcessedOn" timestamptz,
        "LastError" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_CrmOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_CorrelationId" ON crm."CrmOutboxMessage" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_EventType" ON crm."CrmOutboxMessage" ("EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_Status_NextRetryOn" ON crm."CrmOutboxMessage" ("Status", "NextRetryOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_TenantId" ON crm."CrmOutboxMessage" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605152149_AddCrmOutboxMessage', '10.0.8');
    END IF;
END $EF$;
COMMIT;

