DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'crm') THEN
        CREATE SCHEMA crm;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS crm."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260603212808_InitialSchema') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603212808_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'crm') THEN
            CREATE SCHEMA crm;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE TABLE crm."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE crm."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the CRM schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN crm."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON crm."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON crm."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON crm."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132121_AddFgsTenantCompanyCache') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604132121_AddFgsTenantCompanyCache', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE TABLE crm."CrmOutboxMessage" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint,
        "CompanyId" bigint,
        "EventType" character varying(150) NOT NULL,
        "AggregateType" character varying(100),
        "AggregateId" character varying(100),
        "CorrelationId" uuid NOT NULL,
        "CausationId" uuid,
        "ExchangeName" character varying(200),
        "RoutingKey" character varying(200),
        "Payload" jsonb NOT NULL,
        "Headers" jsonb,
        "Status" character varying(50) NOT NULL DEFAULT 'Pending',
        "RetryCount" integer NOT NULL DEFAULT 0,
        "MaxRetryCount" integer NOT NULL DEFAULT 10,
        "NextRetryOn" timestamptz,
        "ProcessedOn" timestamptz,
        "LastError" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_CrmOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_CorrelationId" ON crm."CrmOutboxMessage" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_EventType" ON crm."CrmOutboxMessage" ("EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_Status_NextRetryOn" ON crm."CrmOutboxMessage" ("Status", "NextRetryOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    CREATE INDEX "IX_CrmOutboxMessage_TenantId" ON crm."CrmOutboxMessage" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152149_AddCrmOutboxMessage') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605152149_AddCrmOutboxMessage', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260606084935_StandardizeAuditColumnsToVarchar') THEN
    ALTER TABLE crm."CrmOutboxMessage" ALTER COLUMN "UpdatedBy" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260606084935_StandardizeAuditColumnsToVarchar') THEN
    ALTER TABLE crm."CrmOutboxMessage" ALTER COLUMN "CreatedBy" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260606084935_StandardizeAuditColumnsToVarchar') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260606084935_StandardizeAuditColumnsToVarchar', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmCustomer" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CustomerNumber" character varying(30) NOT NULL,
        "LastServiceLocationSequence" integer NOT NULL DEFAULT 0,
        "Name" character varying(200) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "AddressLine1" character varying(200),
        "AddressLine2" character varying(200),
        "AddressLine3" character varying(200),
        "AddressLine4" character varying(200),
        "City" character varying(100),
        "State" character varying(100),
        "County" character varying(100),
        "Country" character varying(100),
        "PostalCode" character varying(20),
        "FormattedAddress" character varying(1000),
        "Latitude" numeric(18,10),
        "Longitude" numeric(18,10),
        "PlaceId" character varying(500),
        "DefaultPaymentTermId" bigint,
        "DefaultMaterialPricingMatrixId" bigint,
        "DefaultLaborPricingMatrixId" bigint,
        "DefaultOtherPricingMatrixId" bigint,
        "DefaultPORequired" boolean NOT NULL DEFAULT FALSE,
        "TaxExempt" boolean NOT NULL DEFAULT FALSE,
        "TaxExemptNumber" character varying(100),
        "CustomerAccountNumber" character varying(100),
        "ExternalEntityId" character varying(200),
        "ExternalVersion" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmCustomer" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmCustomer_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmEntityTag" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TagId" bigint NOT NULL,
        "EntityTypeId" integer NOT NULL,
        "EntityId" bigint NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmEntityTag" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmEntityTag_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmLead" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED ALWAYS AS IDENTITY,
        "LeadStatusId" bigint NOT NULL,
        "LeadSourceId" bigint NOT NULL,
        "CampaignId" bigint,
        "LeadSummary" character varying(255) NOT NULL,
        "LeadDescription" text,
        "FirstName" character varying(100),
        "LastName" character varying(100),
        "CompanyName" character varying(200),
        "CustomerTypeId" bigint,
        "Email" character varying(255),
        "Phone" character varying(50),
        "PrimaryContactMethodId" bigint,
        "ServiceZipCode" character varying(20),
        "AssignedToUserId" bigint,
        "LeadReceivedOn" timestamp with time zone NOT NULL,
        "QualifiedOn" timestamp with time zone,
        "DisqualifiedOn" timestamp with time zone,
        "DisqualificationReasonId" bigint,
        "CustomerId" bigint,
        "ConvertedOn" timestamp with time zone,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmLead" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmLead_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE crm."CrmLead" IS 'Stores inbound sales inquiries and prospects prior to qualification and conversion into customers and opportunities.';
    COMMENT ON COLUMN crm."CrmLead"."LeadStatusId" IS 'Current lead status selected from setup.FgsLeadStatus.';
    COMMENT ON COLUMN crm."CrmLead"."LeadSourceId" IS 'Source that generated the lead selected from setup.FgsLeadSource.';
    COMMENT ON COLUMN crm."CrmLead"."CampaignId" IS 'Marketing campaign associated with the lead.';
    COMMENT ON COLUMN crm."CrmLead"."LeadSummary" IS 'Short summary describing the lead inquiry.';
    COMMENT ON COLUMN crm."CrmLead"."LeadDescription" IS 'Detailed description of the lead inquiry and customer requirements.';
    COMMENT ON COLUMN crm."CrmLead"."FirstName" IS 'Lead contact first name.';
    COMMENT ON COLUMN crm."CrmLead"."LastName" IS 'Lead contact last name.';
    COMMENT ON COLUMN crm."CrmLead"."CompanyName" IS 'Company or organization associated with the lead.';
    COMMENT ON COLUMN crm."CrmLead"."CustomerTypeId" IS 'Customer type associated with the lead.';
    COMMENT ON COLUMN crm."CrmLead"."Email" IS 'Primary email address for the lead.';
    COMMENT ON COLUMN crm."CrmLead"."Phone" IS 'Primary phone number for the lead.';
    COMMENT ON COLUMN crm."CrmLead"."PrimaryContactMethodId" IS 'Preferred or originating contact method for the lead.';
    COMMENT ON COLUMN crm."CrmLead"."ServiceZipCode" IS 'ZIP or postal code where service is requested.';
    COMMENT ON COLUMN crm."CrmLead"."AssignedToUserId" IS 'User assigned to work the lead.';
    COMMENT ON COLUMN crm."CrmLead"."LeadReceivedOn" IS 'Date and time the lead was originally received.';
    COMMENT ON COLUMN crm."CrmLead"."QualifiedOn" IS 'Date and time the lead was qualified.';
    COMMENT ON COLUMN crm."CrmLead"."DisqualifiedOn" IS 'Date and time the lead was disqualified.';
    COMMENT ON COLUMN crm."CrmLead"."DisqualificationReasonId" IS 'Reason the lead was disqualified selected from setup.FgsLeadDisqualificationReason.';
    COMMENT ON COLUMN crm."CrmLead"."CustomerId" IS 'Customer record created from this lead after conversion.';
    COMMENT ON COLUMN crm."CrmLead"."ConvertedOn" IS 'Date and time the lead was converted into a customer.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmNote" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EntityTypeId" integer NOT NULL,
        "EntityId" bigint NOT NULL,
        "NoteTypeId" smallint NOT NULL,
        "Title" character varying(200),
        "NoteText" text NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsPinned" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmNote" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CrmNote_EntityTypeId" CHECK ("EntityTypeId" BETWEEN 1 AND 5),
        CONSTRAINT "CK_CrmNote_NoteTypeId" CHECK ("NoteTypeId" BETWEEN 1 AND 5),
        CONSTRAINT "FK_CrmNote_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmServiceLocation" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" bigint NOT NULL,
        "LocationSequence" integer NOT NULL,
        "LocationNumber" character varying(50) NOT NULL,
        CONSTRAINT "PK_CrmServiceLocation" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmServiceLocation_Customer" FOREIGN KEY ("CustomerId") REFERENCES crm."CrmCustomer" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CrmServiceLocation_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmContact" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" bigint,
        "ServiceLocationId" bigint,
        "DisplayName" character varying(200) NOT NULL,
        "Title" character varying(100),
        "DepartmentName" character varying(100),
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsDefaultContact" boolean NOT NULL DEFAULT FALSE,
        "CanReceiveEstimates" boolean NOT NULL DEFAULT FALSE,
        "CanReceiveInvoices" boolean NOT NULL DEFAULT FALSE,
        "CanReceiveAppointments" boolean NOT NULL DEFAULT TRUE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmContact" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CrmContact_Owner" CHECK (("CustomerId" IS NOT NULL AND "ServiceLocationId" IS NULL) OR ("CustomerId" IS NULL AND "ServiceLocationId" IS NOT NULL)),
        CONSTRAINT "FK_CrmContact_Customer" FOREIGN KEY ("CustomerId") REFERENCES crm."CrmCustomer" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CrmContact_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_CrmContact_ServiceLocation" FOREIGN KEY ("ServiceLocationId") REFERENCES crm."CrmServiceLocation" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE TABLE crm."CrmContactCommunication" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ContactId" bigint NOT NULL,
        "CommunicationTypeId" smallint NOT NULL,
        "Label" character varying(100),
        "Value" character varying(1000) NOT NULL,
        "Extension" character varying(20),
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsPrimary" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmContactCommunication" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CrmContactCommunication_CommunicationTypeId" CHECK ("CommunicationTypeId" BETWEEN 1 AND 7),
        CONSTRAINT "FK_CrmContactCommunication_Contact" FOREIGN KEY ("ContactId") REFERENCES crm."CrmContact" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CrmContactCommunication_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContact_CustomerId" ON crm."CrmContact" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContact_DisplayName" ON crm."CrmContact" ("TenantId", "CompanyId", "DisplayName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContact_IsActive" ON crm."CrmContact" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContact_ServiceLocationId" ON crm."CrmContact" ("ServiceLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmContact_DefaultCustomer" ON crm."CrmContact" ("TenantId", "CompanyId", "CustomerId") WHERE "IsDefaultContact" = true AND "CustomerId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmContact_DefaultServiceLocation" ON crm."CrmContact" ("TenantId", "CompanyId", "ServiceLocationId") WHERE "IsDefaultContact" = true AND "ServiceLocationId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContactCommunication_CommunicationTypeId" ON crm."CrmContactCommunication" ("TenantId", "CompanyId", "CommunicationTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContactCommunication_ContactId" ON crm."CrmContactCommunication" ("TenantId", "CompanyId", "ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContactCommunication_ContactId1" ON crm."CrmContactCommunication" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContactCommunication_IsActive" ON crm."CrmContactCommunication" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmContactCommunication_Value" ON crm."CrmContactCommunication" ("TenantId", "CompanyId", "Value");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmContactCommunication_Primary" ON crm."CrmContactCommunication" ("TenantId", "CompanyId", "ContactId", "CommunicationTypeId") WHERE "IsPrimary" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmCustomer_CustomerAccountNumber" ON crm."CrmCustomer" ("TenantId", "CompanyId", "CustomerAccountNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmCustomer_DisplayName" ON crm."CrmCustomer" ("TenantId", "CompanyId", "DisplayName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmCustomer_ExternalEntityId" ON crm."CrmCustomer" ("TenantId", "CompanyId", "ExternalEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmCustomer_IsActive" ON crm."CrmCustomer" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmCustomer_CustomerNumber" ON crm."CrmCustomer" ("TenantId", "CompanyId", "CustomerNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmEntityTag_Entity" ON crm."CrmEntityTag" ("TenantId", "CompanyId", "EntityTypeId", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmEntityTag_TagId" ON crm."CrmEntityTag" ("TenantId", "CompanyId", "TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmEntityTag" ON crm."CrmEntityTag" ("TenantId", "CompanyId", "TagId", "EntityTypeId", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId" ON crm."CrmLead" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_AssignedToUserId" ON crm."CrmLead" ("TenantId", "CompanyId", "AssignedToUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_CampaignId" ON crm."CrmLead" ("TenantId", "CompanyId", "CampaignId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_CustomerId" ON crm."CrmLead" ("TenantId", "CompanyId", "CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_CustomerTypeId" ON crm."CrmLead" ("TenantId", "CompanyId", "CustomerTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_DisqualificationReasonId" ON crm."CrmLead" ("TenantId", "CompanyId", "DisqualificationReasonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_LeadReceivedOn" ON crm."CrmLead" ("TenantId", "CompanyId", "LeadReceivedOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_LeadSourceId" ON crm."CrmLead" ("TenantId", "CompanyId", "LeadSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_LeadStatusId" ON crm."CrmLead" ("TenantId", "CompanyId", "LeadStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_PrimaryContactMethodId" ON crm."CrmLead" ("TenantId", "CompanyId", "PrimaryContactMethodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmLead_TenantId_CompanyId_ServiceZipCode" ON crm."CrmLead" ("TenantId", "CompanyId", "ServiceZipCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmNote_Entity" ON crm."CrmNote" ("TenantId", "CompanyId", "EntityTypeId", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmNote_Entity_DisplayOrder" ON crm."CrmNote" ("TenantId", "CompanyId", "EntityTypeId", "EntityId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmNote_IsActive" ON crm."CrmNote" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmNote_IsPinned" ON crm."CrmNote" ("TenantId", "CompanyId", "IsPinned");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmNote_NoteTypeId" ON crm."CrmNote" ("TenantId", "CompanyId", "NoteTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmServiceLocation_CustomerId" ON crm."CrmServiceLocation" ("TenantId", "CompanyId", "CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE INDEX "IX_CrmServiceLocation_CustomerId1" ON crm."CrmServiceLocation" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmServiceLocation_Customer_LocationSequence" ON crm."CrmServiceLocation" ("TenantId", "CompanyId", "CustomerId", "LocationSequence");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    CREATE UNIQUE INDEX "UQ_CrmServiceLocation_LocationNumber" ON crm."CrmServiceLocation" ("TenantId", "CompanyId", "LocationNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260611122230_AddCrmCoreEntities') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611122230_AddCrmCoreEntities', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE TABLE crm."CrmReminder" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EntityId" integer,
        "EntityValue" bigint,
        "PriorityId" smallint NOT NULL DEFAULT 2,
        "StatusId" smallint NOT NULL DEFAULT 1,
        "Subject" character varying(250) NOT NULL,
        "ReminderText" text NOT NULL,
        "DueOn" timestamptz NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmReminder" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CrmReminder_Entity" CHECK (("EntityId" IS NULL AND "EntityValue" IS NULL) OR ("EntityId" IS NOT NULL AND "EntityValue" IS NOT NULL)),
        CONSTRAINT "CK_CrmReminder_PriorityId" CHECK ("PriorityId" IN (1, 2, 3, 4)),
        CONSTRAINT "CK_CrmReminder_StatusId" CHECK ("StatusId" IN (1, 2, 3)),
        CONSTRAINT "FK_CrmReminder_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE crm."CrmReminder" IS 'Stores reminders assigned to users or roles for follow-up, review, approval, notification, and workflow activities.';
    COMMENT ON COLUMN crm."CrmReminder"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."CrmReminder"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN crm."CrmReminder"."Id" IS 'Primary key.';
    COMMENT ON COLUMN crm."CrmReminder"."EntityId" IS 'Related entity identifier.';
    COMMENT ON COLUMN crm."CrmReminder"."EntityValue" IS 'Primary key value of the related business record.';
    COMMENT ON COLUMN crm."CrmReminder"."PriorityId" IS 'Priority. 1=Low, 2=Normal, 3=High, 4=Critical.';
    COMMENT ON COLUMN crm."CrmReminder"."StatusId" IS 'Status. 1=Open, 2=Completed, 3=Cancelled.';
    COMMENT ON COLUMN crm."CrmReminder"."Subject" IS 'Reminder subject.';
    COMMENT ON COLUMN crm."CrmReminder"."ReminderText" IS 'Reminder details, notes, instructions, or comments.';
    COMMENT ON COLUMN crm."CrmReminder"."DueOn" IS 'Date and time the reminder is due.';
    COMMENT ON COLUMN crm."CrmReminder"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN crm."CrmReminder"."CreatedBy" IS 'User identifier of the user who created the record.';
    COMMENT ON COLUMN crm."CrmReminder"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN crm."CrmReminder"."UpdatedBy" IS 'User identifier of the user who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE TABLE crm."CrmReminderAssignment" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ReminderId" bigint NOT NULL,
        "UserId" bigint,
        "RoleId" bigint,
        "ResponseText" text,
        "CompletedOn" timestamptz,
        "CompletedByUserId" bigint,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmReminderAssignment" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CrmReminderAssignment_Assignee" CHECK (("UserId" IS NOT NULL AND "RoleId" IS NULL) OR ("UserId" IS NULL AND "RoleId" IS NOT NULL)),
        CONSTRAINT "FK_CrmReminderAssignment_CrmReminder_ReminderId" FOREIGN KEY ("ReminderId") REFERENCES crm."CrmReminder" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CrmReminderAssignment_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE crm."CrmReminderAssignment" IS 'Stores user and role assignments for reminders.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."Id" IS 'Primary key.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."ReminderId" IS 'Related reminder identifier.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."UserId" IS 'Assigned user identifier.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."RoleId" IS 'Assigned role identifier.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."ResponseText" IS 'Response or completion notes entered by the assignee.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."CompletedOn" IS 'Date and time the assignment was completed.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."CompletedByUserId" IS 'User identifier of the user who completed the reminder.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."CreatedBy" IS 'User identifier of the user who created the record.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN crm."CrmReminderAssignment"."UpdatedBy" IS 'User identifier of the user who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminder_CreatedBy" ON crm."CrmReminder" ("TenantId", "CompanyId", "CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminder_EntityId_EntityValue" ON crm."CrmReminder" ("TenantId", "CompanyId", "EntityId", "EntityValue");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminder_StatusId_DueOn" ON crm."CrmReminder" ("TenantId", "CompanyId", "StatusId", "DueOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminder_TenantId_CompanyId" ON crm."CrmReminder" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminderAssignment_ReminderId" ON crm."CrmReminderAssignment" ("TenantId", "CompanyId", "ReminderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminderAssignment_ReminderId1" ON crm."CrmReminderAssignment" ("ReminderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminderAssignment_RoleId" ON crm."CrmReminderAssignment" ("TenantId", "CompanyId", "RoleId") WHERE "RoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminderAssignment_TenantId_CompanyId" ON crm."CrmReminderAssignment" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    CREATE INDEX "IX_CrmReminderAssignment_UserId" ON crm."CrmReminderAssignment" ("TenantId", "CompanyId", "UserId") WHERE "UserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20260615140336_AddCrmReminderEntities') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260615140336_AddCrmReminderEntities', '10.0.8');
    END IF;
END $EF$;
COMMIT;

