START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20261001205705_AddCrmDefaultCustomerAndServiceLocation') THEN
    CREATE TABLE crm."CrmDefaultCustomer" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DefaultPaymentTermId" bigint,
        "DefaultMaterialPricingMatrixId" bigint,
        "DefaultLaborPricingMatrixId" bigint,
        "DefaultOtherPricingMatrixId" bigint,
        "DefaultPORequired" boolean NOT NULL,
        "TaxExempt" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmDefaultCustomer" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmDefaultCustomer_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE crm."CrmDefaultCustomer" IS 'Stores default values used when creating new customers.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."Id" IS 'Primary key.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."DefaultPaymentTermId" IS 'Default payment term applied to a new customer.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."DefaultMaterialPricingMatrixId" IS 'Default material pricing matrix applied to a new customer.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."DefaultLaborPricingMatrixId" IS 'Default labor pricing matrix applied to a new customer.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."DefaultOtherPricingMatrixId" IS 'Default miscellaneous pricing matrix applied to a new customer.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."DefaultPORequired" IS 'Indicates whether a purchase order is required by default for a new customer.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."TaxExempt" IS 'Indicates whether a new customer is tax exempt by default.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."UpdatedOn" IS 'Last update timestamp.';
    COMMENT ON COLUMN crm."CrmDefaultCustomer"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20261001205705_AddCrmDefaultCustomerAndServiceLocation') THEN
    CREATE TABLE crm."CrmDefaultServiceLocation" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DefaultLaborPricingMatrixId" bigint,
        "DefaultMaterialPricingMatrixId" bigint,
        "DefaultOtherPricingMatrixId" bigint,
        "DefaultPaymentMethodId" bigint,
        "EmailAllowed" boolean NOT NULL,
        "EstimateEmailTemplateId" bigint,
        "EstimateSmsTemplateId" bigint,
        "InvoiceEmailTemplateId" bigint,
        "InvoiceSmsTemplateId" bigint,
        "SmsAllowed" boolean NOT NULL,
        "TaxExempt" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100) NOT NULL,
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_CrmDefaultServiceLocation" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrmDefaultServiceLocation_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES crm."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE crm."CrmDefaultServiceLocation" IS 'Stores default values used when creating new customer service locations.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."Id" IS 'Primary key.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."DefaultLaborPricingMatrixId" IS 'Default labor pricing matrix applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."DefaultMaterialPricingMatrixId" IS 'Default material pricing matrix applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."DefaultOtherPricingMatrixId" IS 'Default miscellaneous pricing matrix applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."DefaultPaymentMethodId" IS 'Default payment method applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."EmailAllowed" IS 'Indicates whether email communication is enabled by default for a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."EstimateEmailTemplateId" IS 'Default estimate email template applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."EstimateSmsTemplateId" IS 'Default estimate SMS template applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."InvoiceEmailTemplateId" IS 'Default invoice email template applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."InvoiceSmsTemplateId" IS 'Default invoice SMS template applied to a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."SmsAllowed" IS 'Indicates whether SMS communication is enabled by default for a new service location.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."TaxExempt" IS 'Indicates whether a new service location is tax exempt by default.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."UpdatedOn" IS 'Last update timestamp.';
    COMMENT ON COLUMN crm."CrmDefaultServiceLocation"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM crm."__EFMigrationsHistory" WHERE "MigrationId" = '20261001205705_AddCrmDefaultCustomerAndServiceLocation') THEN
    INSERT INTO crm."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261001205705_AddCrmDefaultCustomerAndServiceLocation', '10.0.8');
    END IF;
END $EF$;
COMMIT;

