using Fgs.Asset.Application.Abstractions.AssetAttributes;
using Fgs.Asset.Application.Features.AssetAttributes.Dtos;
using Fgs.Asset.Domain.Entities;
using Fgs.Asset.Infrastructure.Common;
using Fgs.Asset.Infrastructure.Database;
using Fgs.Persistence.Abstractions;
using Microsoft.EntityFrameworkCore;
namespace Fgs.Asset.Infrastructure.AssetAttributes;
public sealed class FgsAssetAttributeWriteService : IFgsAssetAttributeWriteService
{
    private readonly FgsAssetDbContext _context; private readonly IUnitOfWork _unitOfWork; private readonly AssetEntityAuditHelper _auditHelper;
    public FgsAssetAttributeWriteService(FgsAssetDbContext context, IUnitOfWork unitOfWork, AssetEntityAuditHelper auditHelper) { _context = context; _unitOfWork = unitOfWork; _auditHelper = auditHelper; }
    public async Task<FgsAssetAttributeDetailDto> CreateAsync(FgsAssetAttributeCreateDto dto, CancellationToken cancellationToken = default) { var entity = MapCreate(dto); _auditHelper.StampForCreate(entity); await _context.FgsAssetAttributes.AddAsync(entity, cancellationToken); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    public async Task<FgsAssetAttributeDetailDto> UpdateAsync(long id, FgsAssetAttributeUpdateDto dto, CancellationToken cancellationToken = default) { var entity = await Find(id, cancellationToken) ?? throw new KeyNotFoundException($"Asset Attribute '{id}' was not found."); ApplyUpdate(entity, dto); _auditHelper.StampForUpdate(entity); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    public async Task<FgsAssetAttributeDetailDto> PatchAsync(long id, FgsAssetAttributePatchDto dto, CancellationToken cancellationToken = default) { var entity = await Find(id, cancellationToken) ?? throw new KeyNotFoundException($"Asset Attribute '{id}' was not found."); ApplyPatch(entity, dto); _auditHelper.StampForUpdate(entity); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    private async Task<FgsAssetAttribute?> Find(long id, CancellationToken ct) => await _context.FgsAssetAttributes.FirstOrDefaultAsync(x => x.Id == id, ct);
    private static FgsAssetAttribute MapCreate(FgsAssetAttributeCreateDto dto) => new() { AssetTypeId = dto.AssetTypeId, AttributeCode = dto.AttributeCode.Trim().ToUpperInvariant(), AttributeName = dto.AttributeName.Trim(), InputType = dto.InputType.Trim().ToUpperInvariant(), DefaultOptionId = dto.DefaultOptionId, DefaultValueText = Trim(dto.DefaultValueText), DefaultValueInteger = dto.DefaultValueInteger, DefaultValueDecimal = dto.DefaultValueDecimal, DefaultValueDate = dto.DefaultValueDate, DefaultValueBoolean = dto.DefaultValueBoolean, IsRequired = dto.IsRequired, IsSearchable = dto.IsSearchable, DisplayOrder = dto.DisplayOrder };
    private static void ApplyUpdate(FgsAssetAttribute e, FgsAssetAttributeUpdateDto dto) { e.AssetTypeId = dto.AssetTypeId; e.AttributeCode = dto.AttributeCode.Trim().ToUpperInvariant(); e.AttributeName = dto.AttributeName.Trim(); e.InputType = dto.InputType.Trim().ToUpperInvariant(); e.DefaultOptionId = dto.DefaultOptionId; e.DefaultValueText = Trim(dto.DefaultValueText); e.DefaultValueInteger = dto.DefaultValueInteger; e.DefaultValueDecimal = dto.DefaultValueDecimal; e.DefaultValueDate = dto.DefaultValueDate; e.DefaultValueBoolean = dto.DefaultValueBoolean; e.IsRequired = dto.IsRequired; e.IsSearchable = dto.IsSearchable; e.DisplayOrder = dto.DisplayOrder; }
    private static void ApplyPatch(FgsAssetAttribute e, FgsAssetAttributePatchDto dto) { if (dto.AssetTypeId.HasValue) e.AssetTypeId = dto.AssetTypeId.Value; if (dto.AttributeCode is not null) e.AttributeCode = dto.AttributeCode.Trim().ToUpperInvariant(); if (dto.AttributeName is not null) e.AttributeName = dto.AttributeName.Trim(); if (dto.InputType is not null) e.InputType = dto.InputType.Trim().ToUpperInvariant(); if (dto.DefaultOptionId.HasValue) e.DefaultOptionId = dto.DefaultOptionId; if (dto.DefaultValueText is not null) e.DefaultValueText = Trim(dto.DefaultValueText); if (dto.DefaultValueInteger.HasValue) e.DefaultValueInteger = dto.DefaultValueInteger; if (dto.DefaultValueDecimal.HasValue) e.DefaultValueDecimal = dto.DefaultValueDecimal; if (dto.DefaultValueDate.HasValue) e.DefaultValueDate = dto.DefaultValueDate; if (dto.DefaultValueBoolean.HasValue) e.DefaultValueBoolean = dto.DefaultValueBoolean; if (dto.IsRequired.HasValue) e.IsRequired = dto.IsRequired.Value; if (dto.IsSearchable.HasValue) e.IsSearchable = dto.IsSearchable.Value; if (dto.DisplayOrder.HasValue) e.DisplayOrder = dto.DisplayOrder.Value; if (dto.IsActive.HasValue) e.IsActive = dto.IsActive.Value; }
    private static string? Trim(string? v) => string.IsNullOrWhiteSpace(v) ? null : v.Trim();
    private static FgsAssetAttributeDetailDto Map(FgsAssetAttribute e) => new(e.Id, e.AssetTypeId, e.AttributeCode, e.AttributeName, e.InputType, e.DefaultOptionId, e.DefaultValueText, e.DefaultValueInteger, e.DefaultValueDecimal, e.DefaultValueDate, e.DefaultValueBoolean, e.IsRequired, e.IsSearchable, e.DisplayOrder, e.IsActive);
}
