// <auto-generated />
using System;
using Fgs.Notification.Domain.Enums;
using Fgs.Notification.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fgs.Notification.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FgsNotificationDbContext))]
    partial class FgsNotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification", "notification_status", new[] { "Queued", "Sending", "Sent", "Delivered", "Opened", "Clicked", "Failed", "Undelivered", "Bounced", "Cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification", "source_application", new[] { "FgsWeb", "FgsMobile", "CustomerPortal", "TechnicianPortal", "WorkflowEngine", "Scheduler", "CreditCard", "CreditCardWidget", "Api", "FgsAddon" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fgs.Notification.Domain.Entities.FgsEmailHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("BccEmailAddresses")
                        .HasColumnType("jsonb")
                        .HasComment("JSON array containing blind carbon copy recipient email addresses.");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Final email body that was sent to the recipient.");

                    b.Property<string>("CcEmailAddresses")
                        .HasColumnType("jsonb")
                        .HasComment("JSON array containing carbon copy recipient email addresses.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasComment("Company identifier.");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User or process that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<DateTimeOffset?>("DeliveredOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the email was confirmed as delivered by the provider.");

                    b.Property<long?>("EmailTemplateId")
                        .HasColumnType("bigint")
                        .HasComment("Email template used to generate the email.");

                    b.Property<DateTimeOffset?>("FailedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the email failed to send or deliver.");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasComment("Failure reason returned by the email provider when send fails.");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Sender display name.");

                    b.Property<string>("FromEmailAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Sender email address.");

                    b.Property<DateTimeOffset?>("OpenedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the email was opened.");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Provider-specific message identifier used for troubleshooting and webhook tracking.");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Email provider used to send the message.");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the associated business record.");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Business record associated with the email such as Estimate, Invoice, WorkOrder, Opportunity, Customer, or User.");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the email was sent.");

                    b.Property<NotificationSourceApplication>("SourceApplication")
                        .HasColumnType("notification.source_application")
                        .HasComment("Application or component that originated the email.");

                    b.Property<NotificationStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("notification.notification_status")
                        .HasDefaultValue(NotificationStatus.Queued)
                        .HasComment("Current notification status.");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Email subject line.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("Tenant identifier.");

                    b.Property<string>("ToEmailAddresses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("JSON array containing recipient email addresses.");

                    b.HasKey("Id")
                        .HasName("PK_FgsEmailHistory");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("IX_FgsEmailHistory_ProviderMessageId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsEmailHistory_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "SentOn")
                        .HasDatabaseName("IX_FgsEmailHistory_SentOn");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_FgsEmailHistory_Status");

                    b.HasIndex("TenantId", "CompanyId", "RecordType", "RecordId")
                        .HasDatabaseName("IX_FgsEmailHistory_Record");

                    b.ToTable("FgsEmailHistory", "notification", t =>
                        {
                            t.HasComment("Stores outbound email history for business entities and provides a permanent audit trail of email communications.");
                        });
                });

            modelBuilder.Entity("Fgs.Notification.Domain.Entities.FgsProcessedIntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ProcessedOn")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_FgsProcessedIntegrationEvent_MessageId");

                    b.ToTable("FgsProcessedIntegrationEvent", "notification");
                });

            modelBuilder.Entity("Fgs.Notification.Domain.Entities.FgsSmsHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasComment("Company identifier.");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User or process that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<DateTimeOffset?>("DeliveredOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the SMS was confirmed as delivered by the provider.");

                    b.Property<DateTimeOffset?>("FailedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the SMS failed to send or deliver.");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasComment("Failure reason returned by the SMS provider.");

                    b.Property<string>("FromPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Phone number or short code used to send the SMS.");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Final SMS message that was sent to the recipient.");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Provider-specific message identifier used for troubleshooting and webhook tracking.");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("SMS provider used to send the message.");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the associated business record.");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Business record associated with the SMS such as Estimate, Invoice, WorkOrder, Opportunity, Customer, or User.");

                    b.Property<short>("SegmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasComment("Number of SMS segments billed by the provider.");

                    b.Property<DateTimeOffset?>("SentOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the SMS was sent.");

                    b.Property<NotificationSourceApplication>("SourceApplication")
                        .HasColumnType("notification.source_application")
                        .HasComment("Application or component that originated the SMS.");

                    b.Property<NotificationStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("notification.notification_status")
                        .HasDefaultValue(NotificationStatus.Queued)
                        .HasComment("Current notification status.");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint")
                        .HasComment("SMS template used to generate the message.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("Tenant identifier.");

                    b.Property<string>("ToPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Recipient mobile phone number.");

                    b.HasKey("Id")
                        .HasName("PK_FgsSmsHistory");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("IX_FgsSmsHistory_ProviderMessageId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsSmsHistory_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "SentOn")
                        .HasDatabaseName("IX_FgsSmsHistory_SentOn");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_FgsSmsHistory_Status");

                    b.HasIndex("TenantId", "CompanyId", "RecordType", "RecordId")
                        .HasDatabaseName("IX_FgsSmsHistory_Record");

                    b.ToTable("FgsSmsHistory", "notification", t =>
                        {
                            t.HasComment("Stores outbound SMS history for business entities and provides a permanent audit trail of SMS communications.");
                        });
                });

            modelBuilder.Entity("Fgs.Notification.Domain.Entities.FgsTenantCompanyCache", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("Tenant identifier.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasComment("Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Unique company code within a tenant.");

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uuid")
                        .HasComment("Globally unique company identifier used by integrations and external systems.");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Display name of the company.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the company is active.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Timestamp of the most recent synchronization from tenant.FgsTenantCompany.");

                    b.HasKey("TenantId", "CompanyId")
                        .HasName("PK_FgsTenantCompanyCache");

                    b.HasIndex("CompanyGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsTenantCompanyCache_CompanyGuid");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_CompanyName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_IsActive");

                    b.ToTable("FgsTenantCompanyCache", "notification", t =>
                        {
                            t.HasComment("Local cache of tenant company information used by the notification schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
