START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    DROP TABLE IF EXISTS notification."FgsNotificationHistory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    DROP TABLE IF EXISTS notification."FgsEmailHistory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    CREATE TYPE notification.notification_status AS ENUM ('Queued', 'Sending', 'Sent', 'Delivered', 'Opened', 'Clicked', 'Failed', 'Undelivered', 'Bounced', 'Cancelled');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    CREATE TYPE notification.source_application AS ENUM ('FgsWeb', 'FgsMobile', 'CustomerPortal', 'TechnicianPortal', 'WorkflowEngine', 'Scheduler', 'CreditCard', 'CreditCardWidget', 'Api', 'FgsAddon');
    COMMENT ON TYPE notification.source_application IS 'Identifies the FGS application or component that originated the outbound notification.';
    COMMENT ON VALUE notification.source_application 'FgsWeb' IS 'Notification generated by the FGS web application.';
    COMMENT ON VALUE notification.source_application 'FgsMobile' IS 'Notification generated by the FGS mobile application.';
    COMMENT ON VALUE notification.source_application 'CustomerPortal' IS 'Notification generated by the customer self-service portal.';
    COMMENT ON VALUE notification.source_application 'TechnicianPortal' IS 'Notification generated by the technician portal.';
    COMMENT ON VALUE notification.source_application 'WorkflowEngine' IS 'Notification generated automatically by the workflow engine.';
    COMMENT ON VALUE notification.source_application 'Scheduler' IS 'Notification generated by scheduled or background jobs.';
    COMMENT ON VALUE notification.source_application 'CreditCard' IS 'Notification generated by the credit card processing service.';
    COMMENT ON VALUE notification.source_application 'CreditCardWidget' IS 'Notification generated by the embedded credit card payment widget.';
    COMMENT ON VALUE notification.source_application 'Api' IS 'Notification generated by an API request or integration.';
    COMMENT ON VALUE notification.source_application 'FgsAddon' IS 'Notification generated by an FGS add-on or extension.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    CREATE TABLE notification."FgsEmailHistory" (
        "Id" bigint GENERATED ALWAYS AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RecordType" character varying(50) NOT NULL,
        "RecordId" bigint NOT NULL,
        "EmailTemplateId" bigint,
        "Status" notification.notification_status NOT NULL DEFAULT 'Queued'::notification.notification_status,
        "SourceApplication" notification.source_application NOT NULL,
        "Subject" character varying(500) NOT NULL,
        "FromEmailAddress" character varying(500) NOT NULL,
        "FromDisplayName" character varying(255),
        "ToEmailAddresses" jsonb NOT NULL,
        "CcEmailAddresses" jsonb,
        "BccEmailAddresses" jsonb,
        "Body" text NOT NULL,
        "ProviderName" character varying(100),
        "ProviderMessageId" character varying(500),
        "SentOn" timestamptz,
        "DeliveredOn" timestamptz,
        "OpenedOn" timestamptz,
        "FailedOn" timestamptz,
        "FailureReason" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" bigint,
        CONSTRAINT "PK_FgsEmailHistory" PRIMARY KEY ("Id")
    );
    COMMENT ON TABLE notification."FgsEmailHistory" IS 'Stores outbound email history for business entities and provides a permanent audit trail of email communications.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."Id" IS 'Primary key.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."RecordType" IS 'Business record associated with the email such as Estimate, Invoice, WorkOrder, Opportunity, Customer, or User.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."RecordId" IS 'Identifier of the associated business record.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."EmailTemplateId" IS 'Email template used to generate the email.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."Status" IS 'Current notification status.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."SourceApplication" IS 'Application or component that originated the email.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."Subject" IS 'Email subject line.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."FromEmailAddress" IS 'Sender email address.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."FromDisplayName" IS 'Sender display name.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."ToEmailAddresses" IS 'JSON array containing recipient email addresses.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."CcEmailAddresses" IS 'JSON array containing carbon copy recipient email addresses.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."BccEmailAddresses" IS 'JSON array containing blind carbon copy recipient email addresses.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."Body" IS 'Final email body that was sent to the recipient.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."ProviderName" IS 'Email provider used to send the message.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."ProviderMessageId" IS 'Provider-specific message identifier used for troubleshooting and webhook tracking.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."SentOn" IS 'Date and time the email was sent.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."DeliveredOn" IS 'Date and time the email was confirmed as delivered by the provider.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."OpenedOn" IS 'Date and time the email was opened.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."FailedOn" IS 'Date and time the email failed to send or deliver.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."FailureReason" IS 'Failure reason returned by the email provider when send fails.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN notification."FgsEmailHistory"."CreatedBy" IS 'User or process that created the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    CREATE TABLE notification."FgsSmsHistory" (
        "Id" bigint GENERATED ALWAYS AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RecordType" character varying(50) NOT NULL,
        "RecordId" bigint NOT NULL,
        "TemplateId" bigint,
        "Status" notification.notification_status NOT NULL DEFAULT 'Queued'::notification.notification_status,
        "SourceApplication" notification.source_application NOT NULL,
        "FromPhoneNumber" character varying(30) NOT NULL,
        "ToPhoneNumber" character varying(30) NOT NULL,
        "Message" text NOT NULL,
        "ProviderName" character varying(100),
        "ProviderMessageId" character varying(500),
        "SegmentCount" smallint NOT NULL DEFAULT 1,
        "SentOn" timestamptz,
        "DeliveredOn" timestamptz,
        "FailedOn" timestamptz,
        "FailureReason" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" bigint,
        CONSTRAINT "PK_FgsSmsHistory" PRIMARY KEY ("Id")
    );
    COMMENT ON TABLE notification."FgsSmsHistory" IS 'Stores outbound SMS history for business entities and provides a permanent audit trail of SMS communications.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."Id" IS 'Primary key.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."RecordType" IS 'Business record associated with the SMS such as Estimate, Invoice, WorkOrder, Opportunity, Customer, or User.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."RecordId" IS 'Identifier of the associated business record.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."TemplateId" IS 'SMS template used to generate the message.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."Status" IS 'Current notification status.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."SourceApplication" IS 'Application or component that originated the SMS.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."FromPhoneNumber" IS 'Phone number or short code used to send the SMS.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."ToPhoneNumber" IS 'Recipient mobile phone number.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."Message" IS 'Final SMS message that was sent to the recipient.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."ProviderName" IS 'SMS provider used to send the message.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."ProviderMessageId" IS 'Provider-specific message identifier used for troubleshooting and webhook tracking.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."SegmentCount" IS 'Number of SMS segments billed by the provider.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."SentOn" IS 'Date and time the SMS was sent.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."DeliveredOn" IS 'Date and time the SMS was confirmed as delivered by the provider.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."FailedOn" IS 'Date and time the SMS failed to send or deliver.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."FailureReason" IS 'Failure reason returned by the SMS provider.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN notification."FgsSmsHistory"."CreatedBy" IS 'User or process that created the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    CREATE INDEX "IX_FgsEmailHistory_ProviderMessageId" ON notification."FgsEmailHistory" ("ProviderMessageId");
    CREATE INDEX "IX_FgsEmailHistory_Record" ON notification."FgsEmailHistory" ("TenantId", "CompanyId", "RecordType", "RecordId");
    CREATE INDEX "IX_FgsEmailHistory_SentOn" ON notification."FgsEmailHistory" ("TenantId", "CompanyId", "SentOn");
    CREATE INDEX "IX_FgsEmailHistory_Status" ON notification."FgsEmailHistory" ("TenantId", "CompanyId", "Status");
    CREATE INDEX "IX_FgsEmailHistory_TenantCompany" ON notification."FgsEmailHistory" ("TenantId", "CompanyId");
    CREATE INDEX "IX_FgsSmsHistory_ProviderMessageId" ON notification."FgsSmsHistory" ("ProviderMessageId");
    CREATE INDEX "IX_FgsSmsHistory_Record" ON notification."FgsSmsHistory" ("TenantId", "CompanyId", "RecordType", "RecordId");
    CREATE INDEX "IX_FgsSmsHistory_SentOn" ON notification."FgsSmsHistory" ("TenantId", "CompanyId", "SentOn");
    CREATE INDEX "IX_FgsSmsHistory_Status" ON notification."FgsSmsHistory" ("TenantId", "CompanyId", "Status");
    CREATE INDEX "IX_FgsSmsHistory_TenantCompany" ON notification."FgsSmsHistory" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM notification."__EFMigrationsHistory" WHERE "MigrationId" = '20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory') THEN
    INSERT INTO notification."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260720184210_ReshapeEmailHistoryAddSmsHistoryDropNotificationHistory', '10.0.8');
    END IF;
END $EF$;
COMMIT;
