DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'svc') THEN
        CREATE SCHEMA svc;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS svc."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152606_InitialSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'svc') THEN
            CREATE SCHEMA svc;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152606_InitialSchema') THEN
    COMMENT ON SCHEMA svc IS $comment$Service Agreement Domain

    Stores recurring maintenance agreements, membership plans, preventive maintenance contracts and service contracts.

    Responsible for:
    - Service Agreements
    - Covered Assets
    - Visit Scheduling
    - Billing Scheduling
    - Renewals

    Typical lifecycle:

    Lead
    -> Opportunity
    -> Service Agreement
    -> Scheduled Visits
    -> Work Orders
    -> Billing
    -> Renewal

    CRM owns the sales process.
    SVC owns the contract lifecycle after the sale$comment$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152606_InitialSchema') THEN
    INSERT INTO svc."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611152606_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'svc') THEN
            CREATE SCHEMA svc;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE svc."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the svc schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN svc."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreement" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "AgreementNumber" character varying(50) NOT NULL,
        "CustomerId" bigint NOT NULL,
        "CustomerLocationId" bigint NOT NULL,
        "EstimateId" bigint,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "Break1Id" bigint NOT NULL,
        "Break2Id" bigint NOT NULL,
        "JobTypeId" bigint NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "ServiceAgreementStatusId" smallint NOT NULL,
        "VisitFrequencyId" smallint NOT NULL,
        "BillingFrequencyId" smallint NOT NULL,
        "ContractAmount" numeric(18,2) NOT NULL,
        "LaborDiscountPercent" numeric(5,2) NOT NULL DEFAULT 0.0,
        "MaterialDiscountPercent" numeric(5,2) NOT NULL DEFAULT 0.0,
        "AutoRenew" boolean NOT NULL DEFAULT FALSE,
        "RenewedByServiceAgreementId" bigint,
        "SoldDate" date,
        "SoldByEmployeeId" bigint,
        "ActivatedOn" timestamptz,
        "CancelledOn" timestamptz,
        "ExternalEntityId" character varying(200),
        "ExternalVersion" character varying(100),
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreement" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsServiceAgreement_Discounts" CHECK ("LaborDiscountPercent" BETWEEN 0 AND 100 AND "MaterialDiscountPercent" BETWEEN 0 AND 100),
        CONSTRAINT "CK_FgsServiceAgreement_EndDate" CHECK ("EndDate" >= "StartDate"),
        CONSTRAINT "CK_FgsServiceAgreement_Status" CHECK ("ServiceAgreementStatusId" IN (1, 2, 3, 4)),
        CONSTRAINT "FK_FgsServiceAgreement_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE svc."FgsServiceAgreement" IS 'Stores recurring maintenance agreements, membership plans, preventive maintenance contracts, and service contracts. Visit schedules and billing schedules are generated into separate tables.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."AgreementNumber" IS 'User visible service agreement number.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."CustomerId" IS 'Customer that owns the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."CustomerLocationId" IS 'Service location covered by the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."EstimateId" IS 'Estimate that was accepted and converted into this service agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."Name" IS 'Agreement name.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."Description" IS 'Internal agreement description.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."Break1Id" IS 'Business Unit classification for the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."Break2Id" IS 'Secondary operational classification for the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."JobTypeId" IS 'Job type associated with the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."StartDate" IS 'Agreement coverage start date.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."EndDate" IS 'Agreement coverage end date.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."ServiceAgreementStatusId" IS 'Agreement lifecycle status. Values: 1=Draft, 2=Active, 3=Expired, 4=Cancelled.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."VisitFrequencyId" IS 'Frequency used to generate service agreement visit schedules.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."BillingFrequencyId" IS 'Frequency used to generate billing schedules.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."ContractAmount" IS 'Total contract value. Billing schedule amounts are calculated from contract amount and billing frequency.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."LaborDiscountPercent" IS 'Labor discount percentage available under the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."MaterialDiscountPercent" IS 'Material discount percentage available under the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."AutoRenew" IS 'Indicates whether the agreement should automatically renew at expiration.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."RenewedByServiceAgreementId" IS 'Identifier of the agreement created when this agreement was renewed. Null indicates the agreement has not yet been renewed.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."SoldDate" IS 'Date the agreement was sold.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."SoldByEmployeeId" IS 'Employee that sold the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."ActivatedOn" IS 'Date and time the agreement became active.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."CancelledOn" IS 'Date and time the agreement was cancelled.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."ExternalEntityId" IS 'External system identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."ExternalVersion" IS 'External synchronization token or version.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreement"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementCoveredAsset" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint NOT NULL,
        "AssetId" bigint NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementCoveredAsset" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsServiceAgreementCoveredAsset_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE svc."FgsServiceAgreementCoveredAsset" IS 'Stores assets covered under a service agreement. Covered assets are entitled to contract benefits such as labor discounts, material discounts, contract pricing, and service agreement coverage. Coverage is inherited from the parent agreement term.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."AssetId" IS 'Covered customer asset identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementCoveredAsset"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementBillingSchedule" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint NOT NULL,
        "BillingSequence" integer NOT NULL,
        "BillingDate" date NOT NULL,
        "BillingAmount" numeric(18,2) NOT NULL,
        "BillingScheduleStatusId" smallint NOT NULL,
        "InvoiceId" bigint,
        "ExternalInvoiceNumber" character varying(100),
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementBillingSchedule" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsServiceAgreementBillingSchedule_BillingAmount" CHECK ("BillingAmount" >= 0),
        CONSTRAINT "CK_FgsServiceAgreementBillingSchedule_Status" CHECK ("BillingScheduleStatusId" IN (1, 2, 3, 4, 5)),
        CONSTRAINT "FK_FgsServiceAgreementBillingSchedule_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsServiceAgreementBillingSchedule_ServiceAgreement" FOREIGN KEY ("ServiceAgreementId") REFERENCES svc."FgsServiceAgreement" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE svc."FgsServiceAgreementBillingSchedule" IS 'Stores future billing events generated from a service agreement. Billing schedules generate invoices but are not invoices themselves.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."BillingSequence" IS 'Sequential billing number within the service agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."BillingDate" IS 'Scheduled billing date used for invoice generation.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."BillingAmount" IS 'Amount expected to be billed for this billing event.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."BillingScheduleStatusId" IS 'Billing schedule status. Values: 1=Pending, 2=InvoiceCreated, 3=Invoiced, 4=Skipped, 5=Cancelled.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."InvoiceId" IS 'Generated invoice identifier associated with the billing event.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."ExternalInvoiceNumber" IS 'Invoice number from a legacy or external system used during data migration.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementBillingSchedule"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementVisit" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint NOT NULL,
        "VisitNumber" integer NOT NULL,
        "JobTypeId" bigint NOT NULL,
        "ExpectedServiceDate" date NOT NULL,
        "ServiceAgreementVisitStatusId" smallint NOT NULL,
        "WorkOrderId" bigint,
        "ExternalWorkOrderNumber" character varying(100),
        "CompletedOn" timestamptz,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementVisit" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsServiceAgreementVisit_Status" CHECK ("ServiceAgreementVisitStatusId" IN (1, 2, 3, 4, 5)),
        CONSTRAINT "FK_FgsServiceAgreementVisit_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsServiceAgreementVisit_ServiceAgreement" FOREIGN KEY ("ServiceAgreementId") REFERENCES svc."FgsServiceAgreement" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE svc."FgsServiceAgreementVisit" IS 'Stores contractually required maintenance visits generated from a service agreement. Visits may later generate work orders to perform the required maintenance service.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."VisitNumber" IS 'Sequential visit number within the service agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."JobTypeId" IS 'Job type used when generating a work order from the service agreement visit.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."ExpectedServiceDate" IS 'Expected date the maintenance service should be performed according to the agreement.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."ServiceAgreementVisitStatusId" IS 'Visit lifecycle status. Values: 1=Pending, 2=WorkOrderCreated, 3=Completed, 4=Skipped, 5=Cancelled.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."WorkOrderId" IS 'Generated work order identifier associated with the visit.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."ExternalWorkOrderNumber" IS 'Work order number from a legacy or external system used during data migration.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."CompletedOn" IS 'Date and time the maintenance visit was completed.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisit"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementNote" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint,
        "ServiceAgreementVisitId" bigint,
        "ServiceAgreementBillingScheduleId" bigint,
        "NoteTypeId" bigint,
        "Note" text NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementNote" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsServiceAgreementNote_Parent" CHECK (("ServiceAgreementId" IS NOT NULL AND "ServiceAgreementVisitId" IS NULL AND "ServiceAgreementBillingScheduleId" IS NULL)
    OR ("ServiceAgreementId" IS NULL AND "ServiceAgreementVisitId" IS NOT NULL AND "ServiceAgreementBillingScheduleId" IS NULL)
    OR ("ServiceAgreementId" IS NULL AND "ServiceAgreementVisitId" IS NULL AND "ServiceAgreementBillingScheduleId" IS NOT NULL)),
        CONSTRAINT "FK_FgsServiceAgreementNote_BillingSchedule" FOREIGN KEY ("ServiceAgreementBillingScheduleId") REFERENCES svc."FgsServiceAgreementBillingSchedule" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsServiceAgreementNote_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsServiceAgreementNote_ServiceAgreement" FOREIGN KEY ("ServiceAgreementId") REFERENCES svc."FgsServiceAgreement" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsServiceAgreementNote_ServiceAgreementVisit" FOREIGN KEY ("ServiceAgreementVisitId") REFERENCES svc."FgsServiceAgreementVisit" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE svc."FgsServiceAgreementNote" IS 'Stores notes related to service agreements, service agreement visits, and service agreement billing schedules. A note belongs to exactly one parent entity.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."ServiceAgreementVisitId" IS 'Parent service agreement visit identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."ServiceAgreementBillingScheduleId" IS 'Parent service agreement billing schedule identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."NoteTypeId" IS 'Optional note classification identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."Note" IS 'Note text.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementNote"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementVisitAsset" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint NOT NULL,
        "ServiceAgreementVisitId" bigint NOT NULL,
        "AssetId" bigint NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementVisitAsset" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsServiceAgreementVisitAsset_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsServiceAgreementVisitAsset_ServiceAgreementVisit" FOREIGN KEY ("ServiceAgreementVisitId") REFERENCES svc."FgsServiceAgreementVisit" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE svc."FgsServiceAgreementVisitAsset" IS 'Stores assets associated with a service agreement maintenance visit. A visit may include one or more covered assets that require maintenance service.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."ServiceAgreementVisitId" IS 'Parent service agreement visit identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."AssetId" IS 'Asset associated with the service agreement visit.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitAsset"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE TABLE svc."FgsServiceAgreementVisitItem" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ServiceAgreementId" bigint NOT NULL,
        "ServiceAgreementVisitId" bigint NOT NULL,
        "InventoryItemId" bigint,
        "ItemName" character varying(200),
        "Description" text,
        "Quantity" numeric(18,2) NOT NULL DEFAULT 1.0,
        "IsRequired" boolean NOT NULL DEFAULT TRUE,
        "DisplayOrder" integer NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsServiceAgreementVisitItem" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsServiceAgreementVisitItem_Item" CHECK ("InventoryItemId" IS NOT NULL OR COALESCE(TRIM("ItemName"), '') <> ''),
        CONSTRAINT "CK_FgsServiceAgreementVisitItem_Quantity" CHECK ("Quantity" > 0),
        CONSTRAINT "FK_FgsServiceAgreementVisitItem_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES svc."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsServiceAgreementVisitItem_ServiceAgreementVisit" FOREIGN KEY ("ServiceAgreementVisitId") REFERENCES svc."FgsServiceAgreementVisit" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE svc."FgsServiceAgreementVisitItem" IS 'Stores recommended items associated with a service agreement maintenance visit. Items may come from the inventory catalog or be entered manually. Actual material usage is recorded on the work order.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."ServiceAgreementId" IS 'Parent service agreement identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."ServiceAgreementVisitId" IS 'Parent service agreement visit identifier.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."InventoryItemId" IS 'Inventory item identifier. May be NULL when the item is manually entered.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."ItemName" IS 'Item name used when the item does not exist in the inventory catalog.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."Description" IS 'Additional item description or maintenance instructions.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."Quantity" IS 'Expected quantity required for the maintenance visit.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."IsRequired" IS 'Indicates whether the item is required for the maintenance visit.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."DisplayOrder" IS 'Display order within the maintenance visit item list.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."CreatedOn" IS 'Record creation timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."CreatedBy" IS 'User that created the record.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."UpdatedOn" IS 'Record last update timestamp.';
    COMMENT ON COLUMN svc."FgsServiceAgreementVisitItem"."UpdatedBy" IS 'User that last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreement_CustomerId" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId", "CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreement_CustomerLocationId" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId", "CustomerLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreement_EndDate" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId", "EndDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreement_Status" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId", "ServiceAgreementStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreement_TenantId_CompanyId" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsServiceAgreement_AgreementNumber" ON svc."FgsServiceAgreement" ("TenantId", "CompanyId", "AgreementNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_BillingDate" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId", "BillingDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_InvoiceId" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId", "InvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_ServiceAgreementId" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_ServiceAgreementId1" ON svc."FgsServiceAgreementBillingSchedule" ("ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_Status" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId", "BillingScheduleStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementBillingSchedule_TenantId_CompanyId" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsServiceAgreementBillingSchedule_Agreement_Sequence" ON svc."FgsServiceAgreementBillingSchedule" ("TenantId", "CompanyId", "ServiceAgreementId", "BillingSequence");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementCoveredAsset_AssetId" ON svc."FgsServiceAgreementCoveredAsset" ("TenantId", "CompanyId", "AssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementCoveredAsset_ServiceAgreementId" ON svc."FgsServiceAgreementCoveredAsset" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementCoveredAsset_TenantId_CompanyId" ON svc."FgsServiceAgreementCoveredAsset" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsServiceAgreementCoveredAsset_Agreement_Asset" ON svc."FgsServiceAgreementCoveredAsset" ("TenantId", "CompanyId", "ServiceAgreementId", "AssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_BillingScheduleId" ON svc."FgsServiceAgreementNote" ("TenantId", "CompanyId", "ServiceAgreementBillingScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_ServiceAgreementBillingScheduleId" ON svc."FgsServiceAgreementNote" ("ServiceAgreementBillingScheduleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_ServiceAgreementId" ON svc."FgsServiceAgreementNote" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_ServiceAgreementId1" ON svc."FgsServiceAgreementNote" ("ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_ServiceAgreementVisitId" ON svc."FgsServiceAgreementNote" ("TenantId", "CompanyId", "ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_ServiceAgreementVisitId1" ON svc."FgsServiceAgreementNote" ("ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementNote_TenantId_CompanyId" ON svc."FgsServiceAgreementNote" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_ExpectedServiceDate" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "ExpectedServiceDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_JobTypeId" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "JobTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_ServiceAgreementId" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_ServiceAgreementId1" ON svc."FgsServiceAgreementVisit" ("ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_Status" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "ServiceAgreementVisitStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_TenantId_CompanyId" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisit_WorkOrderId" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "WorkOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsServiceAgreementVisit_Agreement_VisitNumber" ON svc."FgsServiceAgreementVisit" ("TenantId", "CompanyId", "ServiceAgreementId", "VisitNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitAsset_AssetId" ON svc."FgsServiceAgreementVisitAsset" ("TenantId", "CompanyId", "AssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitAsset_ServiceAgreementId" ON svc."FgsServiceAgreementVisitAsset" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitAsset_ServiceAgreementVisitId" ON svc."FgsServiceAgreementVisitAsset" ("TenantId", "CompanyId", "ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitAsset_ServiceAgreementVisitId1" ON svc."FgsServiceAgreementVisitAsset" ("ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitAsset_TenantId_CompanyId" ON svc."FgsServiceAgreementVisitAsset" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsServiceAgreementVisitAsset_Visit_Asset" ON svc."FgsServiceAgreementVisitAsset" ("TenantId", "CompanyId", "ServiceAgreementVisitId", "AssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_DisplayOrder" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId", "ServiceAgreementVisitId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_InventoryItemId" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_IsRequired" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId", "IsRequired");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_ServiceAgreementId" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId", "ServiceAgreementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_ServiceAgreementVisitId" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId", "ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_ServiceAgreementVisitId1" ON svc."FgsServiceAgreementVisitItem" ("ServiceAgreementVisitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsServiceAgreementVisitItem_TenantId_CompanyId" ON svc."FgsServiceAgreementVisitItem" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON svc."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON svc."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON svc."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM svc."__EFMigrationsHistory" WHERE "MigrationId" = '20260611152830_AddSvcSchema') THEN
    INSERT INTO svc."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611152830_AddSvcSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

