using Fgs.Audit.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Fgs.Audit.Infrastructure.Database.Configurations;

internal sealed class FgsEventConfiguration : IEntityTypeConfiguration<FgsEvent>
{
    public void Configure(EntityTypeBuilder<FgsEvent> entity)
    {
        entity.ToTable(
            "FgsEvent",
            t => t.HasComment(
                "Stores business, system, security, and integration events generated by the FSM platform. Provides the primary audit history for all business entities."));

        entity.HasKey(e => e.Id).HasName("PK_FgsEvent");
        entity.Property(e => e.Id)
            .UseIdentityByDefaultColumn()
            .HasIdentityOptions(startValue: 1, incrementBy: 1)
            .HasComment("Unique identifier of the event.");

        entity.Property(e => e.TenantId).IsRequired()
            .HasComment("Tenant that owns the event.");
        entity.Property(e => e.CompanyId).IsRequired()
            .HasComment("Company within the tenant that owns the event.");
        entity.Property(e => e.EventCode).HasMaxLength(100).IsRequired()
            .HasComment("Application-defined event code identifying the event.");
        entity.Property(e => e.EventSource).IsRequired()
            .HasComment("Application, service, integration, or process that generated the event.");
        entity.Property(e => e.RecordType).IsRequired()
            .HasComment("Business entity associated with the event.");
        entity.Property(e => e.EntityId).IsRequired()
            .HasComment("Primary key of the associated business entity.");
        entity.Property(e => e.EntityNumber).HasMaxLength(50)
            .HasComment("Business reference number displayed to users, such as WO-100245 or INV-10234.");
        entity.Property(e => e.UserName).HasMaxLength(150)
            .HasComment("Display name of the user responsible for the event at the time it occurred.");
        entity.Property(e => e.Summary).HasMaxLength(500).IsRequired()
            .HasComment("Short human-readable description displayed in the event history.");
        entity.Property(e => e.OccurredOn)
            .HasColumnType("timestamp")
            .HasDefaultValueSql("now()")
            .IsRequired()
            .HasComment("Date and time the event occurred. Used for partitioning.");
        entity.Property(e => e.CreatedOn)
            .HasColumnType("timestamp")
            .HasDefaultValueSql("now()")
            .IsRequired()
            .HasComment("Date and time the event record was written to the audit database.");

        entity.HasIndex(e => new { e.TenantId, e.CompanyId, e.OccurredOn })
            .IsDescending(false, false, true)
            .HasDatabaseName("IX_FgsEvent_TenantCompanyOccurredOn");
        entity.HasIndex(e => new { e.RecordType, e.EntityId })
            .HasDatabaseName("IX_FgsEvent_Entity");
        entity.HasIndex(e => e.EventCode)
            .HasDatabaseName("IX_FgsEvent_EventCode");
        entity.HasIndex(e => e.EventSource)
            .HasDatabaseName("IX_FgsEvent_EventSource");
        entity.HasIndex(e => e.OccurredOn)
            .IsDescending()
            .HasDatabaseName("IX_FgsEvent_OccurredOn");

        entity.HasMany(e => e.Details)
            .WithOne(d => d.Event)
            .HasForeignKey(d => d.EventId)
            .HasConstraintName("FK_FgsEventDetail_Event")
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasMany(e => e.Attachments)
            .WithOne(a => a.Event)
            .HasForeignKey(a => a.EventId)
            .HasConstraintName("FK_FgsEventAttachment_Event")
            .OnDelete(DeleteBehavior.Cascade);
    }
}
