namespace Fgs.Inventory.Application.Features.PurchaseOrders.Dtos;

public sealed record FgsPurchaseOrderSummaryDto(
    long Id,
    string PurchaseOrderNumber,
    long VendorId,
    string PurchaseOrderStatus,
    DateTimeOffset PurchaseOrderDate,
    DateTimeOffset? ExpectedDeliveryDate,
    decimal TotalAmount);

public sealed record FgsPurchaseOrderDetailDto(
    long Id,
    string PurchaseOrderNumber,
    long VendorId,
    string PurchaseOrderStatus,
    DateTimeOffset PurchaseOrderDate,
    DateTimeOffset? ExpectedDeliveryDate,
    long? RequestedByEmployeeId,
    string? RequestedByName,
    long? BuyerEmployeeId,
    long? ShipToInventoryLocationId,
    long? ShipToServiceLocationId,
    string? ShipToName,
    string? ShipToAddress1,
    string? ShipToAddress2,
    string? ShipToCity,
    string? ShipToStateProvince,
    string? ShipToPostalCode,
    string? ShipToCountry,
    string? VendorReferenceNumber,
    string? VendorContactName,
    string? VendorEmail,
    string? VendorPhoneNumber,
    decimal Subtotal,
    decimal DiscountAmount,
    decimal TaxableAmount,
    string? PurchaseTaxJson,
    decimal FreightAmount,
    decimal OtherCharges,
    decimal TotalAmount,
    string? VendorNotes,
    string? InternalNotes,
    IReadOnlyList<FgsPurchaseOrderLineDetailDto> Details);

public sealed record FgsPurchaseOrderLineDetailDto(
    long Id,
    short LineNumber,
    long ItemId,
    string? VendorPartNumber,
    string ItemDescription,
    string UnitOfMeasureCode,
    decimal OrderedQuantity,
    decimal ReceivedQuantity,
    decimal UnitCost,
    decimal DiscountAmount,
    bool IsTaxable,
    decimal ExtendedAmount,
    DateTimeOffset? ExpectedDeliveryDate,
    string? Notes);

/// <summary>
/// Nested line on create/update/patch. Omit <see cref="Id"/> (or null) to insert; supply Id to update.
/// Omitted existing lines are removed on create/update (and on patch when Details is provided).
/// </summary>
public sealed record FgsPurchaseOrderLineDto(
    long? Id,
    short LineNumber,
    long ItemId,
    string? VendorPartNumber,
    string ItemDescription,
    string UnitOfMeasureCode,
    decimal OrderedQuantity,
    decimal ReceivedQuantity,
    decimal UnitCost,
    decimal DiscountAmount,
    bool IsTaxable,
    decimal ExtendedAmount,
    DateTimeOffset? ExpectedDeliveryDate,
    string? Notes);

public sealed record FgsPurchaseOrderCreateDto(
    string PurchaseOrderNumber,
    long VendorId,
    string PurchaseOrderStatus,
    DateTimeOffset PurchaseOrderDate,
    DateTimeOffset? ExpectedDeliveryDate,
    long? RequestedByEmployeeId,
    string? RequestedByName,
    long? BuyerEmployeeId,
    long? ShipToInventoryLocationId,
    long? ShipToServiceLocationId,
    string? ShipToName,
    string? ShipToAddress1,
    string? ShipToAddress2,
    string? ShipToCity,
    string? ShipToStateProvince,
    string? ShipToPostalCode,
    string? ShipToCountry,
    string? VendorReferenceNumber,
    string? VendorContactName,
    string? VendorEmail,
    string? VendorPhoneNumber,
    decimal Subtotal,
    decimal DiscountAmount,
    decimal TaxableAmount,
    string? PurchaseTaxJson,
    decimal FreightAmount,
    decimal OtherCharges,
    decimal TotalAmount,
    string? VendorNotes,
    string? InternalNotes,
    IReadOnlyList<FgsPurchaseOrderLineDto>? Details = null);

public sealed record FgsPurchaseOrderUpdateDto(
    string PurchaseOrderNumber,
    long VendorId,
    string PurchaseOrderStatus,
    DateTimeOffset PurchaseOrderDate,
    DateTimeOffset? ExpectedDeliveryDate,
    long? RequestedByEmployeeId,
    string? RequestedByName,
    long? BuyerEmployeeId,
    long? ShipToInventoryLocationId,
    long? ShipToServiceLocationId,
    string? ShipToName,
    string? ShipToAddress1,
    string? ShipToAddress2,
    string? ShipToCity,
    string? ShipToStateProvince,
    string? ShipToPostalCode,
    string? ShipToCountry,
    string? VendorReferenceNumber,
    string? VendorContactName,
    string? VendorEmail,
    string? VendorPhoneNumber,
    decimal Subtotal,
    decimal DiscountAmount,
    decimal TaxableAmount,
    string? PurchaseTaxJson,
    decimal FreightAmount,
    decimal OtherCharges,
    decimal TotalAmount,
    string? VendorNotes,
    string? InternalNotes,
    IReadOnlyList<FgsPurchaseOrderLineDto>? Details = null);

public sealed record FgsPurchaseOrderPatchDto(
    string? PurchaseOrderNumber,
    long? VendorId,
    string? PurchaseOrderStatus,
    DateTimeOffset? PurchaseOrderDate,
    DateTimeOffset? ExpectedDeliveryDate,
    long? RequestedByEmployeeId,
    string? RequestedByName,
    long? BuyerEmployeeId,
    long? ShipToInventoryLocationId,
    long? ShipToServiceLocationId,
    string? ShipToName,
    string? ShipToAddress1,
    string? ShipToAddress2,
    string? ShipToCity,
    string? ShipToStateProvince,
    string? ShipToPostalCode,
    string? ShipToCountry,
    string? VendorReferenceNumber,
    string? VendorContactName,
    string? VendorEmail,
    string? VendorPhoneNumber,
    decimal? Subtotal,
    decimal? DiscountAmount,
    decimal? TaxableAmount,
    string? PurchaseTaxJson,
    decimal? FreightAmount,
    decimal? OtherCharges,
    decimal? TotalAmount,
    string? VendorNotes,
    string? InternalNotes,
    IReadOnlyList<FgsPurchaseOrderLineDto>? Details = null);

public sealed record FgsPurchaseOrderListFilters(
    string? PurchaseOrderNumber = null,
    long? VendorId = null,
    string? PurchaseOrderStatus = null);
