-- =============================================================================
-- 20260508172853_AddFsgSetupBusinessTypeAndTimeCardOption (UP) — PostgreSQL / fgs
-- Mirrors EF migration:
-- UserService.Infrastructure/Persistence/Migrations/20260508172853_AddFsgSetupBusinessTypeAndTimeCardOption.cs
--
-- Prerequisites: schema fgs, table fgs."Company" with business_type_id (existing
--                 rows should reference seeded ids, e.g. 1 for HVAC).
--
-- Optional: omit the __ef_migrations_history INSERT if this database is managed
--           only by EF (avoids duplicate key when migration already applied).
-- =============================================================================

BEGIN;

CREATE TABLE fgs."FSGSetupBusinessType" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupBusinessType" PRIMARY KEY (id)
);

CREATE TABLE fgs."FSGSetupTimeCardOption" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(100) NOT NULL,
    description character varying(2000),
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupTimeCardOption" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_FSGSetupBusinessType_code" ON fgs."FSGSetupBusinessType" (code);

CREATE UNIQUE INDEX "IX_FSGSetupTimeCardOption_code" ON fgs."FSGSetupTimeCardOption" (code);

CREATE INDEX "IX_Company_business_type_id" ON fgs."Company" (business_type_id);

INSERT INTO fgs."FSGSetupBusinessType" (code, name, sort_order, is_active, created_on)
VALUES
    ('HVAC', 'HVAC', 1, TRUE, now()),
    ('PLUMBING', 'Plumbing', 2, TRUE, now()),
    ('ELECTRICAL', 'Electrical', 3, TRUE, now()),
    ('PESTCONTROL', 'Pest Control', 4, TRUE, now()),
    ('LAWNCARE', 'Lawn Care', 5, TRUE, now()),
    ('TRASHPICKUP', 'Trash Pickup', 6, TRUE, now()),
    ('GARAGEDOOR', 'Garage Door', 7, TRUE, now()),
    ('HOUSECLEANING', 'House Cleaning', 8, TRUE, now()),
    ('PAINTING', 'Painting', 9, TRUE, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO fgs."FSGSetupTimeCardOption" (code, description, is_active, created_on)
VALUES
    ('NONE', 'No formal technician time tracking workflow', TRUE, now()),
    ('DISPATCHARRIVECOMPLETE', 'Tracks dispatch, arrival, and completion timestamps', TRUE, now()),
    ('CHECKINCHECKOUT', 'Technician manually checks in and checks out', TRUE, now())
ON CONFLICT (code) DO NOTHING;

ALTER TABLE fgs."Company"
    ADD CONSTRAINT "FK_Company_FSGSetupBusinessType_business_type_id"
    FOREIGN KEY (business_type_id) REFERENCES fgs."FSGSetupBusinessType" (id) ON DELETE RESTRICT;

INSERT INTO fgs.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260508172853_AddFsgSetupBusinessTypeAndTimeCardOption', '10.0.0');

COMMIT;
