-- =============================================================================
-- 20260508163550_UpdateTenantCompanyAndAuditable (UP) — PostgreSQL / fgs
-- Applies the same changes as EF migration
-- UserService.Infrastructure/Persistence/Migrations/20260508163550_UpdateTenantCompanyAndAuditable.cs
--
-- Prerequisites: schema fgs exists with InitialCreate objects (tenant, tenant_company,
--                users, invite, auth_identity) as created by 20260507184939_InitialCreate.
--
-- Optional: omit the __ef_migrations_history INSERT if you are not using EF migrations
--           on this database (avoids duplicate key if migration was already applied).
--
-- Data:     UPDATE block maps users/invite.company_id to MIN(Company.id) per tenant_id
--           (safe when one company per tenant; review if you have multiple subsidiaries).
-- =============================================================================

BEGIN;

ALTER TABLE fgs.invite DROP CONSTRAINT "FK_invite_tenant_company_tenant_id_company_id";

ALTER TABLE fgs.invite DROP CONSTRAINT "FK_invite_tenant_tenant_id";

ALTER TABLE fgs.tenant_company DROP CONSTRAINT "FK_tenant_company_tenant_tenant_id";

ALTER TABLE fgs.users DROP CONSTRAINT "FK_users_tenant_company_tenant_id_company_id";

ALTER TABLE fgs.users DROP CONSTRAINT "FK_users_tenant_tenant_id";

DROP INDEX fgs."IX_users_tenant_id_company_id";

ALTER TABLE fgs.tenant DROP CONSTRAINT "PK_tenant";

DROP INDEX fgs."IX_invite_tenant_id_company_id";

ALTER TABLE fgs.tenant_company DROP CONSTRAINT "PK_tenant_company";

ALTER TABLE fgs.tenant DROP COLUMN status;

ALTER TABLE fgs.tenant_company DROP COLUMN company_id;

ALTER TABLE fgs.tenant RENAME TO "Tenant";

ALTER TABLE fgs.tenant_company RENAME TO "Company";

ALTER TABLE fgs."Tenant" RENAME COLUMN created_at TO created_on;

ALTER TABLE fgs."Tenant" RENAME COLUMN updated_at TO updated_on;

ALTER TABLE fgs."Company" RENAME COLUMN created_at TO created_on;

ALTER TABLE fgs."Company" RENAME COLUMN updated_at TO updated_on;

ALTER INDEX fgs.ix_tenant_company_tenant RENAME TO ix_company_tenant;

ALTER TABLE fgs.users ALTER COLUMN company_id TYPE bigint;

ALTER TABLE fgs."Tenant" ALTER COLUMN name TYPE character varying(200);

ALTER TABLE fgs."Tenant" ADD created_by uuid;

ALTER TABLE fgs."Tenant" ADD default_currency character varying(20);

ALTER TABLE fgs."Tenant" ADD default_language_id integer;

ALTER TABLE fgs."Tenant" ADD email character varying(300);

ALTER TABLE fgs."Tenant" ADD is_active boolean NOT NULL DEFAULT TRUE;

ALTER TABLE fgs."Tenant" ADD legal_name character varying(300);

ALTER TABLE fgs."Tenant" ADD phone_number character varying(50);

ALTER TABLE fgs."Tenant" ADD primary_location_id uuid;

ALTER TABLE fgs."Tenant" ADD subscription_plan_id integer;

ALTER TABLE fgs."Tenant" ADD time_zone character varying(100);

ALTER TABLE fgs."Tenant" ADD updated_by uuid;

ALTER TABLE fgs."Tenant" ADD website character varying(500);

ALTER TABLE fgs.invite ALTER COLUMN company_id TYPE bigint;

ALTER TABLE fgs."Company" ALTER COLUMN name TYPE character varying(200);

ALTER TABLE fgs."Company" ADD id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE fgs."Company" ADD business_type_id integer NOT NULL DEFAULT 0;

ALTER TABLE fgs."Company" ADD code character varying(100) NOT NULL DEFAULT '';

ALTER TABLE fgs."Company" ADD compact_logo_url character varying(1000);

ALTER TABLE fgs."Company" ADD company_guid uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE fgs."Company" ADD company_number bigint NOT NULL DEFAULT 0;

ALTER TABLE fgs."Company" ADD created_by uuid;

ALTER TABLE fgs."Company" ADD email character varying(300);

ALTER TABLE fgs."Company" ADD favicon_url character varying(1000);

ALTER TABLE fgs."Company" ADD full_logo_url character varying(1000);

ALTER TABLE fgs."Company" ADD icon_logo_url character varying(1000);

ALTER TABLE fgs."Company" ADD is_active boolean NOT NULL DEFAULT TRUE;

ALTER TABLE fgs."Company" ADD legal_name character varying(300);

ALTER TABLE fgs."Company" ADD phone_number character varying(50);

ALTER TABLE fgs."Company" ADD primary_location_id uuid;

ALTER TABLE fgs."Company" ADD tax_id character varying(100);

ALTER TABLE fgs."Company" ADD updated_by uuid;

ALTER TABLE fgs."Company" ADD website character varying(500);

ALTER TABLE fgs."Tenant" ADD CONSTRAINT "PK_Tenant" PRIMARY KEY (id);

ALTER TABLE fgs."Company" ADD CONSTRAINT "PK_Company" PRIMARY KEY (id);

UPDATE fgs."Company" SET company_guid = gen_random_uuid() WHERE company_guid = '00000000-0000-0000-0000-000000000000';
UPDATE fgs."Company" SET code = LEFT(COALESCE(NULLIF(TRIM(name), ''), 'company'), 100) WHERE code = '';
UPDATE fgs."Company" SET business_type_id = 1 WHERE business_type_id = 0;
UPDATE fgs."Company" SET company_number = 1 WHERE company_number = 0;
UPDATE fgs.users u SET company_id = m.id FROM (SELECT tenant_id, MIN(id) AS id FROM fgs."Company" GROUP BY tenant_id) m WHERE u.tenant_id = m.tenant_id;
UPDATE fgs.invite i SET company_id = m.id FROM (SELECT tenant_id, MIN(id) AS id FROM fgs."Company" GROUP BY tenant_id) m WHERE i.tenant_id = m.tenant_id;

CREATE INDEX "IX_users_company_id" ON fgs.users (company_id);

CREATE INDEX "IX_invite_company_id" ON fgs.invite (company_id);

CREATE UNIQUE INDEX "IX_Company_company_guid" ON fgs."Company" (company_guid);

ALTER TABLE fgs."Company" ADD CONSTRAINT "FK_Company_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES fgs."Tenant" (id) ON DELETE RESTRICT;

ALTER TABLE fgs.invite ADD CONSTRAINT "FK_invite_Company_company_id" FOREIGN KEY (company_id) REFERENCES fgs."Company" (id) ON DELETE RESTRICT;

ALTER TABLE fgs.invite ADD CONSTRAINT "FK_invite_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES fgs."Tenant" (id) ON DELETE RESTRICT;

ALTER TABLE fgs.users ADD CONSTRAINT "FK_users_Company_company_id" FOREIGN KEY (company_id) REFERENCES fgs."Company" (id) ON DELETE RESTRICT;

ALTER TABLE fgs.users ADD CONSTRAINT "FK_users_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES fgs."Tenant" (id) ON DELETE RESTRICT;

INSERT INTO fgs.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260508163550_UpdateTenantCompanyAndAuditable', '10.0.0');

COMMIT;
