-- =============================================================================
-- 20260508174113_AddFsgSetupAccountingLanguageMasterEntityLocation (UP) — PostgreSQL / fgs
-- Mirrors EF migration:
-- UserService.Infrastructure/Persistence/Migrations/20260508174113_AddFsgSetupAccountingLanguageMasterEntityLocation.cs
--
-- Optional: omit __ef_migrations_history INSERT if EF already applied this migration.
-- =============================================================================

BEGIN;

CREATE TABLE fgs."FSGSetupAccountingIntegrationType" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupAccountingIntegrationType" PRIMARY KEY (id)
);

CREATE TABLE fgs."FSGSetupLanguage" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    culture_code character varying(50) NOT NULL,
    is_default boolean NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupLanguage" PRIMARY KEY (id)
);

CREATE TABLE fgs."FSGSetupLocationType" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupLocationType" PRIMARY KEY (id)
);

CREATE TABLE fgs."FSGSetupMasterEntityType" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    is_active boolean NOT NULL,
    created_on timestamp with time zone NOT NULL,
    created_by uuid,
    updated_on timestamp with time zone,
    updated_by uuid,
    CONSTRAINT "PK_FSGSetupMasterEntityType" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_FSGSetupAccountingIntegrationType_code" ON fgs."FSGSetupAccountingIntegrationType" (code);

CREATE UNIQUE INDEX "IX_FSGSetupLanguage_code" ON fgs."FSGSetupLanguage" (code);

CREATE UNIQUE INDEX "IX_FSGSetupLocationType_code" ON fgs."FSGSetupLocationType" (code);

CREATE UNIQUE INDEX "IX_FSGSetupMasterEntityType_code" ON fgs."FSGSetupMasterEntityType" (code);

INSERT INTO fgs."FSGSetupAccountingIntegrationType" (code, name, is_active, created_on)
VALUES
    ('NONE', 'No Accounting', TRUE, now()),
    ('QUICKBOOKSONLINE', 'QuickBooks Online', TRUE, now()),
    ('SAGEINTACCT', 'Sage Intacct', TRUE, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO fgs."FSGSetupLanguage" (code, name, culture_code, is_default, sort_order, is_active, created_on)
VALUES
    ('EN', 'English', 'en-US', TRUE, 1, TRUE, now()),
    ('ES', 'Spanish', 'es-US', FALSE, 2, TRUE, now()),
    ('FR', 'French', 'fr-FR', FALSE, 3, TRUE, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO fgs."FSGSetupMasterEntityType" (code, name, is_active, created_on)
VALUES
    ('TENANT', 'TENANT', TRUE, now()),
    ('COMPANY', 'COMPANY', TRUE, now()),
    ('SERVICELOCATION', 'SERVICELOCATION', TRUE, now()),
    ('BILLTO', 'BILLTO', TRUE, now()),
    ('VENDOR', 'VENDOR', TRUE, now()),
    ('SUBCONTRACTOR', 'SUBCONTRACTOR', TRUE, now()),
    ('LEAD', 'LEAD', TRUE, now()),
    ('PROPOSAL', 'PROPOSAL', TRUE, now()),
    ('CUSTOMER', 'CUSTOMER', TRUE, now()),
    ('WORKORDER', 'WORKORDER', TRUE, now()),
    ('INVOICE', 'INVOICE', TRUE, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO fgs."FSGSetupLocationType" (code, name, is_active, created_on)
VALUES
    ('BILLING', 'BILLING', TRUE, now()),
    ('SHIPPING', 'SHIPPING', TRUE, now()),
    ('PHYSICAL', 'PHYSICAL', TRUE, now()),
    ('SERVICE', 'SERVICE', TRUE, now()),
    ('MAILING', 'MAILING', TRUE, now()),
    ('HQ', 'HQ', TRUE, now()),
    ('REMITTO', 'REMITTO', TRUE, now()),
    ('JOBSITE', 'JOBSITE', TRUE, now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO fgs.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260508174113_AddFsgSetupAccountingLanguageMasterEntityLocation', '10.0.0');

COMMIT;
