-- Adds fgs."CompanyConfiguration" (one row per company) and records migration 20260508181254_AddCompanyConfiguration in __ef_migrations_history.

START TRANSACTION;
CREATE TABLE fgs."CompanyConfiguration" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TimeCardOptionId" integer NOT NULL,
    "AccountingIntegrationTypeId" integer,
    "EnableCallBookingWidget" boolean NOT NULL DEFAULT TRUE,
    "EnablePaymentWidget" boolean NOT NULL DEFAULT TRUE,
    "EnableCustomerPortal" boolean NOT NULL DEFAULT TRUE,
    "EnableRulesManagement" boolean NOT NULL DEFAULT FALSE,
    "EnableAutoArrive" boolean NOT NULL DEFAULT FALSE,
    "WorkLocationRadiusForAutoArrive" integer,
    "OTStartTime" time without time zone,
    "OTEndTime" time without time zone,
    "DTStartTime" time without time zone,
    "DTEndTime" time without time zone,
    "BillHoursFromDispatchOrArrive" character varying(20) NOT NULL DEFAULT 'DISPATCH',
    "SourceCodeRequiredOnWorkOrder" boolean NOT NULL DEFAULT FALSE,
    "SourceCodeRequiredOnServiceLocation" boolean NOT NULL DEFAULT FALSE,
    "BillToStartNumber" bigint NOT NULL DEFAULT 100,
    "POStartNumber" bigint NOT NULL DEFAULT 100,
    "QuoteStartNumber" bigint NOT NULL DEFAULT 100,
    "WorkOrderStartNumber" bigint NOT NULL DEFAULT 100,
    "InvoiceNumberPrefix" character varying(20),
    "QuoteNumberPrefix" character varying(20),
    "PONumberPrefix" character varying(20),
    "WorkOrderNumberPrefix" character varying(20),
    "InvoiceBatchNumberFormat" character varying(200),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_CompanyConfiguration" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyConfiguration_AccountingIntegrationType" FOREIGN KEY ("AccountingIntegrationTypeId") REFERENCES fgs."FSGSetupAccountingIntegrationType" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CompanyConfiguration_Company" FOREIGN KEY ("CompanyId") REFERENCES fgs."Company" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyConfiguration_TimeCardOption" FOREIGN KEY ("TimeCardOptionId") REFERENCES fgs."FSGSetupTimeCardOption" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IxCompanyConfigurationAccountingIntegrationTypeId" ON fgs."CompanyConfiguration" ("AccountingIntegrationTypeId");

CREATE INDEX "IxCompanyConfigurationTimeCardOptionId" ON fgs."CompanyConfiguration" ("TimeCardOptionId");

CREATE UNIQUE INDEX "IxCompanyConfigurationCompany" ON fgs."CompanyConfiguration" ("CompanyId");

INSERT INTO fgs.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260508181254_AddCompanyConfiguration', '10.0.0');

COMMIT;

