using Fgs.Setup.Application.Abstractions.SetupPricingMatrices;
using Fgs.Setup.Application.Abstractions.SetupPricingMatrixLabors;
using Fgs.Setup.Application.Abstractions.SetupPricingMatrixLaborTiers;
using Fgs.Setup.Application.Abstractions.SetupTechSkillLevels;
using Fgs.Setup.Application.Features.SetupPricingMatrixLaborTiers.Commands.CreateFgsSetupPricingMatrixLaborTier;
using Fgs.Setup.Application.Features.SetupPricingMatrixLaborTiers.Commands.UpdateFgsSetupPricingMatrixLaborTier;
using Fgs.Setup.Application.Features.SetupPricingMatrixLaborTiers.Commands.PatchFgsSetupPricingMatrixLaborTier;
using FluentValidation;
namespace Fgs.Setup.Application.Features.SetupPricingMatrixLaborTiers.Validators;
public sealed class CreateFgsSetupPricingMatrixLaborTierCommandValidator:AbstractValidator<CreateFgsSetupPricingMatrixLaborTierCommand>
{
 public CreateFgsSetupPricingMatrixLaborTierCommandValidator(IFgsSetupPricingMatrixLaborReadRepository labors,IFgsSetupPricingMatrixLaborTierReadRepository tiers,IFgsSetupPricingMatrixReadRepository matrices,IFgsSetupTechSkillLevelReadRepository skills)
 {RuleFor(x=>x.Dto.DurationMinutes).GreaterThan(0);RuleFor(x=>x.Dto.Rate).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>await Check(d.PricingMatrixLaborId,d.SequenceOrder,d.TechSkillLevelId,null,labors,tiers,matrices,skills,c,ct));}
 internal static async Task Check(long laborId,short sequence,long? skill,long? exclude,IFgsSetupPricingMatrixLaborReadRepository labors,IFgsSetupPricingMatrixLaborTierReadRepository tiers,IFgsSetupPricingMatrixReadRepository matrices,IFgsSetupTechSkillLevelReadRepository skills,ValidationContext<CreateFgsSetupPricingMatrixLaborTierCommand> c,CancellationToken ct)
 {var matrixId=await labors.GetPricingMatrixIdAsync(laborId,true,ct);if(!matrixId.HasValue){c.AddFailure("Dto.PricingMatrixLaborId","The specified active pricing matrix labor was not found.");return;}var flags=await matrices.GetFlagsByIdAsync(matrixId.Value,ct);if(flags?.IsLaborTierStructure!=true)c.AddFailure("Dto.PricingMatrixLaborId","The pricing matrix does not allow labor tiers.");if(await tiers.ExistsBySequenceOrderAsync(laborId,sequence,exclude,ct))c.AddFailure("Dto.SequenceOrder","Sequence order must be unique per labor line.");if(flags is not null){if(!flags.IsLaborRateBySkillLevel&&skill.HasValue)c.AddFailure("Dto.TechSkillLevelId","Tech skill level must be null.");if(flags.IsLaborRateBySkillLevel&&!skill.HasValue)c.AddFailure("Dto.TechSkillLevelId","Tech skill level is required.");}if(skill.HasValue&&await skills.GetByIdAsync(skill.Value,ct)is null)c.AddFailure("Dto.TechSkillLevelId","The specified tech skill level was not found.");}
}
public sealed class UpdateFgsSetupPricingMatrixLaborTierCommandValidator:AbstractValidator<UpdateFgsSetupPricingMatrixLaborTierCommand>
{public UpdateFgsSetupPricingMatrixLaborTierCommandValidator(IFgsSetupPricingMatrixLaborReadRepository l,IFgsSetupPricingMatrixLaborTierReadRepository t,IFgsSetupPricingMatrixReadRepository m,IFgsSetupTechSkillLevelReadRepository s){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.DurationMinutes).GreaterThan(0);RuleFor(x=>x.Dto.Rate).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>{var mid=await l.GetPricingMatrixIdAsync(d.PricingMatrixLaborId,true,ct);if(!mid.HasValue){c.AddFailure("Dto.PricingMatrixLaborId","The specified active pricing matrix labor was not found.");return;}var f=await m.GetFlagsByIdAsync(mid.Value,ct);if(f?.IsLaborTierStructure!=true)c.AddFailure("Dto.PricingMatrixLaborId","The pricing matrix does not allow labor tiers.");if(await t.ExistsBySequenceOrderAsync(d.PricingMatrixLaborId,d.SequenceOrder,c.InstanceToValidate.Id,ct))c.AddFailure("Dto.SequenceOrder","Sequence order must be unique per labor line.");if(f is not null&&!f.IsLaborRateBySkillLevel&&d.TechSkillLevelId.HasValue)c.AddFailure("Dto.TechSkillLevelId","Tech skill level must be null.");if(f?.IsLaborRateBySkillLevel==true&&!d.TechSkillLevelId.HasValue)c.AddFailure("Dto.TechSkillLevelId","Tech skill level is required.");if(d.TechSkillLevelId.HasValue&&await s.GetByIdAsync(d.TechSkillLevelId.Value,ct)is null)c.AddFailure("Dto.TechSkillLevelId","The specified tech skill level was not found.");});}}
public sealed class PatchFgsSetupPricingMatrixLaborTierCommandValidator:AbstractValidator<PatchFgsSetupPricingMatrixLaborTierCommand>{public PatchFgsSetupPricingMatrixLaborTierCommandValidator(){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.DurationMinutes).GreaterThan(0).When(x=>x.Dto.DurationMinutes.HasValue);RuleFor(x=>x.Dto.Rate).GreaterThanOrEqualTo(0).When(x=>x.Dto.Rate.HasValue);}}
