-- =============================================================================
-- Migration: 20260517120000_NotificationTemplates
-- Script:   20260517120000_NotificationTemplates_Up.sql
-- Creates dbo.FgsSetupCommunicationTemplate (optional TenantId / CompanyId)
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260517120000_NotificationTemplates') THEN
    CREATE TABLE dbo."FgsSetupCommunicationTemplate" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "TenantId" uuid,
        "CompanyId" uuid,
        "TemplateType" text NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Subject" text,
        "Body" text NOT NULL,
        "IsMobileVisible" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamptz,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_FgsSetupCommunicationTemplate" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260517120000_NotificationTemplates') THEN
    CREATE INDEX "IX_FgsSetupCommunicationTemplate_TenantId_CompanyId"
        ON dbo."FgsSetupCommunicationTemplate" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260517120000_NotificationTemplates') THEN
    CREATE UNIQUE INDEX "IX_FgsSetupCommunicationTemplate_TenantId_CompanyId_TemplateType_Code"
        ON dbo."FgsSetupCommunicationTemplate" ("TenantId", "CompanyId", "TemplateType", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260517120000_NotificationTemplates') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260517120000_NotificationTemplates', '10.0.8');
    END IF;
END $EF$;

COMMIT;
