namespace Fgs.Asset.Application.Features.Assets.Dtos;

public sealed record FgsAssetSummaryDto(
    long Id,
    Guid AssetGuid,
    string AssetNumber,
    long? ServiceLocationId,
    string? UnitNumber,
    long? AssetTypeId,
    long? AssetManufacturerId,
    long? AssetModelId,
    string? AssetDescription,
    string? CustomerAssetNumber,
    string? CustomerAssetName,
    string? ManufacturerName,
    string? ModelNumber,
    string? SerialNumber,
    DateOnly? ManufactureDate,
    DateOnly? InstallDate,
    long? InstalledWorkOrderId,
    bool IsInstalledByCompany,
    bool IsOurInstallation,
    long AssetStatusId,
    bool IsActive);

public sealed record FgsAssetDetailDto(
    long Id,
    Guid AssetGuid,
    string AssetNumber,
    long? ServiceLocationId,
    string? UnitNumber,
    long? AssetTypeId,
    long? AssetManufacturerId,
    long? AssetModelId,
    string? AssetDescription,
    string? CustomerAssetNumber,
    string? CustomerAssetName,
    string? ManufacturerName,
    string? ModelNumber,
    string? SerialNumber,
    DateOnly? ManufactureDate,
    DateOnly? InstallDate,
    long? InstalledWorkOrderId,
    bool IsInstalledByCompany,
    bool IsOurInstallation,
    long AssetStatusId,
    bool IsActive);

public sealed record FgsAssetLookupDto(long Id, string AssetNumber, string? CustomerAssetName);

public sealed record FgsAssetCreateDto(
    string AssetNumber,
    long? ServiceLocationId,
    string? UnitNumber,
    long? AssetTypeId,
    long? AssetManufacturerId,
    long? AssetModelId,
    string? AssetDescription,
    string? CustomerAssetNumber,
    string? CustomerAssetName,
    string? ManufacturerName,
    string? ModelNumber,
    string? SerialNumber,
    DateOnly? ManufactureDate,
    DateOnly? InstallDate,
    long? InstalledWorkOrderId,
    bool IsInstalledByCompany,
    bool IsOurInstallation,
    long AssetStatusId);

public sealed record FgsAssetUpdateDto(
    string AssetNumber,
    long? ServiceLocationId,
    string? UnitNumber,
    long? AssetTypeId,
    long? AssetManufacturerId,
    long? AssetModelId,
    string? AssetDescription,
    string? CustomerAssetNumber,
    string? CustomerAssetName,
    string? ManufacturerName,
    string? ModelNumber,
    string? SerialNumber,
    DateOnly? ManufactureDate,
    DateOnly? InstallDate,
    long? InstalledWorkOrderId,
    bool IsInstalledByCompany,
    bool IsOurInstallation,
    long AssetStatusId);

public sealed record FgsAssetPatchDto(
    string? AssetNumber,
    long? ServiceLocationId,
    string? UnitNumber,
    long? AssetTypeId,
    long? AssetManufacturerId,
    long? AssetModelId,
    string? AssetDescription,
    string? CustomerAssetNumber,
    string? CustomerAssetName,
    string? ManufacturerName,
    string? ModelNumber,
    string? SerialNumber,
    DateOnly? ManufactureDate,
    DateOnly? InstallDate,
    long? InstalledWorkOrderId,
    bool? IsInstalledByCompany,
    bool? IsOurInstallation,
    long? AssetStatusId,
    bool? IsActive);

public sealed record FgsAssetListFilters(
    string? AssetNumber = null,
    long? ServiceLocationId = null,
    long? AssetStatusId = null);
