DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS inventory."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260603213321_InitialSchema') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603213321_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
            CREATE SCHEMA inventory;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE TABLE inventory."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE inventory."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the inventory schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON inventory."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON inventory."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON inventory."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604132520_AddFgsTenantCompanyCache', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE TABLE inventory."InventoryOutboxMessage" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint,
        "CompanyId" bigint,
        "EventType" character varying(150) NOT NULL,
        "AggregateType" character varying(100),
        "AggregateId" character varying(100),
        "CorrelationId" uuid NOT NULL,
        "CausationId" uuid,
        "ExchangeName" character varying(200),
        "RoutingKey" character varying(200),
        "Payload" jsonb NOT NULL,
        "Headers" jsonb,
        "Status" character varying(50) NOT NULL DEFAULT 'Pending',
        "RetryCount" integer NOT NULL DEFAULT 0,
        "MaxRetryCount" integer NOT NULL DEFAULT 10,
        "NextRetryOn" timestamptz,
        "ProcessedOn" timestamptz,
        "LastError" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_InventoryOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_CorrelationId" ON inventory."InventoryOutboxMessage" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_EventType" ON inventory."InventoryOutboxMessage" ("EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_Status_NextRetryOn" ON inventory."InventoryOutboxMessage" ("Status", "NextRetryOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_TenantId" ON inventory."InventoryOutboxMessage" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605152224_AddInventoryOutboxMessage', '10.0.8');
    END IF;
END $EF$;
COMMIT;

