DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS inventory."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260603213321_InitialSchema') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603213321_InitialSchema', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
            CREATE SCHEMA inventory;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE TABLE inventory."FgsTenantCompanyCache" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyCode" character varying(100) NOT NULL,
        "CompanyName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsTenantCompanyCache" PRIMARY KEY ("TenantId", "CompanyId")
    );
    COMMENT ON TABLE inventory."FgsTenantCompanyCache" IS 'Local cache of tenant company information used by the inventory schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyId" IS 'Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyGuid" IS 'Globally unique company identifier used by integrations and external systems.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyCode" IS 'Unique company code within a tenant.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."CompanyName" IS 'Display name of the company.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."IsActive" IS 'Indicates whether the company is active.';
    COMMENT ON COLUMN inventory."FgsTenantCompanyCache"."UpdatedOn" IS 'Timestamp of the most recent synchronization from tenant.FgsTenantCompany.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_CompanyName" ON inventory."FgsTenantCompanyCache" ("CompanyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE INDEX "IX_FgsTenantCompanyCache_IsActive" ON inventory."FgsTenantCompanyCache" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    CREATE UNIQUE INDEX "UQ_FgsTenantCompanyCache_CompanyGuid" ON inventory."FgsTenantCompanyCache" ("CompanyGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260604132520_AddFgsTenantCompanyCache') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604132520_AddFgsTenantCompanyCache', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE TABLE inventory."InventoryOutboxMessage" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint,
        "CompanyId" bigint,
        "EventType" character varying(150) NOT NULL,
        "AggregateType" character varying(100),
        "AggregateId" character varying(100),
        "CorrelationId" uuid NOT NULL,
        "CausationId" uuid,
        "ExchangeName" character varying(200),
        "RoutingKey" character varying(200),
        "Payload" jsonb NOT NULL,
        "Headers" jsonb,
        "Status" character varying(50) NOT NULL DEFAULT 'Pending',
        "RetryCount" integer NOT NULL DEFAULT 0,
        "MaxRetryCount" integer NOT NULL DEFAULT 10,
        "NextRetryOn" timestamptz,
        "ProcessedOn" timestamptz,
        "LastError" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_InventoryOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_CorrelationId" ON inventory."InventoryOutboxMessage" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_EventType" ON inventory."InventoryOutboxMessage" ("EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_Status_NextRetryOn" ON inventory."InventoryOutboxMessage" ("Status", "NextRetryOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    CREATE INDEX "IX_InventoryOutboxMessage_TenantId" ON inventory."InventoryOutboxMessage" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260605152224_AddInventoryOutboxMessage') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605152224_AddInventoryOutboxMessage', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260606085013_StandardizeAuditColumnsToVarchar') THEN
    ALTER TABLE inventory."InventoryOutboxMessage" ALTER COLUMN "UpdatedBy" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260606085013_StandardizeAuditColumnsToVarchar') THEN
    ALTER TABLE inventory."InventoryOutboxMessage" ALTER COLUMN "CreatedBy" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260606085013_StandardizeAuditColumnsToVarchar') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260606085013_StandardizeAuditColumnsToVarchar', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryCategory" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CategoryCode" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Description" text,
        "TextColor" character varying(20),
        "BackgroundColor" character varying(20),
        "DisplayIconFileId" bigint,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsSystem" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsInventoryCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryCategory_TenantId_CompanyId_CategoryCode" UNIQUE ("TenantId", "CompanyId", "CategoryCode"),
        CONSTRAINT "FK_FgsInventoryCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventoryCategory" IS 'Stores the first level of inventory classification.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."Id" IS 'Unique identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."CategoryCode" IS 'Unique category code within a company.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."Name" IS 'Category display name.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."Description" IS 'Optional description.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."TextColor" IS 'UI text color.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."BackgroundColor" IS 'UI background color.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."DisplayIconFileId" IS 'Display icon stored in FgsFile.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."DisplayOrder" IS 'Display order.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."IsSystem" IS 'Seeded system record.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."CreatedOn" IS 'Created timestamp.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."CreatedBy" IS 'Created by user.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."UpdatedOn" IS 'Updated timestamp.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."UpdatedBy" IS 'Updated by user.';
    COMMENT ON COLUMN inventory."FgsInventoryCategory"."IsActive" IS 'Active flag.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryItemType" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "ItemTypeCode" character varying(30) NOT NULL,
        "Name" character varying(50) NOT NULL,
        "Description" text,
        "TracksQuantity" boolean NOT NULL DEFAULT FALSE,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsSystem" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsInventoryItemType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryItemType_TenantId_CompanyId_ItemTypeCode" UNIQUE ("TenantId", "CompanyId", "ItemTypeCode"),
        CONSTRAINT "FK_FgsInventoryItemType_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventoryItemType" IS 'Stores inventory item types used to classify inventory items and determine whether quantity is tracked.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."Id" IS 'Unique identifier for the inventory item type.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."TenantId" IS 'Tenant that owns this record.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."CompanyId" IS 'Company that owns this record.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."ItemTypeCode" IS 'Unique code for the inventory item type within a company.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."Name" IS 'Display name of the inventory item type.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."Description" IS 'Optional description of the inventory item type.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."TracksQuantity" IS 'Indicates whether inventory quantities are maintained for this item type.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."DisplayOrder" IS 'Controls display order in user interfaces.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."IsSystem" IS 'Indicates whether this is a system-defined record.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."UpdatedBy" IS 'User who last updated the record.';
    COMMENT ON COLUMN inventory."FgsInventoryItemType"."IsActive" IS 'Indicates whether the record is active.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryLocation" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "InventoryLocationCode" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "InventoryLocationType" character varying(30) NOT NULL,
        "ParentInventoryLocationId" bigint,
        "Description" text,
        "Address1" character varying(200),
        "Address2" character varying(200),
        "City" character varying(100),
        "StateProvince" character varying(100),
        "PostalCode" character varying(20),
        "Country" character varying(100),
        "ContactName" character varying(150),
        "PhoneNumber" character varying(50),
        "Email" character varying(255),
        "TextColor" character varying(20),
        "BackgroundColor" character varying(20),
        "DisplayIconFileId" bigint,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsDefault" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsInventoryLocation" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryLocation_TenantId_CompanyId_InventoryLocationCode" UNIQUE ("TenantId", "CompanyId", "InventoryLocationCode"),
        CONSTRAINT "CK_FgsInventoryLocation_InventoryLocationType" CHECK ("InventoryLocationType" IN ('WAREHOUSE', 'TRUCK', 'TRAILER', 'JOBSITE', 'CONSIGNMENT', 'VENDOR')),
        CONSTRAINT "FK_FgsInventoryLocation_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryLocation_ParentInventoryLocation" FOREIGN KEY ("ParentInventoryLocationId") REFERENCES inventory."FgsInventoryLocation" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventoryLocation" IS 'Stores all inventory locations including warehouses, trucks, trailers, job sites, vendor locations and consignment locations.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Id" IS 'Primary key.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."InventoryLocationCode" IS 'Unique inventory location code.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Name" IS 'Display name.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."InventoryLocationType" IS 'WAREHOUSE, TRUCK, TRAILER, JOBSITE, CONSIGNMENT or VENDOR.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."ParentInventoryLocationId" IS 'Optional parent inventory location.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Description" IS 'Description or notes.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Address1" IS 'Address line 1.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Address2" IS 'Address line 2.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."City" IS 'City.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."StateProvince" IS 'State or province.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."PostalCode" IS 'Postal code.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Country" IS 'Country.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."ContactName" IS 'Primary contact.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."PhoneNumber" IS 'Contact phone.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."Email" IS 'Contact email.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."TextColor" IS 'UI text color.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."BackgroundColor" IS 'UI background color.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."DisplayIconFileId" IS 'Display icon file identifier.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."DisplayOrder" IS 'Display order.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."IsDefault" IS 'Default inventory location.';
    COMMENT ON COLUMN inventory."FgsInventoryLocation"."IsActive" IS 'Active flag.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsVendor" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "VendorCode" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LegalName" character varying(200),
        "VendorType" character varying(50) NOT NULL,
        "VendorStatus" character varying(30) NOT NULL DEFAULT 'ACTIVE',
        "VendorAccountNumber" character varying(100),
        "PaymentTermId" bigint,
        "ContactName" character varying(150),
        "ContactTitle" character varying(100),
        "Email" character varying(255),
        "PurchaseOrderEmail" character varying(255),
        "PhoneNumber" character varying(50),
        "MobileNumber" character varying(50),
        "FaxNumber" character varying(50),
        "Website" character varying(255),
        "Address1" character varying(200),
        "Address2" character varying(200),
        "City" character varying(100),
        "StateProvince" character varying(100),
        "PostalCode" character varying(20),
        "Country" character varying(100),
        "TaxIdNumber" character varying(100),
        "LicenseNumber" character varying(100),
        "InsurancePolicyNumber" character varying(100),
        "Notes" text,
        "Is1099Eligible" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsVendor" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsVendor_TenantId_CompanyId_VendorCode" UNIQUE ("TenantId", "CompanyId", "VendorCode"),
        CONSTRAINT "CK_FgsVendor_VendorStatus" CHECK ("VendorStatus" IN ('ACTIVE', 'INACTIVE', 'ON_HOLD')),
        CONSTRAINT "CK_FgsVendor_VendorType" CHECK ("VendorType" IN ('VENDOR', 'SUBCONTRACTOR')),
        CONSTRAINT "FK_FgsVendor_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsVendor" IS 'Stores vendor and subcontractor master information for purchasing, AP, and subcontractor management.';
    COMMENT ON COLUMN inventory."FgsVendor"."PaymentTermId" IS 'References setup payment terms; scalar only — no cross-schema FK.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventorySubCategory" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "InventoryCategoryId" bigint NOT NULL,
        "SubCategoryCode" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Description" text,
        "TextColor" character varying(20),
        "BackgroundColor" character varying(20),
        "DisplayIconFileId" bigint,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsSystem" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsInventorySubCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventorySubCategory_TenantId_CompanyId_InventoryCategoryId_SubCategoryCode" UNIQUE ("TenantId", "CompanyId", "InventoryCategoryId", "SubCategoryCode"),
        CONSTRAINT "FK_FgsInventorySubCategory_FgsInventoryCategory" FOREIGN KEY ("InventoryCategoryId") REFERENCES inventory."FgsInventoryCategory" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventorySubCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventorySubCategory" IS 'Stores inventory sub-categories used to classify inventory items under a parent category.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."Id" IS 'Unique identifier.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."InventoryCategoryId" IS 'Parent inventory category.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."SubCategoryCode" IS 'Unique code within a category.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."Name" IS 'Display name.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."Description" IS 'Description.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."TextColor" IS 'UI text color.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."BackgroundColor" IS 'UI background color.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."DisplayIconFileId" IS 'Icon file identifier.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."DisplayOrder" IS 'Display order.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."IsSystem" IS 'System record.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."CreatedOn" IS 'Created date/time.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."CreatedBy" IS 'Created by.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."UpdatedOn" IS 'Updated date/time.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."UpdatedBy" IS 'Updated by.';
    COMMENT ON COLUMN inventory."FgsInventorySubCategory"."IsActive" IS 'Active flag.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsPurchaseOrder" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOrderNumber" character varying(50) NOT NULL,
        "VendorId" bigint NOT NULL,
        "PurchaseOrderStatus" character varying(30) NOT NULL DEFAULT 'OPEN',
        "PurchaseOrderDate" timestamptz NOT NULL DEFAULT (now()),
        "ExpectedDeliveryDate" timestamptz,
        "RequestedByEmployeeId" bigint,
        "RequestedByName" character varying(150),
        "BuyerEmployeeId" bigint,
        "ShipToInventoryLocationId" bigint,
        "ShipToServiceLocationId" bigint,
        "ShipToName" character varying(200),
        "ShipToAddress1" character varying(200),
        "ShipToAddress2" character varying(200),
        "ShipToCity" character varying(100),
        "ShipToStateProvince" character varying(100),
        "ShipToPostalCode" character varying(20),
        "ShipToCountry" character varying(100),
        "VendorReferenceNumber" character varying(100),
        "VendorContactName" character varying(150),
        "VendorEmail" character varying(255),
        "VendorPhoneNumber" character varying(50),
        "Subtotal" numeric(18,2) NOT NULL DEFAULT 0.0,
        "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "TaxableAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "PurchaseTaxJson" jsonb,
        "FreightAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "OtherCharges" numeric(18,2) NOT NULL DEFAULT 0.0,
        "TotalAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "VendorNotes" text,
        "InternalNotes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsPurchaseOrder" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsPurchaseOrder_TenantId_CompanyId_PurchaseOrderNumber" UNIQUE ("TenantId", "CompanyId", "PurchaseOrderNumber"),
        CONSTRAINT "CK_FgsPurchaseOrder_PurchaseOrderStatus" CHECK ("PurchaseOrderStatus" IN ('OPEN', 'PARTIAL', 'RECEIVED', 'CLOSED', 'CANCELLED')),
        CONSTRAINT "FK_FgsPurchaseOrder_FgsInventoryLocation" FOREIGN KEY ("ShipToInventoryLocationId") REFERENCES inventory."FgsInventoryLocation" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsPurchaseOrder_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsPurchaseOrder_FgsVendor" FOREIGN KEY ("VendorId") REFERENCES inventory."FgsVendor" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsPurchaseOrder" IS 'Stores purchase order header information including vendor, shipping destination, tax summary and purchasing details.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."PurchaseOrderNumber" IS 'User-visible purchase order number.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."PurchaseOrderStatus" IS 'OPEN, PARTIAL, RECEIVED, CLOSED or CANCELLED.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."RequestedByEmployeeId" IS 'Employee requesting the purchase.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."RequestedByName" IS 'Snapshot of the requester name when the purchase order was created.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."BuyerEmployeeId" IS 'Employee responsible for purchasing and vendor follow-up.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."ShipToInventoryLocationId" IS 'Inventory location receiving the shipment.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."ShipToServiceLocationId" IS 'Service location or job site receiving the shipment.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."PurchaseTaxJson" IS 'JSON tax breakdown supporting multiple tax jurisdictions such as GST, PST, HST, VAT and Sales Tax.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."VendorNotes" IS 'Notes printed on the purchase order for the vendor.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrder"."InternalNotes" IS 'Internal office notes not printed on the purchase order.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryItem" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "InventoryItemTypeId" bigint NOT NULL,
        "InventoryCategoryId" bigint,
        "InventorySubCategoryId" bigint,
        "ItemCode" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "PurchaseDescription" text,
        "SalesDescription" text,
        "ManufacturerPartNumber" character varying(100),
        "ManufacturerName" character varying(150),
        "Sku" character varying(100),
        "UPCCode" character varying(100),
        "UnitOfMeasure" character varying(50),
        "TracksInventory" boolean NOT NULL DEFAULT FALSE,
        "UnitCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "StandardUnitCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "SalesPrice" numeric(18,2) NOT NULL DEFAULT 0.0,
        "DefaultTaxable" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsInventoryItem" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryItem_TenantId_CompanyId_ItemCode" UNIQUE ("TenantId", "CompanyId", "ItemCode"),
        CONSTRAINT "FK_FgsInventoryItem_FgsInventoryCategory" FOREIGN KEY ("InventoryCategoryId") REFERENCES inventory."FgsInventoryCategory" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItem_FgsInventoryItemType" FOREIGN KEY ("InventoryItemTypeId") REFERENCES inventory."FgsInventoryItemType" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItem_FgsInventorySubCategory" FOREIGN KEY ("InventorySubCategoryId") REFERENCES inventory."FgsInventorySubCategory" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItem_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventoryItem" IS 'Inventory item master record for purchasing, sales, and stock tracking.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryItemAlternate" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "InventoryItemId" bigint NOT NULL,
        "AlternateInventoryItemId" bigint NOT NULL,
        "PriorityOrder" smallint NOT NULL DEFAULT 1,
        "Notes" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsInventoryItemAlternate" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryItemAlternate_TenantId_CompanyId_InventoryItemId_AlternateInventoryItemId" UNIQUE ("TenantId", "CompanyId", "InventoryItemId", "AlternateInventoryItemId"),
        CONSTRAINT "FK_FgsInventoryItemAlternate_FgsInventoryItem_AlternateInventoryItemId" FOREIGN KEY ("AlternateInventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItemAlternate_FgsInventoryItem_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItemAlternate_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryItemDependency" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "InventoryItemId" bigint NOT NULL,
        "DependentInventoryItemId" bigint NOT NULL,
        "Quantity" numeric(18,4) NOT NULL DEFAULT 1.0,
        "IsRequired" boolean NOT NULL DEFAULT TRUE,
        "Notes" text,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsInventoryItemDependency" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryItemDependency_TenantId_CompanyId_InventoryItemId_DependentInventoryItemId" UNIQUE ("TenantId", "CompanyId", "InventoryItemId", "DependentInventoryItemId"),
        CONSTRAINT "FK_FgsInventoryItemDependency_FgsInventoryItem_DependentInventoryItemId" FOREIGN KEY ("DependentInventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItemDependency_FgsInventoryItem_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryItemDependency_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryStock" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "InventoryItemId" bigint NOT NULL,
        "QuantityOnHand" numeric(18,4) NOT NULL DEFAULT 0.0,
        "QuantityCommitted" numeric(18,4) NOT NULL DEFAULT 0.0,
        "QuantityAvailable" numeric(18,4) NOT NULL DEFAULT 0.0,
        "AverageCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "LastCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "LastPurchaseDate" timestamptz,
        "LastSoldDate" timestamptz,
        "UpdatedOn" timestamptz NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_FgsInventoryStock" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryStock_TenantId_CompanyId_InventoryItemId" UNIQUE ("TenantId", "CompanyId", "InventoryItemId"),
        CONSTRAINT "FK_FgsInventoryStock_FgsInventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryStock_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsInventoryTransaction" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TransactionNumber" character varying(50) NOT NULL,
        "InventoryItemId" bigint NOT NULL,
        "TransactionType" character varying(30) NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "FromInventoryLocationId" bigint,
        "ToInventoryLocationId" bigint,
        "UnitCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "TransactionDate" timestamptz NOT NULL DEFAULT (now()),
        "ReferenceType" character varying(30),
        "ReferenceId" bigint,
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" text,
        CONSTRAINT "PK_FgsInventoryTransaction" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventoryTransaction_TenantId_CompanyId_TransactionNumber" UNIQUE ("TenantId", "CompanyId", "TransactionNumber"),
        CONSTRAINT "CK_FgsInventoryTransaction_TransactionType" CHECK ("TransactionType" IN ('INITIAL', 'PURCHASE_RECEIPT', 'TRANSFER', 'USAGE', 'ADJUSTMENT', 'RETURN', 'PHYSICAL_COUNT')),
        CONSTRAINT "FK_FgsInventoryTransaction_FgsInventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryTransaction_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryTransaction_FromInventoryLocation" FOREIGN KEY ("FromInventoryLocationId") REFERENCES inventory."FgsInventoryLocation" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventoryTransaction_ToInventoryLocation" FOREIGN KEY ("ToInventoryLocationId") REFERENCES inventory."FgsInventoryLocation" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventoryTransaction" IS 'Stores an immutable audit log of every inventory movement between inventory locations or into and out of inventory.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsPurchaseOrderDetail" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOrderId" bigint NOT NULL,
        "LineNumber" smallint NOT NULL,
        "ItemId" bigint NOT NULL,
        "VendorPartNumber" character varying(100),
        "ItemDescription" character varying(255) NOT NULL,
        "UnitOfMeasureCode" character varying(25) NOT NULL,
        "OrderedQuantity" numeric(18,4) NOT NULL DEFAULT 0.0,
        "ReceivedQuantity" numeric(18,4) NOT NULL DEFAULT 0.0,
        "UnitCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "DiscountAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "IsTaxable" boolean NOT NULL DEFAULT TRUE,
        "ExtendedAmount" numeric(18,2) NOT NULL DEFAULT 0.0,
        "ExpectedDeliveryDate" timestamptz,
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsPurchaseOrderDetail" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsPurchaseOrderDetail_TenantId_CompanyId_PurchaseOrderId_LineNumber" UNIQUE ("TenantId", "CompanyId", "PurchaseOrderId", "LineNumber"),
        CONSTRAINT "FK_FgsPurchaseOrderDetail_FgsInventoryItem" FOREIGN KEY ("ItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsPurchaseOrderDetail_FgsPurchaseOrder" FOREIGN KEY ("PurchaseOrderId") REFERENCES inventory."FgsPurchaseOrder" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsPurchaseOrderDetail_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsPurchaseOrderDetail" IS 'Stores purchase order line items for inventory purchased from vendors.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrderDetail"."ItemDescription" IS 'Description printed on the purchase order.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrderDetail"."UnitCost" IS 'Unit cost at the time the purchase order was created.';
    COMMENT ON COLUMN inventory."FgsPurchaseOrderDetail"."ExtendedAmount" IS 'Extended amount calculated from quantity, unit cost and discount before document-level taxes and freight.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE TABLE inventory."FgsVendorInventoryItem" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "VendorId" bigint NOT NULL,
        "InventoryItemId" bigint NOT NULL,
        "VendorPartNumber" character varying(100),
        "VendorPartName" character varying(200),
        "LastCost" numeric(18,2) NOT NULL DEFAULT 0.0,
        "LastReceivedDate" timestamptz,
        "PurchaseOrderComments" text,
        "VendorPriority" smallint NOT NULL,
        "LeadTimeDays" smallint,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsVendorInventoryItem" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsVendorInventoryItem_TenantId_CompanyId_VendorId_InventoryItemId" UNIQUE ("TenantId", "CompanyId", "VendorId", "InventoryItemId"),
        CONSTRAINT "FK_FgsVendorInventoryItem_FgsInventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsVendorInventoryItem_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsVendorInventoryItem_FgsVendor" FOREIGN KEY ("VendorId") REFERENCES inventory."FgsVendor" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsVendorInventoryItem" IS 'Stores vendor-specific purchasing information for inventory items, including vendor part numbers, descriptions, pricing, purchasing priority, lead times, and other information used during purchase order creation and inventory replenishment.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."VendorPartNumber" IS 'Vendor''s part number used when purchasing this inventory item.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."VendorPartName" IS 'Vendor''s description of the inventory item as it appears on catalogs or purchase orders.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."LastCost" IS 'Most recent purchase cost from this vendor for the inventory item.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."LastReceivedDate" IS 'Date the inventory item was last received from this vendor.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."PurchaseOrderComments" IS 'Vendor-specific notes automatically included or displayed during purchase order creation for this inventory item.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."VendorPriority" IS 'Specifies the purchasing priority for this vendor and inventory item combination. Lower numbers indicate higher priority.';
    COMMENT ON COLUMN inventory."FgsVendorInventoryItem"."LeadTimeDays" IS 'Expected number of days required for the vendor to deliver the inventory item after the purchase order is placed.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryCategory_TenantId_CompanyId" ON inventory."FgsInventoryCategory" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryCategory_TenantId_CompanyId_IsActive" ON inventory."FgsInventoryCategory" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryCategory_TenantId_CompanyId_Name" ON inventory."FgsInventoryCategory" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_InventoryCategoryId" ON inventory."FgsInventoryItem" ("TenantId", "CompanyId", "InventoryCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_InventoryCategoryId1" ON inventory."FgsInventoryItem" ("InventoryCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_InventoryItemTypeId" ON inventory."FgsInventoryItem" ("InventoryItemTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_InventorySubCategoryId" ON inventory."FgsInventoryItem" ("TenantId", "CompanyId", "InventoryItemTypeId", "InventorySubCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_InventorySubCategoryId1" ON inventory."FgsInventoryItem" ("InventorySubCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_TenantId_CompanyId_InventoryItemTypeId" ON inventory."FgsInventoryItem" ("TenantId", "CompanyId", "InventoryItemTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItem_TenantId_CompanyId_Name" ON inventory."FgsInventoryItem" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemAlternate_AlternateInventoryItemId" ON inventory."FgsInventoryItemAlternate" ("AlternateInventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemAlternate_InventoryItemId" ON inventory."FgsInventoryItemAlternate" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemAlternate_TenantId_CompanyId_InventoryItemId" ON inventory."FgsInventoryItemAlternate" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemDependency_DependentInventoryItemId" ON inventory."FgsInventoryItemDependency" ("DependentInventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemDependency_InventoryItemId" ON inventory."FgsInventoryItemDependency" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemDependency_TenantId_CompanyId_InventoryItemId" ON inventory."FgsInventoryItemDependency" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemType_TenantId_CompanyId" ON inventory."FgsInventoryItemType" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemType_TenantId_CompanyId_IsActive" ON inventory."FgsInventoryItemType" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryItemType_TenantId_CompanyId_Name" ON inventory."FgsInventoryItemType" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryLocation_ParentInventoryLocationId" ON inventory."FgsInventoryLocation" ("ParentInventoryLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryLocation_TenantId_CompanyId" ON inventory."FgsInventoryLocation" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryLocation_TenantId_CompanyId_InventoryLocationType" ON inventory."FgsInventoryLocation" ("TenantId", "CompanyId", "InventoryLocationType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryLocation_TenantId_CompanyId_Name" ON inventory."FgsInventoryLocation" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryStock_InventoryItemId" ON inventory."FgsInventoryStock" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryStock_TenantId_CompanyId" ON inventory."FgsInventoryStock" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryStock_TenantId_CompanyId_InventoryItemId" ON inventory."FgsInventoryStock" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryStock_TenantId_CompanyId_LastPurchaseDate" ON inventory."FgsInventoryStock" ("TenantId", "CompanyId", "LastPurchaseDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryStock_TenantId_CompanyId_LastSoldDate" ON inventory."FgsInventoryStock" ("TenantId", "CompanyId", "LastSoldDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventorySubCategory_InventoryCategoryId" ON inventory."FgsInventorySubCategory" ("InventoryCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventorySubCategory_TenantId_CompanyId" ON inventory."FgsInventorySubCategory" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventorySubCategory_TenantId_CompanyId_InventoryCategoryId" ON inventory."FgsInventorySubCategory" ("TenantId", "CompanyId", "InventoryCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventorySubCategory_TenantId_CompanyId_IsActive" ON inventory."FgsInventorySubCategory" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventorySubCategory_TenantId_CompanyId_Name" ON inventory."FgsInventorySubCategory" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_FromInventoryLocationId" ON inventory."FgsInventoryTransaction" ("FromInventoryLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_InventoryItemId" ON inventory."FgsInventoryTransaction" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId_InventoryItemId" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId_ReferenceType_ReferenceId" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId", "ReferenceType", "ReferenceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId_TransactionDate" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId", "TransactionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId_TransactionType" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId", "TransactionType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_ToInventoryLocationId" ON inventory."FgsInventoryTransaction" ("ToInventoryLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_ShipToInventoryLocationId" ON inventory."FgsPurchaseOrder" ("ShipToInventoryLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_TenantId_CompanyId" ON inventory."FgsPurchaseOrder" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_TenantId_CompanyId_BuyerEmployeeId" ON inventory."FgsPurchaseOrder" ("TenantId", "CompanyId", "BuyerEmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_TenantId_CompanyId_PurchaseOrderDate" ON inventory."FgsPurchaseOrder" ("TenantId", "CompanyId", "PurchaseOrderDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_TenantId_CompanyId_PurchaseOrderStatus" ON inventory."FgsPurchaseOrder" ("TenantId", "CompanyId", "PurchaseOrderStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_TenantId_CompanyId_VendorId" ON inventory."FgsPurchaseOrder" ("TenantId", "CompanyId", "VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrder_VendorId" ON inventory."FgsPurchaseOrder" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrderDetail_ItemId" ON inventory."FgsPurchaseOrderDetail" ("ItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrderDetail_PurchaseOrderId" ON inventory."FgsPurchaseOrderDetail" ("PurchaseOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrderDetail_TenantId_CompanyId" ON inventory."FgsPurchaseOrderDetail" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrderDetail_TenantId_CompanyId_ItemId" ON inventory."FgsPurchaseOrderDetail" ("TenantId", "CompanyId", "ItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsPurchaseOrderDetail_TenantId_CompanyId_PurchaseOrderId" ON inventory."FgsPurchaseOrderDetail" ("TenantId", "CompanyId", "PurchaseOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendor_TenantId_CompanyId" ON inventory."FgsVendor" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendor_TenantId_CompanyId_Name" ON inventory."FgsVendor" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendor_TenantId_CompanyId_PhoneNumber" ON inventory."FgsVendor" ("TenantId", "CompanyId", "PhoneNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendor_TenantId_CompanyId_VendorContactName" ON inventory."FgsVendor" ("TenantId", "CompanyId", "ContactName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendorInventoryItem_InventoryItemId" ON inventory."FgsVendorInventoryItem" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendorInventoryItem_TenantId_CompanyId_InventoryItemId" ON inventory."FgsVendorInventoryItem" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendorInventoryItem_TenantId_CompanyId_VendorId" ON inventory."FgsVendorInventoryItem" ("TenantId", "CompanyId", "VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    CREATE INDEX "IX_FgsVendorInventoryItem_VendorId" ON inventory."FgsVendorInventoryItem" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260627155750_AddInventoryCoreEntities') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260627155750_AddInventoryCoreEntities', '10.0.8');
    END IF;
END $EF$;
COMMIT;

