START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    ALTER TABLE inventory."FgsInventoryItem" DROP COLUMN "DefaultTaxable";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
            CREATE SCHEMA inventory;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE TYPE inventory."FgsInventorySerialStatus" AS ENUM ('Available', 'Reserved', 'Installed', 'InTransit', 'Returned', 'Scrapped', 'Lost', 'OnHold');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    ALTER TABLE inventory."FgsInventoryTransaction" ADD "SerialNumber" character varying(200);
    COMMENT ON COLUMN inventory."FgsInventoryTransaction"."SerialNumber" IS 'Serial number of the inventory item involved in the transaction. Null for non-serialized inventory items.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    ALTER TABLE inventory."FgsInventoryItem" ADD "IsSerialized" boolean NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN inventory."FgsInventoryItem"."IsSerialized" IS 'Indicates whether individual serial numbers are tracked for this inventory item.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE TABLE inventory."FgsInventorySerial" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "InventoryItemId" bigint NOT NULL,
        "SerialNumber" character varying(200) NOT NULL,
        "InventorySerialStatus" inventory."FgsInventorySerialStatus" NOT NULL DEFAULT 'Available'::inventory."FgsInventorySerialStatus",
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsInventorySerial" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsInventorySerial_TenantId_CompanyId_InventoryItemId_SerialNumber" UNIQUE ("TenantId", "CompanyId", "InventoryItemId", "SerialNumber"),
        CONSTRAINT "FK_FgsInventorySerial_FgsInventoryItem" FOREIGN KEY ("InventoryItemId") REFERENCES inventory."FgsInventoryItem" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsInventorySerial_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES inventory."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE inventory."FgsInventorySerial" IS 'Stores individual serialized inventory units and their current lifecycle status. Inventory movement history is maintained in FgsInventoryTransaction.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."Id" IS 'Unique identifier for the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."TenantId" IS 'Identifies the tenant that owns the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."CompanyId" IS 'Identifies the company that owns the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."InventoryItemId" IS 'References the inventory item associated with this serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."SerialNumber" IS 'Manufacturer or company-assigned serial number uniquely identifying the physical inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."InventorySerialStatus" IS 'Current lifecycle status of the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."Notes" IS 'Optional notes associated with the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."CreatedOn" IS 'Date and time when the serialized inventory unit was created.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."CreatedBy" IS 'User who created the serialized inventory unit.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."UpdatedOn" IS 'Date and time when the serialized inventory unit was last modified.';
    COMMENT ON COLUMN inventory."FgsInventorySerial"."UpdatedBy" IS 'User who last modified the serialized inventory unit.';
    COMMENT ON TYPE inventory."FgsInventorySerialStatus" IS 'Represents the current lifecycle status of a serialized inventory unit.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE INDEX "IX_FgsInventoryTransaction_TenantId_CompanyId_SerialNumber" ON inventory."FgsInventoryTransaction" ("TenantId", "CompanyId", "SerialNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE INDEX "IX_FgsInventorySerial_InventoryItemId" ON inventory."FgsInventorySerial" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE INDEX "IX_FgsInventorySerial_TenantId_CompanyId_InventoryItemId" ON inventory."FgsInventorySerial" ("TenantId", "CompanyId", "InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    CREATE INDEX "IX_FgsInventorySerial_TenantId_CompanyId_InventorySerialStatus" ON inventory."FgsInventorySerial" ("TenantId", "CompanyId", "InventorySerialStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM inventory."__EFMigrationsHistory" WHERE "MigrationId" = '20260803193809_AddInventorySerialAndItemSerializedFlag') THEN
    INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803193809_AddInventorySerialAndItemSerializedFlag', '10.0.8');
    END IF;
END $EF$;
COMMIT;

