namespace Fgs.Billing.Application.Features.Invoices.Dtos;

public sealed record FgsInvoiceSummaryDto(
    long Id,
    string InvoiceNumber,
    short InvoiceTypeId,
    long CustomerId,
    long ServiceLocationId,
    DateOnly InvoiceDate,
    DateOnly? DueDate,
    decimal InvoiceTotal,
    decimal BalanceDue,
    bool IsApproved,
    bool IsPosted);

public sealed record FgsInvoiceLineDto(
    long Id,
    int LineNumber,
    int BillingCategoryId,
    string? ItemCode,
    string ItemDescription,
    decimal Quantity,
    decimal UnitPrice,
    decimal ExtendedPrice,
    bool IsTaxable);

public sealed record FgsInvoiceDetailDto(
    long Id,
    string InvoiceNumber,
    short InvoiceTypeId,
    long CustomerId,
    long ServiceLocationId,
    long? WorkOrderId,
    long? ProjectId,
    long? ServiceAgreementId,
    long? MaintenanceVisitId,
    string? ServiceJobNum,
    bool IsAgreementBilling,
    bool IsRecurringInvoice,
    long? RecurringScheduleId,
    string? WorkOrderNumber,
    int? JobTypeId,
    long? LeadEmployeeId,
    string? CustomerPONumber,
    DateOnly InvoiceDate,
    DateOnly AccountingDate,
    DateOnly? DueDate,
    int? NetTermId,
    int? PreferredPaymentMethodId,
    long? LaborPricingMatrixId,
    long? MaterialPricingMatrixId,
    long? OtherPricingMatrixId,
    int? GLBreak1Id,
    int? GLBreak2Id,
    string? TaxingAuthorityJson,
    string? BillToAddressJson,
    string? ServiceLocationAddressJson,
    string? CompanyAddressJson,
    long? InvoiceTemplateId,
    bool IsSigned,
    DateTime? SignedOn,
    decimal InvoiceSubtotal,
    decimal TotalDiscount,
    decimal TaxableAmount,
    decimal TotalTax,
    decimal InvoiceTotal,
    decimal AppliedAmount,
    decimal BalanceDue,
    bool IsApproved,
    long? ApprovedBy,
    DateTime? ApprovedOn,
    bool IsPosted,
    long? PostedBy,
    DateTime? PostedOn,
    long? InvoiceBatchId,
    string? ExternalAccountingId,
    string? ExternalAccountingSyncToken,
    IReadOnlyList<FgsInvoiceLineDto> Lines);

public sealed record FgsInvoiceLookupDto(
    long Id,
    string InvoiceNumber);

public sealed record FgsInvoiceCreateDto(
    string InvoiceNumber,
    short InvoiceTypeId,
    long CustomerId,
    long ServiceLocationId,
    long? WorkOrderId,
    long? ProjectId,
    long? ServiceAgreementId,
    long? MaintenanceVisitId,
    string? ServiceJobNum,
    bool IsAgreementBilling,
    bool IsRecurringInvoice,
    long? RecurringScheduleId,
    string? WorkOrderNumber,
    int? JobTypeId,
    long? LeadEmployeeId,
    string? CustomerPONumber,
    DateOnly InvoiceDate,
    DateOnly AccountingDate,
    DateOnly? DueDate,
    int? NetTermId,
    int? PreferredPaymentMethodId,
    long? LaborPricingMatrixId,
    long? MaterialPricingMatrixId,
    long? OtherPricingMatrixId,
    int? GLBreak1Id,
    int? GLBreak2Id,
    string? TaxingAuthorityJson,
    string? BillToAddressJson,
    string? ServiceLocationAddressJson,
    string? CompanyAddressJson,
    long? InvoiceTemplateId,
    decimal InvoiceSubtotal,
    decimal TotalDiscount,
    decimal TaxableAmount,
    decimal TotalTax,
    decimal InvoiceTotal,
    decimal BalanceDue);

public sealed record FgsInvoiceUpdateDto(
    string InvoiceNumber,
    short InvoiceTypeId,
    long CustomerId,
    long ServiceLocationId,
    long? WorkOrderId,
    long? ProjectId,
    long? ServiceAgreementId,
    long? MaintenanceVisitId,
    string? ServiceJobNum,
    bool IsAgreementBilling,
    bool IsRecurringInvoice,
    long? RecurringScheduleId,
    string? WorkOrderNumber,
    int? JobTypeId,
    long? LeadEmployeeId,
    string? CustomerPONumber,
    DateOnly InvoiceDate,
    DateOnly AccountingDate,
    DateOnly? DueDate,
    int? NetTermId,
    int? PreferredPaymentMethodId,
    long? LaborPricingMatrixId,
    long? MaterialPricingMatrixId,
    long? OtherPricingMatrixId,
    int? GLBreak1Id,
    int? GLBreak2Id,
    string? TaxingAuthorityJson,
    string? BillToAddressJson,
    string? ServiceLocationAddressJson,
    string? CompanyAddressJson,
    long? InvoiceTemplateId,
    decimal InvoiceSubtotal,
    decimal TotalDiscount,
    decimal TaxableAmount,
    decimal TotalTax,
    decimal InvoiceTotal,
    decimal BalanceDue);

public sealed record FgsInvoicePatchDto(
    string? InvoiceNumber,
    short? InvoiceTypeId,
    long? CustomerId,
    long? ServiceLocationId,
    long? WorkOrderId,
    long? ProjectId,
    long? ServiceAgreementId,
    long? MaintenanceVisitId,
    string? ServiceJobNum,
    bool? IsAgreementBilling,
    bool? IsRecurringInvoice,
    long? RecurringScheduleId,
    string? WorkOrderNumber,
    int? JobTypeId,
    long? LeadEmployeeId,
    string? CustomerPONumber,
    DateOnly? InvoiceDate,
    DateOnly? AccountingDate,
    DateOnly? DueDate,
    int? NetTermId,
    int? PreferredPaymentMethodId,
    long? LaborPricingMatrixId,
    long? MaterialPricingMatrixId,
    long? OtherPricingMatrixId,
    int? GLBreak1Id,
    int? GLBreak2Id,
    string? TaxingAuthorityJson,
    string? BillToAddressJson,
    string? ServiceLocationAddressJson,
    string? CompanyAddressJson,
    long? InvoiceTemplateId,
    decimal? InvoiceSubtotal,
    decimal? TotalDiscount,
    decimal? TaxableAmount,
    decimal? TotalTax,
    decimal? InvoiceTotal,
    decimal? BalanceDue);

public sealed record FgsInvoiceListFilters(
    string? InvoiceNumber = null,
    long? CustomerId = null,
    bool? IsPosted = null,
    bool? IsApproved = null);
