// <auto-generated />
using System;
using Fgs.Scheduling.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fgs.Scheduling.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FgsSchedulingDbContext))]
    [Migration("20260614161609_AddDispatchSchedulingSchema")]
    partial class AddDispatchSchedulingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dispatch")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("AppointmentStatusId")
                        .HasColumnType("smallint")
                        .HasComment("Appointment status. 1=Unassigned, 2=Open, 3=Completed.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<long?>("CrewId")
                        .HasColumnType("bigint")
                        .HasComment("Scheduled crew assigned to the appointment.");

                    b.Property<DateTimeOffset?>("CustomerApprovedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time customer approved the appointment visit.");

                    b.Property<string>("CustomerContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Contact name used for appointment reminders and confirmations.");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("numeric(8,2)")
                        .HasComment("Estimated appointment duration used for scheduling and dispatch planning.");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time")
                        .HasComment("Customer promised local appointment time.");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasComment("Customer promised service date.");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the source record.");

                    b.Property<short>("SourceTypeId")
                        .HasColumnType("smallint")
                        .HasComment("Source type. Typically Lead, Opportunity or Work Order.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsAppointment");

                    b.HasIndex("TenantId", "CompanyId", "AppointmentStatusId")
                        .HasDatabaseName("IX_FgsAppointment_Status");

                    b.HasIndex("TenantId", "CompanyId", "CrewId")
                        .HasDatabaseName("IX_FgsAppointment_Crew");

                    b.HasIndex("TenantId", "CompanyId", "ServiceDate")
                        .HasDatabaseName("IX_FgsAppointment_ServiceDate");

                    b.HasIndex("TenantId", "CompanyId", "SourceTypeId", "SourceId")
                        .HasDatabaseName("IX_FgsAppointment_Source");

                    b.ToTable("FgsAppointment", "dispatch", t =>
                        {
                            t.HasComment("Represents a scheduled customer visit for a lead, opportunity or work order.");

                            t.HasCheckConstraint("CK_FgsAppointment_EstimatedHours", "\"EstimatedHours\" > 0");

                            t.HasCheckConstraint("CK_FgsAppointment_Status", "\"AppointmentStatusId\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointmentAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActualEndOn")
                        .HasColumnType("timestamptz")
                        .HasComment("System-maintained end timestamp derived from assignment events.");

                    b.Property<DateTimeOffset?>("ActualStartOn")
                        .HasColumnType("timestamptz")
                        .HasComment("System-maintained start timestamp derived from assignment events.");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasComment("Appointment associated with the assignment.");

                    b.Property<long>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who assigned the technician.");

                    b.Property<DateTimeOffset>("AssignedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the technician was assigned.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<long?>("CrewId")
                        .HasColumnType("bigint")
                        .HasComment("Crew assignment snapshot at the time of scheduling.");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasComment("Employee assigned to the appointment. References user service; no FK by design.");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("numeric(8,2)")
                        .HasComment("Estimated hours assigned to the technician.");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time")
                        .HasComment("Scheduled local start time for the technician assignment.");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasComment("Scheduled service date for the technician assignment.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsAppointmentAssignment");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("TenantId", "CompanyId", "AppointmentId")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_Appointment");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_Employee");

                    b.HasIndex("TenantId", "CompanyId", "ServiceDate")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_ServiceDate");

                    b.HasIndex("TenantId", "CompanyId", "AppointmentId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsAppointmentAssignment_AppointmentEmployee");

                    b.HasIndex("TenantId", "CompanyId", "CrewId", "ServiceDate")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_Crew");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "ActualStartOn", "ActualEndOn")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_Overlap");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "ServiceDate", "ScheduledTime")
                        .HasDatabaseName("IX_FgsAppointmentAssignment_EmployeeSchedule");

                    b.ToTable("FgsAppointmentAssignment", "dispatch", t =>
                        {
                            t.HasComment("Represents a technician assigned to a scheduled appointment.");

                            t.HasCheckConstraint("CK_FgsAppointmentAssignment_EstimatedHours", "\"EstimatedHours\" > 0");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointmentAssignmentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasComment("Appointment assignment associated with the event. NULL for technician-only events such as On Duty, Off Duty, Lunch Start and Lunch End.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasComment("Employee associated with the event. References user service; no FK by design.");

                    b.Property<bool>("EnteredByOffice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates the event was entered or reconstructed by office staff rather than captured by the technician.");

                    b.Property<DateTimeOffset>("EventOccurredOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Actual timestamp when the event occurred.");

                    b.Property<short>("EventTypeId")
                        .HasColumnType("smallint")
                        .HasComment("References glo.GloAppointmentAssignmentEventType.EventTypeId.");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Optional notes entered by office staff or technician.");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasComment("Business service date associated with the event. Used for overnight work and payroll calculations.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsAppointmentAssignmentEvent");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "AssignmentId")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_Assignment");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_Employee");

                    b.HasIndex("TenantId", "CompanyId", "EventTypeId")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_EventType");

                    b.HasIndex("TenantId", "CompanyId", "ServiceDate")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_ServiceDate");

                    b.HasIndex("TenantId", "CompanyId", "AssignmentId", "EventOccurredOn")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_AssignmentEventOccurredOn");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "EventOccurredOn")
                        .HasDatabaseName("IX_FgsAppointmentAssignmentEvent_EmployeeEventOccurredOn");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId", "EventTypeId", "EventOccurredOn")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsAppointmentAssignmentEvent_NoDuplicates");

                    b.ToTable("FgsAppointmentAssignmentEvent", "dispatch", t =>
                        {
                            t.HasComment("Stores technician activity events used for dispatch tracking, payroll calculations, utilization reporting and technician history.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsCrew", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<string>("CrewCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasComment("Short unique crew code used on dispatch boards, reports and integrations.");

                    b.Property<string>("CrewName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Display name of the crew.");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Optional crew description.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates whether the crew is available for scheduling and dispatching.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsCrew");

                    b.HasAlternateKey("TenantId", "CompanyId", "Id")
                        .HasName("UX_FgsCrew_TenantCompany_Id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsCrew_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "CrewCode")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsCrew_CrewCode");

                    b.HasIndex("TenantId", "CompanyId", "CrewName")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsCrew_CrewName");

                    b.HasIndex("TenantId", "CompanyId", "IsActive")
                        .HasDatabaseName("IX_FgsCrew_IsActive");

                    b.ToTable("FgsCrew", "dispatch", t =>
                        {
                            t.HasComment("Represents a technician crew used for scheduling, dispatching and workload management.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsCrewMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<long>("CrewId")
                        .HasColumnType("bigint")
                        .HasComment("Crew associated with the technician.");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasComment("Employee assigned to the crew. References user service; no FK by design.");

                    b.Property<bool>("IsLead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the employee is the lead technician or foreman for the crew.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsCrewMember");

                    b.HasIndex("CrewId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsCrewMember_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "CrewId")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsCrewMember_LeadPerCrew")
                        .HasFilter("\"IsLead\" = true");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsCrewMember_Employee");

                    b.HasIndex("TenantId", "CompanyId", "CrewId", "IsLead")
                        .HasDatabaseName("IX_FgsCrewMember_IsLead");

                    b.ToTable("FgsCrewMember", "dispatch", t =>
                        {
                            t.HasComment("Stores technician membership within a crew.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayroll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AdjustmentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Positive or negative payroll adjustment amount.");

                    b.Property<decimal>("BonusAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Bonus amount included in payroll.");

                    b.Property<decimal>("BurdenAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Calculated burden amount used for costing and profitability reporting.");

                    b.Property<string>("BurdenTypeId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("P")
                        .HasComment("Burden calculation method. P=Percent, F=Fixed Amount.");

                    b.Property<decimal>("BurdenValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasComment("Burden percentage or fixed amount snapshot used during payroll calculation.");

                    b.Property<decimal>("CommissionAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Commission amount included in payroll.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<decimal>("DoubleTimeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Double-time pay amount.");

                    b.Property<decimal>("DoubleTimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Double-time hours included in payroll calculation.");

                    b.Property<decimal>("DoubleTimeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasComment("Double-time pay rate snapshot at calculation time.");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasComment("Employee associated with this payroll record. References user service; no FK by design.");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Employee name snapshot captured at payroll calculation time.");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Employee number snapshot captured at payroll calculation time.");

                    b.Property<decimal>("GrossPayAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Total gross pay exported to the payroll provider.");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasComment("Optional payroll notes, explanations and adjustment reasons.");

                    b.Property<decimal>("OvertimeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Overtime pay amount.");

                    b.Property<decimal>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Overtime hours included in payroll calculation.");

                    b.Property<decimal>("OvertimeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasComment("Overtime pay rate snapshot at calculation time.");

                    b.Property<long>("PayPeriodId")
                        .HasColumnType("bigint")
                        .HasComment("Payroll pay period associated with this payroll record.");

                    b.Property<decimal>("RegularAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Regular pay amount.");

                    b.Property<decimal>("RegularHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Regular hours included in payroll calculation.");

                    b.Property<decimal>("RegularRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasComment("Regular pay rate snapshot at calculation time.");

                    b.Property<long?>("SignatureFileId")
                        .HasColumnType("bigint")
                        .HasComment("Reference to employee payroll acknowledgement signature document.");

                    b.Property<string>("SignedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Name of person who signed the payroll acknowledgement.");

                    b.Property<DateTimeOffset?>("SignedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time payroll acknowledgement was signed.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsPayroll");

                    b.HasIndex("PayPeriodId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsPayroll_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "EmployeeId")
                        .HasDatabaseName("IX_FgsPayroll_Employee");

                    b.HasIndex("TenantId", "CompanyId", "PayPeriodId")
                        .HasDatabaseName("IX_FgsPayroll_PayPeriod");

                    b.HasIndex("TenantId", "CompanyId", "SignedOn")
                        .HasDatabaseName("IX_FgsPayroll_SignedOn");

                    b.HasIndex("TenantId", "CompanyId", "PayPeriodId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsPayroll_PayPeriodEmployee");

                    b.ToTable("FgsPayroll", "dispatch", t =>
                        {
                            t.HasComment("Stores payroll results for a single employee within a payroll pay period.");

                            t.HasCheckConstraint("CK_FgsPayroll_BurdenType", "\"BurdenTypeId\" IN ('P', 'F')");

                            t.HasCheckConstraint("CK_FgsPayroll_Signature", "(\"SignedOn\" IS NULL AND \"SignatureFileId\" IS NULL AND \"SignedBy\" IS NULL) OR (\"SignedOn\" IS NOT NULL AND \"SignatureFileId\" IS NOT NULL AND \"SignedBy\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayrollLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Positive or negative payroll line amount.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasComment("User-facing payroll line description.");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasComment("Optional notes and explanation for the payroll line.");

                    b.Property<long>("PayrollId")
                        .HasColumnType("bigint")
                        .HasComment("Parent payroll record.");

                    b.Property<short>("PayrollLineTypeId")
                        .HasColumnType("smallint")
                        .HasComment("Payroll line type. 1=Commission, 2=Bonus, 3=Adjustment.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsPayrollLine");

                    b.HasIndex("PayrollId");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsPayrollLine_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "PayrollId")
                        .HasDatabaseName("IX_FgsPayrollLine_Payroll");

                    b.HasIndex("TenantId", "CompanyId", "PayrollLineTypeId")
                        .HasDatabaseName("IX_FgsPayrollLine_Type");

                    b.HasIndex("TenantId", "CompanyId", "PayrollId", "PayrollLineTypeId")
                        .HasDatabaseName("IX_FgsPayrollLine_PayrollType");

                    b.ToTable("FgsPayrollLine", "dispatch", t =>
                        {
                            t.HasComment("Stores payroll detail lines associated with a payroll record.");

                            t.HasCheckConstraint("CK_FgsPayrollLine_Type", "\"PayrollLineTypeId\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayrollPayPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who approved payroll.");

                    b.Property<DateTimeOffset?>("ApprovedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time payroll was approved.");

                    b.Property<long?>("CalculatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who generated payroll calculations.");

                    b.Property<DateTimeOffset?>("CalculatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time payroll calculations were generated.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<string>("ExportReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Optional external payroll batch number, export file identifier or payroll provider reference.");

                    b.Property<long?>("ExportedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who exported payroll.");

                    b.Property<DateTimeOffset?>("ExportedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time payroll was exported.");

                    b.Property<string>("PayPeriodCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Human-readable payroll period code such as 2026-PP12, 2026-06A or 2026-06B.");

                    b.Property<short>("PayrollStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasComment("Payroll status. 1=Open, 2=Calculated, 3=Approved, 4=Exported.");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date")
                        .HasComment("Inclusive payroll period end date.");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date")
                        .HasComment("Inclusive payroll period start date.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("Id")
                        .HasName("PK_FgsPayrollPayPeriod");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsPayrollPayPeriod_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "PayPeriodCode")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsPayrollPayPeriod_PayPeriodCode");

                    b.HasIndex("TenantId", "CompanyId", "PayrollStatusId")
                        .HasDatabaseName("IX_FgsPayrollPayPeriod_Status");

                    b.HasIndex("TenantId", "CompanyId", "PeriodEndDate")
                        .HasDatabaseName("IX_FgsPayrollPayPeriod_EndDate");

                    b.HasIndex("TenantId", "CompanyId", "PeriodStartDate")
                        .HasDatabaseName("IX_FgsPayrollPayPeriod_StartDate");

                    b.HasIndex("TenantId", "CompanyId", "PeriodStartDate", "PeriodEndDate")
                        .IsUnique()
                        .HasDatabaseName("UX_FgsPayrollPayPeriod_DateRange");

                    b.ToTable("FgsPayrollPayPeriod", "dispatch", t =>
                        {
                            t.HasComment("Defines payroll processing periods used to calculate, approve and export payroll.");

                            t.HasCheckConstraint("CK_FgsPayrollPayPeriod_Approved", "(\"ApprovedOn\" IS NULL AND \"ApprovedBy\" IS NULL) OR (\"ApprovedOn\" IS NOT NULL AND \"ApprovedBy\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_FgsPayrollPayPeriod_Calculated", "(\"CalculatedOn\" IS NULL AND \"CalculatedBy\" IS NULL) OR (\"CalculatedOn\" IS NOT NULL AND \"CalculatedBy\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_FgsPayrollPayPeriod_DateRange", "\"PeriodEndDate\" >= \"PeriodStartDate\"");

                            t.HasCheckConstraint("CK_FgsPayrollPayPeriod_Exported", "(\"ExportedOn\" IS NULL AND \"ExportedBy\" IS NULL) OR (\"ExportedOn\" IS NOT NULL AND \"ExportedBy\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_FgsPayrollPayPeriod_Status", "\"PayrollStatusId\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("Tenant identifier.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasComment("Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Unique company code within a tenant.");

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uuid")
                        .HasComment("Globally unique company identifier used by integrations and external systems.");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Display name of the company.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the company is active.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Timestamp of the most recent synchronization from tenant.FgsTenantCompany.");

                    b.HasKey("TenantId", "CompanyId")
                        .HasName("PK_FgsTenantCompanyCache");

                    b.HasIndex("CompanyGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsTenantCompanyCache_CompanyGuid");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_CompanyName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_IsActive");

                    b.ToTable("FgsTenantCompanyCache", "dispatch", t =>
                        {
                            t.HasComment("Local cache of tenant company information used by the Dispatch schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("Break1Id")
                        .HasColumnType("bigint")
                        .HasComment("Primary break classification identifier. References setup service; no FK by design.");

                    b.Property<long?>("Break2Id")
                        .HasColumnType("bigint")
                        .HasComment("Secondary break classification identifier. References setup service; no FK by design.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Onsite contact person name.");

                    b.Property<string>("ContactPersonPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Onsite contact person phone number.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was created.");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasComment("Customer identifier. References CRM service; no FK by design.");

                    b.Property<string>("CustomerPO")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Customer purchase order reference.");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamptz")
                        .HasComment("Work order end date and time.");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric(8,2)")
                        .HasComment("Estimated hours for the work order.");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("bigint")
                        .HasComment("Job type identifier. References setup.FgsJobType through application logic; no FK by design.");

                    b.Property<long?>("LaborPricingMatrixId")
                        .HasColumnType("bigint")
                        .HasComment("Labor pricing matrix identifier. References setup service; no FK by design.");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasComment("Service location identifier. References CRM service; no FK by design.");

                    b.Property<long?>("MaterialPricingMatrixId")
                        .HasColumnType("bigint")
                        .HasComment("Material pricing matrix identifier. References setup service; no FK by design.");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasComment("Special instructions for technicians.");

                    b.Property<long?>("OtherPricingMatrixId")
                        .HasColumnType("bigint")
                        .HasComment("Other pricing matrix identifier. References setup service; no FK by design.");

                    b.Property<long?>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasComment("Payment method identifier. References setup service; no FK by design.");

                    b.Property<string>("PersonCalling")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Name of person who called to request service.");

                    b.Property<string>("PersonCallingPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Phone number of person who called.");

                    b.Property<long>("PriorityId")
                        .HasColumnType("bigint")
                        .HasComment("Priority identifier. References setup service; no FK by design.");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("text")
                        .HasComment("Customer problem description.");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasComment("Optional project identifier. References project service; no FK by design.");

                    b.Property<DateTimeOffset>("RequestedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the work order was requested.");

                    b.Property<long?>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Service agreement identifier. References service agreement service; no FK by design.");

                    b.Property<long?>("ServiceAgreementVisitId")
                        .HasColumnType("bigint")
                        .HasComment("Service agreement visit identifier. References service agreement service; no FK by design.");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Source of the work order such as Manual, Portal, API, Corrigo, ServiceChannel, Verizon, AHS, etc.");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasComment("Work order start date and time.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long?>("TimeSlotId")
                        .HasColumnType("bigint")
                        .HasComment("Promised time window. References setup.FgsSetupTimeSlot through application logic; no FK by design.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Unique work order number within tenant and company.");

                    b.Property<long?>("WorkOrderResolutionId")
                        .HasColumnType("bigint")
                        .HasComment("Completion or cancellation reason identifier. References setup service; no FK by design.");

                    b.Property<long>("WorkOrderStatusId")
                        .HasColumnType("bigint")
                        .HasComment("Work order status. New, Started, Completed, or Cancelled.");

                    b.HasKey("Id")
                        .HasName("PK_FgsWorkOrder");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsWorkOrder_TenantCompany");

                    b.HasIndex("TenantId", "CompanyId", "CustomerId")
                        .HasDatabaseName("IX_FgsWorkOrder_Customer");

                    b.HasIndex("TenantId", "CompanyId", "JobTypeId")
                        .HasDatabaseName("IX_FgsWorkOrder_JobType");

                    b.HasIndex("TenantId", "CompanyId", "LocationId")
                        .HasDatabaseName("IX_FgsWorkOrder_Location");

                    b.HasIndex("TenantId", "CompanyId", "PriorityId")
                        .HasDatabaseName("IX_FgsWorkOrder_Priority");

                    b.HasIndex("TenantId", "CompanyId", "ProjectId")
                        .HasDatabaseName("IX_FgsWorkOrder_Project");

                    b.HasIndex("TenantId", "CompanyId", "RequestedOn")
                        .HasDatabaseName("IX_FgsWorkOrder_RequestedOn");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsWorkOrder_ServiceAgreement");

                    b.HasIndex("TenantId", "CompanyId", "Source")
                        .HasDatabaseName("IX_FgsWorkOrder_Source");

                    b.HasIndex("TenantId", "CompanyId", "TimeSlotId")
                        .HasDatabaseName("IX_FgsWorkOrder_TimeSlot");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsWorkOrder_WorkOrderNumber");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderStatusId")
                        .HasDatabaseName("IX_FgsWorkOrder_Status");

                    b.ToTable("FgsWorkOrder", "dispatch", t =>
                        {
                            t.HasComment("Master work order record representing a customer service request that can be scheduled through one or more appointments.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderAsset", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<long>("WorkOrderId")
                        .HasColumnType("bigint")
                        .HasComment("Parent work order identifier.");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint")
                        .HasComment("Asset identifier. References asset service; no FK by design.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was created.");

                    b.HasKey("TenantId", "CompanyId", "WorkOrderId", "AssetId")
                        .HasName("PK_FgsWorkOrderAsset");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("FgsWorkOrderAsset", "dispatch", t =>
                        {
                            t.HasComment("Associates assets with a work order.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderIntegration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Primary identifier from the external system.");

                    b.Property<string>("ExternalWorkOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("External work order number visible to users in the external system.");

                    b.Property<string>("IntegrationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Integration source such as Corrigo, ServiceChannel, Verizon, AHS, etc.");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasComment("Raw JSON payload received from the external system.");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that processed or booked the work order.");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was processed or booked into dispatch.");

                    b.Property<DateTimeOffset>("ReceivedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the payload was received from the external system.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Received")
                        .HasComment("Current processing status of the imported work order.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<long?>("WorkOrderId")
                        .HasColumnType("bigint")
                        .HasComment("Dispatch work order created from this integration record.");

                    b.HasKey("Id")
                        .HasName("PK_FgsWorkOrderIntegration");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("IX_FgsWorkOrderIntegration_WorkOrderId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsWorkOrderIntegration_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "ReceivedOn")
                        .HasDatabaseName("IX_FgsWorkOrderIntegration_ReceivedOn");

                    b.HasIndex("TenantId", "CompanyId", "Status")
                        .HasDatabaseName("IX_FgsWorkOrderIntegration_Status");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderId")
                        .HasDatabaseName("IX_FgsWorkOrderIntegration_WorkOrderId");

                    b.HasIndex("TenantId", "CompanyId", "IntegrationName", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsWorkOrderIntegration_External");

                    b.ToTable("FgsWorkOrderIntegration", "dispatch", t =>
                        {
                            t.HasComment("Stores externally received work orders and their raw payloads before they are reviewed and booked into dispatch.");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Primary key.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2)
                        .HasComment("Company identifier.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Date and time the record was created.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Additional item description or technician notes.");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasComment("Display order within the work order item list.");

                    b.Property<long?>("InventoryItemId")
                        .HasColumnType("bigint")
                        .HasComment("Inventory item identifier. May be NULL when the item is manually entered.");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Item name used when the item does not exist in the inventory catalog.");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(1.0m)
                        .HasComment("Quantity of material used on the work order.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1)
                        .HasComment("Tenant identifier.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User who last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<long>("WorkOrderId")
                        .HasColumnType("bigint")
                        .HasComment("Parent work order identifier.");

                    b.HasKey("Id")
                        .HasName("PK_FgsWorkOrderItem");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("IX_FgsWorkOrderItem_WorkOrderId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsWorkOrderItem_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "InventoryItemId")
                        .HasDatabaseName("IX_FgsWorkOrderItem_InventoryItemId");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderId")
                        .HasDatabaseName("IX_FgsWorkOrderItem_WorkOrderId");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderId", "DisplayOrder")
                        .HasDatabaseName("IX_FgsWorkOrderItem_DisplayOrder");

                    b.ToTable("FgsWorkOrderItem", "dispatch", t =>
                        {
                            t.HasComment("Stores materials used on a work order. Items may come from the inventory catalog or be entered manually. Customer billing is stored separately on invoice lines.");

                            t.HasCheckConstraint("CK_FgsWorkOrderItem_Item", "\"InventoryItemId\" IS NOT NULL OR COALESCE(TRIM(BOTH FROM \"ItemName\"), '') <> ''");

                            t.HasCheckConstraint("CK_FgsWorkOrderItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointment", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsAppointment_TenantCompany");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsCrew", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "CrewId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FgsAppointment_Crew");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointmentAssignment", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsAppointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsAppointmentAssignment_Appointment");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsAppointmentAssignment_TenantCompany");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsCrew", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "CrewId")
                        .HasPrincipalKey("TenantId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FgsAppointmentAssignment_Crew");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsAppointmentAssignmentEvent", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsAppointmentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FgsAppointmentAssignmentEvent_FgsAppointmentAssignment");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsAppointmentAssignmentEvent_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsCrew", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsCrew_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsCrewMember", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsCrew", null)
                        .WithMany()
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsCrewMember_FgsCrew");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsCrewMember_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayroll", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsPayrollPayPeriod", null)
                        .WithMany()
                        .HasForeignKey("PayPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsPayroll_FgsPayrollPayPeriod");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsPayroll_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayrollLine", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsPayroll", null)
                        .WithMany()
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsPayrollLine_FgsPayroll");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsPayrollLine_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsPayrollPayPeriod", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsPayrollPayPeriod_FgsTenantCompanyCache");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrder", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrder_TenantCompany");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderAsset", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsWorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrderAsset_WorkOrder");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrderAsset_TenantCompany");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderIntegration", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsWorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_FgsWorkOrderIntegration_WorkOrder");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrderIntegration_FgsTenantCompanyCache_TenantId_CompanyId");
                });

            modelBuilder.Entity("Fgs.Scheduling.Domain.Entities.FgsWorkOrderItem", b =>
                {
                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsWorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrderItem_WorkOrder");

                    b.HasOne("Fgs.Scheduling.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsWorkOrderItem_FgsTenantCompanyCache_TenantId_CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
