-- =============================================================================
-- Migration: 20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption
-- Script:   20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption_down.sql
-- Path:     Persistence/Database/Scripts/Rollback
-- Database: PostgreSQL
-- Idempotent (dotnet ef migrations script --idempotent).
-- =============================================================================

START TRANSACTION;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    ALTER TABLE audit."FgsCredentialAudit" DROP CONSTRAINT "FK_FgsCredentialAudit_Credential";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    DROP TABLE setup."FgsCredential";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    DROP TABLE glo."GloCredential";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    DROP TABLE glo."GloCredentialProviderType";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    ALTER TABLE audit."FgsCredentialAudit" RENAME COLUMN "CredentialId" TO "CredentialSecretId";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    ALTER INDEX audit."IX_FgsCredentialAudit_CredentialId" RENAME TO "IX_FgsCredentialAudit_CredentialSecretId";
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE TABLE glo."GloCredentialProviderType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloCredentialProviderType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialProviderType_Code" ON glo."GloCredentialProviderType" ("Code");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE TABLE setup."FgsCredentialProvider" (
        "Id" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" character varying(100) NOT NULL,
        "CreatedBy" character varying(100),
        "CreatedOn" timestamptz NOT NULL,
        "CredentialProviderTypeId" integer NOT NULL,
        "Description" character varying(1000),
        "Environment" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        "Name" character varying(200) NOT NULL,
        "UpdatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsCredentialProvider" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredentialProvider_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE TABLE glo."GloCredentialCategory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "CreatedBy" character varying(100),
        "CreatedOn" timestamptz NOT NULL,
        "IsActive" boolean NOT NULL,
        "Name" character varying(200) NOT NULL,
        "UpdatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloCredentialCategory" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE TABLE setup."FgsCredentialProviderConfiguration" (
        "Id" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "ConfigurationKey" character varying(200) NOT NULL,
        "ConfigurationValue" text,
        "CreatedBy" character varying(100),
        "CreatedOn" timestamptz NOT NULL,
        "CredentialProviderId" uuid NOT NULL,
        "Environment" character varying(50),
        "IsActive" boolean NOT NULL,
        "UpdatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsCredentialProviderConfiguration" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredProvCfg_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsCredProvCfg_Provider" FOREIGN KEY ("CredentialProviderId") REFERENCES setup."FgsCredentialProvider" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE TABLE setup."FgsCredentialSecret" (
        "Id" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CreatedBy" character varying(100),
        "CreatedOn" timestamptz NOT NULL,
        "CredentialProviderId" uuid NOT NULL,
        "EncryptedDek" text NOT NULL,
        "EncryptedSecretValue" text NOT NULL,
        "EncryptionKeyId" character varying(500) NOT NULL,
        "ExpiresOn" timestamptz,
        "IsActive" boolean NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "LastRotatedOn" timestamptz,
        "SecretName" character varying(200) NOT NULL,
        "UpdatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "VersionNo" integer NOT NULL,
        CONSTRAINT "PK_FgsCredentialSecret" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredentialSecret_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsCredentialSecret_Provider" FOREIGN KEY ("CredentialProviderId") REFERENCES setup."FgsCredentialProvider" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE UNIQUE INDEX "IX_FgsCredentialProvider_TenantId_CompanyId_Code" ON setup."FgsCredentialProvider" ("TenantId", "CompanyId", "Code");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredentialProviderConfiguration_CredentialProviderId" ON setup."FgsCredentialProviderConfiguration" ("CredentialProviderId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredProvCfg_Tenant_Company" ON setup."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredProvCfg_Tenant_Company_Prov" ON setup."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId", "CredentialProviderId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE UNIQUE INDEX "UQ_FgsCredentialProviderConfiguration" ON setup."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId", "CredentialProviderId", "ConfigurationKey", "Environment");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredentialSecret_CredentialProviderId" ON setup."FgsCredentialSecret" ("CredentialProviderId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredentialSecret_IsActive" ON setup."FgsCredentialSecret" ("IsActive");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredentialSecret_Tenant_Company" ON setup."FgsCredentialSecret" ("TenantId", "CompanyId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE INDEX "IX_FgsCredentialSecret_Tenant_Company_Prov" ON setup."FgsCredentialSecret" ("TenantId", "CompanyId", "CredentialProviderId");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE UNIQUE INDEX "UQ_FgsCredentialSecret" ON setup."FgsCredentialSecret" ("TenantId", "CompanyId", "CredentialProviderId", "SecretName", "VersionNo");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialCategory_Code" ON glo."GloCredentialCategory" ("Code");
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    ALTER TABLE audit."FgsCredentialAudit" ADD CONSTRAINT "FK_FgsCredentialAudit_CredentialSecret" FOREIGN KEY ("CredentialSecretId") REFERENCES setup."FgsCredentialSecret" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;
DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption') THEN
    DELETE FROM shared."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260601192509_ReplaceCredentialModelWithKmsEnvelopeEncryption';
    END IF;
END $EF$;
COMMIT;

