using Fgs.Setup.Application.Common.Locations;

namespace Fgs.Setup.Application.Features.Employees.Dtos;

public sealed record FgsEmployeeAddressDetailDto(
    Guid Id,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? Country,
    string? PostalCode);

public sealed record FgsEmployeeTechnicianProfileDetailDto(
    long Id,
    string TechCode,
    string? TechName,
    bool CanBeScheduled,
    decimal DailyCapacityHours,
    long? DispatchZoneId,
    short StartLocationTypeId,
    TimeOnly? StartTime,
    int? TechTradeId,
    int? TechSkillId,
    long? TruckId,
    string? CustomerFacingPhone,
    string? Notes);

public sealed record FgsEmployeeTechnicianProfileWriteDto(
    string TechCode,
    string? TechName,
    bool CanBeScheduled = true,
    decimal? DailyCapacityHours = null,
    long? DispatchZoneId = null,
    short StartLocationTypeId = 0,
    TimeOnly? StartTime = null,
    int? TechTradeId = null,
    int? TechSkillId = null,
    long? TruckId = null,
    string? CustomerFacingPhone = null,
    string? Notes = null);

public sealed record FgsEmployeeSummaryDto(
    long Id,
    Guid? UserId,
    string EmployeeNumber,
    short EmployeeTypeId,
    string DisplayName,
    string LegalFirstName,
    string? LegalMiddleName,
    string LegalLastName,
    DateOnly? BirthDate,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    short StatusId,
    string? PersonalEmail,
    string? OfficeEmail,
    string? PersonalPhone,
    string? OfficePhone,
    long? ProfilePhotoFileId,
    decimal? RegularRate,
    decimal? OvertimeRate,
    decimal? DoubleTimeRate,
    short? LaborBurdenTypeId,
    decimal? LaborBurdenValue,
    bool IsPurchaser,
    string? Notes,
    bool HasTechnicianProfile);

public sealed record FgsEmployeeDetailDto(
    long Id,
    Guid? UserId,
    string EmployeeNumber,
    short EmployeeTypeId,
    string DisplayName,
    string LegalFirstName,
    string? LegalMiddleName,
    string LegalLastName,
    DateOnly? BirthDate,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    short StatusId,
    string? PersonalEmail,
    string? OfficeEmail,
    string? PersonalPhone,
    string? OfficePhone,
    FgsEmployeeAddressDetailDto? Address,
    long? ProfilePhotoFileId,
    decimal? RegularRate,
    decimal? OvertimeRate,
    decimal? DoubleTimeRate,
    short? LaborBurdenTypeId,
    decimal? LaborBurdenValue,
    bool IsPurchaser,
    string? Notes,
    FgsEmployeeTechnicianProfileDetailDto? TechnicianProfile);

public sealed record FgsEmployeeLookupDto(
    long Id,
    string EmployeeNumber,
    string DisplayName);

public sealed record FgsEmployeeCreateDto(
    Guid? UserId,
    string EmployeeNumber,
    short EmployeeTypeId,
    string DisplayName,
    string LegalFirstName,
    string? LegalMiddleName,
    string LegalLastName,
    DateOnly? BirthDate,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    short StatusId,
    string? PersonalEmail,
    string? OfficeEmail,
    string? PersonalPhone,
    string? OfficePhone,
    LocationWriteDto Address,
    long? ProfilePhotoFileId,
    decimal? RegularRate,
    short? LaborBurdenTypeId,
    decimal? LaborBurdenValue,
    bool IsPurchaser = false,
    string? Notes = null,
    FgsEmployeeTechnicianProfileWriteDto? TechnicianProfile = null);

public sealed record FgsEmployeeUpdateDto(
    Guid? UserId,
    string EmployeeNumber,
    short EmployeeTypeId,
    string DisplayName,
    string LegalFirstName,
    string? LegalMiddleName,
    string LegalLastName,
    DateOnly? BirthDate,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    short StatusId,
    string? PersonalEmail,
    string? OfficeEmail,
    string? PersonalPhone,
    string? OfficePhone,
    LocationWriteDto Address,
    long? ProfilePhotoFileId,
    decimal? RegularRate,
    decimal? OvertimeRate,
    decimal? DoubleTimeRate,
    short? LaborBurdenTypeId,
    decimal? LaborBurdenValue,
    bool IsPurchaser,
    string? Notes,
    FgsEmployeeTechnicianProfileWriteDto? TechnicianProfile = null);

public sealed record FgsEmployeePatchDto(
    Guid? UserId,
    string? EmployeeNumber,
    short? EmployeeTypeId,
    string? DisplayName,
    string? LegalFirstName,
    string? LegalMiddleName,
    string? LegalLastName,
    DateOnly? BirthDate,
    DateOnly? HireDate,
    DateOnly? TerminationDate,
    short? StatusId,
    string? PersonalEmail,
    string? OfficeEmail,
    string? PersonalPhone,
    string? OfficePhone,
    LocationWriteDto? Address,
    long? ProfilePhotoFileId,
    decimal? RegularRate,
    decimal? OvertimeRate,
    decimal? DoubleTimeRate,
    short? LaborBurdenTypeId,
    decimal? LaborBurdenValue,
    bool? IsPurchaser,
    string? Notes,
    bool? IsActive = null,
    FgsEmployeeTechnicianProfileWriteDto? TechnicianProfile = null);

public sealed record FgsEmployeeListFilters(
    string? EmployeeNumber = null,
    short? EmployeeTypeId = null,
    short? StatusId = null,
    IReadOnlyList<long>? TechTradeIds = null,
    IReadOnlyList<long>? TechSkillIds = null,
    IReadOnlyList<long>? DispatchZoneIds = null,
    IReadOnlyList<long>? RoleIds = null,
    IReadOnlyList<Guid>? UserIds = null);
