using Fgs.Setup.Application.Abstractions.SetupPricingMatrices;
using Fgs.Setup.Application.Abstractions.SetupPricingMatrixMaterialTiers;
using Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Commands.CreateFgsSetupPricingMatrixMaterialTier;
using Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Commands.UpdateFgsSetupPricingMatrixMaterialTier;
using Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Commands.PatchFgsSetupPricingMatrixMaterialTier;
using FluentValidation;
namespace Fgs.Setup.Application.Features.SetupPricingMatrixMaterialTiers.Validators;
public sealed class CreateFgsSetupPricingMatrixMaterialTierCommandValidator:AbstractValidator<CreateFgsSetupPricingMatrixMaterialTierCommand>
{public CreateFgsSetupPricingMatrixMaterialTierCommandValidator(IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixMaterialTierReadRepository r){RuleFor(x=>x.Dto.FromCost).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>await Check(d.PricingMatrixId,d.FromCost,d.ToCost,null,m,r,c,ct));}
 internal static async Task Check(long id,decimal from,decimal? to,long? exclude,IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixMaterialTierReadRepository r,ValidationContext<CreateFgsSetupPricingMatrixMaterialTierCommand> c,CancellationToken ct){var f=await m.GetFlagsByIdAsync(id,ct);if(f is null){c.AddFailure("Dto.PricingMatrixId","The specified pricing matrix was not found.");return;}if(await r.ExistsActiveOtherItemsForMatrixAsync(id,ct))c.AddFailure("Dto.PricingMatrixId","Material tiers cannot coexist with active pricing matrix other items.");if(f.PriceAdjustmentTypeId<1||f.PriceAdjustmentTypeId>3)c.AddFailure("Dto.PricingMatrixId","Price adjustment type must be between 1 and 3.");if(to.HasValue&&to<from)c.AddFailure("Dto.ToCost","To cost must be greater than or equal to from cost.");if(await r.ExistsByFromCostAsync(id,from,exclude,ct))c.AddFailure("Dto.FromCost","From cost must be unique per pricing matrix.");}}
public sealed class UpdateFgsSetupPricingMatrixMaterialTierCommandValidator:AbstractValidator<UpdateFgsSetupPricingMatrixMaterialTierCommand>{public UpdateFgsSetupPricingMatrixMaterialTierCommandValidator(IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixMaterialTierReadRepository r){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.FromCost).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>{var f=await m.GetFlagsByIdAsync(d.PricingMatrixId,ct);if(f is null){c.AddFailure("Dto.PricingMatrixId","The specified pricing matrix was not found.");return;}if(await r.ExistsActiveOtherItemsForMatrixAsync(d.PricingMatrixId,ct))c.AddFailure("Dto.PricingMatrixId","Material tiers cannot coexist with active pricing matrix other items.");if(f.PriceAdjustmentTypeId<1||f.PriceAdjustmentTypeId>3)c.AddFailure("Dto.PricingMatrixId","Price adjustment type must be between 1 and 3.");if(d.ToCost.HasValue&&d.ToCost<d.FromCost)c.AddFailure("Dto.ToCost","To cost must be greater than or equal to from cost.");if(await r.ExistsByFromCostAsync(d.PricingMatrixId,d.FromCost,c.InstanceToValidate.Id,ct))c.AddFailure("Dto.FromCost","From cost must be unique per pricing matrix.");});}}
public sealed class PatchFgsSetupPricingMatrixMaterialTierCommandValidator:AbstractValidator<PatchFgsSetupPricingMatrixMaterialTierCommand>{public PatchFgsSetupPricingMatrixMaterialTierCommandValidator(){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.FromCost).GreaterThanOrEqualTo(0).When(x=>x.Dto.FromCost.HasValue);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0).When(x=>x.Dto.AdjustmentValue.HasValue);}}
