-- =============================================================================
-- Migration: 20260602150004_AddWarehouseVehicleAndMaintenanceTables
-- Script:   20260602150004_AddWarehouseVehicleAndMaintenanceTables_up.sql
-- Path:     Persistence/Database/Scripts/Execute
-- Database: PostgreSQL
--
-- Creates setup.FgsWarehouse, setup.FgsVehicle, setup.FgsVehicleMaintenance,
-- glo.GloVehicleMaintenanceType (with seed rows), and GloMasterEntityType seed.
-- Idempotent (dotnet ef migrations script --idempotent).
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE TABLE setup."FgsWarehouse" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "WarehouseCode" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "WarehouseType" character varying(30) NOT NULL,
        "LocationId" uuid,
        "Description" text,
        "IsDefault" boolean NOT NULL DEFAULT FALSE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsWarehouse" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsWarehouse_TenantId_CompanyId_WarehouseCode" UNIQUE ("TenantId", "CompanyId", "WarehouseCode"),
        CONSTRAINT "CK_FgsWarehouse_WarehouseType" CHECK ("WarehouseType" IN ('Warehouse', 'Truck', 'Trailer', 'JobSite', 'Consignment', 'Vendor')),
        CONSTRAINT "FK_FgsWarehouse_FgsLocation_LocationId" FOREIGN KEY ("LocationId") REFERENCES shared."FgsLocation" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsWarehouse_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsWarehouse" IS 'Stores inventory warehouse, truck, trailer, job site, consignment, and vendor storage locations.';
    COMMENT ON COLUMN setup."FgsWarehouse"."Id" IS 'Primary key.';
    COMMENT ON COLUMN setup."FgsWarehouse"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN setup."FgsWarehouse"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN setup."FgsWarehouse"."WarehouseCode" IS 'Unique warehouse code within the tenant and company scope.';
    COMMENT ON COLUMN setup."FgsWarehouse"."Name" IS 'Display name of the warehouse or inventory location.';
    COMMENT ON COLUMN setup."FgsWarehouse"."WarehouseType" IS 'Type of inventory location. Allowed values: Warehouse, Truck, Trailer, JobSite, Consignment, Vendor.';
    COMMENT ON COLUMN setup."FgsWarehouse"."LocationId" IS 'Optional reference to the physical address or geo location in FgsLocation.';
    COMMENT ON COLUMN setup."FgsWarehouse"."Description" IS 'Optional description or notes for the warehouse.';
    COMMENT ON COLUMN setup."FgsWarehouse"."IsDefault" IS 'Indicates whether this warehouse is the default inventory location for the company.';
    COMMENT ON COLUMN setup."FgsWarehouse"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN setup."FgsWarehouse"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN setup."FgsWarehouse"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN setup."FgsWarehouse"."UpdatedBy" IS 'User who last updated the record.';
    COMMENT ON COLUMN setup."FgsWarehouse"."IsActive" IS 'Indicates whether the warehouse is active and available for inventory operations.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE TABLE glo."GloVehicleMaintenanceType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceTypeCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloVehicleMaintenanceType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloVehicleMaintenanceType_MaintenanceTypeCode" UNIQUE ("MaintenanceTypeCode")
    );
    COMMENT ON TABLE glo."GloVehicleMaintenanceType" IS 'Stores standard vehicle maintenance types used when recording maintenance activities for company vehicles.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."Id" IS 'Primary key.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."MaintenanceTypeCode" IS 'Unique system code identifying the maintenance type.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."Name" IS 'Display name of the maintenance type.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."Description" IS 'Description of the maintenance type.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."DisplayOrder" IS 'Controls display order in lists and dropdowns.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."IsActive" IS 'Indicates whether the maintenance type is active and available for selection.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN glo."GloVehicleMaintenanceType"."UpdatedOn" IS 'Date and time the record was last updated.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE TABLE setup."FgsVehicle" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "WarehouseId" bigint NOT NULL,
        "OwnershipType" character varying(20) NOT NULL DEFAULT 'Owned',
        "OwnershipCompany" character varying(200),
        "Year" smallint,
        "Make" character varying(100),
        "Model" character varying(100),
        "Color" character varying(50),
        "VIN" character varying(50) NOT NULL,
        "LicensePlate" character varying(50),
        "LicensePlateState" character varying(50),
        "PurchaseDate" date,
        "PurchasePrice" numeric(18,2),
        "PurchasedFrom" character varying(200),
        "IsPurchasedNew" boolean,
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsVehicle" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsVehicle_WarehouseId" UNIQUE ("WarehouseId"),
        CONSTRAINT "CK_FgsVehicle_OwnershipType" CHECK ("OwnershipType" IN ('Owned', 'Leased', 'Rented')),
        CONSTRAINT "FK_FgsVehicle_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsVehicle_FgsWarehouse_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES setup."FgsWarehouse" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsVehicle" IS 'Stores company-owned or leased vehicles used for field service operations. Each vehicle is associated with a truck warehouse that serves as an inventory location.';
    COMMENT ON COLUMN setup."FgsVehicle"."Id" IS 'Primary key.';
    COMMENT ON COLUMN setup."FgsVehicle"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN setup."FgsVehicle"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN setup."FgsVehicle"."WarehouseId" IS 'Associated truck warehouse used as the vehicle inventory location.';
    COMMENT ON COLUMN setup."FgsVehicle"."OwnershipType" IS 'Indicates whether the vehicle is owned, leased, or rented.';
    COMMENT ON COLUMN setup."FgsVehicle"."OwnershipCompany" IS 'Name of the leasing company, rental provider, or other organization that owns the vehicle when it is not company-owned.';
    COMMENT ON COLUMN setup."FgsVehicle"."Year" IS 'Vehicle model year.';
    COMMENT ON COLUMN setup."FgsVehicle"."Make" IS 'Vehicle manufacturer such as Ford, Chevrolet, GMC, Ram, Toyota, etc.';
    COMMENT ON COLUMN setup."FgsVehicle"."Model" IS 'Vehicle model such as F-150, Transit, Silverado, Express, etc.';
    COMMENT ON COLUMN setup."FgsVehicle"."Color" IS 'Vehicle exterior color.';
    COMMENT ON COLUMN setup."FgsVehicle"."VIN" IS 'Vehicle Identification Number assigned by the manufacturer.';
    COMMENT ON COLUMN setup."FgsVehicle"."LicensePlate" IS 'Vehicle registration plate number.';
    COMMENT ON COLUMN setup."FgsVehicle"."LicensePlateState" IS 'State or province issuing the vehicle registration.';
    COMMENT ON COLUMN setup."FgsVehicle"."PurchaseDate" IS 'Date the vehicle was purchased or acquired.';
    COMMENT ON COLUMN setup."FgsVehicle"."PurchasePrice" IS 'Amount paid to acquire the vehicle.';
    COMMENT ON COLUMN setup."FgsVehicle"."PurchasedFrom" IS 'Name of the dealership, seller, auction, fleet provider, or other source from which the vehicle was acquired.';
    COMMENT ON COLUMN setup."FgsVehicle"."IsPurchasedNew" IS 'Indicates whether the vehicle was purchased new or used.';
    COMMENT ON COLUMN setup."FgsVehicle"."Notes" IS 'Internal notes and remarks regarding the vehicle.';
    COMMENT ON COLUMN setup."FgsVehicle"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN setup."FgsVehicle"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN setup."FgsVehicle"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN setup."FgsVehicle"."UpdatedBy" IS 'User who last updated the record.';
    COMMENT ON COLUMN setup."FgsVehicle"."IsActive" IS 'Indicates whether the vehicle is active and available for service operations.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE TABLE setup."FgsVehicleMaintenance" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "VehicleId" bigint NOT NULL,
        "VehicleMaintenanceTypeId" integer NOT NULL,
        "ServiceDate" date NOT NULL,
        "MileageAtService" integer,
        "ServiceProvider" character varying(200),
        "InvoiceNumber" character varying(100),
        "Cost" numeric(18,2),
        "NextServiceDate" date,
        "NextServiceMileage" integer,
        "IsCompleted" boolean NOT NULL DEFAULT TRUE,
        "Description" character varying(500),
        "Notes" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsVehicleMaintenance" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsVehicleMaintenance_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsVehicleMaintenance_FgsVehicle_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES setup."FgsVehicle" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsVehicleMaintenance_GloVehicleMaintenanceType_VehicleMaintenanceTypeId" FOREIGN KEY ("VehicleMaintenanceTypeId") REFERENCES glo."GloVehicleMaintenanceType" ("Id") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsVehicleMaintenance" IS 'Stores completed and scheduled maintenance activities, inspections, repairs, and service history for company vehicles.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."Id" IS 'Primary key.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."TenantId" IS 'Tenant identifier.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."CompanyId" IS 'Company identifier.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."VehicleId" IS 'Vehicle that received or is scheduled to receive maintenance service.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."VehicleMaintenanceTypeId" IS 'Type of maintenance activity being performed or scheduled.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."ServiceDate" IS 'Date the maintenance was performed or is scheduled to be performed.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."MileageAtService" IS 'Vehicle odometer reading at the time the maintenance was performed.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."ServiceProvider" IS 'Name of the repair shop, dealership, service provider, or maintenance vendor.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."InvoiceNumber" IS 'Vendor invoice, receipt, repair order, or work order number associated with the maintenance activity.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."Cost" IS 'Total cost incurred for the maintenance activity.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."NextServiceDate" IS 'Recommended next service date based on maintenance provider recommendations.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."NextServiceMileage" IS 'Recommended next service mileage based on maintenance provider recommendations.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."IsCompleted" IS 'Indicates whether the maintenance activity has been completed. False indicates a scheduled or pending maintenance item.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."Description" IS 'Short summary of the maintenance activity performed or scheduled.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."Notes" IS 'Detailed notes, observations, recommendations, or repair information related to the maintenance activity.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."CreatedOn" IS 'Date and time the record was created.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."CreatedBy" IS 'User who created the record.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."UpdatedOn" IS 'Date and time the record was last updated.';
    COMMENT ON COLUMN setup."FgsVehicleMaintenance"."UpdatedBy" IS 'User who last updated the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicle_TenantId_CompanyId_IsActive" ON setup."FgsVehicle" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicle_TenantId_CompanyId_WarehouseId" ON setup."FgsVehicle" ("TenantId", "CompanyId", "WarehouseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_TenantId_CompanyId_IsCompleted" ON setup."FgsVehicleMaintenance" ("TenantId", "CompanyId", "IsCompleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_TenantId_CompanyId_NextServiceDate" ON setup."FgsVehicleMaintenance" ("TenantId", "CompanyId", "NextServiceDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_TenantId_CompanyId_ServiceDate" ON setup."FgsVehicleMaintenance" ("TenantId", "CompanyId", "ServiceDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_TenantId_CompanyId_VehicleId" ON setup."FgsVehicleMaintenance" ("TenantId", "CompanyId", "VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_TenantId_CompanyId_VehicleMaintenanceTypeId" ON setup."FgsVehicleMaintenance" ("TenantId", "CompanyId", "VehicleMaintenanceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_VehicleId" ON setup."FgsVehicleMaintenance" ("VehicleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsVehicleMaintenance_VehicleMaintenanceTypeId" ON setup."FgsVehicleMaintenance" ("VehicleMaintenanceTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsWarehouse_LocationId" ON setup."FgsWarehouse" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsWarehouse_TenantId_CompanyId_IsActive" ON setup."FgsWarehouse" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_FgsWarehouse_TenantId_CompanyId_WarehouseType" ON setup."FgsWarehouse" ("TenantId", "CompanyId", "WarehouseType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    CREATE INDEX "IX_GloVehicleMaintenanceType_DisplayOrder" ON glo."GloVehicleMaintenanceType" ("DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    INSERT INTO glo."GloVehicleMaintenanceType"
    (
        "MaintenanceTypeCode",
        "Name",
        "Description",
        "DisplayOrder"
    )
    SELECT
        v."MaintenanceTypeCode",
        v."Name",
        v."Description",
        v."DisplayOrder"
    FROM (
        VALUES
            ('OIL_CHANGE',           'Oil Change',           'Engine oil and filter replacement.',                              1::smallint),
            ('TIRE_ROTATION',        'Tire Rotation',        'Rotation of vehicle tires to promote even wear.',                 2::smallint),
            ('TIRE_REPLACEMENT',     'Tire Replacement',     'Replacement of one or more vehicle tires.',                       3::smallint),
            ('BRAKE_SERVICE',        'Brake Service',        'Inspection, repair, or replacement of brake components.',           4::smallint),
            ('INSPECTION',           'Inspection',           'General vehicle inspection and safety check.',                    5::smallint),
            ('BATTERY_REPLACEMENT',  'Battery Replacement',  'Replacement of vehicle battery.',                                 6::smallint),
            ('TRANSMISSION_SERVICE', 'Transmission Service', 'Maintenance or repair of transmission system.',                   7::smallint),
            ('REGISTRATION_RENEWAL', 'Registration Renewal', 'Vehicle registration renewal.',                                   8::smallint),
            ('REPAIR',               'Repair',               'General repair work not covered by a specific maintenance type.', 9::smallint),
            ('OTHER',                'Other',                'Other maintenance activity.',                                     99::smallint)
    ) AS v("MaintenanceTypeCode", "Name", "Description", "DisplayOrder")
    WHERE NOT EXISTS (
        SELECT 1
        FROM glo."GloVehicleMaintenanceType" t
        WHERE t."MaintenanceTypeCode" = v."MaintenanceTypeCode"
    );

    SELECT setval(
        pg_get_serial_sequence('glo."GloVehicleMaintenanceType"', 'Id'),
        COALESCE((SELECT MAX("Id") FROM glo."GloVehicleMaintenanceType"), 1),
        true);

    INSERT INTO glo."GloMasterEntityType"
    (
        "Code",
        "IsDocumentAllowed",
        "SortOrder",
        "IsActive",
        "CreatedOn",
        "CreatedBy"
    )
    SELECT
        v."Code",
        v."IsDocumentAllowed",
        v."SortOrder",
        v."IsActive",
        timezone('utc', now()),
        'System'
    FROM (
        VALUES
            ('Warehouse',          true, 12, true),
            ('Vehicle',            true, 13, true),
            ('VehicleMaintenance', true, 14, true)
    ) AS v("Code", "IsDocumentAllowed", "SortOrder", "IsActive")
    WHERE NOT EXISTS (
        SELECT 1
        FROM glo."GloMasterEntityType" t
        WHERE t."Code" = v."Code"
    );

    SELECT setval(
        pg_get_serial_sequence('glo."GloMasterEntityType"', 'Id'),
        COALESCE((SELECT MAX("Id") FROM glo."GloMasterEntityType"), 1),
        true);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shared."__EFMigrationsHistory" WHERE "MigrationId" = '20260602150004_AddWarehouseVehicleAndMaintenanceTables') THEN
    INSERT INTO shared."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260602150004_AddWarehouseVehicleAndMaintenanceTables', '10.0.8');
    END IF;
END $EF$;
COMMIT;

