-- =============================================================================
-- Migration: 20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage
-- Script:   20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage_up.sql
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    DROP TABLE dbo."FgsOutboxMessage";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    CREATE TABLE dbo."GloOutboxMessage" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint,
        "CompanyId" bigint,
        "EventType" character varying(150) NOT NULL,
        "AggregateType" character varying(100),
        "AggregateId" character varying(100),
        "CorrelationId" uuid NOT NULL,
        "CausationId" uuid,
        "ExchangeName" character varying(200),
        "RoutingKey" character varying(200),
        "Payload" jsonb NOT NULL,
        "Headers" jsonb,
        "Status" character varying(50) NOT NULL DEFAULT 'Pending',
        "RetryCount" integer NOT NULL DEFAULT 0,
        "MaxRetryCount" integer NOT NULL DEFAULT 10,
        "NextRetryOn" timestamptz,
        "ProcessedOn" timestamptz,
        "LastError" text,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" bigint,
        "UpdatedOn" timestamptz,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_GloOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    CREATE INDEX "IX_GloOutboxMessage_CorrelationId" ON dbo."GloOutboxMessage" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    CREATE INDEX "IX_GloOutboxMessage_EventType" ON dbo."GloOutboxMessage" ("EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    CREATE INDEX "IX_GloOutboxMessage_Status_NextRetryOn" ON dbo."GloOutboxMessage" ("Status", "NextRetryOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    CREATE INDEX "IX_GloOutboxMessage_TenantId" ON dbo."GloOutboxMessage" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260523075504_ReplaceFgsOutboxMessageWithGloOutboxMessage', '10.0.8');
    END IF;
END $EF$;

COMMIT;
