-- =============================================================================
-- Migration: 20260522154248_AddGloTradeSkillLeadSourceZoneCategory
-- Script:   20260522154248_AddGloTradeSkillLeadSourceZoneCategory_up.sql
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloTrade" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "BusinessTypeId" integer NOT NULL,
        "TradeCode" character varying(50) NOT NULL,
        "TradeName" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_GloTrade" PRIMARY KEY ("Id"),
        CONSTRAINT "UX_GloTrade_TradeCode" UNIQUE ("TradeCode"),
        CONSTRAINT "FK_GloTrade_GloBusinessType_BusinessTypeId"
            FOREIGN KEY ("BusinessTypeId") REFERENCES dbo."GloBusinessType" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloSkill" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "BusinessTypeId" integer NOT NULL,
        "TradeId" smallint NOT NULL,
        "SkillCode" character varying(50) NOT NULL,
        "SkillName" character varying(100) NOT NULL,
        "Description" character varying(255),
        "RequiresCertification" boolean NOT NULL DEFAULT false,
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloSkill" PRIMARY KEY ("Id"),
        CONSTRAINT "UX_GloSkill_SkillCode" UNIQUE ("SkillCode"),
        CONSTRAINT "FK_GloSkill_GloBusinessType_BusinessTypeId"
            FOREIGN KEY ("BusinessTypeId") REFERENCES dbo."GloBusinessType" ("Id"),
        CONSTRAINT "FK_GloSkill_GloTrade_TradeId"
            FOREIGN KEY ("TradeId") REFERENCES dbo."GloTrade" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloLeadSource" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "SourceCode" character varying(50) NOT NULL,
        "SourceName" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloLeadSource" PRIMARY KEY ("Id"),
        CONSTRAINT "UX_GloLeadSource_SourceCode" UNIQUE ("SourceCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."FgsLeadSource" (
        "Id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "SourceCode" character varying(50) NOT NULL,
        "SourceName" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsLeadSource" PRIMARY KEY ("Id"),
        CONSTRAINT "UX_FgsLeadSource_TenantId_CompanyId_SourceCode"
            UNIQUE ("TenantId", "CompanyId", "SourceCode"),
        CONSTRAINT "FK_FgsLeadSource_FgsTenantCompany_TenantId_CompanyId"
            FOREIGN KEY ("TenantId", "CompanyId")
            REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber")
            ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloZone" (
        "Id" smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloZone" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloZone_Code" UNIQUE ("Code"),
        CONSTRAINT "CK_GloZone_Code_Upper" CHECK ("Code" = upper("Code"))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloCategory" (
        "Id" smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
        "BusinessTypeId" integer NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloCategory_BusinessTypeId_Code" UNIQUE ("BusinessTypeId", "Code"),
        CONSTRAINT "FK_GloCategory_GloBusinessType_BusinessTypeId"
            FOREIGN KEY ("BusinessTypeId") REFERENCES dbo."GloBusinessType" ("Id")
            ON DELETE RESTRICT,
        CONSTRAINT "CK_GloCategory_Code_Upper" CHECK ("Code" = upper("Code"))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloSubCategory" (
        "Id" smallint GENERATED ALWAYS AS IDENTITY NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT true,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloSubCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloSubCategory_Code" UNIQUE ("Code"),
        CONSTRAINT "CK_GloSubCategory_Code_Upper" CHECK ("Code" = upper("Code"))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE TABLE dbo."GloCategorySubCategory" (
        "BusinessTypeId" integer NOT NULL,
        "CategoryId" smallint NOT NULL,
        "SubCategoryId" smallint NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "PK_GloCategorySubCategory"
            PRIMARY KEY ("BusinessTypeId", "CategoryId", "SubCategoryId"),
        CONSTRAINT "FK_GloCategorySubCategory_GloBusinessType_BusinessTypeId"
            FOREIGN KEY ("BusinessTypeId") REFERENCES dbo."GloBusinessType" ("Id")
            ON DELETE RESTRICT,
        CONSTRAINT "FK_GloCategorySubCategory_GloCategory_CategoryId"
            FOREIGN KEY ("CategoryId") REFERENCES dbo."GloCategory" ("Id")
            ON DELETE RESTRICT,
        CONSTRAINT "FK_GloCategorySubCategory_GloSubCategory_SubCategoryId"
            FOREIGN KEY ("SubCategoryId") REFERENCES dbo."GloSubCategory" ("Id")
            ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE INDEX "IX_GloCategorySubCategory_CategoryId"
        ON dbo."GloCategorySubCategory" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE INDEX "IX_GloCategorySubCategory_SubCategoryId"
        ON dbo."GloCategorySubCategory" ("SubCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE INDEX "IX_GloSkill_BusinessTypeId" ON dbo."GloSkill" ("BusinessTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE INDEX "IX_GloSkill_TradeId" ON dbo."GloSkill" ("TradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    CREATE INDEX "IX_GloTrade_BusinessTypeId" ON dbo."GloTrade" ("BusinessTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260522154248_AddGloTradeSkillLeadSourceZoneCategory') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522154248_AddGloTradeSkillLeadSourceZoneCategory', '10.0.8');
    END IF;
END $EF$;

COMMIT;
