-- =============================================================================
-- Migration: 20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy
-- Script:   20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy_up.sql
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE TABLE dbo."FgsTag" (
        "Id" bigint GENERATED ALWAYS AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "TagCode" character varying(50),
        "Name" character varying(100) NOT NULL,
        "NormalizedName" character varying(100) NOT NULL,
        "Description" text,
        "BackgroundColor" character varying(20),
        "TextColor" character varying(20),
        "IconFileId" bigint,
        "UsageCount" integer NOT NULL DEFAULT 0,
        "IsSystemGenerated" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" bigint,
        "UpdatedOn" timestamptz,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_FgsTag" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsTag_FgsFile_IconFileId" FOREIGN KEY ("IconFileId") REFERENCES dbo."FgsFile" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_FgsTag_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE TABLE dbo."GloTag" (
        "Id" integer GENERATED ALWAYS AS IDENTITY,
        "TagCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "NormalizedName" character varying(100) NOT NULL,
        "Description" text,
        "BackgroundColor" character varying(20),
        "TextColor" character varying(20),
        "IconFileId" bigint,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsSystemGenerated" boolean NOT NULL DEFAULT TRUE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloTag" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GloTag_FgsFile_IconFileId" FOREIGN KEY ("IconFileId") REFERENCES dbo."FgsFile" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE TABLE dbo."GloTitleOfCourtesy" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(25) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "SortOrder" integer NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloTitleOfCourtesy" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_GloTitleOfCourtesy_Code_Upper" CHECK ("Code" = upper("Code")),
        CONSTRAINT "CK_GloTitleOfCourtesy_SortOrder" CHECK ("SortOrder" >= 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE TABLE dbo."GloUnitOfMeasure" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UnitCode" character varying(30) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Abbreviation" character varying(20) NOT NULL,
        "Description" text,
        "UnitType" character varying(50) NOT NULL,
        "DecimalPlaces" smallint NOT NULL DEFAULT 2,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "IsSystem" boolean NOT NULL DEFAULT TRUE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_GloUnitOfMeasure" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_FgsTag_IconFileId" ON dbo."FgsTag" ("IconFileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_FgsTag_IsActive" ON dbo."FgsTag" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_FgsTag_Name" ON dbo."FgsTag" ("TenantId", "CompanyId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_FgsTag_UsageCount" ON dbo."FgsTag" ("TenantId", "CompanyId", "UsageCount" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UX_FgsTag_TenantId_CompanyId_NormalizedName" ON dbo."FgsTag" ("TenantId", "CompanyId", "NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UX_FgsTag_TenantId_CompanyId_TagCode" ON dbo."FgsTag" ("TenantId", "CompanyId", "TagCode") WHERE "TagCode" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloTag_DisplayOrder" ON dbo."GloTag" ("DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloTag_IconFileId" ON dbo."GloTag" ("IconFileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloTag_IsActive" ON dbo."GloTag" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloTag_Name" ON dbo."GloTag" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UX_GloTag_NormalizedName" ON dbo."GloTag" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UX_GloTag_TagCode" ON dbo."GloTag" ("TagCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloTitleOfCourtesy_SortOrder" ON dbo."GloTitleOfCourtesy" ("SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UQ_GloTitleOfCourtesy_Code" ON dbo."GloTitleOfCourtesy" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE INDEX "IX_GloUnitOfMeasure_UnitType" ON dbo."GloUnitOfMeasure" ("UnitType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    CREATE UNIQUE INDEX "UQ_GloUnitOfMeasure_UnitCode" ON dbo."GloUnitOfMeasure" ("UnitCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260523182019_AddGloUnitOfMeasureGloTagFgsTagGloTitleOfCourtesy', '10.0.8');
    END IF;
END $EF$;

COMMIT;
