START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    ALTER TABLE dbo."FgsSetupGLBreak" DROP COLUMN IF EXISTS "Trades";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    ALTER TABLE dbo."GloBillingCategory" ADD COLUMN IF NOT EXISTS "Description" text NULL;
    ALTER TABLE dbo."GloBillingCategory" ADD COLUMN IF NOT EXISTS "DisplayOrder" smallint NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    CREATE TABLE dbo."FgsSetupGLBreakTrade" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GLBreakId" bigint NOT NULL,
        "TradeCode" character varying(50) NOT NULL,
        "CreatedOn" timestamptz NOT NULL DEFAULT now(),
        "CreatedBy" character varying(100),
        CONSTRAINT "PK_FgsSetupGLBreakTrade" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupGLBreakTrade" UNIQUE ("TenantId", "CompanyId", "GLBreakId", "TradeCode"),
        CONSTRAINT "FK_FgsSetupGLBreakTrade_FgsSetupGLBreak_GLBreakId" FOREIGN KEY ("GLBreakId") REFERENCES dbo."FgsSetupGLBreak" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsSetupGLBreakTrade_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    CREATE INDEX "IX_FgsSetupGLBreakTrade_GLBreakId" ON dbo."FgsSetupGLBreakTrade" ("GLBreakId");
    CREATE INDEX "IX_FgsSetupGLBreakTrade_TenantId_CompanyId" ON dbo."FgsSetupGLBreakTrade" ("TenantId", "CompanyId");
    CREATE INDEX "IX_FgsSetupGLBreakTrade_TradeCode" ON dbo."FgsSetupGLBreakTrade" ("TenantId", "CompanyId", "TradeCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    CREATE INDEX IF NOT EXISTS "IX_FgsSetupGLBreak_TenantId_CompanyId_BreakLevel" ON dbo."FgsSetupGLBreak" ("TenantId", "CompanyId", "BreakLevel");
    CREATE INDEX IF NOT EXISTS "IX_FgsSetupGLBreak_AddressId" ON dbo."FgsSetupGLBreak" ("AddressId");
    CREATE INDEX IF NOT EXISTS "IX_FgsSetupGLBreak_LogoFileId" ON dbo."FgsSetupGLBreak" ("LogoFileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'CK_FgsSetupGLBreak_BreakLevel'
          AND conrelid = 'dbo."FgsSetupGLBreak"'::regclass) THEN
        ALTER TABLE dbo."FgsSetupGLBreak"
            ADD CONSTRAINT "CK_FgsSetupGLBreak_BreakLevel" CHECK ("BreakLevel" IN (1, 2));
    END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    COMMENT ON TABLE dbo."GloBillingCategory" IS 'Global billing line category lookup used during tenant provisioning (equipment, labor, tax, etc.).';
    COMMENT ON COLUMN dbo."GloBillingCategory"."BillingCategoryType" IS 'Short billing category code (primary key), e.g. IN, LB, TX.';
    COMMENT ON COLUMN dbo."GloBillingCategory"."BillingCategoryName" IS 'Display name of the billing category.';
    COMMENT ON COLUMN dbo."GloBillingCategory"."Description" IS 'Optional description of how the billing category is used.';
    COMMENT ON COLUMN dbo."GloBillingCategory"."DisplayOrder" IS 'Controls sorting/display order of billing categories in dropdowns and setup screens.';

    COMMENT ON TABLE dbo."FgsSetupGLBreak" IS 'Stores GL break configuration for financial reporting segmentation by trade, division, branch, or organizational unit.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."Id" IS 'Surrogate primary key.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."TenantId" IS 'Owning tenant identifier.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."CompanyId" IS 'Tenant-scoped company number (maps to FgsTenantCompany.CompanyNumber).';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."Code" IS 'Unique GL break code within tenant, company, and break level scope.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."Name" IS 'Display name of the GL break.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."BreakLabel" IS 'Optional label displayed in UI and financial documents.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."BreakLevel" IS 'Break hierarchy level. Allowed values: 1 or 2.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."LogoFileId" IS 'Optional reference to uploaded logo file in FgsFile.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."AddressId" IS 'Optional reference to branch or break address in FgsLocation.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."IsActive" IS 'Indicates whether the GL break is active.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."CreatedOn" IS 'UTC timestamp when the record was created.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."CreatedBy" IS 'User or process that created the record.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."UpdatedOn" IS 'UTC timestamp when the record was last updated.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreak"."UpdatedBy" IS 'User or process that last updated the record.';

    COMMENT ON TABLE dbo."FgsSetupGLBreakTrade" IS 'Stores trade-to-GL-break mappings used for financial segmentation and reporting.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."Id" IS 'Surrogate primary key.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."TenantId" IS 'Owning tenant identifier.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."CompanyId" IS 'Tenant-scoped company number.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."GLBreakId" IS 'Reference to the associated GL break configuration.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."TradeCode" IS 'Technician or operational trade code associated with the GL break such as HVAC, Plumbing, Electrical, or Drain.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."CreatedOn" IS 'UTC timestamp when the record was created.';
    COMMENT ON COLUMN dbo."FgsSetupGLBreakTrade"."CreatedBy" IS 'User or process that created the record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527143747_UpdateGloBillingCategoryAndFgsSetupGLBreakTrade', '10.0.8');
    END IF;
END $EF$;

COMMIT;
