-- =============================================================================
-- Migration: 20260523083815_AddGloSeedTableMappings
-- Script:   20260523083815_AddGloSeedTableMappings_up.sql
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    CREATE TABLE dbo."GloSeedTableMapping" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SeedCode" character varying(100) NOT NULL,
        "SourceDatabaseName" character varying(150),
        "SourceSchemaName" character varying(100) NOT NULL DEFAULT 'public',
        "SourceTableName" character varying(150) NOT NULL,
        "TargetDatabaseName" character varying(150),
        "TargetSchemaName" character varying(100) NOT NULL DEFAULT 'public',
        "TargetTableName" character varying(150) NOT NULL,
        "SeedOrder" integer NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_GloSeedTableMapping" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    CREATE TABLE dbo."GloSeedTableColumnMapping" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SeedTableMappingId" bigint NOT NULL,
        "SourceColumnName" character varying(150),
        "TargetColumnName" character varying(150) NOT NULL,
        "TransformationType" character varying(50),
        "StaticValue" text,
        "ColumnOrder" integer NOT NULL DEFAULT 0,
        "IsRequired" boolean NOT NULL DEFAULT FALSE,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamptz,
        "CreatedBy" bigint,
        "UpdatedBy" bigint,
        CONSTRAINT "PK_GloSeedTableColumnMapping" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GloSeedTableColumnMapping_GloSeedTableMapping" FOREIGN KEY ("SeedTableMappingId") REFERENCES dbo."GloSeedTableMapping" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    CREATE INDEX "IX_GloSeedTableColumnMapping_SeedTableMappingId" ON dbo."GloSeedTableColumnMapping" ("SeedTableMappingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    CREATE INDEX "IX_GloSeedTableMapping_SeedOrder" ON dbo."GloSeedTableMapping" ("SeedOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    CREATE UNIQUE INDEX "UX_GloSeedTableMapping_SeedCode" ON dbo."GloSeedTableMapping" ("SeedCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260523083815_AddGloSeedTableMappings') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260523083815_AddGloSeedTableMappings', '10.0.8');
    END IF;
END $EF$;

COMMIT;
