using Fgs.Setup.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Fgs.Setup.Infrastructure.Database.Configurations;

internal class FgsJobTypeBillingCategoryAccountingConfiguration : IEntityTypeConfiguration<FgsJobTypeBillingCategoryAccounting>
{
    public void Configure(EntityTypeBuilder<FgsJobTypeBillingCategoryAccounting> entity)
    {
        entity.ToTable("FgsJobTypeBillingCategoryAccounting", t =>
            t.HasComment(
                "Stores optional accounting overrides for a specific Job Type and Billing Category combination. These mappings allow a Job Type to override the default Revenue, COGS, and Inventory Offset GL accounts defined for the Billing Category."));

        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id)
            .UseIdentityByDefaultColumn()
            .HasComment("Primary key identity of the Job Type and Billing Category accounting configuration record.");

        entity.Property(e => e.TenantId)
            .HasComment("Tenant identifier owning this Job Type and Billing Category accounting configuration.");

        entity.Property(e => e.CompanyId)
            .HasComment("Company identifier within the tenant owning this Job Type and Billing Category accounting configuration.");

        entity.HasAlternateKey(e => new { e.TenantId, e.CompanyId, e.JobTypeId, e.BillingCategoryId })
            .HasName("UQ_FgsJobTypeBillingCategoryAccounting_TenantId_CompanyId_JobTypeId_BillingCategoryId");

        entity.Property(e => e.JobTypeId)
            .HasComment("Identifier of the Job Type to which the accounting override applies.");

        entity.Property(e => e.BillingCategoryId)
            .HasComment("Identifier of the Billing Category for which the Job Type accounting override is defined.");

        entity.Property(e => e.RevenueAccountId)
            .HasComment(
                "Optional GL account used for revenue generated by the Job Type when the specified Billing Category applies. If not configured, the Billing Category default Revenue account can be used.");

        entity.Property(e => e.CogsAccountId)
            .HasComment(
                "Optional GL account used for cost of goods sold when the specified Billing Category applies to the Job Type. If not configured, the Billing Category default COGS account can be used.");

        entity.Property(e => e.InventoryOffsetAccountId)
            .HasComment(
                "Optional GL account used as the inventory offset when the specified Billing Category is an Inventory billing category. If not configured, the Billing Category default Inventory Offset account can be used.");

        entity.Property(e => e.CreatedOn)
            .IsRequired()
            .HasColumnType("timestamptz")
            .HasDefaultValueSql("now()")
            .HasComment("Date and time the Job Type and Billing Category accounting configuration was created.");

        entity.Property(e => e.CreatedBy)
            .HasMaxLength(100)
            .HasComment("User identifier that created the Job Type and Billing Category accounting configuration.");

        entity.Property(e => e.UpdatedOn)
            .HasColumnType("timestamptz")
            .HasComment("Date and time the Job Type and Billing Category accounting configuration was last updated.");

        entity.Property(e => e.UpdatedBy)
            .HasMaxLength(100)
            .HasComment("User identifier that last updated the Job Type and Billing Category accounting configuration.");

        entity.HasIndex(e => new { e.TenantId, e.CompanyId, e.JobTypeId })
            .HasDatabaseName("IX_FgsJobTypeBillingCategoryAccounting_TenantId_CompanyId_JobTypeId");

        entity.HasIndex(e => new { e.TenantId, e.CompanyId, e.BillingCategoryId })
            .HasDatabaseName("IX_FgsJobTypeBillingCategoryAccounting_TenantId_CompanyId_BillingCategoryId");

        entity.HasOne<FgsJobType>()
            .WithMany()
            .HasForeignKey(e => e.JobTypeId)
            .HasConstraintName("FK_FgsJobTypeBillingCategoryAccounting_FgsJobType")
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasOne<FgsBillingCategory>()
            .WithMany()
            .HasForeignKey(e => e.BillingCategoryId)
            .HasConstraintName("FK_FgsJobTypeBillingCategoryAccounting_FgsBillingCategory")
            .OnDelete(DeleteBehavior.Cascade);
    }
}
