using Fgs.Setup.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Fgs.Setup.Infrastructure.Database.Configurations;

internal sealed class GloInventoryTransactionTypeConfiguration : IEntityTypeConfiguration<GloInventoryTransactionType>
{
    public void Configure(EntityTypeBuilder<GloInventoryTransactionType> entity)
    {
        entity.ToTable(
            "GloInventoryTransactionType",
            t => t.HasComment("Defines specific inventory ledger transactions generated by inventory business processes."));

        entity.HasKey(e => e.Id).HasName("PK_GloInventoryTransactionType");
        entity.Property(e => e.Id).UseIdentityByDefaultColumn();

        entity.Property(e => e.InventoryTransactionSourceTypeId)
            .HasComment("References the inventory transaction source type that generates this transaction.");
        entity.Property(e => e.Code).HasMaxLength(50).IsRequired()
            .HasComment("System transaction code.");
        entity.Property(e => e.Name).HasMaxLength(100).IsRequired()
            .HasComment("Display name of the inventory transaction type.");
        entity.Property(e => e.Description).HasMaxLength(500)
            .HasComment("Description of the inventory transaction type.");
        entity.Property(e => e.SortOrder).HasDefaultValue(1)
            .HasComment("Display order.");
        entity.Property(e => e.IsActive).HasDefaultValue(true)
            .HasComment("Indicates whether the transaction type is active.");
        entity.Property(e => e.CreatedOn).IsRequired().HasColumnType("timestamptz").HasDefaultValueSql("now()");

        entity.HasOne<GloInventoryTransactionSourceType>()
            .WithMany()
            .HasForeignKey(e => e.InventoryTransactionSourceTypeId)
            .HasConstraintName("FK_GloInventoryTransactionType_GloInventoryTransactionSourceType")
            .OnDelete(DeleteBehavior.Restrict);

        entity.HasIndex(e => e.Code)
            .IsUnique()
            .HasDatabaseName("UQ_GloInventoryTransactionType_Code");
        entity.HasIndex(e => e.InventoryTransactionSourceTypeId)
            .HasDatabaseName("IX_GloInventoryTransactionType_SourceType");
        entity.HasIndex(e => e.IsActive)
            .HasDatabaseName("IX_GloInventoryTransactionType_IsActive");
    }
}
