using Dapper;
using Fgs.Asset.Application.Abstractions.AssetAttributeValues;
using Fgs.Asset.Application.Abstractions.Persistence;
using Fgs.Asset.Application.Common.AssetCrud;
using Fgs.Asset.Application.Features.AssetAttributeValues.Dtos;
using Fgs.Asset.Infrastructure.Common;
using Fgs.Foundation.Paging;
using Fgs.MultiTenancy;
namespace Fgs.Asset.Infrastructure.AssetAttributeValues;
internal sealed class FgsAssetAttributeValueReadRepository : IFgsAssetAttributeValueReadRepository
{
    private readonly IAssetReadConnectionFactory _connectionFactory; private readonly ITenantContextAccessor _tenantContextAccessor;
    public FgsAssetAttributeValueReadRepository(IAssetReadConnectionFactory connectionFactory, ITenantContextAccessor tenantContextAccessor) { _connectionFactory = connectionFactory; _tenantContextAccessor = tenantContextAccessor; }
    public async Task<FgsAssetAttributeValueDetailDto?> GetByIdAsync(long id, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var sql = $"SELECT {FgsAssetAttributeValueSql.SelectDetailColumns} FROM {FgsAssetAttributeValueSql.Table} WHERE \"Id\" = @Id AND \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return (await connection.QueryFirstOrDefaultAsync<FgsAssetAttributeValueDetailRow>(new CommandDefinition(sql, new { Id = id, TenantId = tenantId, CompanyId = companyId }, cancellationToken: cancellationToken)))?.ToDto(); }
    public async Task<PagedResult<FgsAssetAttributeValueSummaryDto>> ListAsync(AssetListQuery query, FgsAssetAttributeValueListFilters filters, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var paging = query.ToPagedQuery(); var page = Math.Max(1, paging.Page); var pageSize = Math.Clamp(paging.PageSize, 1, 200); var offset = (page - 1) * pageSize; var where = new List<string> { "\"TenantId\" = @TenantId", "\"CompanyId\" = @CompanyId" }; if (filters.AssetId.HasValue) where.Add("\"AssetId\" = @AssetId"); if (filters.AssetAttributeId.HasValue) where.Add("\"AssetAttributeId\" = @AssetAttributeId"); if (!string.IsNullOrWhiteSpace(paging.Search)) where.Add("\"ValueText\" ILIKE @Search"); var whereClause = string.Join(" AND ", where); var sql = $"SELECT {FgsAssetAttributeValueSql.SelectSummaryColumns} FROM {FgsAssetAttributeValueSql.Table} WHERE {whereClause} {FgsAssetAttributeValueSql.ResolveOrderBy(paging.SortBy, paging.SortDirection)} LIMIT @PageSize OFFSET @Offset; SELECT COUNT(*) FROM {FgsAssetAttributeValueSql.Table} WHERE {whereClause};"; var parameters = new { TenantId = tenantId, CompanyId = companyId, AssetId = filters.AssetId, AssetAttributeId = filters.AssetAttributeId, Search = string.IsNullOrWhiteSpace(paging.Search) ? null : $"%{paging.Search.Trim()}%", PageSize = pageSize, Offset = offset }; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); await using var multi = await connection.QueryMultipleAsync(new CommandDefinition(sql, parameters, cancellationToken: cancellationToken)); var rows = (await multi.ReadAsync<FgsAssetAttributeValueSummaryRow>()).ToList(); return new PagedResult<FgsAssetAttributeValueSummaryDto>(rows.Select(r => r.ToDto()).ToList(), page, pageSize, await multi.ReadSingleAsync<int>()); }
    public async Task<IReadOnlyList<FgsAssetAttributeValueLookupDto>> LookupAsync(CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var sql = $"SELECT {FgsAssetAttributeValueSql.SelectLookupColumns} FROM {FgsAssetAttributeValueSql.Table} WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId ORDER BY \"Id\" ASC"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return (await connection.QueryAsync<FgsAssetAttributeValueLookupRow>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId }, cancellationToken: cancellationToken))).Select(r => r.ToDto()).ToList(); }
    public async Task<bool> ExistsAssetIdAsync(long assetId, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAsset\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetId }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsAssetAttributeIdAsync(long assetAttributeId, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAssetAttribute\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetAttributeId }, cancellationToken: cancellationToken)); }
}
