START TRANSACTION;

ALTER TABLE setup."FgsSetupPostalCode" DROP COLUMN IF EXISTS "TripChargeAmount";
ALTER TABLE setup."FgsSetupPostalCode" DROP COLUMN IF EXISTS "StateProvinceCode";
ALTER TABLE setup."FgsSetupPostalCode" DROP COLUMN IF EXISTS "CountryCode";
ALTER TABLE setup."FgsSetupPostalCode" DROP COLUMN IF EXISTS "City";

COMMENT ON COLUMN setup."FgsSetupPricingMatrix"."IsLaborTierStructure" IS NULL;

CREATE TABLE IF NOT EXISTS glo."GloTimeCardOption" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_GloTimeCardOption" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_GloTimeCardOption_Code" UNIQUE ("Code"),
    CONSTRAINT "CK_GloTimeCardOption_Code_Upper" CHECK ("Code" = UPPER("Code"))
);

DELETE FROM setup."__EFMigrationsHistory"
WHERE "MigrationId" = '20260802062516_AddPostalCodeGeoTripChargeDropTimeCardOption';

COMMIT;
