-- Rollback for 20260927051512_RemapJobTypeCategoryAndMoveColors
START TRANSACTION;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobTypeTask" DROP CONSTRAINT IF EXISTS "FK_FgsJobTypeTask_FgsJobTypeCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    DELETE FROM setup."FgsJobTypeTask";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    DROP TABLE IF EXISTS setup."FgsJobTypeCategory";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    CREATE TABLE setup."FgsJobTypeCategory" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "JobTypeId" bigint NOT NULL,
        "JobCategoryId" bigint NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsJobTypeCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsJobTypeCategory_FgsJobCategory" FOREIGN KEY ("JobCategoryId") REFERENCES setup."FgsJobCategory" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsJobTypeCategory_FgsJobType" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsJobTypeCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE setup."FgsJobTypeCategory" IS 'Maps Job Categories to Job Types. A Job Type can contain one or more Job Categories, each with its own display order.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."Id" IS 'Unique identifier for the Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."TenantId" IS 'Identifier of the tenant that owns this Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CompanyId" IS 'Identifier of the company within the tenant that owns this Job Type Category mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobTypeId" IS 'Identifier of the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."JobCategoryId" IS 'Identifier of the Job Category assigned to the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."DisplayOrder" IS 'Controls the display sequence of Job Categories within the Job Type.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedOn" IS 'Date and time when the mapping was created.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."CreatedBy" IS 'User who created the mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedOn" IS 'Date and time when the mapping was last modified.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."UpdatedBy" IS 'User who last modified the mapping.';
    COMMENT ON COLUMN setup."FgsJobTypeCategory"."IsActive" IS 'Indicates whether the Job Category assignment is active.';
    CREATE INDEX "IX_FgsJobTypeCategory_JobCategoryId" ON setup."FgsJobTypeCategory" ("JobCategoryId");
    CREATE INDEX "IX_FgsJobTypeCategory_JobTypeId" ON setup."FgsJobTypeCategory" ("JobTypeId");
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId");
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobCategory" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobCategoryId");
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_JobType" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId");
    CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company_DisplayOrder" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "DisplayOrder");
    CREATE UNIQUE INDEX "UX_FgsJobTypeCategory_Tenant_Company_JobType_Category" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "JobTypeId", "JobCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobTypeTask" ADD CONSTRAINT "FK_FgsJobTypeTask_FgsJobTypeCategory" FOREIGN KEY ("JobTypeCategoryId") REFERENCES setup."FgsJobTypeCategory" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobCategory" DROP COLUMN IF EXISTS "BackgroundColor";
    ALTER TABLE setup."FgsJobCategory" DROP COLUMN IF EXISTS "TextColor";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    ALTER TABLE setup."FgsJobType" ADD "BackgroundColor" character varying(20);
    COMMENT ON COLUMN setup."FgsJobType"."BackgroundColor" IS 'Optional background color used when displaying the Job Type in the user interface.';
    ALTER TABLE setup."FgsJobType" ADD "TextColor" character varying(20);
    COMMENT ON COLUMN setup."FgsJobType"."TextColor" IS 'Optional text color used when displaying the Job Type in the user interface.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors') THEN
    DELETE FROM setup."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260927051512_RemapJobTypeCategoryAndMoveColors';
    END IF;
END $EF$;
COMMIT;
