-- Rollback for 20260728183140_RedesignJobTypeHierarchy
-- Restores the prior Job Type catalog shape. Data created under the new hierarchy is lost.

START TRANSACTION;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy') THEN
        IF EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE c.conname = 'FK_FgsPriceBook_JobTypeId'
              AND n.nspname = 'setup'
              AND t.relname = 'FgsPriceBook') THEN
            ALTER TABLE setup."FgsPriceBook" DROP CONSTRAINT "FK_FgsPriceBook_JobTypeId";
        END IF;

        DELETE FROM setup."FgsPriceBookItem";
        DELETE FROM setup."FgsPriceBook";

        DROP TABLE IF EXISTS setup."FgsJobTypeTask";
        DROP TABLE IF EXISTS setup."FgsJobTypeCategory";
        DROP TABLE IF EXISTS setup."FgsJobType";
        DROP TABLE IF EXISTS setup."FgsJobCategory";

        CREATE TABLE setup."FgsJobTypeCategory" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "CategoryCode" character varying(50) NOT NULL,
            "Name" character varying(150) NOT NULL,
            "Description" text,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobTypeCategory" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobTypeCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );

        CREATE TABLE setup."FgsJobTypeSubCategory" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "SubCategoryCode" character varying(50) NOT NULL,
            "Name" character varying(150) NOT NULL,
            "Description" text,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobTypeSubCategory" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobTypeSubCategory_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );

        CREATE TABLE glo."GloJobTypeSubCategory" (
            "Id" smallint GENERATED ALWAYS AS IDENTITY,
            "BusinessTypeId" integer,
            "Code" character varying(50) NOT NULL,
            "CreatedBy" character varying(100),
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "Description" character varying(255),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            "Name" character varying(100) NOT NULL,
            "UpdatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            CONSTRAINT "PK_GloJobTypeSubCategory" PRIMARY KEY ("Id"),
            CONSTRAINT "CK_GloJobTypeSubCategory_Code_Upper" CHECK ("Code" = upper("Code")),
            CONSTRAINT "FK_GloJobTypeSubCategory_GloBusinessType_BusinessTypeId" FOREIGN KEY ("BusinessTypeId") REFERENCES glo."GloBusinessType" ("Id") ON DELETE RESTRICT
        );

        CREATE TABLE setup."FgsJobType" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TenantId" bigint NOT NULL,
            "CompanyId" bigint NOT NULL,
            "JobTypeCategoryId" bigint NOT NULL,
            "JobTypeSubCategoryId" bigint,
            "JobTypeCode" character varying(50) NOT NULL,
            "TaskName" character varying(200) NOT NULL,
            "Description" text,
            "UsedFor" character varying(50) NOT NULL,
            "Trade" character varying(100),
            "EstimatedDurationMinutes" integer,
            "BusinessUnit" character varying(100),
            "Priority" smallint NOT NULL DEFAULT 5,
            "BackgroundColor" character varying(20),
            "TextColor" character varying(20),
            "ShowToFieldTech" boolean NOT NULL DEFAULT TRUE,
            "ShowOnCustomerPortal" boolean NOT NULL DEFAULT TRUE,
            "DisplayOrder" smallint NOT NULL DEFAULT 1,
            "CreatedOn" timestamptz NOT NULL DEFAULT (now()),
            "CreatedBy" character varying(100),
            "UpdatedOn" timestamptz,
            "UpdatedBy" character varying(100),
            "IsActive" boolean NOT NULL DEFAULT TRUE,
            CONSTRAINT "PK_FgsJobType" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_FgsJobType_FgsJobTypeCategory" FOREIGN KEY ("JobTypeCategoryId") REFERENCES setup."FgsJobTypeCategory" ("Id") ON DELETE RESTRICT,
            CONSTRAINT "FK_FgsJobType_FgsJobTypeSubCategory" FOREIGN KEY ("JobTypeSubCategoryId") REFERENCES setup."FgsJobTypeSubCategory" ("Id") ON DELETE RESTRICT,
            CONSTRAINT "FK_FgsJobType_FgsTenantCompanyCache_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES setup."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
        );

        CREATE UNIQUE INDEX "UX_FgsJobTypeCategory_Tenant_Company_CategoryCode" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId", "CategoryCode");
        CREATE INDEX "IX_FgsJobTypeCategory_Tenant_Company" ON setup."FgsJobTypeCategory" ("TenantId", "CompanyId");
        CREATE INDEX "IX_FgsJobTypeSubCategory_Tenant_Company" ON setup."FgsJobTypeSubCategory" ("TenantId", "CompanyId");
        CREATE UNIQUE INDEX "UX_FgsJobTypeSubCategory_Tenant_Company_SubCategoryCode" ON setup."FgsJobTypeSubCategory" ("TenantId", "CompanyId", "SubCategoryCode");
        CREATE INDEX "IX_GloJobTypeSubCategory_BusinessTypeId" ON glo."GloJobTypeSubCategory" ("BusinessTypeId");
        CREATE UNIQUE INDEX "UQ_GloJobTypeSubCategory_Code" ON glo."GloJobTypeSubCategory" ("Code");
        CREATE INDEX "IX_FgsJobType_JobTypeCategoryId" ON setup."FgsJobType" ("JobTypeCategoryId");
        CREATE INDEX "IX_FgsJobType_JobTypeSubCategoryId" ON setup."FgsJobType" ("JobTypeSubCategoryId");
        CREATE INDEX "IX_FgsJobType_Tenant_Company" ON setup."FgsJobType" ("TenantId", "CompanyId");
        CREATE INDEX "IX_FgsJobType_Tenant_Company_BusinessUnit" ON setup."FgsJobType" ("TenantId", "CompanyId", "BusinessUnit");
        CREATE INDEX "IX_FgsJobType_Tenant_Company_Trade" ON setup."FgsJobType" ("TenantId", "CompanyId", "Trade");
        CREATE INDEX "IX_FgsJobType_Tenant_Company_UsedFor" ON setup."FgsJobType" ("TenantId", "CompanyId", "UsedFor");
        CREATE UNIQUE INDEX "UX_FgsJobType_Tenant_Company_JobTypeCode" ON setup."FgsJobType" ("TenantId", "CompanyId", "JobTypeCode");

        ALTER TABLE setup."FgsPriceBook" ADD CONSTRAINT "FK_FgsPriceBook_JobTypeId" FOREIGN KEY ("JobTypeId") REFERENCES setup."FgsJobType" ("Id") ON DELETE RESTRICT;

        DELETE FROM setup."__EFMigrationsHistory" WHERE "MigrationId" = '20260728183140_RedesignJobTypeHierarchy';
    END IF;
END $EF$;

COMMIT;
