using Fgs.Audit.Domain.Enums;
using Fgs.Kernel.Entities;

namespace Fgs.Audit.Domain.Entities;

/// <summary>
/// Stores business, system, security, and integration events generated by the FSM platform.
/// Provides the primary audit history for all business entities.
/// </summary>
public class FgsEvent : ITenantCompanyScoped
{
    public long Id { get; set; }

    public long TenantId { get; set; }

    public long CompanyId { get; set; }

    public string EventCode { get; set; } = null!;

    public AuditEventSource EventSource { get; set; }

    public AuditRecordType RecordType { get; set; }

    public long EntityId { get; set; }

    public string? EntityNumber { get; set; }

    public string? UserName { get; set; }

    public string Summary { get; set; } = null!;

    public DateTime OccurredOn { get; set; }

    public DateTime CreatedOn { get; set; }

    public ICollection<FgsEventDetail> Details { get; set; } = new List<FgsEventDetail>();

    public ICollection<FgsEventAttachment> Attachments { get; set; } = new List<FgsEventAttachment>();
}
