-- Initial schema (fgs), setup reference data, and EF migration history row for 20260508175756_InitialCreateWithSetupSeed.
-- Table and column identifiers use PascalCase (quoted). History table name matches MigrationsHistoryTable("__ef_migrations_history", "fgs").

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'fgs') THEN
        CREATE SCHEMA fgs;
    END IF;
END $EF$;

CREATE TABLE IF NOT EXISTS fgs.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_EfMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE fgs."FSGSetupAccountingIntegrationType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupAccountingIntegrationType" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."FSGSetupBusinessType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupBusinessType" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."FSGSetupLanguage" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CultureCode" character varying(50) NOT NULL,
    "IsDefault" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupLanguage" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."FSGSetupLocationType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupLocationType" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."FSGSetupMasterEntityType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupMasterEntityType" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."FSGSetupTimeCardOption" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(100) NOT NULL,
    "Description" character varying(2000),
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_FSGSetupTimeCardOption" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."Tenant" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "LegalName" character varying(300),
    "Email" character varying(300),
    "PhoneNumber" character varying(50),
    "Website" character varying(500),
    "PrimaryLocationId" uuid,
    "SubscriptionPlanId" integer,
    "TimeZone" character varying(100),
    "DefaultCurrency" character varying(20),
    "DefaultLanguageId" integer,
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Tenant" PRIMARY KEY ("Id")
);

CREATE TABLE fgs."Company" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyGuid" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CompanyNumber" bigint NOT NULL,
    "BusinessTypeId" integer NOT NULL,
    "Code" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "LegalName" character varying(300),
    "Email" character varying(300),
    "PhoneNumber" character varying(50),
    "Website" character varying(500),
    "TaxId" character varying(100),
    "PrimaryLocationId" uuid,
    "FullLogoUrl" character varying(1000),
    "CompactLogoUrl" character varying(1000),
    "IconLogoUrl" character varying(1000),
    "FaviconUrl" character varying(1000),
    "IsActive" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "UpdatedOn" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Company_FSGSetupBusinessType_BusinessTypeId" FOREIGN KEY ("BusinessTypeId") REFERENCES fgs."FSGSetupBusinessType" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Company_Tenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES fgs."Tenant" ("Id") ON DELETE RESTRICT
);

CREATE TABLE fgs."Users" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Email" citext NOT NULL,
    "DisplayName" text,
    "Status" text NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Role" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES fgs."Company" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_Tenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES fgs."Tenant" ("Id") ON DELETE RESTRICT
);

CREATE TABLE fgs."AuthIdentity" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Issuer" text NOT NULL,
    "ObjectId" text NOT NULL,
    "Subject" text,
    "EmailSnapshot" citext,
    "LinkedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuthIdentity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuthIdentity_Users_UserId" FOREIGN KEY ("UserId") REFERENCES fgs."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE fgs."Invite" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "InvitedEmail" citext NOT NULL,
    "CompanyId" bigint NOT NULL,
    "TokenHash" bytea NOT NULL,
    "Status" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "AcceptedAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Invite" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invite_Company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES fgs."Company" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invite_Tenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES fgs."Tenant" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Invite_Users_UserId" FOREIGN KEY ("UserId") REFERENCES fgs."Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IxAuthIdentityIssuerObjectId" ON fgs."AuthIdentity" ("Issuer", "ObjectId");

CREATE INDEX "IxAuthIdentityUser" ON fgs."AuthIdentity" ("UserId");

CREATE INDEX "IxCompanyBusinessTypeId" ON fgs."Company" ("BusinessTypeId");

CREATE UNIQUE INDEX "IxCompanyCompanyGuid" ON fgs."Company" ("CompanyGuid");

CREATE INDEX "IxCompanyTenant" ON fgs."Company" ("TenantId");

CREATE UNIQUE INDEX "IxFSGSetupAccountingIntegrationTypeCode" ON fgs."FSGSetupAccountingIntegrationType" ("Code");

CREATE UNIQUE INDEX "IxFSGSetupBusinessTypeCode" ON fgs."FSGSetupBusinessType" ("Code");

CREATE UNIQUE INDEX "IxFSGSetupLanguageCode" ON fgs."FSGSetupLanguage" ("Code");

CREATE UNIQUE INDEX "IxFSGSetupLocationTypeCode" ON fgs."FSGSetupLocationType" ("Code");

CREATE UNIQUE INDEX "IxFSGSetupMasterEntityTypeCode" ON fgs."FSGSetupMasterEntityType" ("Code");

CREATE UNIQUE INDEX "IxFSGSetupTimeCardOptionCode" ON fgs."FSGSetupTimeCardOption" ("Code");

CREATE INDEX "IxInviteCompanyId" ON fgs."Invite" ("CompanyId");

CREATE INDEX "IxInvitePending" ON fgs."Invite" ("TenantId") WHERE "Status" = 'pending';

CREATE INDEX "IxInviteTokenHash" ON fgs."Invite" ("TokenHash");

CREATE INDEX "IxInviteUser" ON fgs."Invite" ("UserId");

CREATE INDEX "IxUsersCompanyId" ON fgs."Users" ("CompanyId");

CREATE INDEX "IxUsersTenant" ON fgs."Users" ("TenantId");

CREATE UNIQUE INDEX "IxUsersTenantEmail" ON fgs."Users" ("TenantId", "Email");

INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (1, 'HVAC', 'HVAC', 1, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (2, 'PLUMBING', 'Plumbing', 2, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (3, 'ELECTRICAL', 'Electrical', 3, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (4, 'PESTCONTROL', 'Pest Control', 4, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (5, 'LAWNCARE', 'Lawn Care', 5, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (6, 'TRASHPICKUP', 'Trash Pickup', 6, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (7, 'GARAGEDOOR', 'Garage Door', 7, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (8, 'HOUSECLEANING', 'House Cleaning', 8, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupBusinessType" ("Id", "Code", "Name", "SortOrder", "IsActive", "CreatedOn")
VALUES (9, 'PAINTING', 'Painting', 9, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

INSERT INTO fgs."FSGSetupTimeCardOption" ("Id", "Code", "Description", "IsActive", "CreatedOn")
VALUES (1, 'NONE', 'No formal technician time tracking workflow', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupTimeCardOption" ("Id", "Code", "Description", "IsActive", "CreatedOn")
VALUES (2, 'DISPATCHARRIVECOMPLETE', 'Tracks dispatch, arrival, and completion timestamps', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupTimeCardOption" ("Id", "Code", "Description", "IsActive", "CreatedOn")
VALUES (3, 'CHECKINCHECKOUT', 'Technician manually checks in and checks out', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

INSERT INTO fgs."FSGSetupAccountingIntegrationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (1, 'NONE', 'No Accounting', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupAccountingIntegrationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (2, 'QUICKBOOKSONLINE', 'QuickBooks Online', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupAccountingIntegrationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (3, 'SAGEINTACCT', 'Sage Intacct', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

INSERT INTO fgs."FSGSetupLanguage" ("Id", "Code", "Name", "CultureCode", "IsDefault", "SortOrder", "IsActive", "CreatedOn")
VALUES (1, 'EN', 'English', 'en-US', TRUE, 1, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLanguage" ("Id", "Code", "Name", "CultureCode", "IsDefault", "SortOrder", "IsActive", "CreatedOn")
VALUES (2, 'ES', 'Spanish', 'es-US', FALSE, 2, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLanguage" ("Id", "Code", "Name", "CultureCode", "IsDefault", "SortOrder", "IsActive", "CreatedOn")
VALUES (3, 'FR', 'French', 'fr-FR', FALSE, 3, TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (1, 'TENANT', 'TENANT', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (2, 'COMPANY', 'COMPANY', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (3, 'SERVICELOCATION', 'SERVICELOCATION', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (4, 'BILLTO', 'BILLTO', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (5, 'VENDOR', 'VENDOR', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (6, 'SUBCONTRACTOR', 'SUBCONTRACTOR', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (7, 'LEAD', 'LEAD', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (8, 'PROPOSAL', 'PROPOSAL', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (9, 'CUSTOMER', 'CUSTOMER', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (10, 'WORKORDER', 'WORKORDER', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupMasterEntityType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (11, 'INVOICE', 'INVOICE', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (1, 'BILLING', 'BILLING', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (2, 'SHIPPING', 'SHIPPING', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (3, 'PHYSICAL', 'PHYSICAL', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (4, 'SERVICE', 'SERVICE', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (5, 'MAILING', 'MAILING', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (6, 'HQ', 'HQ', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (7, 'REMITTO', 'REMITTO', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');
INSERT INTO fgs."FSGSetupLocationType" ("Id", "Code", "Name", "IsActive", "CreatedOn")
VALUES (8, 'JOBSITE', 'JOBSITE', TRUE, TIMESTAMPTZ '2026-01-01T00:00:00Z');

SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupBusinessType"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupBusinessType") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupBusinessType"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupTimeCardOption"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupTimeCardOption") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupTimeCardOption"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupAccountingIntegrationType"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupAccountingIntegrationType") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupAccountingIntegrationType"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupLanguage"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupLanguage") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupLanguage"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupMasterEntityType"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupMasterEntityType") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupMasterEntityType"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('fgs."FSGSetupLocationType"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM fgs."FSGSetupLocationType") + 1,
        nextval(pg_get_serial_sequence('fgs."FSGSetupLocationType"', 'Id'))),
    false);

INSERT INTO fgs.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260508175756_InitialCreateWithSetupSeed', '10.0.0');

COMMIT;

