using Fgs.User.Domain.Enums;

namespace Fgs.User.Application.Features.ServiceSetups.Dtos;

public sealed record FgsTenantServiceSetupDetailDto(
    long TenantId,
    long CompanyId,
    TimeCardOption TimeCardOptionId,
    int? AccountingIntegrationTypeId,
    bool UseExternalTaxCalculationProvider,
    bool EnableCallBookingWidget,
    bool EnablePaymentWidget,
    bool EnableCustomerPortal,
    bool EnableRulesManagement,
    bool EnableAutoArrive,
    int? WorkLocationRadiusForAutoArrive,
    TimeSpan? OTStartTime,
    TimeSpan? OTEndTime,
    TimeSpan? DTStartTime,
    TimeSpan? DTEndTime,
    string BillHoursFromDispatchOrArrive,
    bool SourceCodeRequiredOnWorkOrder,
    bool SourceCodeRequiredOnServiceLocation,
    long BillToStartNumber,
    long POStartNumber,
    long QuoteStartNumber,
    long WorkOrderStartNumber,
    string? InvoiceNumberPrefix,
    string? QuoteNumberPrefix,
    string? PONumberPrefix,
    string? WorkOrderNumberPrefix,
    string? InvoiceBatchNumberFormat,
    bool IsActive);

public sealed record FgsTenantServiceSetupUpdateDto(
    TimeCardOption TimeCardOptionId,
    int? AccountingIntegrationTypeId,
    bool UseExternalTaxCalculationProvider,
    bool EnableCallBookingWidget,
    bool EnablePaymentWidget,
    bool EnableCustomerPortal,
    bool EnableRulesManagement,
    bool EnableAutoArrive,
    int? WorkLocationRadiusForAutoArrive,
    TimeSpan? OTStartTime,
    TimeSpan? OTEndTime,
    TimeSpan? DTStartTime,
    TimeSpan? DTEndTime,
    string BillHoursFromDispatchOrArrive,
    bool SourceCodeRequiredOnWorkOrder,
    bool SourceCodeRequiredOnServiceLocation,
    long BillToStartNumber,
    long POStartNumber,
    long QuoteStartNumber,
    long WorkOrderStartNumber,
    string? InvoiceNumberPrefix,
    string? QuoteNumberPrefix,
    string? PONumberPrefix,
    string? WorkOrderNumberPrefix,
    string? InvoiceBatchNumberFormat,
    bool IsActive);

public sealed record FgsTenantServiceSetupPatchDto(
    TimeCardOption? TimeCardOptionId = null,
    int? AccountingIntegrationTypeId = null,
    bool? UseExternalTaxCalculationProvider = null,
    bool? EnableCallBookingWidget = null,
    bool? EnablePaymentWidget = null,
    bool? EnableCustomerPortal = null,
    bool? EnableRulesManagement = null,
    bool? EnableAutoArrive = null,
    int? WorkLocationRadiusForAutoArrive = null,
    TimeSpan? OTStartTime = null,
    TimeSpan? OTEndTime = null,
    TimeSpan? DTStartTime = null,
    TimeSpan? DTEndTime = null,
    string? BillHoursFromDispatchOrArrive = null,
    bool? SourceCodeRequiredOnWorkOrder = null,
    bool? SourceCodeRequiredOnServiceLocation = null,
    long? BillToStartNumber = null,
    long? POStartNumber = null,
    long? QuoteStartNumber = null,
    long? WorkOrderStartNumber = null,
    string? InvoiceNumberPrefix = null,
    string? QuoteNumberPrefix = null,
    string? PONumberPrefix = null,
    string? WorkOrderNumberPrefix = null,
    string? InvoiceBatchNumberFormat = null,
    bool? IsActive = null);
