using Fgs.Setup.Application.Abstractions.BillingCategories;
using Fgs.Setup.Application.Abstractions.SetupPricingMatrices;
using Fgs.Setup.Application.Abstractions.SetupPricingMatrixOthers;
using Fgs.Setup.Application.Features.SetupPricingMatrixOthers.Commands.CreateFgsSetupPricingMatrixOther;
using Fgs.Setup.Application.Features.SetupPricingMatrixOthers.Commands.UpdateFgsSetupPricingMatrixOther;
using Fgs.Setup.Application.Features.SetupPricingMatrixOthers.Commands.PatchFgsSetupPricingMatrixOther;
using FluentValidation;
namespace Fgs.Setup.Application.Features.SetupPricingMatrixOthers.Validators;
public sealed class CreateFgsSetupPricingMatrixOtherCommandValidator:AbstractValidator<CreateFgsSetupPricingMatrixOtherCommand>
{public CreateFgsSetupPricingMatrixOtherCommandValidator(IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixOtherReadRepository r,IBillingCategoryReadRepository b){RuleFor(x=>x.Dto.CategoryCode).NotEmpty().MaximumLength(2).Matches("^[A-Z]{1,2}$");RuleFor(x=>x.Dto.Name).NotEmpty().MaximumLength(200);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0).When(x=>x.Dto.AdjustmentValue.HasValue);RuleFor(x=>x.Dto.DiscountPercent).InclusiveBetween(0,100).When(x=>x.Dto.DiscountPercent.HasValue);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>await Check(d.PricingMatrixId,d.CategoryCode,null,m,r,b,c,ct));}
 internal static async Task Check(long id,string code,long? exclude,IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixOtherReadRepository r,IBillingCategoryReadRepository b,ValidationContext<CreateFgsSetupPricingMatrixOtherCommand> c,CancellationToken ct){var f=await m.GetFlagsByIdAsync(id,ct);if(f is null){c.AddFailure("Dto.PricingMatrixId","The specified pricing matrix was not found.");return;}if(await r.ExistsActiveMaterialTiersForMatrixAsync(id,ct))c.AddFailure("Dto.PricingMatrixId","Other items cannot coexist with active material tiers.");if(f.PriceAdjustmentTypeId<1||f.PriceAdjustmentTypeId>3)c.AddFailure("Dto.PricingMatrixId","Price adjustment type must be between 1 and 3.");if(!await b.ExistsByBillingCategoryTypeAsync(code,true,ct))c.AddFailure("Dto.CategoryCode","The billing category code was not found or is inactive.");if(await r.ExistsByCategoryCodeAsync(id,code,exclude,ct))c.AddFailure("Dto.CategoryCode","Category code must be unique per pricing matrix.");}}
public sealed class UpdateFgsSetupPricingMatrixOtherCommandValidator:AbstractValidator<UpdateFgsSetupPricingMatrixOtherCommand>{public UpdateFgsSetupPricingMatrixOtherCommandValidator(IFgsSetupPricingMatrixReadRepository m,IFgsSetupPricingMatrixOtherReadRepository r,IBillingCategoryReadRepository b){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.CategoryCode).NotEmpty().MaximumLength(2).Matches("^[A-Z]{1,2}$");RuleFor(x=>x.Dto.Name).NotEmpty().MaximumLength(200);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0).When(x=>x.Dto.AdjustmentValue.HasValue);RuleFor(x=>x.Dto.DiscountPercent).InclusiveBetween(0,100).When(x=>x.Dto.DiscountPercent.HasValue);RuleFor(x=>x.Dto).CustomAsync(async(d,c,ct)=>{var f=await m.GetFlagsByIdAsync(d.PricingMatrixId,ct);if(f is null){c.AddFailure("Dto.PricingMatrixId","The specified pricing matrix was not found.");return;}if(await r.ExistsActiveMaterialTiersForMatrixAsync(d.PricingMatrixId,ct))c.AddFailure("Dto.PricingMatrixId","Other items cannot coexist with active material tiers.");if(f.PriceAdjustmentTypeId<1||f.PriceAdjustmentTypeId>3)c.AddFailure("Dto.PricingMatrixId","Price adjustment type must be between 1 and 3.");if(!await b.ExistsByBillingCategoryTypeAsync(d.CategoryCode,true,ct))c.AddFailure("Dto.CategoryCode","The billing category code was not found or is inactive.");if(await r.ExistsByCategoryCodeAsync(d.PricingMatrixId,d.CategoryCode,c.InstanceToValidate.Id,ct))c.AddFailure("Dto.CategoryCode","Category code must be unique per pricing matrix.");});}}
public sealed class PatchFgsSetupPricingMatrixOtherCommandValidator:AbstractValidator<PatchFgsSetupPricingMatrixOtherCommand>{public PatchFgsSetupPricingMatrixOtherCommandValidator(){RuleFor(x=>x.Id).GreaterThan(0);RuleFor(x=>x.Dto.CategoryCode).MaximumLength(2).Matches("^[A-Z]{1,2}$").When(x=>x.Dto.CategoryCode is not null);RuleFor(x=>x.Dto.Name).NotEmpty().MaximumLength(200).When(x=>x.Dto.Name is not null);RuleFor(x=>x.Dto.AdjustmentValue).GreaterThanOrEqualTo(0).When(x=>x.Dto.AdjustmentValue.HasValue);RuleFor(x=>x.Dto.DiscountPercent).InclusiveBetween(0,100).When(x=>x.Dto.DiscountPercent.HasValue);}}
