CREATE DATABASE fgs_user;
CREATE DATABASE fgs_job;
CREATE DATABASE fgs_notification;

GRANT ALL PRIVILEGES ON DATABASE fgs_user TO fgs;
GRANT ALL PRIVILEGES ON DATABASE fgs_job TO fgs;
GRANT ALL PRIVILEGES ON DATABASE fgs_notification TO fgs;
