using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fgs.Setup.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class RefactorPricingMatrixAndAddLeadEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_FgsTagEntityType_GloMasterEntityType_MasterEntityTypeId",
                schema: "setup",
                table: "FgsTagEntityType");

            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixLaborTier"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixLabor"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixMaterialTier"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixOther"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrix"" CASCADE;");


            migrationBuilder.Sql(@"
-- Recreates pricing matrix tables with bigint identity keys (run as part of RefactorPricingMatrixAndAddLeadEntities migration)

CREATE TABLE setup.""FgsSetupPricingMatrix""
(
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" bigint NOT NULL,
    ""CompanyId"" bigint NOT NULL,
    ""Code"" varchar(50) NOT NULL,
    ""Name"" varchar(200) NOT NULL,
    ""IsLaborTierStructure"" boolean NOT NULL DEFAULT false,
    ""IsLaborRateBySkillLevel"" boolean NOT NULL DEFAULT false,
    ""EffectiveFrom"" date NOT NULL,
    ""EffectiveTo"" date NULL,
    ""IsMobileVisible"" boolean NOT NULL DEFAULT true,
    ""CreatedOn"" timestamptz NOT NULL DEFAULT now(),
    ""CreatedBy"" varchar(100) NULL,
    ""UpdatedOn"" timestamptz NULL,
    ""UpdatedBy"" varchar(100) NULL,
    ""IsActive"" boolean NOT NULL DEFAULT true,
    CONSTRAINT ""PK_FgsSetupPricingMatrix"" PRIMARY KEY (""Id""),
    CONSTRAINT ""UQ_FgsSetupPricingMatrix_TenantId_CompanyId_Code"" UNIQUE (""TenantId"", ""CompanyId"", ""Code""),
    CONSTRAINT ""CK_FgsSetupPricingMatrix_EffectiveDates"" CHECK (""EffectiveTo"" IS NULL OR ""EffectiveTo"" >= ""EffectiveFrom""),
    CONSTRAINT ""FK_FgsSetupPricingMatrix_FgsTenantCompanyCache_TenantId_CompanyId"" FOREIGN KEY (""TenantId"", ""CompanyId"") REFERENCES setup.""FgsTenantCompanyCache"" (""TenantId"", ""CompanyId"") ON DELETE RESTRICT
);

CREATE INDEX ""IX_FgsSetupPricingMatrix_TenantId_CompanyId_Name"" ON setup.""FgsSetupPricingMatrix"" (""TenantId"", ""CompanyId"", ""Name"");
CREATE INDEX ""IX_FgsSetupPricingMatrix_TenantId_CompanyId_IsActive"" ON setup.""FgsSetupPricingMatrix"" (""TenantId"", ""CompanyId"", ""IsActive"");

CREATE TABLE setup.""FgsSetupPricingMatrixLabor""
(
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" bigint NOT NULL,
    ""CompanyId"" bigint NOT NULL,
    ""PricingMatrixId"" bigint NOT NULL,
    ""LaborRateTypeId"" integer NOT NULL,
    ""TechSkillLevelId"" bigint NULL,
    ""BaseRate"" numeric(18,2) NOT NULL,
    ""OvertimeMultiplier"" numeric(18,2) NULL,
    ""DoubleTimeMultiplier"" numeric(18,2) NULL,
    ""DiscountPercent"" numeric(18,2) NULL,
    ""CreatedOn"" timestamptz NOT NULL DEFAULT now(),
    ""CreatedBy"" varchar(100) NULL,
    ""UpdatedOn"" timestamptz NULL,
    ""UpdatedBy"" varchar(100) NULL,
    ""IsActive"" boolean NOT NULL DEFAULT true,
    CONSTRAINT ""PK_FgsSetupPricingMatrixLabor"" PRIMARY KEY (""Id""),
    CONSTRAINT ""UQ_FgsSetupPricingMatrixLabor"" UNIQUE (""TenantId"", ""CompanyId"", ""PricingMatrixId"", ""LaborRateTypeId"", ""TechSkillLevelId""),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLabor_BaseRate"" CHECK (""BaseRate"" >= 0),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLabor_DiscountPercent"" CHECK (""DiscountPercent"" IS NULL OR (""DiscountPercent"" >= 0 AND ""DiscountPercent"" <= 100)),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLabor_OvertimeMultiplier"" CHECK (""OvertimeMultiplier"" IS NULL OR ""OvertimeMultiplier"" >= 1),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLabor_DoubleTimeMultiplier"" CHECK (""DoubleTimeMultiplier"" IS NULL OR ""DoubleTimeMultiplier"" >= 1),
    CONSTRAINT ""FK_FgsSetupPricingMatrixLabor_FgsTenantCompanyCache_TenantId_CompanyId"" FOREIGN KEY (""TenantId"", ""CompanyId"") REFERENCES setup.""FgsTenantCompanyCache"" (""TenantId"", ""CompanyId"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_FgsSetupPricingMatrixLabor_PricingMatrix"" FOREIGN KEY (""PricingMatrixId"") REFERENCES setup.""FgsSetupPricingMatrix"" (""Id"") ON DELETE CASCADE,
    CONSTRAINT ""FK_FgsSetupPricingMatrixLabor_LaborRateType"" FOREIGN KEY (""LaborRateTypeId"") REFERENCES glo.""GloSetupLaborRateType"" (""Id"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_FgsSetupPricingMatrixLabor_TechSkillLevel"" FOREIGN KEY (""TechSkillLevelId"") REFERENCES setup.""FgsSetupTechSkillLevel"" (""Id"") ON DELETE RESTRICT
);

CREATE INDEX ""IX_FgsSetupPricingMatrixLabor_TenantId_CompanyId_PricingMatrixId"" ON setup.""FgsSetupPricingMatrixLabor"" (""TenantId"", ""CompanyId"", ""PricingMatrixId"");
CREATE INDEX ""IX_FgsSetupPricingMatrixLabor_TenantId_CompanyId_LaborRateTypeId"" ON setup.""FgsSetupPricingMatrixLabor"" (""TenantId"", ""CompanyId"", ""LaborRateTypeId"");
CREATE INDEX ""IX_FgsSetupPricingMatrixLabor_TenantId_CompanyId_TechSkillLevelId"" ON setup.""FgsSetupPricingMatrixLabor"" (""TenantId"", ""CompanyId"", ""TechSkillLevelId"");

CREATE TABLE setup.""FgsSetupPricingMatrixLaborTier""
(
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" bigint NOT NULL,
    ""CompanyId"" bigint NOT NULL,
    ""PricingMatrixLaborId"" bigint NOT NULL,
    ""SequenceOrder"" smallint NOT NULL,
    ""DurationMinutes"" integer NOT NULL,
    ""Rate"" numeric(18,2) NOT NULL,
    ""CreatedOn"" timestamptz NOT NULL DEFAULT now(),
    ""CreatedBy"" varchar(100) NULL,
    ""UpdatedOn"" timestamptz NULL,
    ""UpdatedBy"" varchar(100) NULL,
    ""IsActive"" boolean NOT NULL DEFAULT true,
    CONSTRAINT ""PK_FgsSetupPricingMatrixLaborTier"" PRIMARY KEY (""Id""),
    CONSTRAINT ""UQ_FgsSetupPricingMatrixLaborTier_PricingMatrixLaborId_SequenceOrder"" UNIQUE (""TenantId"", ""CompanyId"", ""PricingMatrixLaborId"", ""SequenceOrder""),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLaborTier_DurationMinutes"" CHECK (""DurationMinutes"" > 0),
    CONSTRAINT ""CK_FgsSetupPricingMatrixLaborTier_Rate"" CHECK (""Rate"" >= 0),
    CONSTRAINT ""FK_FgsSetupPricingMatrixLaborTier_FgsTenantCompanyCache_TenantId_CompanyId"" FOREIGN KEY (""TenantId"", ""CompanyId"") REFERENCES setup.""FgsTenantCompanyCache"" (""TenantId"", ""CompanyId"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_FgsSetupPricingMatrixLaborTier_PricingMatrixLabor"" FOREIGN KEY (""PricingMatrixLaborId"") REFERENCES setup.""FgsSetupPricingMatrixLabor"" (""Id"") ON DELETE CASCADE
);

CREATE INDEX ""IX_FgsSetupPricingMatrixLaborTier_TenantId_CompanyId_PricingMatrixLaborId"" ON setup.""FgsSetupPricingMatrixLaborTier"" (""TenantId"", ""CompanyId"", ""PricingMatrixLaborId"");
CREATE INDEX ""IX_FgsSetupPricingMatrixLaborTier_TenantId_CompanyId_IsActive"" ON setup.""FgsSetupPricingMatrixLaborTier"" (""TenantId"", ""CompanyId"", ""IsActive"");

CREATE TABLE setup.""FgsSetupPricingMatrixMaterialTier""
(
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" bigint NOT NULL,
    ""CompanyId"" bigint NOT NULL,
    ""PricingMatrixId"" bigint NOT NULL,
    ""FromCost"" numeric(18,2) NOT NULL,
    ""ToCost"" numeric(18,2) NULL,
    ""AdjustmentValue"" numeric(18,6) NOT NULL DEFAULT 0,
    ""PriceAdjustmentTypeId"" smallint NOT NULL,
    ""CreatedOn"" timestamptz NOT NULL DEFAULT now(),
    ""CreatedBy"" varchar(100) NULL,
    ""UpdatedOn"" timestamptz NULL,
    ""UpdatedBy"" varchar(100) NULL,
    ""IsActive"" boolean NOT NULL DEFAULT true,
    CONSTRAINT ""PK_FgsSetupPricingMatrixMaterialTier"" PRIMARY KEY (""Id""),
    CONSTRAINT ""UQ_FgsSetupPricingMatrixMaterialTier_Matrix_FromCost"" UNIQUE (""TenantId"", ""CompanyId"", ""PricingMatrixId"", ""FromCost""),
    CONSTRAINT ""CK_FgsSetupPricingMatrixMaterialTier_FromCost"" CHECK (""FromCost"" >= 0),
    CONSTRAINT ""CK_FgsSetupPricingMatrixMaterialTier_ToCost"" CHECK (""ToCost"" IS NULL OR ""ToCost"" >= ""FromCost""),
    CONSTRAINT ""CK_FgsSetupPricingMatrixMaterialTier_AdjustmentValue"" CHECK (""AdjustmentValue"" >= 0),
    CONSTRAINT ""CK_FgsSetupPricingMatrixMaterialTier_PriceAdjustmentTypeId"" CHECK (""PriceAdjustmentTypeId"" BETWEEN 1 AND 3),
    CONSTRAINT ""FK_FgsSetupPricingMatrixMaterialTier_FgsTenantCompanyCache_TenantId_CompanyId"" FOREIGN KEY (""TenantId"", ""CompanyId"") REFERENCES setup.""FgsTenantCompanyCache"" (""TenantId"", ""CompanyId"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_FgsSetupPricingMatrixMaterialTier_PricingMatrix"" FOREIGN KEY (""PricingMatrixId"") REFERENCES setup.""FgsSetupPricingMatrix"" (""Id"") ON DELETE CASCADE
);

COMMENT ON TABLE setup.""FgsSetupPricingMatrixMaterialTier"" IS 'Defines material cost tiers and pricing adjustments used by a pricing matrix. Each tier applies a single pricing adjustment method to determine the selling price from material cost.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixMaterialTier"".""PricingMatrixId"" IS 'Reference to the pricing matrix that contains this tier.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixMaterialTier"".""FromCost"" IS 'Inclusive minimum material cost for this pricing tier.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixMaterialTier"".""ToCost"" IS 'Inclusive maximum material cost for this pricing tier. NULL indicates no upper limit.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixMaterialTier"".""AdjustmentValue"" IS 'Value used by the selected pricing adjustment type. Examples: 25 = 25% markup, 150 = fixed dollar markup, 1.75 = multiplier.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixMaterialTier"".""PriceAdjustmentTypeId"" IS 'Pricing adjustment method. Valid values: 1=Markup Percent, 2=Markup Amount, 3=Multiplier.';

CREATE INDEX ""IX_FgsSetupPricingMatrixMaterialTier_TenantId_CompanyId_PricingMatrixId"" ON setup.""FgsSetupPricingMatrixMaterialTier"" (""TenantId"", ""CompanyId"", ""PricingMatrixId"");
CREATE INDEX ""IX_FgsSetupPricingMatrixMaterialTier_TenantId_CompanyId_PriceAdjustmentTypeId"" ON setup.""FgsSetupPricingMatrixMaterialTier"" (""TenantId"", ""CompanyId"", ""PriceAdjustmentTypeId"");

CREATE TABLE setup.""FgsSetupPricingMatrixOther""
(
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""TenantId"" bigint NOT NULL,
    ""CompanyId"" bigint NOT NULL,
    ""PricingMatrixId"" bigint NOT NULL,
    ""CategoryCode"" varchar(50) NOT NULL,
    ""Name"" varchar(200) NOT NULL,
    ""MarkupPercent"" numeric(18,2) NULL,
    ""DiscountPercent"" numeric(18,2) NULL,
    ""CreatedOn"" timestamptz NOT NULL DEFAULT now(),
    ""CreatedBy"" varchar(100) NULL,
    ""UpdatedOn"" timestamptz NULL,
    ""UpdatedBy"" varchar(100) NULL,
    ""IsActive"" boolean NOT NULL DEFAULT true,
    CONSTRAINT ""PK_FgsSetupPricingMatrixOther"" PRIMARY KEY (""Id""),
    CONSTRAINT ""UQ_FgsSetupPricingMatrixOther"" UNIQUE (""TenantId"", ""CompanyId"", ""PricingMatrixId"", ""CategoryCode""),
    CONSTRAINT ""CK_FgsSetupPricingMatrixOther_MarkupPercent"" CHECK (""MarkupPercent"" IS NULL OR ""MarkupPercent"" >= 0),
    CONSTRAINT ""CK_FgsSetupPricingMatrixOther_DiscountPercent"" CHECK (""DiscountPercent"" IS NULL OR (""DiscountPercent"" >= 0 AND ""DiscountPercent"" <= 100)),
    CONSTRAINT ""FK_FgsSetupPricingMatrixOther_FgsTenantCompanyCache_TenantId_CompanyId"" FOREIGN KEY (""TenantId"", ""CompanyId"") REFERENCES setup.""FgsTenantCompanyCache"" (""TenantId"", ""CompanyId"") ON DELETE RESTRICT,
    CONSTRAINT ""FK_FgsSetupPricingMatrixOther_PricingMatrix"" FOREIGN KEY (""PricingMatrixId"") REFERENCES setup.""FgsSetupPricingMatrix"" (""Id"") ON DELETE CASCADE
);

COMMENT ON TABLE setup.""FgsSetupPricingMatrixOther"" IS 'Stores pricing adjustments for miscellaneous categories such as permits, disposal fees, equipment rentals, trip charges, crane services, and other non-material/non-labor costs.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixOther"".""PricingMatrixId"" IS 'Reference to the pricing matrix.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixOther"".""CategoryCode"" IS 'Unique category code within the pricing matrix.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixOther"".""Name"" IS 'User-friendly category name.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixOther"".""MarkupPercent"" IS 'Markup percentage applied to the base cost.';
COMMENT ON COLUMN setup.""FgsSetupPricingMatrixOther"".""DiscountPercent"" IS 'Optional discount percentage applied after markup.';

CREATE INDEX ""IX_FgsSetupPricingMatrixOther_TenantId_CompanyId_PricingMatrixId"" ON setup.""FgsSetupPricingMatrixOther"" (""TenantId"", ""CompanyId"", ""PricingMatrixId"");
CREATE INDEX ""IX_FgsSetupPricingMatrixOther_TenantId_CompanyId_IsActive"" ON setup.""FgsSetupPricingMatrixOther"" (""TenantId"", ""CompanyId"", ""IsActive"");
");

            migrationBuilder.CreateTable(
                name: "FgsLeadDisqualificationReason",
                schema: "setup",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    TenantId = table.Column<long>(type: "bigint", nullable: false),
                    CompanyId = table.Column<long>(type: "bigint", nullable: false),
                    ReasonCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false, comment: "Unique business code for the disqualification reason within a company."),
                    ReasonName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "User-friendly name displayed throughout the application."),
                    Description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true, comment: "Optional description explaining the reason."),
                    DisplayOrder = table.Column<short>(type: "smallint", nullable: false, defaultValue: (short)1, comment: "Controls the order in which reasons are displayed in dropdowns and lists."),
                    IsSystem = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false, comment: "Indicates whether the reason was seeded by the system or created by a user."),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true, comment: "Indicates whether the reason is available for selection."),
                    CreatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false, defaultValueSql: "now()"),
                    CreatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    UpdatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    UpdatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FgsLeadDisqualificationReason", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FgsLeadDisqualificationReason_FgsTenantCompanyCache_TenantId_CompanyId",
                        columns: x => new { x.TenantId, x.CompanyId },
                        principalSchema: "setup",
                        principalTable: "FgsTenantCompanyCache",
                        principalColumns: new[] { "TenantId", "CompanyId" },
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Stores tenant/company specific lead disqualification reasons used when leads are marked as disqualified.");

            migrationBuilder.CreateTable(
                name: "FgsLeadStatus",
                schema: "setup",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    TenantId = table.Column<long>(type: "bigint", nullable: false, comment: "Identifier of the tenant that owns the lead status."),
                    CompanyId = table.Column<long>(type: "bigint", nullable: false, comment: "Identifier of the company that owns the lead status."),
                    StatusCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false, comment: "Unique business code for the lead status within a company. Examples: NEW, CONTACTED, QUALIFIED, CONVERTED."),
                    StatusName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "User-friendly name displayed throughout the application."),
                    Description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true, comment: "Optional description explaining the purpose of the lead status."),
                    DisplayOrder = table.Column<short>(type: "smallint", nullable: false, defaultValue: (short)1, comment: "Determines the order in which statuses appear in dropdowns, lists, and reports."),
                    IsSystem = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false, comment: "Indicates whether the record was seeded by the system or created by a user."),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true, comment: "Indicates whether the status is available for selection and use."),
                    CreatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false, defaultValueSql: "now()", comment: "Date and time when the record was created."),
                    CreatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true, comment: "User who created the record."),
                    UpdatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true, comment: "Date and time when the record was last updated."),
                    UpdatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true, comment: "User who last updated the record.")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FgsLeadStatus", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FgsLeadStatus_FgsTenantCompanyCache_TenantId_CompanyId",
                        columns: x => new { x.TenantId, x.CompanyId },
                        principalSchema: "setup",
                        principalTable: "FgsTenantCompanyCache",
                        principalColumns: new[] { "TenantId", "CompanyId" },
                        onDelete: ReferentialAction.Restrict);
                },
                comment: "Stores tenant/company specific lead statuses used in the CRM lead lifecycle. Seeded from glo.GloLeadStatus during onboarding and may be customized by users.");

            migrationBuilder.CreateTable(
                name: "GloLeadDisqualificationReason",
                schema: "glo",
                columns: table => new
                {
                    Id = table.Column<short>(type: "smallint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ReasonCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false, comment: "Unique business code for the disqualification reason."),
                    ReasonName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, comment: "User-friendly name displayed throughout the application."),
                    Description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true, comment: "Optional description explaining the reason."),
                    DisplayOrder = table.Column<short>(type: "smallint", nullable: false, defaultValue: (short)1, comment: "Controls the order in which reasons are displayed."),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true, comment: "Indicates whether the reason is available for seeding and use."),
                    CreatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false, defaultValueSql: "now()"),
                    UpdatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    CreatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    UpdatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GloLeadDisqualificationReason", x => x.Id);
                },
                comment: "Master list of lead disqualification reasons used to seed tenant-specific records into setup.FgsLeadDisqualificationReason.");

            migrationBuilder.CreateTable(
                name: "GloLeadStatus",
                schema: "glo",
                columns: table => new
                {
                    Id = table.Column<short>(type: "smallint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    StatusCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    StatusName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Description = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    DisplayOrder = table.Column<short>(type: "smallint", nullable: false, defaultValue: (short)1),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    CreatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false, defaultValueSql: "now()"),
                    UpdatedOn = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    CreatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    UpdatedBy = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GloLeadStatus", x => x.Id);
                });


            migrationBuilder.CreateIndex(
                name: "IX_FgsLeadDisqualificationReason_TenantId_CompanyId",
                schema: "setup",
                table: "FgsLeadDisqualificationReason",
                columns: new[] { "TenantId", "CompanyId" });

            migrationBuilder.CreateIndex(
                name: "IX_FgsLeadDisqualificationReason_TenantId_CompanyId_DisplayOrder",
                schema: "setup",
                table: "FgsLeadDisqualificationReason",
                columns: new[] { "TenantId", "CompanyId", "DisplayOrder" });

            migrationBuilder.CreateIndex(
                name: "UX_FgsLeadDisqualificationReason_TenantId_CompanyId_ReasonCode",
                schema: "setup",
                table: "FgsLeadDisqualificationReason",
                columns: new[] { "TenantId", "CompanyId", "ReasonCode" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "UX_FgsLeadDisqualificationReason_TenantId_CompanyId_ReasonName",
                schema: "setup",
                table: "FgsLeadDisqualificationReason",
                columns: new[] { "TenantId", "CompanyId", "ReasonName" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FgsLeadStatus_TenantId_CompanyId_DisplayOrder",
                schema: "setup",
                table: "FgsLeadStatus",
                columns: new[] { "TenantId", "CompanyId", "DisplayOrder" });

            migrationBuilder.CreateIndex(
                name: "UX_FgsLeadStatus_TenantId_CompanyId_StatusCode",
                schema: "setup",
                table: "FgsLeadStatus",
                columns: new[] { "TenantId", "CompanyId", "StatusCode" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "UX_FgsLeadStatus_TenantId_CompanyId_StatusName",
                schema: "setup",
                table: "FgsLeadStatus",
                columns: new[] { "TenantId", "CompanyId", "StatusName" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GloLeadDisqualificationReason_DisplayOrder",
                schema: "glo",
                table: "GloLeadDisqualificationReason",
                column: "DisplayOrder");

            migrationBuilder.CreateIndex(
                name: "UX_GloLeadDisqualificationReason_ReasonCode",
                schema: "glo",
                table: "GloLeadDisqualificationReason",
                column: "ReasonCode",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "UX_GloLeadDisqualificationReason_ReasonName",
                schema: "glo",
                table: "GloLeadDisqualificationReason",
                column: "ReasonName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_GloLeadStatus_DisplayOrder",
                schema: "glo",
                table: "GloLeadStatus",
                column: "DisplayOrder");

            migrationBuilder.CreateIndex(
                name: "UX_GloLeadStatus_StatusCode",
                schema: "glo",
                table: "GloLeadStatus",
                column: "StatusCode",
                unique: true);

        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FgsLeadDisqualificationReason",
                schema: "setup");

            migrationBuilder.DropTable(
                name: "FgsLeadStatus",
                schema: "setup");

            migrationBuilder.DropTable(
                name: "GloLeadDisqualificationReason",
                schema: "glo");

            migrationBuilder.DropTable(
                name: "GloLeadStatus",
                schema: "glo");

            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixLaborTier"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixLabor"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixMaterialTier"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrixOther"" CASCADE;
DROP TABLE IF EXISTS setup.""FgsSetupPricingMatrix"" CASCADE;");

            migrationBuilder.AddForeignKey(
                name: "FK_FgsTagEntityType_GloMasterEntityType_MasterEntityTypeId",
                schema: "setup",
                table: "FgsTagEntityType",
                column: "MasterEntityTypeId",
                principalSchema: "glo",
                principalTable: "GloMasterEntityType",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
