select  * from setup."FgsUniversalPricingService"
select  * from setup."FgsUniversalMatrixAddOn"
select   * from setup."FgsUniversalMatrixFrequencyDiscount"
select   * from setup."FgsUniversalMatrixItem"
select   * from setup."FgsUniversalMatrixOneTimeFee"
select   * from setup."FgsUniversalMatrixSizeTier"
select   * from setup."FgsUniversalMatrixTier"
select * from setup."FgsSetupTechSkillLevel"

select   * from setup."FgsSetupPricingMatrix" 
select   * from setup."FgsSetupPricingMatrixLabor"
select   * from setup."FgsSetupPricingMatrixLaborTier"
select   * from setup."FgsSetupPricingMatrixMaterialTier"
select   * from setup."FgsSetupPricingMatrixOther"

select   * from  asset."FgsServiceLocationCache"
select   * from setup."FgsSetupLaborRateType"
select   * from setup."FgsVehicle"
select   * from setup."FgsBillingCategory"
select   * from inventory."FgsInventoryLocation"
setup."FgsSetupTimeSlot"
select   * from audit."FgsCredentialAudit"
select * from glo."GloRole"
select * from identity."FgsRole"
select * from identity."FgsUser"
select * from  identity."FgsUserRole"
select * from  setup."FgsUniversalMatrixItem"