<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fgs.Communication.Application\Fgs.Communication.Application.csproj" />
    <ProjectReference Include="..\Fgs.Communication.Domain\Fgs.Communication.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Security\Fgs.Security\Fgs.Security.csproj" />
    <ProjectReference Include="..\..\Shared\Credentials\Fgs.Credentials\Fgs.Credentials.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Seed\" />
  </ItemGroup>

</Project>
