upstream user_service {
    least_conn;
    zone user_service 128k;
    server user-service:5001 max_fails=3 fail_timeout=10s;
    keepalive 128;
}

upstream notification_service {
    least_conn;
    zone notification_service 128k;
    server notification-service:5002 max_fails=3 fail_timeout=10s;
    keepalive 128;
}

upstream setup_service {
    least_conn;
    zone setup_service 128k;
    server setup-service:5004 max_fails=3 fail_timeout=10s;
    keepalive 128;
}

upstream file_service {
    least_conn;
    zone file_service 128k;
    server file-service:5005 max_fails=3 fail_timeout=10s;
    keepalive 128;
}

upstream audit_service {
    least_conn;
    zone audit_service 128k;
    server audit-service:5008 max_fails=3 fail_timeout=10s;
    keepalive 128;
}

upstream inventory_service {
    least_conn;
    zone inventory_service 128k;
    server inventory-service:5012 max_fails=3 fail_timeout=10s;
    keepalive 128;
}
