upstream user_service {
    least_conn;
    server user-service:5001 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream notification_service {
    least_conn;
    server notification-service:5002 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream setup_service {
    least_conn;
    server setup-service:5004 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream file_service {
    least_conn;
    server file-service:5005 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream audit_service {
    least_conn;
    server audit-service:5008 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream inventory_service {
    least_conn;
    server inventory-service:5012 max_fails=3 fail_timeout=10s;
    keepalive 32;
}
