START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    ALTER TABLE tenant."FgsTenantServiceSetup" ADD "AutoBookMaintenanceScheduleCalls" boolean NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN tenant."FgsTenantServiceSetup"."AutoBookMaintenanceScheduleCalls" IS 'Controls whether maintenance schedule calls are automatically booked. TRUE = maintenance schedule calls are automatically booked; FALSE = maintenance schedule calls must be booked manually.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE TABLE identity."FgsRoleMenu" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RoleId" bigint NOT NULL,
        "MenuId" integer NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsRoleMenu" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsRoleMenu_FgsRole" FOREIGN KEY ("RoleId") REFERENCES identity."FgsRole" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsRoleMenu_FgsTenantCompanyCache" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES identity."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE identity."FgsRoleMenu" IS 'Stores the menu items assigned to each role within a tenant company and defines which navigation items the role can access.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."Id" IS 'Unique identifier for the role menu assignment.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."TenantId" IS 'Tenant that owns the role menu assignment.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."CompanyId" IS 'Company within the tenant that owns the role menu assignment.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."RoleId" IS 'Role that is granted access to the menu item.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."MenuId" IS 'Global menu item that the role is allowed to access.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."DisplayOrder" IS 'Controls the display order of the menu item for the role.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."CreatedOn" IS 'Date and time the role menu assignment was created.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."CreatedBy" IS 'User or system that created the role menu assignment.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."UpdatedOn" IS 'Date and time the role menu assignment was last modified.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."UpdatedBy" IS 'User or system that last modified the role menu assignment.';
    COMMENT ON COLUMN identity."FgsRoleMenu"."IsActive" IS 'Indicates whether the role currently has access to the menu item.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE TABLE identity."FgsTenantMenu" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "MenuId" integer NOT NULL,
        "DisplayOrder" smallint NOT NULL DEFAULT 1,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsTenantMenu" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsTenantMenu_FgsTenantCompanyCache" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES identity."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE identity."FgsTenantMenu" IS 'Stores the menu items enabled for a company within a tenant based on the tenant subscription and available platform features.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."Id" IS 'Unique identifier for the tenant menu assignment.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."TenantId" IS 'Tenant that owns the menu assignment.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."CompanyId" IS 'Company within the tenant that receives the menu item.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."MenuId" IS 'Global menu item assigned to the tenant company.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."DisplayOrder" IS 'Controls the display order of the menu item for the tenant company.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."CreatedOn" IS 'Date and time the tenant menu assignment was created.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."CreatedBy" IS 'User or system that created the tenant menu assignment.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."UpdatedOn" IS 'Date and time the tenant menu assignment was last modified.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."UpdatedBy" IS 'User or system that last modified the tenant menu assignment.';
    COMMENT ON COLUMN identity."FgsTenantMenu"."IsActive" IS 'Indicates whether the menu item is currently available to the tenant company.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE INDEX "IX_FgsRoleMenu_RoleId" ON identity."FgsRoleMenu" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE INDEX "IX_FgsRoleMenu_TenantId_CompanyId_RoleId_IsActive" ON identity."FgsRoleMenu" ("TenantId", "CompanyId", "RoleId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE UNIQUE INDEX "IX_FgsRoleMenu_TenantId_CompanyId_RoleId_MenuId" ON identity."FgsRoleMenu" ("TenantId", "CompanyId", "RoleId", "MenuId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE INDEX "IX_FgsTenantMenu_TenantId_CompanyId_IsActive" ON identity."FgsTenantMenu" ("TenantId", "CompanyId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    CREATE UNIQUE INDEX "IX_FgsTenantMenu_TenantId_CompanyId_MenuId" ON identity."FgsTenantMenu" ("TenantId", "CompanyId", "MenuId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260831175851_AddTenantRoleMenusAndAutoBookMaintenance') THEN
    INSERT INTO identity."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831175851_AddTenantRoleMenusAndAutoBookMaintenance', '10.0.8');
    END IF;
END $EF$;
COMMIT;

