DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
        CREATE SCHEMA identity;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS identity."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tenant') THEN
            CREATE SCHEMA tenant;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE tenant."FgsLocation" (
        "Id" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "MasterEntityTypeId" integer NOT NULL,
        "EntityNumber" bigint,
        "AddressLine1" character varying(200),
        "AddressLine2" character varying(200),
        "AddressLine3" character varying(200),
        "AddressLine4" character varying(200),
        "City" character varying(100),
        "State" character varying(100),
        "County" character varying(100),
        "Country" character varying(100),
        "PostalCode" character varying(20),
        "FormattedAddress" character varying(1000),
        "Latitude" numeric(18,10),
        "Longitude" numeric(18,10),
        "PlaceId" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsLocation" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE identity."FgsRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RoleCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "GloRoleId" smallint,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsRole" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE tenant."FgsTenant" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantGuid" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "FgsTenantStatusId" smallint NOT NULL DEFAULT 1,
        "TenantCode" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LegalName" character varying(300),
        "Email" character varying(300),
        "PhoneNumber" character varying(50),
        "Website" character varying(500),
        "PhysicalLocationId" uuid,
        "BillingLocationId" uuid,
        "SubscriptionPlanId" integer,
        "TimeZone" character varying(100),
        "DefaultCurrency" character varying(20),
        "DefaultLanguageId" integer,
        "IsActive" boolean NOT NULL,
        "StorageBucketName" character varying(255),
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenant" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE tenant."FgsTenantCompany" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyNumber" bigint NOT NULL,
        "BusinessTypeId" integer NOT NULL,
        "CompanySize" character varying(20),
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LegalName" character varying(300),
        "Email" character varying(300),
        "PhoneNumber" character varying(50),
        "Website" character varying(500),
        "TaxId" character varying(100),
        "PhysicalLocationId" uuid,
        "BillingLocationId" uuid,
        "FullLogoUrl" character varying(1000),
        "CompactLogoUrl" character varying(1000),
        "IconLogoUrl" character varying(1000),
        "FaviconUrl" character varying(1000),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenantCompany" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_FgsTenantCompany_TenantId_CompanyGuid" UNIQUE ("TenantId", "CompanyGuid"),
        CONSTRAINT "UX_Company_Tenant_Code" UNIQUE ("TenantId", "Code"),
        CONSTRAINT "UX_Company_Tenant_CompanyNumber" UNIQUE ("TenantId", "CompanyNumber")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE tenant."FgsTenantServiceSetup" (
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloTimeCardOptionId" integer NOT NULL,
        "AccountingIntegrationTypeId" integer,
        "UseExternalTaxCalculationProvider" boolean NOT NULL,
        "EnableCallBookingWidget" boolean NOT NULL,
        "EnablePaymentWidget" boolean NOT NULL,
        "EnableCustomerPortal" boolean NOT NULL,
        "EnableRulesManagement" boolean NOT NULL,
        "EnableAutoArrive" boolean NOT NULL,
        "WorkLocationRadiusForAutoArrive" integer,
        "OTStartTime" interval,
        "OTEndTime" interval,
        "DTStartTime" interval,
        "DTEndTime" interval,
        "BillHoursFromDispatchOrArrive" character varying(20) NOT NULL,
        "SourceCodeRequiredOnWorkOrder" boolean NOT NULL,
        "SourceCodeRequiredOnServiceLocation" boolean NOT NULL,
        "BillToStartNumber" bigint NOT NULL,
        "POStartNumber" bigint NOT NULL,
        "QuoteStartNumber" bigint NOT NULL,
        "WorkOrderStartNumber" bigint NOT NULL,
        "InvoiceNumberPrefix" character varying(20),
        "QuoteNumberPrefix" character varying(20),
        "PONumberPrefix" character varying(20),
        "WorkOrderNumberPrefix" character varying(20),
        "InvoiceBatchNumberFormat" character varying(200),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenantServiceSetup" PRIMARY KEY ("TenantId", "CompanyId"),
        CONSTRAINT "CK_FgsTenantServiceSetup_DTRange" CHECK ("DTStartTime" IS NULL OR "DTEndTime" IS NULL OR "DTEndTime" > "DTStartTime"),
        CONSTRAINT "CK_FgsTenantServiceSetup_OTRange" CHECK ("OTStartTime" IS NULL OR "OTEndTime" IS NULL OR "OTEndTime" > "OTStartTime"),
        CONSTRAINT "CK_FgsTenantServiceSetup_WorkLocationRadius" CHECK ("WorkLocationRadiusForAutoArrive" IS NULL OR "WorkLocationRadiusForAutoArrive" >= 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE identity."FgsUser" (
        "Id" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Email" character varying(300) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "EntraObjectId" character varying(100),
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsUser" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsUser_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES tenant."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUser_FgsTenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES tenant."FgsTenant" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE identity."FgsInvitation" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "Email" character varying(300) NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "ExpiresAtUtc" timestamptz NOT NULL,
        "AcceptedAtUtc" timestamptz,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsInvitation" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsInvitation_FgsUser_UserId" FOREIGN KEY ("UserId") REFERENCES identity."FgsUser" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE TABLE identity."FgsUserRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloRoleId" smallint,
        "FgsRoleId" bigint,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_FgsUserRole" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsUserRole_OnlyOneRole" CHECK (("GloRoleId" IS NOT NULL AND "FgsRoleId" IS NULL) OR ("GloRoleId" IS NULL AND "FgsRoleId" IS NOT NULL)),
        CONSTRAINT "FK_FgsUserRole_FgsRole_FgsRoleId" FOREIGN KEY ("FgsRoleId") REFERENCES identity."FgsRole" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUserRole_FgsUser_UserId" FOREIGN KEY ("UserId") REFERENCES identity."FgsUser" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsInvitation_TenantId_Email_Status" ON identity."FgsInvitation" ("TenantId", "Email", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsInvitation_TokenHash" ON identity."FgsInvitation" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsInvitation_UserId" ON identity."FgsInvitation" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsLocation_Tenant_Company_Entity" ON tenant."FgsLocation" ("TenantId", "CompanyId", "MasterEntityTypeId", "EntityNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsRole_TenantId_CompanyId_RoleCode" ON identity."FgsRole" ("TenantId", "CompanyId", "RoleCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsTenant_TenantCode" ON tenant."FgsTenant" ("TenantCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsTenant_TenantGuid" ON tenant."FgsTenant" ("TenantGuid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsUser_TenantId_CompanyId" ON identity."FgsUser" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsUser_TenantId_Email" ON identity."FgsUser" ("TenantId", "Email") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsUserRole_FgsRoleId" ON identity."FgsUserRole" ("FgsRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsUserRole_GloRoleId" ON identity."FgsUserRole" ("GloRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsUserRole_TenantId_CompanyId" ON identity."FgsUserRole" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE INDEX "IX_FgsUserRole_UserId" ON identity."FgsUserRole" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_FgsRoleId" ON identity."FgsUserRole" ("UserId", "FgsRoleId") WHERE "FgsRoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_GloRoleId" ON identity."FgsUserRole" ("UserId", "GloRoleId") WHERE "GloRoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260603225414_InitialIdentityTenant') THEN
    INSERT INTO identity."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603225414_InitialIdentityTenant', '10.0.8');
    END IF;
END $EF$;
COMMIT;

