START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260715193000_AddFgsPublicEndpointAndLastLogin') THEN
    CREATE TABLE identity."FgsPublicEndpoint" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "EndpointType" character varying(50) NOT NULL,
        "EnvironmentCode" character varying(20) NOT NULL,
        "BaseUrl" character varying(500) NOT NULL,
        "DisplayName" character varying(100),
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_FgsPublicEndpoint" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsPublicEndpoint_FgsTenantCompanyCache" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES identity."FgsTenantCompanyCache" ("TenantId", "CompanyId") ON DELETE RESTRICT
    );
    COMMENT ON TABLE identity."FgsPublicEndpoint" IS 'Stores public endpoints exposed by the platform for each tenant and company. Used during authentication and by client applications to discover the appropriate application or integration endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."Id" IS 'Unique identifier for the service endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."TenantId" IS 'Tenant that owns the service endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."CompanyId" IS 'Company that owns the service endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."EndpointType" IS 'Type of public endpoint. Supported values are BFF for the application backend and API for third-party integrations.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."EnvironmentCode" IS 'Deployment environment of the endpoint. Supported values are PROD, SANDBOX, TRAINING, QA, PREVIEW and DEVELOPMENT.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."BaseUrl" IS 'Base URL clients use to access the public endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."DisplayName" IS 'User-friendly name displayed when multiple environments are available.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."CreatedOn" IS 'Date and time the service endpoint was created.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."CreatedBy" IS 'User or system that created the service endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."UpdatedOn" IS 'Date and time the service endpoint was last modified.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."UpdatedBy" IS 'User or system that last modified the service endpoint.';
    COMMENT ON COLUMN identity."FgsPublicEndpoint"."IsActive" IS 'Indicates whether the endpoint is available for use.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260715193000_AddFgsPublicEndpointAndLastLogin') THEN
    CREATE INDEX "IX_FgsPublicEndpoint_Tenant_Company" ON identity."FgsPublicEndpoint" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260715193000_AddFgsPublicEndpointAndLastLogin') THEN
    CREATE UNIQUE INDEX "IX_FgsPublicEndpoint_Tenant_Company_Type_Environment" ON identity."FgsPublicEndpoint" ("TenantId", "CompanyId", "EndpointType", "EnvironmentCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM identity."__EFMigrationsHistory" WHERE "MigrationId" = '20260715193000_AddFgsPublicEndpointAndLastLogin') THEN
    INSERT INTO identity."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715193000_AddFgsPublicEndpointAndLastLogin', '10.0.8');
    END IF;
END $EF$;
COMMIT;

