-- =============================================================================
-- Migration: 20260518163137_Initial_Migration
-- Script:   20260518163137_Initial_Migration_Up.sql
-- Database: PostgreSQL (schema: dbo)
--
-- Full User Service schema aligned with CleanUpTables PDF spec.
-- Idempotent (matches: dotnet ef migrations script --idempotent).
-- Seed data: run Database/Seed/Initial_Migration_Seed.sql separately.
-- =============================================================================

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dbo') THEN
        CREATE SCHEMA dbo;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS dbo."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dbo') THEN
            CREATE SCHEMA dbo;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsOutboxMessage" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "Payload" jsonb NOT NULL,
        "IdempotencyKey" character varying(200) NOT NULL,
        "CorrelationId" character varying(100),
        "Status" character varying(50) NOT NULL,
        "RetryCount" integer NOT NULL,
        "LastError" character varying(2000),
        "CreatedOn" timestamptz NOT NULL,
        "ProcessedOn" timestamptz,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_FgsOutboxMessage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsTenant" (
        "Id" uuid NOT NULL,
        "TenantCode" character varying(50) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LegalName" character varying(300),
        "Email" character varying(300),
        "PhoneNumber" character varying(50),
        "Website" character varying(500),
        "PhysicalLocationId" uuid,
        "BillingLocationId" uuid,
        "SubscriptionPlanId" integer,
        "TimeZone" character varying(100),
        "DefaultCurrency" character varying(20),
        "DefaultLanguageId" integer,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenant" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsTenantCompany" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyGuid" uuid NOT NULL,
        "CompanyNumber" bigint NOT NULL,
        "BusinessTypeId" integer NOT NULL,
        "CompanySize" character varying(20),
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LegalName" character varying(300),
        "Email" character varying(300),
        "PhoneNumber" character varying(50),
        "Website" character varying(500),
        "TaxId" character varying(100),
        "PhysicalLocationId" uuid,
        "BillingLocationId" uuid,
        "FullLogoUrl" character varying(1000),
        "CompactLogoUrl" character varying(1000),
        "IconLogoUrl" character varying(1000),
        "FaviconUrl" character varying(1000),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenantCompany" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_FgsTenantCompany_TenantId_CompanyGuid" UNIQUE ("TenantId", "CompanyGuid"),
        CONSTRAINT "AK_FgsTenantCompany_TenantId_CompanyNumber" UNIQUE ("TenantId", "CompanyNumber")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloAccountingIntegrationType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloAccountingIntegrationType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloBillingCategory" (
        "BillingCategoryType" character varying(2) NOT NULL,
        "BillingCategoryName" character varying(100) NOT NULL,
        CONSTRAINT "PK_GloBillingCategory" PRIMARY KEY ("BillingCategoryType")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloBusinessType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloBusinessType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloCommunicationToken" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TokenCode" text NOT NULL,
        "DisplayName" text NOT NULL,
        "SourceTableName" text NOT NULL,
        "SourceColumnName" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloCommunicationToken" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloCommunicationToken_TokenCode" UNIQUE ("TokenCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloCountry" (
        "CountryCode" character varying(2) NOT NULL,
        "CountryName" character varying(100) NOT NULL,
        "CurrencyCode" character varying(3),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_GloCountry" PRIMARY KEY ("CountryCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloCredentialCategory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloCredentialCategory" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloCredentialProviderType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloCredentialProviderType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloLanguage" (
        "LanguageCode" character varying(5) NOT NULL,
        "LanguageName" character varying(100) NOT NULL,
        "CultureCode" character varying(10) NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_GloLanguage" PRIMARY KEY ("LanguageCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloLocationType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloLocationType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloMasterEntityType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "IsDocumentAllowed" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedOn" timestamptz,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloMasterEntityType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloMasterEntityType_Code" UNIQUE ("Code")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloPaymentMethodType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "DisplayName" text NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_GloPaymentMethodType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloPaymentMethodType_Code" UNIQUE ("Code")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloResolutionType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ResolutionTypeCode" character varying(50) NOT NULL,
        "ResolutionTypeName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloResolutionType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloResolutionType_Code" UNIQUE ("ResolutionTypeCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloRole" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
        "RoleCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "RoleLevel" character varying(20) NOT NULL,
        "IsAssignable" boolean NOT NULL DEFAULT TRUE,
        "IsSystemRole" boolean NOT NULL DEFAULT FALSE,
        "SortOrder" smallint NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (timezone('utc', now())),
        CONSTRAINT "PK_GloRole" PRIMARY KEY ("Id"),
        CONSTRAINT "UX_GloRole_RoleCode" UNIQUE ("RoleCode"),
        CONSTRAINT "CK_GloRole_RoleCode_NotEmpty" CHECK (length(trim("RoleCode")) > 0),
        CONSTRAINT "CK_GloRole_Name_NotEmpty" CHECK (length(trim("Name")) > 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloSetupDescriptionType" (
        "Id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (timezone('utc', now())),
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloSetupDescriptionType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloSetupDescriptionType_Code" UNIQUE ("Code")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloSetupLaborRateType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "SortOrder" integer NOT NULL DEFAULT 0,
        "IsSystem" boolean NOT NULL DEFAULT TRUE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedOn" timestamptz NOT NULL DEFAULT (timezone('utc', now())),
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloSetupLaborRateType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloSetupLaborRateType_Name" UNIQUE ("Name")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloTimeCardOption" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        CONSTRAINT "PK_GloTimeCardOption" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_GloTimeCardOption_Code" UNIQUE ("Code"),
        CONSTRAINT "CK_GloTimeCardOption_Code_Upper" CHECK ("Code" = UPPER("Code"))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsCredentialProvider" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CredentialProviderTypeId" integer NOT NULL,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Environment" character varying(50) NOT NULL,
        "Description" character varying(1000),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsCredentialProvider" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredentialProvider_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupCommunicationTemplate" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "TemplateType" text NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Subject" text,
        "Body" text NOT NULL,
        "IsMobileVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupCommunicationTemplate" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupCommunicationTemplate" UNIQUE ("TenantId", "CompanyId", "TemplateType", "Code"),
        CONSTRAINT "FK_FgsSetupCommunicationTemplate_FgsTenantCompany_TenantId_Com~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupGLBreak" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "BreakLabel" text,
        "BreakLevel" integer NOT NULL,
        "LogoUrl" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupGLBreak" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupGLBreak" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "FK_FgsSetupGLBreak_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPaymentTerm" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Name" text NOT NULL,
        "DueDateMethod" text NOT NULL,
        "NumberOfDays" integer,
        "IsAccountsReceivable" boolean NOT NULL,
        "IsAccountsPayable" boolean NOT NULL,
        "IsMobileVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPaymentTerm" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupPaymentTerm" UNIQUE ("TenantId", "CompanyId", "Name"),
        CONSTRAINT "FK_FgsSetupPaymentTerm_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPriceSheet" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "IsLaborTierStructure" boolean NOT NULL,
        "IsLaborRateBySkillLevel" boolean NOT NULL,
        "EffectiveFrom" date NOT NULL,
        "EffectiveTo" date,
        "IsMobileVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPriceSheet" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupPricingMatrix" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "FK_FgsSetupPriceSheet_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPriceSheetLaborTier" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupPriceSheetLaborId" bigint NOT NULL,
        "SequenceOrder" integer NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "Rate" numeric NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPriceSheetLaborTier" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupPriceSheetLaborTier_FgsTenantCompany_TenantId_Compa~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPriceSheetMaterial" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupPriceSheetId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "DefaultMarkupPercent" numeric,
        "DefaultDiscountPercent" numeric,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPriceSheetMaterial" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupPriceSheetMaterial_FgsTenantCompany_TenantId_Compan~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPriceSheetOther" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupPriceSheetId" bigint NOT NULL,
        "CategoryCode" text NOT NULL,
        "Name" text NOT NULL,
        "MarkupPercent" numeric,
        "DiscountPercent" numeric,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPriceSheetOther" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupPricingMatrixOther" UNIQUE ("TenantId", "CompanyId", "FgsSetupPriceSheetId", "CategoryCode"),
        CONSTRAINT "CK_FgsSetupPricingMatrixOther_DiscountPercent" CHECK ("DiscountPercent" IS NULL OR ("DiscountPercent" >= 0 AND "DiscountPercent" <= 100)),
        CONSTRAINT "CK_FgsSetupPricingMatrixOther_MarkupPercent" CHECK ("MarkupPercent" IS NULL OR ("MarkupPercent" >= 0 AND "MarkupPercent" <= 100)),
        CONSTRAINT "FK_FgsSetupPriceSheetOther_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupServiceAssetManufacturer" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupServiceAssetManufacturer" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupServiceAssetManufacturer" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupServiceAssetManufacturer_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "FK_FgsSetupServiceAssetManufacturer_FgsTenantCompany_TenantId_~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupServiceAssetType" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupServiceAssetType" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupServiceAssetType" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupServiceAssetType_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "FK_FgsSetupServiceAssetType_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTax" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "TaxCode" text NOT NULL,
        "Name" text NOT NULL,
        "IsExternalSystemRecord" boolean NOT NULL,
        "Description" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTax" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTax" UNIQUE ("TenantId", "CompanyId", "TaxCode"),
        CONSTRAINT "CK_FgsSetupTax_TaxCode_Upper" CHECK ("TaxCode" = UPPER("TaxCode")),
        CONSTRAINT "FK_FgsSetupTax_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTaxAuthority" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "RegionCode" text,
        "IsExternalSystemRecord" boolean NOT NULL,
        "Description" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTaxAuthority" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTaxAuthority" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupTaxAuthority_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "CK_FgsSetupTaxAuthority_RegionCode_Upper" CHECK ("RegionCode" IS NULL OR "RegionCode" = UPPER("RegionCode")),
        CONSTRAINT "FK_FgsSetupTaxAuthority_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTechSkillLevel" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "SortOrder" integer,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTechSkillLevel" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTechSkillLevel" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupTechSkillLevel_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "CK_FgsSetupTechSkillLevel_SortOrder" CHECK ("SortOrder" >= 0),
        CONSTRAINT "FK_FgsSetupTechSkillLevel_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTechTrade" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "TradeCode" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "SortOrder" integer,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTechTrade" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTechTrade" UNIQUE ("TenantId", "CompanyId", "TradeCode"),
        CONSTRAINT "CK_FgsSetupTechTrade_SortOrder" CHECK ("SortOrder" >= 0),
        CONSTRAINT "CK_FgsSetupTechTrade_TradeCode_Upper" CHECK ("TradeCode" = UPPER("TradeCode")),
        CONSTRAINT "FK_FgsSetupTechTrade_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTitleOfCourtesy" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "DisplayName" text NOT NULL,
        "SortOrder" integer,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTitleOfCourtesy" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTitleOfCourtesy" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupTitleOfCourtesy_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "CK_FgsSetupTitleOfCourtesy_SortOrder" CHECK ("SortOrder" >= 0),
        CONSTRAINT "FK_FgsSetupTitleOfCourtesy_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupZone" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupZone" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupZone" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupZone_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "FK_FgsSetupZone_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsUser" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "Email" character varying(300) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "EntraObjectId" character varying(100),
        "Role" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsUser" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsUser_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUser_FgsTenant_TenantId" FOREIGN KEY ("TenantId") REFERENCES dbo."FgsTenant" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."GloStateProvince" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CountryCode" character varying(2) NOT NULL,
        "StateProvinceCode" character varying(10) NOT NULL,
        "StateProvinceName" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_GloStateProvince" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GloStateProvince_Country" FOREIGN KEY ("CountryCode") REFERENCES dbo."GloCountry" ("CountryCode") ON DELETE RESTRICT,
        CONSTRAINT "UQ_GloStateProvince" UNIQUE ("CountryCode", "StateProvinceCode")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsLocation" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "MasterEntityTypeId" integer NOT NULL,
        "EntityNumber" bigint,
        "AddressLine1" character varying(200),
        "AddressLine2" character varying(200),
        "AddressLine3" character varying(200),
        "AddressLine4" character varying(200),
        "City" character varying(100),
        "State" character varying(100),
        "County" character varying(100),
        "Country" character varying(100),
        "PostalCode" character varying(20),
        "FormattedAddress" character varying(1000),
        "Latitude" numeric(18,10),
        "Longitude" numeric(18,10),
        "PlaceId" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsLocation" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsLocation_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsLocation_MasterEntityType" FOREIGN KEY ("MasterEntityTypeId") REFERENCES dbo."GloMasterEntityType" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPaymentMethod" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloPaymentMethodTypeId" integer NOT NULL,
        "DisplayName" text NOT NULL,
        "IsMobileVisible" boolean NOT NULL,
        "IsCustomerPortalVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPaymentMethod" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupPaymentMethod" UNIQUE ("TenantId", "CompanyId", "GloPaymentMethodTypeId"),
        CONSTRAINT "FK_FgsSetupPaymentMethod_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupPaymentMethod_GloPayType" FOREIGN KEY ("GloPaymentMethodTypeId") REFERENCES dbo."GloPaymentMethodType" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsResolutionCode" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloResolutionTypeId" integer NOT NULL,
        "ResolutionCode" character varying(50) NOT NULL,
        "ResolutionName" character varying(200) NOT NULL,
        "IsMobileVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsResolutionCode" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsResolutionCode_Code" UNIQUE ("TenantId", "CompanyId", "ResolutionCode"),
        CONSTRAINT "CK_FgsResolutionCode_Code_Upper" CHECK ("ResolutionCode" = UPPER("ResolutionCode")),
        CONSTRAINT "FK_FgsResolutionCode_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsResolutionCode_GloResType" FOREIGN KEY ("GloResolutionTypeId") REFERENCES dbo."GloResolutionType" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RoleCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "GloRoleId" smallint,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsRole" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsRole_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsRole_GloRole_GloRoleId" FOREIGN KEY ("GloRoleId") REFERENCES dbo."GloRole" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPriceSheetLabor" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupPriceSheetId" bigint NOT NULL,
        "FgsSetupLaborRateTypeId" integer,
        "FgsSetupTechSkillLevelId" bigint,
        "RateType" text NOT NULL,
        "BaseRate" numeric NOT NULL,
        "OvertimeMultiplier" numeric,
        "DoubleTimeMultiplier" numeric,
        "DiscountPercent" numeric,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPriceSheetLabor" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupPriceSheetLabor_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupPriceSheetLabor_GloSetupLaborRateType_FgsSetupLabor~" FOREIGN KEY ("FgsSetupLaborRateTypeId") REFERENCES dbo."GloSetupLaborRateType" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsTenantServiceSetup" (
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloTimeCardOptionId" integer NOT NULL,
        "AccountingIntegrationTypeId" integer,
        "UseExternalTaxCalculationProvider" boolean NOT NULL,
        "EnableCallBookingWidget" boolean NOT NULL,
        "EnablePaymentWidget" boolean NOT NULL,
        "EnableCustomerPortal" boolean NOT NULL,
        "EnableRulesManagement" boolean NOT NULL,
        "EnableAutoArrive" boolean NOT NULL,
        "WorkLocationRadiusForAutoArrive" integer,
        "OTStartTime" interval,
        "OTEndTime" interval,
        "DTStartTime" interval,
        "DTEndTime" interval,
        "BillHoursFromDispatchOrArrive" character varying(20) NOT NULL,
        "SourceCodeRequiredOnWorkOrder" boolean NOT NULL,
        "SourceCodeRequiredOnServiceLocation" boolean NOT NULL,
        "BillToStartNumber" bigint NOT NULL,
        "POStartNumber" bigint NOT NULL,
        "QuoteStartNumber" bigint NOT NULL,
        "WorkOrderStartNumber" bigint NOT NULL,
        "InvoiceNumberPrefix" character varying(20),
        "QuoteNumberPrefix" character varying(20),
        "PONumberPrefix" character varying(20),
        "WorkOrderNumberPrefix" character varying(20),
        "InvoiceBatchNumberFormat" character varying(200),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsTenantServiceSetup" PRIMARY KEY ("TenantId", "CompanyId"),
        CONSTRAINT "CK_FgsTenantServiceSetup_DTRange" CHECK ("DTStartTime" IS NULL OR "DTEndTime" IS NULL OR "DTEndTime" > "DTStartTime"),
        CONSTRAINT "CK_FgsTenantServiceSetup_OTRange" CHECK ("OTStartTime" IS NULL OR "OTEndTime" IS NULL OR "OTEndTime" > "OTStartTime"),
        CONSTRAINT "CK_FgsTenantServiceSetup_WorkLocationRadius" CHECK ("WorkLocationRadiusForAutoArrive" IS NULL OR "WorkLocationRadiusForAutoArrive" >= 0),
        CONSTRAINT "FK_FgsTenantServiceSetup_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsTenantServiceSetup_TimeCardOption" FOREIGN KEY ("GloTimeCardOptionId") REFERENCES dbo."GloTimeCardOption" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsCredentialProviderConfiguration" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CredentialProviderId" uuid NOT NULL,
        "ConfigurationKey" character varying(200) NOT NULL,
        "ConfigurationValue" text,
        "Environment" character varying(50),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsCredentialProviderConfiguration" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredProvCfg_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsCredProvCfg_Provider" FOREIGN KEY ("CredentialProviderId") REFERENCES dbo."FgsCredentialProvider" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsCredentialSecret" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CredentialProviderId" uuid NOT NULL,
        "SecretName" character varying(200) NOT NULL,
        "EncryptedSecretValue" text NOT NULL,
        "EncryptedDek" text NOT NULL,
        "EncryptionKeyId" character varying(500) NOT NULL,
        "VersionNo" integer NOT NULL,
        "LastRotatedOn" timestamptz,
        "ExpiresOn" timestamptz,
        "IsActive" boolean NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsCredentialSecret" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredentialSecret_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsCredentialSecret_Provider" FOREIGN KEY ("CredentialProviderId") REFERENCES dbo."FgsCredentialProvider" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupServiceAssetModelReference" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupServiceAssetTypeId" bigint NOT NULL,
        "FgsSetupServiceAssetManufacturerId" bigint NOT NULL,
        "ModelNumber" text,
        "ModelDescription" text NOT NULL,
        "SerialNumberPattern" text,
        "Notes" text,
        "UrlsJson" jsonb,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupServiceAssetModelReference" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsSvcAssetModelRef_UrlsJson" CHECK ("UrlsJson" IS NULL OR jsonb_typeof("UrlsJson") = 'array'),
        CONSTRAINT "FK_FgsSvcAssetModelRef_AssetType" FOREIGN KEY ("FgsSetupServiceAssetTypeId") REFERENCES dbo."FgsSetupServiceAssetType" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSvcAssetModelRef_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSvcAssetModelRef_Mfr" FOREIGN KEY ("FgsSetupServiceAssetManufacturerId") REFERENCES dbo."FgsSetupServiceAssetManufacturer" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTaxDetail" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupTaxId" bigint NOT NULL,
        "FgsSetupTaxAuthorityId" bigint NOT NULL,
        "EffectiveFromDate" date NOT NULL,
        "EffectiveToDate" date,
        "TaxPercent" numeric NOT NULL,
        "IsExternalSystemRecord" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTaxDetail" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsSetupTaxDetail_EffectiveDates" CHECK ("EffectiveToDate" IS NULL OR "EffectiveToDate" >= "EffectiveFromDate"),
        CONSTRAINT "CK_FgsSetupTaxDetail_TaxPercent" CHECK ("TaxPercent" >= 0 AND "TaxPercent" <= 100),
        CONSTRAINT "FK_FgsSetupTaxDetail_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupTaxDetail_Tax" FOREIGN KEY ("FgsSetupTaxId") REFERENCES dbo."FgsSetupTax" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupTaxDetail_TaxAuth" FOREIGN KEY ("FgsSetupTaxAuthorityId") REFERENCES dbo."FgsSetupTaxAuthority" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupDescription" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "DescriptionTypeCode" text NOT NULL,
        "ShortNote" character varying(30),
        "Body" text NOT NULL,
        "FgsSetupTechTradeId" bigint,
        "SortOrder" integer NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupDescription" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupDescription_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupDescription_TechTrade" FOREIGN KEY ("FgsSetupTechTradeId") REFERENCES dbo."FgsSetupTechTrade" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupGLBreakTechTrade" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupGLBreakId" bigint NOT NULL,
        "FgsSetupTechTradeId" bigint NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupGLBreakTechTrade" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsSetupGLBreak_FgsSetupGLBreakId" FOREIGN KEY ("FgsSetupGLBreakId") REFERENCES dbo."FgsSetupGLBreak" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsSetupTechTrade_FgsSetupTechTrad~" FOREIGN KEY ("FgsSetupTechTradeId") REFERENCES dbo."FgsSetupTechTrade" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupPostalCode" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "PostalCode" text NOT NULL,
        "FgsSetupZoneId" bigint,
        "FgsSetupTaxId" bigint,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupPostalCode" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupPostalCode" UNIQUE ("TenantId", "CompanyId", "PostalCode"),
        CONSTRAINT "FK_FgsSetupPostalCode_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupPostalCode_Tax" FOREIGN KEY ("FgsSetupTaxId") REFERENCES dbo."FgsSetupTax" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupPostalCode_Zone" FOREIGN KEY ("FgsSetupZoneId") REFERENCES dbo."FgsSetupZone" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsSetupTimeSlot" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupZoneId" bigint,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "BeginTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "MarkTechArrivedLateAfter" interval,
        "MarkWorkOrderDelayedCompletionAfter" interval,
        "IsMobileVisible" boolean NOT NULL,
        "IsCustomerPortalVisible" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupTimeSlot" PRIMARY KEY ("Id"),
        CONSTRAINT "UQ_FgsSetupTimeSlot" UNIQUE ("TenantId", "CompanyId", "Code"),
        CONSTRAINT "CK_FgsSetupTimeSlot_Code_Upper" CHECK ("Code" = UPPER("Code")),
        CONSTRAINT "CK_FgsSetupTimeSlot_TimeRange" CHECK ("EndTime" > "BeginTime"),
        CONSTRAINT "FK_FgsSetupTimeSlot_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupTimeSlot_Zone" FOREIGN KEY ("FgsSetupZoneId") REFERENCES dbo."FgsSetupZone" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsInvitation" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Email" character varying(300) NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "ExpiresAtUtc" timestamptz NOT NULL,
        "AcceptedAtUtc" timestamptz,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_FgsInvitation" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsInvitation_FgsUser_UserId" FOREIGN KEY ("UserId") REFERENCES dbo."FgsUser" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsUserRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloRoleId" smallint,
        "FgsRoleId" bigint,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_FgsUserRole" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsUserRole_OnlyOneRole" CHECK (("GloRoleId" IS NOT NULL AND "FgsRoleId" IS NULL) OR ("GloRoleId" IS NULL AND "FgsRoleId" IS NOT NULL)),
        CONSTRAINT "FK_FgsUserRole_FgsRole_FgsRoleId" FOREIGN KEY ("FgsRoleId") REFERENCES dbo."FgsRole" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUserRole_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUserRole_FgsUser_UserId" FOREIGN KEY ("UserId") REFERENCES dbo."FgsUser" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsUserRole_GloRole_GloRoleId" FOREIGN KEY ("GloRoleId") REFERENCES dbo."GloRole" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE TABLE dbo."FgsCredentialAudit" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "CredentialSecretId" uuid NOT NULL,
        "ActionType" character varying(100) NOT NULL,
        "Remarks" character varying(1000),
        "OldVersionNo" integer,
        "NewVersionNo" integer,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        CONSTRAINT "PK_FgsCredentialAudit" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsCredentialAudit_Company" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsCredentialAudit_CredentialSecret" FOREIGN KEY ("CredentialSecretId") REFERENCES dbo."FgsCredentialSecret" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialAudit_CredentialSecretId" ON dbo."FgsCredentialAudit" ("CredentialSecretId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialAudit_Tenant_Company" ON dbo."FgsCredentialAudit" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialAudit_Tenant_Company_Cred" ON dbo."FgsCredentialAudit" ("TenantId", "CompanyId", "CredentialSecretId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "UQ_FgsCredentialAudit" ON dbo."FgsCredentialAudit" ("TenantId", "CompanyId", "CredentialSecretId", "ActionType", "NewVersionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsCredentialProvider_TenantId_CompanyId_Code" ON dbo."FgsCredentialProvider" ("TenantId", "CompanyId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialProviderConfiguration_CredentialProviderId" ON dbo."FgsCredentialProviderConfiguration" ("CredentialProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredProvCfg_Tenant_Company" ON dbo."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredProvCfg_Tenant_Company_Prov" ON dbo."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId", "CredentialProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "UQ_FgsCredentialProviderConfiguration" ON dbo."FgsCredentialProviderConfiguration" ("TenantId", "CompanyId", "CredentialProviderId", "ConfigurationKey", "Environment");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialSecret_CredentialProviderId" ON dbo."FgsCredentialSecret" ("CredentialProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialSecret_IsActive" ON dbo."FgsCredentialSecret" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialSecret_Tenant_Company" ON dbo."FgsCredentialSecret" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsCredentialSecret_Tenant_Company_Prov" ON dbo."FgsCredentialSecret" ("TenantId", "CompanyId", "CredentialProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "UQ_FgsCredentialSecret" ON dbo."FgsCredentialSecret" ("TenantId", "CompanyId", "CredentialProviderId", "SecretName", "VersionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsInvitation_TenantId_Email_Status" ON dbo."FgsInvitation" ("TenantId", "Email", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsInvitation_TokenHash" ON dbo."FgsInvitation" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsInvitation_UserId" ON dbo."FgsInvitation" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsLocation_MasterEntityTypeId" ON dbo."FgsLocation" ("MasterEntityTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsLocation_Tenant_Company_Entity" ON dbo."FgsLocation" ("TenantId", "CompanyId", "MasterEntityTypeId", "EntityNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsOutboxMessage_IdempotencyKey" ON dbo."FgsOutboxMessage" ("IdempotencyKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsOutboxMessage_Status_CreatedOn" ON dbo."FgsOutboxMessage" ("Status", "CreatedOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsResolutionCode_GloResolutionTypeId" ON dbo."FgsResolutionCode" ("GloResolutionTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsResolutionCode_GloResType" ON dbo."FgsResolutionCode" ("TenantId", "CompanyId", "GloResolutionTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsRole_GloRoleId" ON dbo."FgsRole" ("GloRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsRole_TenantId_CompanyId_RoleCode" ON dbo."FgsRole" ("TenantId", "CompanyId", "RoleCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupCommunicationTemplate_TenantId_CompanyId" ON dbo."FgsSetupCommunicationTemplate" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupDescription_TechTrade" ON dbo."FgsSetupDescription" ("FgsSetupTechTradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupDescription_Tenant_Company_Type" ON dbo."FgsSetupDescription" ("TenantId", "CompanyId", "DescriptionTypeCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupDescription_TenantId_CompanyId" ON dbo."FgsSetupDescription" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupGLBreak_TenantId_CompanyId" ON dbo."FgsSetupGLBreak" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsSetupGLBreakTechTrade_FgsSetupGLBreakId_FgsSetupTechTrad~" ON dbo."FgsSetupGLBreakTechTrade" ("FgsSetupGLBreakId", "FgsSetupTechTradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupGLBreakTechTrade_FgsSetupTechTradeId" ON dbo."FgsSetupGLBreakTechTrade" ("FgsSetupTechTradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupGLBreakTechTrade_TenantId_CompanyId" ON dbo."FgsSetupGLBreakTechTrade" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPaymentMethod_GloPaymentMethodTypeId" ON dbo."FgsSetupPaymentMethod" ("GloPaymentMethodTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPaymentMethod_TenantId_CompanyId" ON dbo."FgsSetupPaymentMethod" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPaymentTerm_TenantId_CompanyId" ON dbo."FgsSetupPaymentTerm" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPostalCode_TaxId" ON dbo."FgsSetupPostalCode" ("FgsSetupTaxId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPostalCode_TenantId_CompanyId" ON dbo."FgsSetupPostalCode" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPostalCode_ZoneId" ON dbo."FgsSetupPostalCode" ("FgsSetupZoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheet_TenantId_CompanyId" ON dbo."FgsSetupPriceSheet" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetLabor_FgsSetupLaborRateTypeId" ON dbo."FgsSetupPriceSheetLabor" ("FgsSetupLaborRateTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetLabor_TenantId_CompanyId" ON dbo."FgsSetupPriceSheetLabor" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetLaborTier_TenantId_CompanyId" ON dbo."FgsSetupPriceSheetLaborTier" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetMaterial_TenantId_CompanyId" ON dbo."FgsSetupPriceSheetMaterial" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetOther_TenantId_CompanyId" ON dbo."FgsSetupPriceSheetOther" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupServiceAssetManufacturer_TenantId_CompanyId" ON dbo."FgsSetupServiceAssetManufacturer" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSvcAssetModelRef_Mfr" ON dbo."FgsSetupServiceAssetModelReference" ("TenantId", "CompanyId", "FgsSetupServiceAssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSvcAssetModelRef_MfrId" ON dbo."FgsSetupServiceAssetModelReference" ("FgsSetupServiceAssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSvcAssetModelRef_Type" ON dbo."FgsSetupServiceAssetModelReference" ("TenantId", "CompanyId", "FgsSetupServiceAssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSvcAssetModelRef_TypeId" ON dbo."FgsSetupServiceAssetModelReference" ("FgsSetupServiceAssetTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSvcAssetModelRef_TypeMfr" ON dbo."FgsSetupServiceAssetModelReference" ("TenantId", "CompanyId", "FgsSetupServiceAssetTypeId", "FgsSetupServiceAssetManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_ServiceAsset_UrlsJson" ON dbo."FgsSetupServiceAssetModelReference" USING gin ("UrlsJson");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupServiceAssetType_TenantId_CompanyId" ON dbo."FgsSetupServiceAssetType" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTax_TenantId_CompanyId" ON dbo."FgsSetupTax" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxAuthority_RegionCode" ON dbo."FgsSetupTaxAuthority" ("TenantId", "CompanyId", "RegionCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxAuthority_TenantId_CompanyId" ON dbo."FgsSetupTaxAuthority" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_EffectiveDates" ON dbo."FgsSetupTaxDetail" ("EffectiveFromDate", "EffectiveToDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_Tax" ON dbo."FgsSetupTaxDetail" ("TenantId", "CompanyId", "FgsSetupTaxId", "EffectiveFromDate", "EffectiveToDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_TaxAuth" ON dbo."FgsSetupTaxDetail" ("TenantId", "CompanyId", "FgsSetupTaxAuthorityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_TaxAuthId" ON dbo."FgsSetupTaxDetail" ("FgsSetupTaxAuthorityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_TaxId" ON dbo."FgsSetupTaxDetail" ("FgsSetupTaxId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTaxDetail_TenantId_CompanyId" ON dbo."FgsSetupTaxDetail" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTechSkillLevel_SortOrder" ON dbo."FgsSetupTechSkillLevel" ("TenantId", "CompanyId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTechSkillLevel_TenantId_CompanyId" ON dbo."FgsSetupTechSkillLevel" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTechTrade_SortOrder" ON dbo."FgsSetupTechTrade" ("TenantId", "CompanyId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTechTrade_TenantId_CompanyId" ON dbo."FgsSetupTechTrade" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTimeSlot_TenantId_CompanyId" ON dbo."FgsSetupTimeSlot" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTimeSlot_Zone" ON dbo."FgsSetupTimeSlot" ("TenantId", "CompanyId", "FgsSetupZoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTimeSlot_ZoneId" ON dbo."FgsSetupTimeSlot" ("FgsSetupZoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTitleOfCourtesy_SortOrder" ON dbo."FgsSetupTitleOfCourtesy" ("TenantId", "CompanyId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupTitleOfCourtesy_TenantId_CompanyId" ON dbo."FgsSetupTitleOfCourtesy" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsSetupZone_TenantId_CompanyId" ON dbo."FgsSetupZone" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsTenant_TenantCode" ON dbo."FgsTenant" ("TenantCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsTenantCompany_TenantId_Code" ON dbo."FgsTenantCompany" ("TenantId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsTenantCompany_TenantId_CompanyNumber" ON dbo."FgsTenantCompany" ("TenantId", "CompanyNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsTenantServiceSetup_GloTimeCardOptionId" ON dbo."FgsTenantServiceSetup" ("GloTimeCardOptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsUser_TenantId_CompanyId" ON dbo."FgsUser" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsUser_TenantId_Email" ON dbo."FgsUser" ("TenantId", "Email") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsUserRole_FgsRoleId" ON dbo."FgsUserRole" ("FgsRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsUserRole_GloRoleId" ON dbo."FgsUserRole" ("GloRoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsUserRole_TenantId_CompanyId" ON dbo."FgsUserRole" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE INDEX "IX_FgsUserRole_UserId" ON dbo."FgsUserRole" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_FgsRoleId" ON dbo."FgsUserRole" ("UserId", "FgsRoleId") WHERE "FgsRoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_GloRoleId" ON dbo."FgsUserRole" ("UserId", "GloRoleId") WHERE "GloRoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_GloAccountingIntegrationType_Code" ON dbo."GloAccountingIntegrationType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_GloBusinessType_Code" ON dbo."GloBusinessType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialCategory_Code" ON dbo."GloCredentialCategory" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialProviderType_Code" ON dbo."GloCredentialProviderType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    CREATE UNIQUE INDEX "IX_GloLocationType_Code" ON dbo."GloLocationType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518163137_Initial_Migration') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260518163137_Initial_Migration', '10.0.8');
    END IF;
END $EF$;
COMMIT;

