-- =============================================================================
-- Migration: 20260518144909_GlobalRolesSetupDescriptionAndLaborRate
-- Script:   20260518144909_GlobalRolesSetupDescriptionAndLaborRate_Up.sql
-- Database: PostgreSQL (schema: dbo)
--
-- Behavior:
--   1. Adds FgsSetupDescription.ShortNote.
--   2. Creates GloRole, GloSetupDescriptionType, GloSetupLaborRateType, FgsRole, FgsUserRole.
--   3. Replaces FgsSetupGLBreak.FgsSetupTechTradeId with FgsSetupGLBreakTechTrade junction.
--   4. Adds FK from FgsSetupPriceSheetLabor to GloSetupLaborRateType.
--   5. Seeds global role, description type, and labor rate type reference data.
--   6. Records MigrationId in "__EFMigrationsHistory" when not yet present.
--
-- Seed defaults:
--   CreatedOn  -> timezone('utc', now())
--   CreatedBy  -> 'System' (where applicable)
--
-- Notes:
--   - Matches: 20260518144909_GlobalRolesSetupDescriptionAndLaborRate.cs
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    ALTER TABLE dbo."FgsSetupDescription" ADD COLUMN IF NOT EXISTS "ShortNote" character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."GloRole" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "RoleCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "RoleLevel" character varying(20) NOT NULL,
        "IsAssignable" boolean NOT NULL,
        "IsSystemRole" boolean NOT NULL,
        "SortOrder" smallint NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_GloRole" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE UNIQUE INDEX "IX_GloRole_RoleCode" ON dbo."GloRole" ("RoleCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."GloSetupDescriptionType" (
        "Id" uuid NOT NULL,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloSetupDescriptionType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE UNIQUE INDEX "IX_GloSetupDescriptionType_Code" ON dbo."GloSetupDescriptionType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."GloSetupLaborRateType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        "SortOrder" integer NOT NULL,
        "IsSystem" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        CONSTRAINT "PK_GloSetupLaborRateType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE UNIQUE INDEX "IX_GloSetupLaborRateType_Name" ON dbo."GloSetupLaborRateType" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."FgsRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "RoleCode" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        "GloRoleId" smallint,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsRole" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsRole_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsRole_GloRole_GloRoleId" FOREIGN KEY ("GloRoleId") REFERENCES dbo."GloRole" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE INDEX "IX_FgsRole_GloRoleId" ON dbo."FgsRole" ("GloRoleId");
    CREATE UNIQUE INDEX "IX_FgsRole_TenantId_CompanyId_RoleCode" ON dbo."FgsRole" ("TenantId", "CompanyId", "RoleCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."FgsUserRole" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "UserId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "GloRoleId" smallint,
        "FgsRoleId" bigint,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_FgsUserRole" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_FgsUserRole_OnlyOneRole" CHECK (("GloRoleId" IS NOT NULL AND "FgsRoleId" IS NULL) OR ("GloRoleId" IS NULL AND "FgsRoleId" IS NOT NULL)),
        CONSTRAINT "FK_FgsUserRole_FgsRole_FgsRoleId" FOREIGN KEY ("FgsRoleId") REFERENCES dbo."FgsRole" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUserRole_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsUserRole_FgsUser_UserId" FOREIGN KEY ("UserId") REFERENCES dbo."FgsUser" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsUserRole_GloRole_GloRoleId" FOREIGN KEY ("GloRoleId") REFERENCES dbo."GloRole" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE INDEX "IX_FgsUserRole_FgsRoleId" ON dbo."FgsUserRole" ("FgsRoleId");
    CREATE INDEX "IX_FgsUserRole_GloRoleId" ON dbo."FgsUserRole" ("GloRoleId");
    CREATE INDEX "IX_FgsUserRole_TenantId_CompanyId" ON dbo."FgsUserRole" ("TenantId", "CompanyId");
    CREATE INDEX "IX_FgsUserRole_UserId" ON dbo."FgsUserRole" ("UserId");
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_FgsRoleId" ON dbo."FgsUserRole" ("UserId", "FgsRoleId") WHERE "FgsRoleId" IS NOT NULL;
    CREATE UNIQUE INDEX "IX_FgsUserRole_UserId_GloRoleId" ON dbo."FgsUserRole" ("UserId", "GloRoleId") WHERE "GloRoleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE TABLE dbo."FgsSetupGLBreakTechTrade" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "TenantId" uuid NOT NULL,
        "CompanyId" bigint NOT NULL,
        "FgsSetupGLBreakId" bigint NOT NULL,
        "FgsSetupTechTradeId" bigint NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" character varying(100),
        "UpdatedOn" timestamptz,
        "UpdatedBy" character varying(100),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FgsSetupGLBreakTechTrade" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsSetupGLBreak_FgsSetupGLBreakId" FOREIGN KEY ("FgsSetupGLBreakId") REFERENCES dbo."FgsSetupGLBreak" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsSetupTechTrade_FgsSetupTechTradeId" FOREIGN KEY ("FgsSetupTechTradeId") REFERENCES dbo."FgsSetupTechTrade" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_FgsSetupGLBreakTechTrade_FgsTenantCompany_TenantId_CompanyId" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyNumber") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE UNIQUE INDEX "IX_FgsSetupGLBreakTechTrade_FgsSetupGLBreakId_FgsSetupTechTradeId" ON dbo."FgsSetupGLBreakTechTrade" ("FgsSetupGLBreakId", "FgsSetupTechTradeId");
    CREATE INDEX "IX_FgsSetupGLBreakTechTrade_FgsSetupTechTradeId" ON dbo."FgsSetupGLBreakTechTrade" ("FgsSetupTechTradeId");
    CREATE INDEX "IX_FgsSetupGLBreakTechTrade_TenantId_CompanyId" ON dbo."FgsSetupGLBreakTechTrade" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetLabor_FgsSetupLaborRateTypeId" ON dbo."FgsSetupPriceSheetLabor" ("FgsSetupLaborRateTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    ALTER TABLE dbo."FgsSetupPriceSheetLabor"
        ADD CONSTRAINT "FK_FgsSetupPriceSheetLabor_GloSetupLaborRateType_FgsSetupLaborRateTypeId"
        FOREIGN KEY ("FgsSetupLaborRateTypeId")
        REFERENCES dbo."GloSetupLaborRateType" ("Id")
        ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate')
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'dbo' AND table_name = 'FgsSetupGLBreak' AND column_name = 'FgsSetupTechTradeId') THEN
    INSERT INTO dbo."FgsSetupGLBreakTechTrade"
        ("TenantId", "CompanyId", "FgsSetupGLBreakId", "FgsSetupTechTradeId", "IsActive", "CreatedOn", "CreatedBy")
    SELECT
        b."TenantId",
        b."CompanyId",
        b."Id",
        b."FgsSetupTechTradeId",
        true,
        timezone('utc', now()),
        'System'
    FROM dbo."FgsSetupGLBreak" b
    WHERE b."FgsSetupTechTradeId" IS NOT NULL
      AND NOT EXISTS (
          SELECT 1
          FROM dbo."FgsSetupGLBreakTechTrade" j
          WHERE j."FgsSetupGLBreakId" = b."Id"
            AND j."FgsSetupTechTradeId" = b."FgsSetupTechTradeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    ALTER TABLE dbo."FgsSetupGLBreak" DROP COLUMN IF EXISTS "FgsSetupTechTradeId";
    END IF;
END $EF$;

DO $EF$
DECLARE
    v_now timestamptz := timezone('utc', now());
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN

    INSERT INTO dbo."GloRole"
        ("RoleCode", "Name", "Description", "RoleLevel", "IsAssignable", "IsSystemRole", "SortOrder", "IsActive", "CreatedOn")
    VALUES
        ('SYSTEM_ADMIN', 'System Administrator', 'Full internal platform administration access.', 'SYSTEM', false, true, 1, true, v_now),
        ('IMPLEMENTATION_SPECIALIST', 'Implementation Specialist', 'Helps onboard and configure customer tenants.', 'SYSTEM', false, true, 2, true, v_now),
        ('SUPPORT_AGENT', 'Support Agent', 'Provides customer support and troubleshooting.', 'SYSTEM', false, true, 3, true, v_now),
        ('BILLING_ADMIN', 'Billing Administrator', 'Manages subscriptions, invoices, and customer payments.', 'SYSTEM', false, true, 4, true, v_now),
        ('SALES_ADMIN', 'Sales Administrator', 'Creates demo tenants and supports sales operations.', 'SYSTEM', false, true, 5, true, v_now),
        ('READONLY_AUDITOR', 'Readonly Auditor', 'Internal audit and compliance access.', 'SYSTEM', false, true, 6, true, v_now),
        ('TENANT_ADMIN', 'Tenant Administrator', 'Super administrator for all companies under the tenant.', 'TENANT', false, false, 10, true, v_now),
        ('COMPANY_ADMIN', 'Company Administrator', 'Full administrator for a single company.', 'COMPANY', true, false, 20, true, v_now),
        ('OPERATIONS_MANAGER', 'Operations Manager', 'Manages overall company operations.', 'COMPANY', true, false, 21, true, v_now),
        ('DISPATCHER', 'Dispatcher', 'Schedules and dispatches service work.', 'COMPANY', true, false, 22, true, v_now),
        ('BILLING', 'Billing Specialist', 'Handles invoicing and billing operations.', 'COMPANY', true, false, 23, true, v_now),
        ('CSR', 'Customer Service Representative', 'Handles customer communication and service requests.', 'COMPANY', true, false, 24, true, v_now),
        ('OFFICE_USER', 'Office User', 'Standard office employee with limited access.', 'COMPANY', true, false, 25, true, v_now),
        ('SERVICE_MANAGER', 'Service Manager', 'Manages all field operations and technicians.', 'FIELD', true, false, 30, true, v_now),
        ('FIELD_SUPERVISOR', 'Field Supervisor', 'Supervises assigned field technicians and teams.', 'FIELD', true, false, 31, true, v_now),
        ('FIELD_TECH', 'Field Technician', 'Performs field service work and job completion.', 'FIELD', true, false, 32, true, v_now)
    ON CONFLICT ("RoleCode") DO NOTHING;

    INSERT INTO dbo."GloSetupDescriptionType" ("Id", "Code", "Name", "Description", "IsActive", "CreatedOn")
    VALUES
        (gen_random_uuid(), 'ReasonForCall', 'Reason For Call', 'Predefined reason for call descriptions', true, v_now),
        (gen_random_uuid(), 'Recommendations', 'Recommendations', 'Predefined recommendation descriptions', true, v_now),
        (gen_random_uuid(), 'WorkSummary', 'Work Summary', 'Predefined work summary descriptions', true, v_now),
        (gen_random_uuid(), 'AgreementDescription', 'Agreement Description', 'Predefined agreement descriptions', true, v_now)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO dbo."GloSetupLaborRateType"
        ("Name", "Description", "SortOrder", "IsSystem", "IsActive", "CreatedOn", "CreatedBy")
    VALUES
        ('Regular', 'Standard labor rate', 1, true, true, v_now, 'System'),
        ('Overtime', 'Overtime labor rate', 2, true, true, v_now, 'System'),
        ('Double-Time', 'Double-time labor rate', 3, true, true, v_now, 'System'),
        ('Holiday', 'Holiday labor rate', 4, true, true, v_now, 'System'),
        ('Weekend', 'Weekend labor rate', 5, true, true, v_now, 'System')
    ON CONFLICT ("Name") DO NOTHING;

    PERFORM setval(pg_get_serial_sequence('dbo."GloRole"', 'Id'), COALESCE((SELECT MAX("Id") FROM dbo."GloRole"), 1), true);
    PERFORM setval(pg_get_serial_sequence('dbo."GloSetupLaborRateType"', 'Id'), COALESCE((SELECT MAX("Id") FROM dbo."GloSetupLaborRateType"), 1), true);

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260518144909_GlobalRolesSetupDescriptionAndLaborRate') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260518144909_GlobalRolesSetupDescriptionAndLaborRate', '10.0.8');
    END IF;
END $EF$;

COMMIT;
