-- =============================================================================
-- Migration: 20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables
-- Script:   20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables_Down.sql
-- Database: PostgreSQL (schema: dbo)
--
-- Rollback: reverses the Up migration while MigrationId is still recorded
--           (idempotent DO blocks). Removes the history row last.
--
-- Notes:
--   - No data re-seeding; recreated tables are empty.
--   - Matches Down() in: 20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables.cs
--   - Generated idempotent pattern from: dotnet ef migrations script (reverse range)
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupTimeSlot" DROP COLUMN "FgsSetupZoneId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupTaxDetail" DROP COLUMN "IsExternalSystemRecord";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupTaxAuthority" DROP COLUMN "IsExternalSystemRecord";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupTax" DROP COLUMN "IsExternalSystemRecord";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupPriceSheetLabor" DROP COLUMN "FgsSetupLaborRateTypeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupPriceSheet" DROP COLUMN "IsLaborRateBySkillLevel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    ALTER TABLE dbo."FgsSetupPriceSheet" DROP COLUMN "IsLaborTierStructure";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE TABLE dbo."FgsSetupPriceSheetMaterialRange" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" uuid NOT NULL,
        "CostFrom" numeric NOT NULL,
        "CostTo" numeric NOT NULL,
        "CreatedBy" uuid,
        "CreatedOn" timestamptz NOT NULL,
        "FgsSetupPriceSheetMaterialId" bigint NOT NULL,
        "IsActive" boolean NOT NULL,
        "MarkupPercent" numeric NOT NULL,
        "UpdatedBy" uuid,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsSetupPriceSheetMaterialRange" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupPriceSheetMaterialRange_FgsTenantCompany_TenantId_C~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyGuid") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE TABLE dbo."FgsSetupServiceAssetMedia" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" uuid NOT NULL,
        "ContentType" text,
        "CreatedBy" uuid,
        "CreatedOn" timestamptz NOT NULL,
        "FgsSetupServiceAssetTypeId" bigint,
        "IsActive" boolean NOT NULL,
        "MediaUrl" text NOT NULL,
        "Title" text NOT NULL,
        "UpdatedBy" uuid,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsSetupServiceAssetMedia" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupServiceAssetMedia_FgsTenantCompany_TenantId_Company~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyGuid") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE TABLE dbo."FgsSetupServiceAssetModelSerialDescription" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" uuid NOT NULL,
        "CompanyId" uuid NOT NULL,
        "CreatedBy" uuid,
        "CreatedOn" timestamptz NOT NULL,
        "FgsSetupServiceAssetManufacturerId" bigint,
        "IsActive" boolean NOT NULL,
        "ModelDescription" text NOT NULL,
        "Notes" text,
        "SerialNumberPattern" text,
        "UpdatedBy" uuid,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_FgsSetupServiceAssetModelSerialDescription" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsSetupServiceAssetModelSerialDescription_FgsTenantCompany~" FOREIGN KEY ("TenantId", "CompanyId") REFERENCES dbo."FgsTenantCompany" ("TenantId", "CompanyGuid") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE INDEX "IX_FgsSetupPriceSheetMaterialRange_TenantId_CompanyId" ON dbo."FgsSetupPriceSheetMaterialRange" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE INDEX "IX_FgsSetupServiceAssetMedia_TenantId_CompanyId" ON dbo."FgsSetupServiceAssetMedia" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    CREATE INDEX "IX_FgsSetupServiceAssetModelSerialDescription_TenantId_Company~" ON dbo."FgsSetupServiceAssetModelSerialDescription" ("TenantId", "CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables') THEN
    DELETE FROM dbo."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260513141646_DropObsoleteSetupAssetAndMaterialRangeTables';
    END IF;
END $EF$;

COMMIT;
