-- =============================================================================
-- Migration: 20260512155244_GloGlobalReferenceTables
-- Script:   20260512155244_GloGlobalReferenceTables_Up.sql
-- Database: PostgreSQL (schema: dbo)
--
-- Behavior:
--   1. Creates global reference tables (Glo*) when MigrationId is not yet recorded.
--   2. Inserts MigrationId '20260512155244_GloGlobalReferenceTables' and ProductVersion
--      into "__EFMigrationsHistory" after successful DDL (see end of script).
--
-- Notes:
--   - Idempotent: each block is guarded by __EFMigrationsHistory.
--   - No reference data (seed) is inserted; populate catalogs separately.
--   - Matches output of: dotnet ef migrations script (idempotent) for this migration.
-- =============================================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloAccountingIntegrationType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloAccountingIntegrationType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloBusinessType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloBusinessType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloCountry" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CountryCode" character varying(10) NOT NULL,
        "CountryName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_GloCountry" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloCredentialCategory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloCredentialCategory" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloCredentialProviderType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloCredentialProviderType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloLanguage" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LanguageCode" character varying(25) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloLanguage" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloLocationType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(100) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "UpdatedOn" timestamptz,
        CONSTRAINT "PK_GloLocationType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloResolutionType" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ResolutionTypeCode" character varying(50) NOT NULL,
        "ResolutionTypeName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamptz,
        "UpdatedBy" uuid,
        CONSTRAINT "PK_GloResolutionType" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE TABLE dbo."GloStateProvince" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "GloCountryId" bigint NOT NULL,
        "RegionCode" character varying(25) NOT NULL,
        "RegionName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamptz NOT NULL,
        CONSTRAINT "PK_GloStateProvince" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GloStateProvince_GloCountry_GloCountryId" FOREIGN KEY ("GloCountryId") REFERENCES dbo."GloCountry" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloAccountingIntegrationType_Code" ON dbo."GloAccountingIntegrationType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloBusinessType_Code" ON dbo."GloBusinessType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialCategory_Code" ON dbo."GloCredentialCategory" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloCredentialProviderType_Code" ON dbo."GloCredentialProviderType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloLanguage_LanguageCode" ON dbo."GloLanguage" ("LanguageCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloLocationType_Code" ON dbo."GloLocationType" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE UNIQUE INDEX "IX_GloResolutionType_ResolutionTypeCode" ON dbo."GloResolutionType" ("ResolutionTypeCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    CREATE INDEX "IX_GloStateProvince_GloCountryId" ON dbo."GloStateProvince" ("GloCountryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dbo."__EFMigrationsHistory" WHERE "MigrationId" = '20260512155244_GloGlobalReferenceTables') THEN
    INSERT INTO dbo."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260512155244_GloGlobalReferenceTables', '10.0.0');
    END IF;
END $EF$;
COMMIT;
