START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'audit') THEN
            CREATE SCHEMA audit;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TYPE audit.event_detail_type AS ENUM ('FIELD_CHANGE', 'CALCULATION', 'VALIDATION', 'WORKFLOW', 'INTEGRATION', 'MESSAGE', 'EXCEPTION', 'NOTE');
    COMMENT ON TYPE audit.event_detail_type IS 'Defines the classification of a detail record associated with an event, such as a field change, calculation, validation, workflow action, integration, message, or exception.';
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'audit') THEN
            CREATE SCHEMA audit;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TYPE audit.event_source AS ENUM ('WEB', 'MOBILE', 'PORTAL', 'API', 'IMPORT', 'EXPORT', 'WORKER', 'SCHEDULER', 'RABBITMQ', 'QBO', 'EMAIL', 'SMS', 'SYSTEM');
    COMMENT ON TYPE audit.event_source IS 'Defines the application, service, integration, or process that originated an event.';
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'audit') THEN
            CREATE SCHEMA audit;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TYPE audit.record_type AS ENUM ('CUSTOMER', 'CONTACT', 'LOCATION', 'CALL', 'WORK_ORDER', 'APPOINTMENT', 'ESTIMATE', 'INVOICE', 'PAYMENT', 'ASSET', 'CONTRACT', 'INVENTORY_ITEM', 'PURCHASE_ORDER', 'TECHNICIAN', 'TASK', 'USER', 'PRICEBOOK', 'JOB_TYPE', 'ATTACHMENT', 'NOTE', 'SYSTEM');
    COMMENT ON TYPE audit.record_type IS 'Defines the type of business record associated with an event. Used together with RecordId to identify the audited record.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TABLE audit."FgsArchiveCatalog" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ArchiveMonth" date NOT NULL,
        "StoragePath" character varying(1000) NOT NULL,
        "FileSize" bigint NOT NULL,
        "CreatedOn" timestamp NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_FgsArchiveCatalog" PRIMARY KEY ("Id")
    );
    COMMENT ON TABLE audit."FgsArchiveCatalog" IS 'Maintains an inventory of archived event partitions.';
    COMMENT ON COLUMN audit."FgsArchiveCatalog"."Id" IS 'Unique identifier of the archive record.';
    COMMENT ON COLUMN audit."FgsArchiveCatalog"."ArchiveMonth" IS 'First day of the month represented by the archived partition (for example, 2026-07-01).';
    COMMENT ON COLUMN audit."FgsArchiveCatalog"."StoragePath" IS 'Object key or path where the archive file is stored.';
    COMMENT ON COLUMN audit."FgsArchiveCatalog"."FileSize" IS 'Size of the archive file in bytes.';
    COMMENT ON COLUMN audit."FgsArchiveCatalog"."CreatedOn" IS 'Date and time the archive record was created.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TABLE audit."FgsEvent" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" bigint NOT NULL,
        "CompanyId" bigint NOT NULL,
        "EventCode" character varying(100) NOT NULL,
        "EventSource" audit.event_source NOT NULL,
        "RecordType" audit.record_type NOT NULL,
        "EntityId" bigint NOT NULL,
        "EntityNumber" character varying(50),
        "UserName" character varying(150),
        "Summary" character varying(500) NOT NULL,
        "OccurredOn" timestamp NOT NULL DEFAULT (now()),
        "CreatedOn" timestamp NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_FgsEvent" PRIMARY KEY ("Id")
    );
    COMMENT ON TABLE audit."FgsEvent" IS 'Stores business, system, security, and integration events generated by the FSM platform. Provides the primary audit history for all business entities.';
    COMMENT ON COLUMN audit."FgsEvent"."Id" IS 'Unique identifier of the event.';
    COMMENT ON COLUMN audit."FgsEvent"."TenantId" IS 'Tenant that owns the event.';
    COMMENT ON COLUMN audit."FgsEvent"."CompanyId" IS 'Company within the tenant that owns the event.';
    COMMENT ON COLUMN audit."FgsEvent"."EventCode" IS 'Application-defined event code identifying the event.';
    COMMENT ON COLUMN audit."FgsEvent"."EventSource" IS 'Application, service, integration, or process that generated the event.';
    COMMENT ON COLUMN audit."FgsEvent"."RecordType" IS 'Business entity associated with the event.';
    COMMENT ON COLUMN audit."FgsEvent"."EntityId" IS 'Primary key of the associated business entity.';
    COMMENT ON COLUMN audit."FgsEvent"."EntityNumber" IS 'Business reference number displayed to users, such as WO-100245 or INV-10234.';
    COMMENT ON COLUMN audit."FgsEvent"."UserName" IS 'Display name of the user responsible for the event at the time it occurred.';
    COMMENT ON COLUMN audit."FgsEvent"."Summary" IS 'Short human-readable description displayed in the event history.';
    COMMENT ON COLUMN audit."FgsEvent"."OccurredOn" IS 'Date and time the event occurred. Used for partitioning.';
    COMMENT ON COLUMN audit."FgsEvent"."CreatedOn" IS 'Date and time the event record was written to the audit database.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TABLE audit."FgsEventAttachment" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EventId" bigint NOT NULL,
        "DocumentId" bigint NOT NULL,
        "Description" character varying(500),
        "CreatedOn" timestamp NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_FgsEventAttachment" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsEventAttachment_Event" FOREIGN KEY ("EventId") REFERENCES audit."FgsEvent" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE audit."FgsEventAttachment" IS 'Associates documents with audit events. Document metadata and storage are managed by the Document Service.';
    COMMENT ON COLUMN audit."FgsEventAttachment"."Id" IS 'Unique identifier of the event attachment.';
    COMMENT ON COLUMN audit."FgsEventAttachment"."EventId" IS 'References the audit event associated with the document.';
    COMMENT ON COLUMN audit."FgsEventAttachment"."DocumentId" IS 'References the associated document managed by the Document Service.';
    COMMENT ON COLUMN audit."FgsEventAttachment"."Description" IS 'Optional description explaining why the document is associated with the event.';
    COMMENT ON COLUMN audit."FgsEventAttachment"."CreatedOn" IS 'Date and time the attachment association was created.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE TABLE audit."FgsEventDetail" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EventId" bigint NOT NULL,
        "EntryType" audit.event_detail_type NOT NULL,
        "Sequence" smallint NOT NULL DEFAULT 1,
        "ItemName" character varying(100) NOT NULL,
        "OldValue" text,
        "NewValue" text,
        "CreatedOn" timestamp NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_FgsEventDetail" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FgsEventDetail_Event" FOREIGN KEY ("EventId") REFERENCES audit."FgsEvent" ("Id") ON DELETE CASCADE
    );
    COMMENT ON TABLE audit."FgsEventDetail" IS 'Stores detailed information associated with an event, including field changes, calculations, validation results, workflow actions, messages, and exceptions.';
    COMMENT ON COLUMN audit."FgsEventDetail"."Id" IS 'Unique identifier of the event detail record.';
    COMMENT ON COLUMN audit."FgsEventDetail"."EventId" IS 'References the parent event.';
    COMMENT ON COLUMN audit."FgsEventDetail"."EntryType" IS 'Classifies the type of detail entry, such as field change, calculation, validation, message, or exception.';
    COMMENT ON COLUMN audit."FgsEventDetail"."Sequence" IS 'Determines the display order of detail entries within an event.';
    COMMENT ON COLUMN audit."FgsEventDetail"."ItemName" IS 'Name of the property, calculation item, validation rule, or message attribute.';
    COMMENT ON COLUMN audit."FgsEventDetail"."OldValue" IS 'Original value before the event occurred. Typically populated for field changes.';
    COMMENT ON COLUMN audit."FgsEventDetail"."NewValue" IS 'New value after the event occurred, or the resulting value for calculations, messages, and other detail types.';
    COMMENT ON COLUMN audit."FgsEventDetail"."CreatedOn" IS 'Date and time the detail record was created.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE UNIQUE INDEX "IX_FgsArchiveCatalog_ArchiveMonth" ON audit."FgsArchiveCatalog" ("ArchiveMonth");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEvent_Entity" ON audit."FgsEvent" ("RecordType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEvent_EventCode" ON audit."FgsEvent" ("EventCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEvent_EventSource" ON audit."FgsEvent" ("EventSource");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEvent_OccurredOn" ON audit."FgsEvent" ("OccurredOn" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEvent_TenantCompanyOccurredOn" ON audit."FgsEvent" ("TenantId", "CompanyId", "OccurredOn" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEventAttachment_DocumentId" ON audit."FgsEventAttachment" ("DocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEventAttachment_EventId" ON audit."FgsEventAttachment" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEventDetail_EntryType" ON audit."FgsEventDetail" ("EntryType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEventDetail_EventId" ON audit."FgsEventDetail" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    CREATE INDEX "IX_FgsEventDetail_EventId_Sequence" ON audit."FgsEventDetail" ("EventId", "Sequence");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM audit."__EFMigrationsHistory" WHERE "MigrationId" = '20260720183429_AddFgsEventTables') THEN
    INSERT INTO audit."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260720183429_AddFgsEventTables', '10.0.8');
    END IF;
END $EF$;
COMMIT;

