// <auto-generated />
using System;
using Fgs.ServiceAgreement.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fgs.ServiceAgreement.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FgsServiceAgreementDbContext))]
    partial class FgsServiceAgreementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("svc")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActivatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the agreement became active.");

                    b.Property<string>("AgreementNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("User visible service agreement number.");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the agreement should automatically renew at expiration.");

                    b.Property<short>("BillingFrequencyId")
                        .HasColumnType("smallint")
                        .HasComment("Frequency used to generate billing schedules.");

                    b.Property<long>("Break1Id")
                        .HasColumnType("bigint")
                        .HasComment("Business Unit classification for the agreement.");

                    b.Property<long>("Break2Id")
                        .HasColumnType("bigint")
                        .HasComment("Secondary operational classification for the agreement.");

                    b.Property<DateTimeOffset?>("CancelledOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the agreement was cancelled.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("ContractAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Total contract value. Billing schedule amounts are calculated from contract amount and billing frequency.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasComment("Customer that owns the agreement.");

                    b.Property<long>("CustomerLocationId")
                        .HasColumnType("bigint")
                        .HasComment("Service location covered by the agreement.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Internal agreement description.");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasComment("Agreement coverage end date.");

                    b.Property<long?>("EstimateId")
                        .HasColumnType("bigint")
                        .HasComment("Estimate that was accepted and converted into this service agreement.");

                    b.Property<string>("ExternalEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("External system identifier.");

                    b.Property<string>("ExternalVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("External synchronization token or version.");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("bigint")
                        .HasComment("Job type associated with the agreement.");

                    b.Property<decimal>("LaborDiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Labor discount percentage available under the agreement.");

                    b.Property<decimal>("MaterialDiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Material discount percentage available under the agreement.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Agreement name.");

                    b.Property<long?>("RenewedByServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Identifier of the agreement created when this agreement was renewed. Null indicates the agreement has not yet been renewed.");

                    b.Property<short>("ServiceAgreementStatusId")
                        .HasColumnType("smallint")
                        .HasComment("Agreement lifecycle status. Values: 1=Draft, 2=Active, 3=Expired, 4=Cancelled.");

                    b.Property<long?>("SoldByEmployeeId")
                        .HasColumnType("bigint")
                        .HasComment("Employee that sold the agreement.");

                    b.Property<DateOnly?>("SoldDate")
                        .HasColumnType("date")
                        .HasComment("Date the agreement was sold.");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasComment("Agreement coverage start date.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.Property<short>("VisitFrequencyId")
                        .HasColumnType("smallint")
                        .HasComment("Frequency used to generate service agreement visit schedules.");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreement_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "AgreementNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsServiceAgreement_AgreementNumber");

                    b.HasIndex("TenantId", "CompanyId", "CustomerId")
                        .HasDatabaseName("IX_FgsServiceAgreement_CustomerId");

                    b.HasIndex("TenantId", "CompanyId", "CustomerLocationId")
                        .HasDatabaseName("IX_FgsServiceAgreement_CustomerLocationId");

                    b.HasIndex("TenantId", "CompanyId", "EndDate")
                        .HasDatabaseName("IX_FgsServiceAgreement_EndDate");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementStatusId")
                        .HasDatabaseName("IX_FgsServiceAgreement_Status");

                    b.ToTable("FgsServiceAgreement", "svc", t =>
                        {
                            t.HasComment("Stores recurring maintenance agreements, membership plans, preventive maintenance contracts, and service contracts. Visit schedules and billing schedules are generated into separate tables.");

                            t.HasCheckConstraint("CK_FgsServiceAgreement_Discounts", "\"LaborDiscountPercent\" BETWEEN 0 AND 100 AND \"MaterialDiscountPercent\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_FgsServiceAgreement_EndDate", "\"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_FgsServiceAgreement_Status", "\"ServiceAgreementStatusId\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementBillingSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BillingAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Amount expected to be billed for this billing event.");

                    b.Property<DateOnly>("BillingDate")
                        .HasColumnType("date")
                        .HasComment("Scheduled billing date used for invoice generation.");

                    b.Property<short>("BillingScheduleStatusId")
                        .HasColumnType("smallint")
                        .HasComment("Billing schedule status. Values: 1=Pending, 2=InvoiceCreated, 3=Invoiced, 4=Skipped, 5=Cancelled.");

                    b.Property<int>("BillingSequence")
                        .HasColumnType("integer")
                        .HasComment("Sequential billing number within the service agreement.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<string>("ExternalInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Invoice number from a legacy or external system used during data migration.");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasComment("Generated invoice identifier associated with the billing event.");

                    b.Property<long>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_ServiceAgreementId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "BillingDate")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_BillingDate");

                    b.HasIndex("TenantId", "CompanyId", "BillingScheduleStatusId")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_Status");

                    b.HasIndex("TenantId", "CompanyId", "InvoiceId")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_InvoiceId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementBillingSchedule_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId", "BillingSequence")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsServiceAgreementBillingSchedule_Agreement_Sequence");

                    b.ToTable("FgsServiceAgreementBillingSchedule", "svc", t =>
                        {
                            t.HasComment("Stores future billing events generated from a service agreement. Billing schedules generate invoices but are not invoices themselves.");

                            t.HasCheckConstraint("CK_FgsServiceAgreementBillingSchedule_BillingAmount", "\"BillingAmount\" >= 0");

                            t.HasCheckConstraint("CK_FgsServiceAgreementBillingSchedule_Status", "\"BillingScheduleStatusId\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementCoveredAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint")
                        .HasComment("Covered customer asset identifier.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<long>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementCoveredAsset_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "AssetId")
                        .HasDatabaseName("IX_FgsServiceAgreementCoveredAsset_AssetId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementCoveredAsset_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsServiceAgreementCoveredAsset_Agreement_Asset");

                    b.ToTable("FgsServiceAgreementCoveredAsset", "svc", t =>
                        {
                            t.HasComment("Stores assets covered under a service agreement. Covered assets are entitled to contract benefits such as labor discounts, material discounts, contract pricing, and service agreement coverage. Coverage is inherited from the parent agreement term.");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Note text.");

                    b.Property<long?>("NoteTypeId")
                        .HasColumnType("bigint")
                        .HasComment("Optional note classification identifier.");

                    b.Property<long?>("ServiceAgreementBillingScheduleId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement billing schedule identifier.");

                    b.Property<long?>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<long?>("ServiceAgreementVisitId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement visit identifier.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgreementBillingScheduleId");

                    b.HasIndex("ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_ServiceAgreementId1");

                    b.HasIndex("ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_ServiceAgreementVisitId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementBillingScheduleId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_BillingScheduleId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementNote_ServiceAgreementVisitId");

                    b.ToTable("FgsServiceAgreementNote", "svc", t =>
                        {
                            t.HasComment("Stores notes related to service agreements, service agreement visits, and service agreement billing schedules. A note belongs to exactly one parent entity.");

                            t.HasCheckConstraint("CK_FgsServiceAgreementNote_Parent", "(\"ServiceAgreementId\" IS NOT NULL AND \"ServiceAgreementVisitId\" IS NULL AND \"ServiceAgreementBillingScheduleId\" IS NULL)\r\nOR (\"ServiceAgreementId\" IS NULL AND \"ServiceAgreementVisitId\" IS NOT NULL AND \"ServiceAgreementBillingScheduleId\" IS NULL)\r\nOR (\"ServiceAgreementId\" IS NULL AND \"ServiceAgreementVisitId\" IS NULL AND \"ServiceAgreementBillingScheduleId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Date and time the maintenance visit was completed.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<DateOnly>("ExpectedServiceDate")
                        .HasColumnType("date")
                        .HasComment("Expected date the maintenance service should be performed according to the agreement.");

                    b.Property<string>("ExternalWorkOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Work order number from a legacy or external system used during data migration.");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("bigint")
                        .HasComment("Job type used when generating a work order from the service agreement visit.");

                    b.Property<long>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<short>("ServiceAgreementVisitStatusId")
                        .HasColumnType("smallint")
                        .HasComment("Visit lifecycle status. Values: 1=Pending, 2=WorkOrderCreated, 3=Completed, 4=Skipped, 5=Cancelled.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.Property<int>("VisitNumber")
                        .HasColumnType("integer")
                        .HasComment("Sequential visit number within the service agreement.");

                    b.Property<long?>("WorkOrderId")
                        .HasColumnType("bigint")
                        .HasComment("Generated work order identifier associated with the visit.");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_ServiceAgreementId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "ExpectedServiceDate")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_ExpectedServiceDate");

                    b.HasIndex("TenantId", "CompanyId", "JobTypeId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_JobTypeId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitStatusId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_Status");

                    b.HasIndex("TenantId", "CompanyId", "WorkOrderId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisit_WorkOrderId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId", "VisitNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsServiceAgreementVisit_Agreement_VisitNumber");

                    b.ToTable("FgsServiceAgreementVisit", "svc", t =>
                        {
                            t.HasComment("Stores contractually required maintenance visits generated from a service agreement. Visits may later generate work orders to perform the required maintenance service.");

                            t.HasCheckConstraint("CK_FgsServiceAgreementVisit_Status", "\"ServiceAgreementVisitStatusId\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisitAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint")
                        .HasComment("Asset associated with the service agreement visit.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<long>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<long>("ServiceAgreementVisitId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement visit identifier.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitAsset_ServiceAgreementVisitId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitAsset_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "AssetId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitAsset_AssetId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitAsset_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitAsset_ServiceAgreementVisitId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsServiceAgreementVisitAsset_Visit_Asset");

                    b.ToTable("FgsServiceAgreementVisitAsset", "svc", t =>
                        {
                            t.HasComment("Stores assets associated with a service agreement maintenance visit. A visit may include one or more covered assets that require maintenance service.");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisitItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that created the record.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()")
                        .HasComment("Record creation timestamp.");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Additional item description or maintenance instructions.");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasComment("Display order within the maintenance visit item list.");

                    b.Property<long?>("InventoryItemId")
                        .HasColumnType("bigint")
                        .HasComment("Inventory item identifier. May be NULL when the item is manually entered.");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates whether the item is required for the maintenance visit.");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Item name used when the item does not exist in the inventory catalog.");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(1m)
                        .HasComment("Expected quantity required for the maintenance visit.");

                    b.Property<long>("ServiceAgreementId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement identifier.");

                    b.Property<long>("ServiceAgreementVisitId")
                        .HasColumnType("bigint")
                        .HasComment("Parent service agreement visit identifier.");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User that last updated the record.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Record last update timestamp.");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_ServiceAgreementVisitId1");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_TenantId_CompanyId");

                    b.HasIndex("TenantId", "CompanyId", "InventoryItemId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_InventoryItemId");

                    b.HasIndex("TenantId", "CompanyId", "IsRequired")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_IsRequired");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_ServiceAgreementId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitId")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_ServiceAgreementVisitId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceAgreementVisitId", "DisplayOrder")
                        .HasDatabaseName("IX_FgsServiceAgreementVisitItem_DisplayOrder");

                    b.ToTable("FgsServiceAgreementVisitItem", "svc", t =>
                        {
                            t.HasComment("Stores recommended items associated with a service agreement maintenance visit. Items may come from the inventory catalog or be entered manually. Actual material usage is recorded on the work order.");

                            t.HasCheckConstraint("CK_FgsServiceAgreementVisitItem_Item", "\"InventoryItemId\" IS NOT NULL OR COALESCE(TRIM(\"ItemName\"), '') <> ''");

                            t.HasCheckConstraint("CK_FgsServiceAgreementVisitItem_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("Tenant identifier.");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasComment("Company identifier mapped from tenant.FgsTenantCompany.CompanyNumber.");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Unique company code within a tenant.");

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uuid")
                        .HasComment("Globally unique company identifier used by integrations and external systems.");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Display name of the company.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the company is active.");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamptz")
                        .HasComment("Timestamp of the most recent synchronization from tenant.FgsTenantCompany.");

                    b.HasKey("TenantId", "CompanyId")
                        .HasName("PK_FgsTenantCompanyCache");

                    b.HasIndex("CompanyGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_FgsTenantCompanyCache_CompanyGuid");

                    b.HasIndex("CompanyName")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_CompanyName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FgsTenantCompanyCache_IsActive");

                    b.ToTable("FgsTenantCompanyCache", "svc", t =>
                        {
                            t.HasComment("Local cache of tenant company information used by the svc schema to eliminate cross-schema dependencies on tenant.FgsTenantCompany.");
                        });
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreement", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreement_FgsTenantCompanyCache_TenantId_CompanyId");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementBillingSchedule", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreement", "ServiceAgreement")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementBillingSchedule_ServiceAgreement");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementBillingSchedule_FgsTenantCompanyCache_TenantId_CompanyId");

                    b.Navigation("ServiceAgreement");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementCoveredAsset", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementCoveredAsset_FgsTenantCompanyCache_TenantId_CompanyId");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementNote", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementBillingSchedule", "ServiceAgreementBillingSchedule")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementBillingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_FgsServiceAgreementNote_BillingSchedule");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreement", "ServiceAgreement")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_FgsServiceAgreementNote_ServiceAgreement");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisit", "ServiceAgreementVisit")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_FgsServiceAgreementNote_ServiceAgreementVisit");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementNote_FgsTenantCompanyCache_TenantId_CompanyId");

                    b.Navigation("ServiceAgreement");

                    b.Navigation("ServiceAgreementBillingSchedule");

                    b.Navigation("ServiceAgreementVisit");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisit", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreement", "ServiceAgreement")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisit_ServiceAgreement");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisit_FgsTenantCompanyCache_TenantId_CompanyId");

                    b.Navigation("ServiceAgreement");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisitAsset", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisit", "ServiceAgreementVisit")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisitAsset_ServiceAgreementVisit");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisitAsset_FgsTenantCompanyCache_TenantId_CompanyId");

                    b.Navigation("ServiceAgreementVisit");
                });

            modelBuilder.Entity("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisitItem", b =>
                {
                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsServiceAgreementVisit", "ServiceAgreementVisit")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisitItem_ServiceAgreementVisit");

                    b.HasOne("Fgs.ServiceAgreement.Domain.Entities.FgsTenantCompanyCache", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FgsServiceAgreementVisitItem_FgsTenantCompanyCache_TenantId_CompanyId");

                    b.Navigation("ServiceAgreementVisit");
                });
#pragma warning restore 612, 618
        }
    }
}
