using Dapper;
using Fgs.Asset.Application.Abstractions.Persistence;
using Fgs.Asset.Application.Abstractions.Assets;
using Fgs.Asset.Application.Common.AssetCrud;
using Fgs.Asset.Application.Features.Assets.Dtos;
using Fgs.Asset.Infrastructure.Common;
using Fgs.Foundation.Paging;
using Fgs.MultiTenancy;
namespace Fgs.Asset.Infrastructure.Assets;
internal sealed class FgsAssetReadRepository : IFgsAssetReadRepository
{
    private readonly IAssetReadConnectionFactory _connectionFactory;
    private readonly ITenantContextAccessor _tenantContextAccessor;
    public FgsAssetReadRepository(IAssetReadConnectionFactory connectionFactory, ITenantContextAccessor tenantContextAccessor) { _connectionFactory = connectionFactory; _tenantContextAccessor = tenantContextAccessor; }
    public async Task<FgsAssetDetailDto?> GetByIdAsync(long id, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var sql = $"SELECT {FgsAssetSql.SelectDetailColumns} FROM {FgsAssetSql.Table} WHERE \"Id\" = @Id AND \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return (await connection.QueryFirstOrDefaultAsync<FgsAssetDetailRow>(new CommandDefinition(sql, new { Id = id, TenantId = tenantId, CompanyId = companyId }, cancellationToken: cancellationToken)))?.ToDto(); }
    public async Task<PagedResult<FgsAssetSummaryDto>> ListAsync(AssetListQuery query, FgsAssetListFilters filters, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var paging = query.ToPagedQuery(); var page = Math.Max(1, paging.Page); var pageSize = Math.Clamp(paging.PageSize, 1, 200); var offset = (page - 1) * pageSize; var where = new List<string> { "\"TenantId\" = @TenantId", "\"CompanyId\" = @CompanyId" }; if (paging.IsActive.HasValue) where.Add("\"IsActive\" = @IsActive"); 
        if (!string.IsNullOrWhiteSpace(filters.AssetNumber)) where.Add("\"AssetNumber\" ILIKE @AssetNumber");
        if (filters.ServiceLocationId.HasValue) where.Add("\"ServiceLocationId\" = @ServiceLocationId");
        if (filters.AssetStatusId.HasValue) where.Add("\"AssetStatusId\" = @AssetStatusId");
 if (!string.IsNullOrWhiteSpace(paging.Search)) where.Add("(\"AssetNumber\" ILIKE @Search OR \"CustomerAssetName\" ILIKE @Search OR \"SerialNumber\" ILIKE @Search)"); var whereClause = string.Join(" AND ", where); var sql = $"SELECT {FgsAssetSql.SelectSummaryColumns} FROM {FgsAssetSql.Table} WHERE {whereClause} {FgsAssetSql.ResolveOrderBy(paging.SortBy, paging.SortDirection)} LIMIT @PageSize OFFSET @Offset; SELECT COUNT(*) FROM {FgsAssetSql.Table} WHERE {whereClause};"; var parameters = new { TenantId = tenantId, CompanyId = companyId, IsActive = paging.IsActive, AssetNumber = string.IsNullOrWhiteSpace(filters.AssetNumber) ? null : $"%{filters.AssetNumber.Trim()}%", ServiceLocationId = filters.ServiceLocationId, AssetStatusId = filters.AssetStatusId, Search = string.IsNullOrWhiteSpace(paging.Search) ? null : $"%{paging.Search.Trim()}%", PageSize = pageSize, Offset = offset }; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); await using var multi = await connection.QueryMultipleAsync(new CommandDefinition(sql, parameters, cancellationToken: cancellationToken)); var rows = (await multi.ReadAsync<FgsAssetSummaryRow>()).ToList(); return new PagedResult<FgsAssetSummaryDto>(rows.Select(r => r.ToDto()).ToList(), page, pageSize, await multi.ReadSingleAsync<int>()); }
    public async Task<IReadOnlyList<FgsAssetLookupDto>> LookupAsync(bool activeOnly = true, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var activeFilter = activeOnly ? "AND \"IsActive\" = TRUE" : string.Empty; var sql = $"SELECT {FgsAssetSql.SelectLookupColumns} FROM {FgsAssetSql.Table} WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId {activeFilter} ORDER BY \"Id\" ASC"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return (await connection.QueryAsync<FgsAssetLookupRow>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId }, cancellationToken: cancellationToken))).Select(r => r.ToDto()).ToList(); }

    public async Task<bool> ExistsByAssetNumberAsync(string assetNumber, long? excludeId = null, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); var exclude = excludeId.HasValue ? "AND \"Id\" <> @ExcludeId" : string.Empty; var sql = $"SELECT EXISTS(SELECT 1 FROM {FgsAssetSql.Table} WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"AssetNumber\" = @AssetNumber {exclude})"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, AssetNumber = assetNumber.Trim(), ExcludeId = excludeId }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsAssetTypeIdAsync(long? assetTypeId, CancellationToken cancellationToken = default) { if (!assetTypeId.HasValue) return true; var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAssetType\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id AND \"IsActive\" = TRUE)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetTypeId.Value }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsAssetManufacturerIdAsync(long? assetManufacturerId, CancellationToken cancellationToken = default) { if (!assetManufacturerId.HasValue) return true; var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAssetManufacturer\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id AND \"IsActive\" = TRUE)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetManufacturerId.Value }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsAssetModelIdAsync(long? assetModelId, CancellationToken cancellationToken = default) { if (!assetModelId.HasValue) return true; var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAssetModel\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id AND \"IsActive\" = TRUE)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetModelId.Value }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsAssetStatusIdAsync(long assetStatusId, CancellationToken cancellationToken = default) { var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsAssetStatus\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"Id\" = @Id AND \"IsActive\" = TRUE)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, Id = assetStatusId }, cancellationToken: cancellationToken)); }
    public async Task<bool> ExistsServiceLocationIdAsync(long? serviceLocationId, CancellationToken cancellationToken = default) { if (!serviceLocationId.HasValue) return true; var (tenantId, companyId) = AssetTenantScopeResolver.ResolveRequired(_tenantContextAccessor); const string sql = "SELECT EXISTS(SELECT 1 FROM asset.\"FgsServiceLocationCache\" WHERE \"TenantId\" = @TenantId AND \"CompanyId\" = @CompanyId AND \"ServiceLocationId\" = @ServiceLocationId)"; await using var connection = await _connectionFactory.CreateOpenConnectionAsync(cancellationToken); return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql, new { TenantId = tenantId, CompanyId = companyId, ServiceLocationId = serviceLocationId.Value }, cancellationToken: cancellationToken)); }

}
