using Fgs.Asset.Application.Abstractions.Assets;
using Fgs.Asset.Application.Features.Assets.Dtos;
using Fgs.Asset.Infrastructure.Common;
using Fgs.Asset.Infrastructure.Database;
using Fgs.Persistence.Abstractions;
using Microsoft.EntityFrameworkCore;
namespace Fgs.Asset.Infrastructure.Assets;
public sealed class FgsAssetWriteService : IFgsAssetWriteService
{
    private readonly FgsAssetDbContext _context; private readonly IUnitOfWork _unitOfWork; private readonly AssetEntityAuditHelper _auditHelper;
    public FgsAssetWriteService(FgsAssetDbContext context, IUnitOfWork unitOfWork, AssetEntityAuditHelper auditHelper) { _context = context; _unitOfWork = unitOfWork; _auditHelper = auditHelper; }
    public async Task<FgsAssetDetailDto> CreateAsync(FgsAssetCreateDto dto, CancellationToken cancellationToken = default) { var entity = new Domain.Entities.FgsAsset { AssetGuid = Guid.NewGuid(), AssetNumber = dto.AssetNumber.Trim(), ServiceLocationId = dto.ServiceLocationId, AssetTypeId = dto.AssetTypeId, AssetManufacturerId = dto.AssetManufacturerId, AssetModelId = dto.AssetModelId, AssetDescription = Trim(dto.AssetDescription), CustomerAssetNumber = Trim(dto.CustomerAssetNumber), CustomerAssetName = Trim(dto.CustomerAssetName), ManufacturerName = Trim(dto.ManufacturerName), ModelNumber = Trim(dto.ModelNumber), SerialNumber = Trim(dto.SerialNumber), ManufactureDate = dto.ManufactureDate, InstallDate = dto.InstallDate, InstalledWorkOrderId = dto.InstalledWorkOrderId, IsInstalledByCompany = dto.IsInstalledByCompany, AssetStatusId = dto.AssetStatusId }; _auditHelper.StampForCreate(entity); await _context.FgsAssets.AddAsync(entity, cancellationToken); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    public async Task<FgsAssetDetailDto> UpdateAsync(long id, FgsAssetUpdateDto dto, CancellationToken cancellationToken = default) { var entity = await Find(id, cancellationToken) ?? throw new KeyNotFoundException($"Asset '{id}' was not found."); Apply(entity, dto); _auditHelper.StampForUpdate(entity); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    public async Task<FgsAssetDetailDto> PatchAsync(long id, FgsAssetPatchDto dto, CancellationToken cancellationToken = default) { var entity = await Find(id, cancellationToken) ?? throw new KeyNotFoundException($"Asset '{id}' was not found."); Patch(entity, dto); _auditHelper.StampForUpdate(entity); await _unitOfWork.SaveChangesAsync(cancellationToken); return Map(entity); }
    private async Task<Domain.Entities.FgsAsset?> Find(long id, CancellationToken ct) => await _context.FgsAssets.FirstOrDefaultAsync(x => x.Id == id, ct);
    private static void Apply(Domain.Entities.FgsAsset e, FgsAssetUpdateDto dto) { e.AssetNumber = dto.AssetNumber.Trim(); e.ServiceLocationId = dto.ServiceLocationId; e.AssetTypeId = dto.AssetTypeId; e.AssetManufacturerId = dto.AssetManufacturerId; e.AssetModelId = dto.AssetModelId; e.AssetDescription = Trim(dto.AssetDescription); e.CustomerAssetNumber = Trim(dto.CustomerAssetNumber); e.CustomerAssetName = Trim(dto.CustomerAssetName); e.ManufacturerName = Trim(dto.ManufacturerName); e.ModelNumber = Trim(dto.ModelNumber); e.SerialNumber = Trim(dto.SerialNumber); e.ManufactureDate = dto.ManufactureDate; e.InstallDate = dto.InstallDate; e.InstalledWorkOrderId = dto.InstalledWorkOrderId; e.IsInstalledByCompany = dto.IsInstalledByCompany; e.AssetStatusId = dto.AssetStatusId; }
    private static void Patch(Domain.Entities.FgsAsset e, FgsAssetPatchDto dto) { if (dto.AssetNumber is not null) e.AssetNumber = dto.AssetNumber.Trim(); if (dto.ServiceLocationId.HasValue) e.ServiceLocationId = dto.ServiceLocationId.Value; if (dto.AssetTypeId.HasValue) e.AssetTypeId = dto.AssetTypeId; if (dto.AssetManufacturerId.HasValue) e.AssetManufacturerId = dto.AssetManufacturerId; if (dto.AssetModelId.HasValue) e.AssetModelId = dto.AssetModelId; if (dto.AssetDescription is not null) e.AssetDescription = Trim(dto.AssetDescription); if (dto.CustomerAssetNumber is not null) e.CustomerAssetNumber = Trim(dto.CustomerAssetNumber); if (dto.CustomerAssetName is not null) e.CustomerAssetName = Trim(dto.CustomerAssetName); if (dto.ManufacturerName is not null) e.ManufacturerName = Trim(dto.ManufacturerName); if (dto.ModelNumber is not null) e.ModelNumber = Trim(dto.ModelNumber); if (dto.SerialNumber is not null) e.SerialNumber = Trim(dto.SerialNumber); if (dto.ManufactureDate.HasValue) e.ManufactureDate = dto.ManufactureDate; if (dto.InstallDate.HasValue) e.InstallDate = dto.InstallDate; if (dto.InstalledWorkOrderId.HasValue) e.InstalledWorkOrderId = dto.InstalledWorkOrderId; if (dto.IsInstalledByCompany.HasValue) e.IsInstalledByCompany = dto.IsInstalledByCompany.Value; if (dto.AssetStatusId.HasValue) e.AssetStatusId = dto.AssetStatusId.Value; if (dto.IsActive.HasValue) e.IsActive = dto.IsActive.Value; }
    private static string? Trim(string? v) => string.IsNullOrWhiteSpace(v) ? null : v.Trim();
    private static FgsAssetDetailDto Map(Domain.Entities.FgsAsset e) => new(e.Id, e.AssetGuid, e.AssetNumber, e.ServiceLocationId, e.AssetTypeId, e.AssetManufacturerId, e.AssetModelId, e.AssetDescription, e.CustomerAssetNumber, e.CustomerAssetName, e.ManufacturerName, e.ModelNumber, e.SerialNumber, e.ManufactureDate, e.InstallDate, e.InstalledWorkOrderId, e.IsInstalledByCompany, e.AssetStatusId, e.IsActive);
}
