namespace Fgs.Crm.Application.Features.Customers.Dtos;

public sealed record CrmCustomerSummaryDto(
    long Id,
    string CustomerNumber,
    string Name,
    string DisplayName,
    string? City,
    string? State,
    string? PostalCode,
    string? Country,
    string? CustomerAccountNumber,
    bool IsActive);

public sealed record CrmCustomerDetailDto(
    long Id,
    string CustomerNumber,
    string Name,
    string DisplayName,
    string? AddressLine1,
    string? AddressLine2,
    string? AddressLine3,
    string? AddressLine4,
    string? City,
    string? State,
    string? County,
    string? Country,
    string? PostalCode,
    string? FormattedAddress,
    decimal? Latitude,
    decimal? Longitude,
    string? PlaceId,
    long? DefaultPaymentTermId,
    long? DefaultMaterialPricingMatrixId,
    long? DefaultLaborPricingMatrixId,
    long? DefaultOtherPricingMatrixId,
    bool DefaultPORequired,
    bool TaxExempt,
    string? TaxExemptNumber,
    string? CustomerAccountNumber,
    string? ExternalEntityId,
    string? ExternalVersion,
    bool IsActive);

public sealed record CrmCustomerLookupDto(
    long Id,
    string CustomerNumber,
    string DisplayName);

public sealed record CrmCustomerCreateDto(
    string CustomerNumber,
    string Name,
    string DisplayName,
    string? AddressLine1,
    string? AddressLine2,
    string? AddressLine3,
    string? AddressLine4,
    string? City,
    string? State,
    string? County,
    string? Country,
    string? PostalCode,
    string? FormattedAddress,
    decimal? Latitude,
    decimal? Longitude,
    string? PlaceId,
    long? DefaultPaymentTermId,
    long? DefaultMaterialPricingMatrixId,
    long? DefaultLaborPricingMatrixId,
    long? DefaultOtherPricingMatrixId,
    bool DefaultPORequired,
    bool TaxExempt,
    string? TaxExemptNumber,
    string? CustomerAccountNumber,
    string? ExternalEntityId,
    string? ExternalVersion);

public sealed record CrmCustomerUpdateDto(
    string CustomerNumber,
    string Name,
    string DisplayName,
    string? AddressLine1,
    string? AddressLine2,
    string? AddressLine3,
    string? AddressLine4,
    string? City,
    string? State,
    string? County,
    string? Country,
    string? PostalCode,
    string? FormattedAddress,
    decimal? Latitude,
    decimal? Longitude,
    string? PlaceId,
    long? DefaultPaymentTermId,
    long? DefaultMaterialPricingMatrixId,
    long? DefaultLaborPricingMatrixId,
    long? DefaultOtherPricingMatrixId,
    bool DefaultPORequired,
    bool TaxExempt,
    string? TaxExemptNumber,
    string? CustomerAccountNumber,
    string? ExternalEntityId,
    string? ExternalVersion);

public sealed record CrmCustomerPatchDto(
    string? CustomerNumber,
    string? Name,
    string? DisplayName,
    string? AddressLine1,
    string? AddressLine2,
    string? AddressLine3,
    string? AddressLine4,
    string? City,
    string? State,
    string? County,
    string? Country,
    string? PostalCode,
    string? FormattedAddress,
    decimal? Latitude,
    decimal? Longitude,
    string? PlaceId,
    long? DefaultPaymentTermId,
    long? DefaultMaterialPricingMatrixId,
    long? DefaultLaborPricingMatrixId,
    long? DefaultOtherPricingMatrixId,
    bool? DefaultPORequired,
    bool? TaxExempt,
    string? TaxExemptNumber,
    string? CustomerAccountNumber,
    string? ExternalEntityId,
    string? ExternalVersion,
    bool? IsActive);

public sealed record CrmCustomerListFilters(
    string? CustomerNumber = null,
    string? Name = null,
    string? DisplayName = null);
